Feature/#8 폰트추가
BCSDLab/TEMP_PROJECT_FE pull request #10
Opened 2022-09-08 13:49 UTC by D0Dam

## #8  request

-[x] SUIT폰트 설치
정적 폰트를 사용했으며 파일 타입은 woff2 입니다.
font-weight는 100(Thin)부터 100단위 씩 900(Heavy)까지, 총 9가지 타입을 지원합니다.
이는 src/assets/fonts/SUIT.css를 통해 각각의 font-face를 확인 할 수 있습니다.
-[x] global font-face 정의
index.scss의 body, html에 font-family: "SUIT"를 적용하였습니다.

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

### Screenshot
![스크린샷 2022-09-08 오후 10 49 05](https://user-images.githubusercontent.com/51052049/189139287-84c1505b-8ff0-4873-aa80-9a6bb69ff44b.png)

2022-09-08 14:09 UTC, ChoiWonBeen commented
yarn lint 해보셨나요?
깃헙 액션에서 lint에러가 나는거보니 PR전에 lint를 확인해주세요.

2022-09-08 16:48 UTC, D0Dam commented
> yarn lint 해보셨나요? 깃헙 액션에서 lint에러가 나는거보니 PR전에 lint를 확인해주세요.

수정했습니다

2022-09-09 00:55 UTC, ChoiWonBeen requested changes
확인하고 추가해주세요~

2022-09-09 00:55 UTC, ChoiWonBeen commented on src/index.scss
> +  font-family: SUIT, sans-serif;
폰트를 쓰다보면, 몇 개의 글꼴로는 표현할 수 없는 특수문자나, 이모지, sub 글자(밽 같은) 등이 나오는 순간 글자를 표시할 방법이 없어집니다.

그래서 2순위부터인 generic 글꼴로 OS마다 브라우저에 기본으로 저장돼있는 **안전한** 시스템 글꼴을 나열해서, 해당 글꼴로 표시하지 못하면 다음 글꼴로 사용하게끔 만들어야 합니다.

https://css-tricks.com/snippets/css/system-font-stack/

2022-09-09 05:23 UTC, D0Dam commented on src/index.scss
> +  font-family: SUIT, sans-serif;
참고 사이트(css-tricks)의 chrome, safari 환경에 적용되어 있는 font-family를 기준으로 수정했습니다!

2022-09-09 05:48 UTC, ChoiWonBeen approved these changes

2022-09-09 08:49 UTC, kimeodml approved these changes

2022-09-09 12:07 UTC, daepan approved these changes
폰트 적용 수고하셨습니다!
궁금한점이 있는데 혹시 fonts/LICENSE 는 필수로 존재해야하나요?
개발에서 저작권 관련되어 있는지 궁금합니다.

2022-09-09 12:13 UTC, SimYunSup requested changes
생각해보면 좋을만한 것들을 중심으로 리뷰했습니다.

2022-09-09 12:13 UTC, SimYunSup commented on src/assets/fonts/SUIT.scss
> +  font-weight: 100;
font-weight를 모두 사용한다면 100~900까지 모두 다운 받는 것이 맞겠지만 다 사용하지 않는다면 불필요한 다운로드가 될 것이고 이는 성능을 늦추게 될 것입니다.
그리고 [해당 링크](https://web.dev/i18n/ko/optimize-webfont-loading/)를 참고하여 `local()` 함수를 사용하고 CDN을 사용하는 것이 좋습니다(이후 백엔드에 부탁해서 S3같은 정적 파일 보관소에 저장해서 각 CloudFront에 연결하는 것으로 CDN에 연결.) 그러므로 백엔드와 협력해서 CDN링크를 넣거나, `local()` 함수만 활용해서 로컬에 있는 폰트를 사용해야 할 것입니다.

2022-09-09 12:13 UTC, SimYunSup commented on src/assets/fonts/LICENSE
> +Copyright (c) 2022, SUNN (http://sunn.us/suit),
해당 폰트에 대한 라이선스는 Webpack을 통해서 배포되어야 할 것입니다. 그러므로 public폴더에 따로 `License`폴더를 만들던가 해서 넣는 것이 맞겠습니다.

2022-09-09 12:13 UTC, SimYunSup commented on src/assets/fonts/SUIT.scss
> +@font-face {
Scss의 장점은 "프로그래밍 가능하다"라는 점입니다. [이 링크](https://yamoo9.gitbook.io/scss-mixins/mixins/font/font-face)를 참고해서 간단하게 만들어보세요.

2022-09-09 12:54 UTC, D0Dam commented
> 폰트 적용 수고하셨습니다! 궁금한점이 있는데 혹시 fonts/LICENSE 는 필수로 존재해야하나요? 개발에서 저작권 관련되어 있는지 궁금합니다.

넵 SUIT 폰트의 경우 자유롭게 수정 및 재배포가 가능한 오픈소스입니다만, 이 경우에도 준수해야할 주요 의무사항이 있습니다.
저작권/개발자 및 기여자 정보를 표시하거나 수정을 하게 된다면 수정한 정보를 표시해야하고 라이선스 정보를 제공해야 한다는 것이 주요 의무사항이라고 할 수 있습니다.

2022-09-09 13:21 UTC, D0Dam commented on src/assets/fonts/SUIT.scss
> +  font-weight: 100;
@SimYunSup 
1. font weight를 필요한 것만 사용한다고 했을 때 그걸 정하는 기준은 어떻게 될까요?  UI/UX 팀과 상의를 해봐야 될 부분인가요..?
2. 우선적으로 local 함수 만을 사용하고 추후에 CDN을 사용하는 방향으로 진행해봐도 될까요?

2022-09-09 13:21 UTC, D0Dam commented on src/assets/fonts/LICENSE
> +Copyright (c) 2022, SUNN (http://sunn.us/suit),
네 public 폴더에 License 폴더 추가하겠습니다.

2022-09-09 13:23 UTC, SimYunSup commented on src/assets/fonts/SUIT.scss
> +  font-weight: 100;
1. 네 맞습니다 이 부분은 UI/UX 측과의 상의가 필요해보이네요.
2. 네 백엔드 측에서도 바로 CDN 연결이 어려울테니 주석 처리 후 추후 바꾸는 방향으로 진행하죠.

2022-09-13 03:26 UTC, ChoiWonBeen commented on src/styles/fonts.scss
> +@include font-face("SUIT", "/assets/fonts/SUIT-Bold", "700");
현재 디자인에 나와있는 폰트는 400, 500, 700 정도인 것 같은데 확인해보고 사용하는 폰트는 주석처리할 필요가 없을거같아요.

2022-09-13 03:34 UTC, D0Dam commented on src/styles/fonts.scss
> +@include font-face("SUIT", "/assets/fonts/SUIT-Bold", "700");
이거 저도 확인해보려고 했는데 어떻게 확인하셨죠..?
일단 수요일날 회의 때 UI/UX 측과 상의 해보고 필요한 것 남기고 삭제한다고 하려 했습니다..!

2022-09-13 04:22 UTC, SimYunSup requested changes
바뀐 부분에 대해 리뷰드렸습니다.

2022-09-13 04:22 UTC, SimYunSup commented on src/styles/fonts.scss
> +@import "./mixin";
1. `@import`는 deprecated 예정입니다. `@use`로 바꿔주세요.
2. 분리한다면 `@forward`키워드를 사용해서 `index.scss`에 넣어서 import를 여러개 하지 마세요.

2022-09-13 04:22 UTC, SimYunSup commented on src/styles/mixin/index.scss
> +@use "sass:string";
해당 파일은 `utiils/styles/` 폴더에 위치하는 것이 맞습니다.

2022-09-13 05:30 UTC, D0Dam commented on src/styles/fonts.scss
> +@import "./mixin";
@SimYunSup 

1.  넵
2.  이 의미는 추가적으로 `font.scss`에 import를 할 일이 생긴다면 이 파일은 따로 건들지 말고 mixin 폴더의 `index.scss`에 `@forward`를 사용해 추가적으로 기능을 넣으라는 말인가요..?

2022-09-13 05:32 UTC, D0Dam commented on src/styles/fonts.scss
> +@include font-face("SUIT", "/assets/fonts/SUIT-Bold", "700");
UI/UX측에서 사용하는 폰트 wegiht가 확인되면 그 때 싹 고치겠습니다!

2022-09-13 07:47 UTC, SimYunSup commented on src/styles/fonts.scss
> +@import "./mixin";
```scss
@forward "src/styles/fonts.scss"
```
위 코드를 `index.scss`에 추가하여 App.js에서 import하는 scss 파일 개수를 줄이라는 의미였습니다.

2022-09-13 08:28 UTC, D0Dam commented on src/styles/fonts.scss
> +@import "./mixin";
아 이해했습니다😄

2022-09-13 10:35 UTC, jaewoogwak commented
저도 라이센스 관련해서 꼭 존재해야하나 궁금했었는데 위에 코멘트 되어있네요~ 코드 읽기 위해 SCSS 몰랐던거 다시 찾아보면서 공부가 됐습니다.  수고하셨습니다~

2022-09-13 10:37 UTC, jaewoogwak approved these changes

2022-09-13 11:28 UTC, SimYunSup approved these changes

2022-09-13 11:33 UTC, merged