[POST] 핀보기 기능
BCSDLab/TEMP_PROJECT_FE pull request #103
Opened 2023-09-07 14:25 UTC by KimKyungYun

## [#24] request
핀보기 기능을 구현했습니다.

- placeId를 핀에서 직접 가져올 수 없어서 검색 api를 통해 가져오고있습니다.
- 기존 UI에서 메뉴가 사이드로 이동하고 핀정보가 해당 메뉴에서 나오는 식으로 바뀌었기 때문에, 핀보기를 side메뉴에서 호출하는 방식으로 변경하였습니다.

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [ ] Docs updated for breaking changes

### Screenshot
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/60084235/c5c730d5-f329-48bf-90e9-ebdb81670814)
![스크린샷(22)](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/60084235/a0e19675-0ea0-4141-b2ac-cba9cdf030de)

2023-09-10 06:53 UTC, kimeodml reviewed
고생하셨습니다! 브랜치 최신화한 다음 코드 수정 부탁드립니다!

2023-09-10 06:53 UTC, kimeodml commented on src/pages/Pin/index.tsx
> +  }, [placeId, sortType]);
이 부분들 react-query대신 async/await을 활용한 이유를 알 수 있을까요?

2023-09-10 06:53 UTC, kimeodml commented on src/pages/Pin/index.tsx
> +                </div>
친구 리뷰는 `작성한 리뷰가 없어요`라는 문구여서 수정이 필요해 보여요!

2023-09-10 06:53 UTC, kimeodml commented on src/pages/Pin/components/Scrap.tsx
> +  const [scrapId, setScrapId] = useState<number>(-1);
새로고침시 값을 유지해야하기 때문에 localStorage에 저장하는 것은 어떨까요??

2023-09-10 06:53 UTC, kimeodml commented on src/pages/Home/static/marker.ts
>  export default MARKER;
이 파일 삭제한다는 게 까먹었네요. 삭제 부탁드립니다!

2023-09-12 13:19 UTC, KimKyungYun commented on src/pages/Pin/index.tsx
> +                </div>
사진이랑 같이 수정했습니다

2023-09-12 13:19 UTC, KimKyungYun commented on src/pages/Home/static/marker.ts
>  export default MARKER;
넵 삭제하겠습니다~!

2023-09-12 13:20 UTC, KimKyungYun commented on src/pages/Pin/index.tsx
> +  }, [placeId, sortType]);
한번 실수로 날라간적이 있었는데 그때 코드가 롤백됐나보네요ㅠ
useQueries로 수정했습니다

2023-09-12 22:13 UTC, KimKyungYun commented on src/pages/Pin/components/Scrap.tsx
> +  const [scrapId, setScrapId] = useState<number>(-1);
useEffect로 목록에 있나 없나 새롭게 조회하기 때문에 따로 추가하진 않았습니다. 방법을 바꾸는게 좋을까요?

2023-09-18 15:01 UTC, kimeodml reviewed
궁금한 사항이 있어서 추가적으로 리뷰했습니다!

2023-09-18 15:01 UTC, kimeodml commented on src/api/shop/entity.ts
> +export interface ShopPinResponse {
`ShopPinResponse`를 따로 추가한 이유를 알 수 있을까요?

2023-09-18 15:01 UTC, kimeodml commented on src/pages/Home/components/Map/index.tsx
> +  }, [selected]);
이 부분 깔끔하게 hooks로 관리하면 어떨까요? 하나의 컴포넌트에 너무 여러개를 불러오는 것 같아서요!

2023-09-18 15:01 UTC, kimeodml commented on src/pages/Pin/index.tsx
> +  };
이 부분도 hooks로 관리하는 건 어떨까요?

2023-09-18 15:01 UTC, kimeodml commented on src/pages/Pin/components/Scrap.tsx
> +  const [scrapId, setScrapId] = useState<number>(-1);
스크랩이 새로고침하면 -1값으로 변해서 localStorage로 관리가 필요해 보여요.
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/88065770/1ed8029f-9b71-4da7-b632-461726e52c0e)

2023-10-17 07:07 UTC, KimKyungYun commented on src/pages/Pin/components/Scrap.tsx
> +  const [scrapId, setScrapId] = useState<number>(-1);
수정했습니다

2023-10-17 07:09 UTC, KimKyungYun commented on src/api/shop/entity.ts
> +export interface ShopPinResponse {
이전에 따로 추가해서 사용하던 파라미터인데 머지 후 제거를 안했네요. 수정했습니다~

2023-10-17 07:23 UTC, KimKyungYun commented on src/pages/Home/components/Map/index.tsx
> +  }, [selected]);
훅으로 따로 분리해서 정리했습니다

2023-10-17 07:24 UTC, KimKyungYun commented on src/pages/Pin/index.tsx
> +  };
훅으로 분리해두었습니다!

2023-10-22 13:20 UTC, kimeodml requested changes
브랜치 최신화 한 후에 추가적으로 리뷰한 거 해결 부탁드립니다! 현재 브랜치가 많이 바뀌어서 코드가 추가적으로 수정이 필요할 수 있습니다. 또한, 브랜치 머지할 때 이전 브랜치의 코드로 머지되지 않게 주의해 주세요! 전에 코드 수정했는데 최신화 할때 이전 내용으로 머지가 되어서 또 다시 수정한 적이 있습니다! 리뷰 단 거 외에는 모바일 쪽 UI만 수정하면 될것 같아요! @KimKyungYun

2023-10-22 13:20 UTC, kimeodml commented on src/pages/Home/components/Map/index.tsx
> +      {isMobile && <BottomNavigation />}
사이드바/바텀 네비게이션이 메인페이지에 한정된 게 아니라서 이 부분은 다시 고려해봐야할것 같아요!

2023-10-22 13:20 UTC, kimeodml commented on src/pages/Pin/hooks/usePinQueries.ts
> +  const queries = useQueries([
이 부분 그냥 `queries`보단 명확하게 변수명을 지정하는 게 좋아보여요.

2023-10-22 13:20 UTC, kimeodml commented on src/pages/SearchDetails/components/SearchItemPC.tsx
> +import styles from 'pages/SearchDetails/SearchDetails.module.scss';
이거 원래 있던 파일 옮긴 건가요 아님 새로 만든 건가요? 이 부분 브랜치 최신화해서 확인 필요해 보입니다ㅠ 이러한 상황때문에 무조건 pr 올렸어도중간중간에  최신 브랜치인지 확인해 주세요!!!

2023-10-22 13:20 UTC, kimeodml commented on src/pages/Pin/components/Carousel.tsx
> +export default function Carousel({ images }:Props) {
요런 이미지 표현을 `Carousel`이라고 하나요?? 신기하네욯ㅎ

2023-10-22 13:20 UTC, kimeodml commented on src/pages/Pin/components/Carousel.tsx
> +      <button className={styles.carousel__left} onClick={() => setCount(count > 0 ? count - 1 : 0)} type="button">{'<'}</button>
각각 화살표에 `cursor: pointer` 추가해 주세요!

2023-10-22 13:20 UTC, kimeodml commented on src/pages/Pin/components/Carousel.tsx
> +        {images && images.map((item:string, index:number) => (
`object-fit`을 사용해서 이미지 크기를 맞출 수는 없을까요? 버튼이랑 이미지 부분이 겹치거든요!

2023-10-22 13:20 UTC, kimeodml commented on src/pages/Pin/components/Scrap.tsx
> +      await deleteScrap(scrapId);
deleteScrap의 scrapId는 데이터상의 scrapId가 필요한 거 아닌가요?? 그래서인지 스크랩 해제가 안 되고 있습니다!
변수명 구분이 필요해 보입니다!

2023-10-31 00:35 UTC, KimKyungYun commented on src/pages/SearchDetails/components/SearchItemPC.tsx
> +import styles from 'pages/SearchDetails/SearchDetails.module.scss';
이부분은 제가 만든게 아니라 delevop 머지했을 때 가져온 파일같습니다.
최신 develop으로 머지하고 진행하겠습니다~

2023-10-31 00:35 UTC, KimKyungYun commented on src/pages/Pin/components/Carousel.tsx
> +export default function Carousel({ images }:Props) {
회전목마처럼 빙글빙글 돈다고해서 carousel이라고 하더라구요 ㅎ

2023-10-31 00:36 UTC, KimKyungYun commented on src/pages/Pin/components/Carousel.tsx
> +      <button className={styles.carousel__left} onClick={() => setCount(count > 0 ? count - 1 : 0)} type="button">{'<'}</button>
추가했습니다!

2023-10-31 00:37 UTC, KimKyungYun commented on src/pages/Pin/components/Carousel.tsx
> +        {images && images.map((item:string, index:number) => (
일부러 약간 겹치게 하고 투명하게 만들어봤는데, 아예 겹치지 않게 하는것이 좋을까요?

2023-10-31 00:53 UTC, KimKyungYun commented on src/pages/Pin/hooks/usePinQueries.ts
> +  const queries = useQueries([
쿼리명 수정했습니다

2023-10-31 00:57 UTC, KimKyungYun commented on src/pages/Pin/components/Scrap.tsx
> +      await deleteScrap(scrapId);
제가 실행해서 확인해 봤을 때는 목록에서 제외되고 추가되는 모습이 다 확인되는데, 혹시 어떻게 출력되고 있는지 알 수 있을까요?

2023-10-31 00:58 UTC, KimKyungYun commented on src/pages/Home/components/Map/index.tsx
> +      {isMobile && <BottomNavigation />}
한번 이 부분에 대해서는 고민해보고 추후 수정하도록 하겠습니다

2023-11-10 10:56 UTC, kimeodml commented on src/pages/Pin/components/Scrap.tsx
> +      await deleteScrap(scrapId);
오잉? 아니네요. 잘못 확인한 것 같네요ㅠ 알맞게 잘 작동됩니다!

2023-11-10 10:58 UTC, kimeodml commented on src/pages/Pin/components/Carousel.tsx
> +        {images && images.map((item:string, index:number) => (
음...이미지 때문에 화살표가 가려진 것 처럼 보여서요! 화살표만 잘 보이면 상관없습니다!

2023-11-10 11:00 UTC, kimeodml commented on src/pages/Home/components/Map/index.tsx
> +      {isMobile && <BottomNavigation />}
음..그럼 이 부분은 다시 원래의 코드로 되돌리기에는 무리일까요?

2023-11-10 11:00 UTC, kimeodml approved these changes

2023-11-13 00:34 UTC, KimKyungYun commented on src/pages/Home/components/Map/index.tsx
> +      {isMobile && <BottomNavigation />}
음 핀보기가 사이드바에서 나오는 디자인으로 구성되어있어서.. 저렇게 사이드nav에 종속되지 않으면 완전 별개로 띄워야하는데, 어떻게 관리하는게 좋아보이시나요? 별개로 구성하면 사이드바를 닫아도 핀보기 페이지는 공중에 남아있게 될 것 같습니다

2023-12-28 02:44 UTC, closed without merging