[SEARCH] 검색페이지 UI 및 자동완성 기능
BCSDLab/TEMP_PROJECT_FE pull request #105
Opened 2023-09-21 12:15 UTC by hyejun0228

## [#86 ] request

- 검색 페이지의 전체적인 UI 수정했습니다. 
- 검색 페이지의 자동완성 api 를 연결했습니다. 자동완성 UI 는 Figma에 자세하게 나와있지 않아 최근 검색어 UI를 참고해서 만들어줬습니다. 

현재 과거의 검색 기록에 대한 API가 나와있지 않아, 추후 API가 추가되면 연결하겠습니다. 
자동완성 기능을 키고 끄는 기능 또한 과거 검색 기록과 UI를 공유하고 있기 때문에 다음 PR에 같이 올리겠습니다. 

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

### Screenshot

<img width="782" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/114041848/883bfa9b-62f9-454e-a418-0730850e7785">
<img width="809" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/114041848/67aaedfc-f555-4c41-9aa5-5d467150ba03">

2023-09-25 05:06 UTC, hanagertrudekim requested changes
수고하셨습니다~
간단하게 자잘한... 리뷰들 했는데 확인해주세요!

2023-09-25 05:06 UTC, hanagertrudeKim commented on src/pages/Search/components/NotFoundPage/NotFoundPage.module.scss
> +  color: var(--color, #666);
이곳에 `color` 설정을 왜 var로 하셨나요?

2023-09-25 05:06 UTC, hanagertrudeKim commented on src/pages/Search/components/NotFoundPage/NotFoundPage.module.scss
> +  line-height: normal;
`nomal` 속성은 기본값이니, 해당 프로퍼티들은 지워주셔도 될것같아요

2023-09-25 05:06 UTC, hanagertrudeKim commented on src/pages/Search/components/NotFoundPage/NotFoundPage.module.scss
> +}
```suggestion
.not-found-page__container {
  padding-top: 180px;
  max-width: 980px;
  margin: 0 auto;

&__title {
  width: 544px;
  height: 100px;
  color: #000;
  font-family: SUIT, system-ui;
  font-size: 40px;
  font-style: normal;
  font-weight: 400;
  line-height: normal;
}
}
```
bem 구조를 활용하는 방식으로 변경해주세요

2023-09-25 05:06 UTC, hanagertrudeKim commented on src/pages/Search/components/NotFoundPage/index.tsx
> +  // 전체 페이지를 이전에 건색 창이랑 동일하게 진행하자.
불필요한 주석은 삭제해주세요

2023-09-25 05:06 UTC, hanagertrudeKim commented on src/pages/Search/components/RelatedSearches/components/ToggleButton.module.scss
> +  &.active {
`.active` 로 선언해줘도 해당 속성이 들어가지않나요?

2023-09-25 05:06 UTC, hanagertrudeKim commented on src/pages/Search/components/RelatedSearches/components/ToggleButton.tsx
> +    <button type="submit" onClick={onClick} data-toggle={toggle ? 'true' : 'false'} className={`${styles.ToggleButton} ${toggle ? styles.active : ''}`}>
`data-toggle` 은 왜 camelCase로 바꾸시지않았나요?

2023-09-25 05:06 UTC, hanagertrudeKim commented on src/pages/Search/components/RelatedSearches/index.tsx
> +  const [toggle, setToggle] = useState(false);
`useBooleanState`를 이용해주세요

2023-09-25 05:06 UTC, hanagertrudeKim commented on src/pages/Search/components/RelatedSearches/index.tsx
> +  const { query: auto } = useFetchAutoComplete(text ?? '') as unknown as ShopData;
`unKnown` 과 `ShopData` 로 중복하여 타입을 단언하신 이유가 있나요?

2023-09-25 05:06 UTC, hanagertrudekim commented on src/pages/Search/components/SearchBar/SearchInput.tsx
> +// 여기서 검색을 눌렀는데 이제 keystring을 넣었는데 값이 없으면 4o4로 이동
주석 없애주세요!

2023-09-25 05:06 UTC, hanagertrudekim commented on src/pages/Search/components/SearchBar/SearchInput.tsx
> +        navigate('/search/not-found');
console 출력은 아직 api 추가하기 전이라 임의로 설정해두신건가요?

2023-09-25 05:06 UTC, hanagertrudekim commented on src/pages/Search/index.tsx
>            {isMobile ? !isSearching && <RollingBanner /> : <RollingBanner />}
이렇게되면 모바일여부에 상관없이 `Recommendation`과 `RollingBanner` 컴포넌트가 나오는거 아닌가요?

2023-09-25 05:06 UTC, hanagertrudekim commented on src/pages/Search/static/recommend.tsx
> +  // </div>,
주석처리하신 이유가 있나요?

2023-09-25 05:14 UTC, hyejun0228 commented on src/pages/Search/components/SearchBar/SearchInput.tsx
> +        navigate('/search/not-found');
저도 페이지를 처음부터 담당했던게 아니라서..해당부분은 아는게 없습니다..! 담당자분께 물어보고 다음 PR에서 수정하겠습니다

2023-09-25 05:15 UTC, hyejun0228 commented on src/pages/Search/index.tsx
>            {isMobile ? !isSearching && <RollingBanner /> : <RollingBanner />}
저도 페이지를 처음부터 담당했던게 아니라서..해당부분은 아는게 없습니다..! 담당자분께 물어보고 다음 PR에서 수정하겠습니다

2023-09-25 05:26 UTC, hyejun0228 commented on src/pages/Search/static/recommend.tsx
> +  // </div>,
이전 Figma에서는 Web, 모바일 페이지에서 해당 text를 랜덤으로 출력해주기 위해 해당 코드를 사용했던것으로 생각됩니다. 
하지만 현재 Fimga에서는 모바일 부분에서만 해당 text를 사용해주는것으로 나와있어, 디자인이 바뀐 Web쪽은 UI/UX팀에게 물어보고 처리해주는게 나을것 같다고 생각해 주석 처리 해뒀습니다. 
이후 PR에서 해당부분 질문 후 수정하겠습니다.

2023-09-25 05:26 UTC, hyejun0228 commented on src/pages/Search/components/SearchBar/SearchInput.tsx
> +// 여기서 검색을 눌렀는데 이제 keystring을 넣었는데 값이 없으면 4o4로 이동
네!

2023-09-25 05:27 UTC, hyejun0228 commented on src/pages/Search/components/NotFoundPage/index.tsx
> +  // 전체 페이지를 이전에 건색 창이랑 동일하게 진행하자.
넵!

2023-09-25 05:31 UTC, hyejun0228 commented on src/pages/Search/components/NotFoundPage/NotFoundPage.module.scss
> +  line-height: normal;
넵 수정하겠습니다

2023-09-25 05:41 UTC, hyejun0228 commented on src/pages/Search/components/NotFoundPage/NotFoundPage.module.scss
> +  color: var(--color, #666);
`NotFoundPage`는 제가 쓴 코드가 아니라 확실하게 이유를 알지 못합니다..! 
var를 사용하지 않아도 간단하게 색을 바꿀 수 있을 것같아 코드 수정해두겠습니다! 
9ba4d60188fd6a55b4ea8df1d18a29343da95ea3

2023-09-26 10:46 UTC, kimeodml requested changes
@hyejun0228 고생하셨습니다! 브랜치 최신화 하면 마저 리뷰 하겠습니다!
이때 **최신 코드가 수정되지 않게** 유의하면서 머지 부탁드려요!!! 전에 최신화하다가 이전 코드로 적용된 흔적이 있었거든요!! 아래 이미지 오류 해결도 부탁드려요~
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/88065770/9d427ada-3ab6-48fc-8409-f6706397498d)

2023-09-26 10:46 UTC, kimeodml commented on src/pages/Search/components/NotFoundPage/index.tsx
> +import img from 'assets/images/search/not-found-img.jpeg';
저 궁금한 게 관련 이미지 파일을 넣을때 images 폴더에 넣는 경우도 있고, svg 폴더에 넣는 경우도 있는데 혹시 기준이 뭔지 알 수 있을까요?

2023-09-26 10:46 UTC, kimeodml commented on src/pages/Search/index.tsx
> +  console.log('test', text);
불필요한 console.log는 지워도 될것같아요.

2023-09-26 10:46 UTC, kimeodml commented on src/pages/SearchDetails/hooks/useFetchAutoComplete.ts
> +  const options = {
상수값은 대문자로 부탁합니다!

2023-09-26 10:46 UTC, kimeodml commented on src/pages/Search/components/RelatedSearches/RelatedSearches.module.scss
> +  z-index: 1;
스크롤바 없애주세요!
```suggestion
  z-index: 1;
  scrollbar-width: none;

  &::-webkit-scrollbar {
    display: none;
  }
```

2023-09-28 12:34 UTC, hyejun0228 commented on src/pages/Search/components/RelatedSearches/components/ToggleButton.tsx
> +    <button type="submit" onClick={onClick} data-toggle={toggle ? 'true' : 'false'} className={`${styles.ToggleButton} ${toggle ? styles.active : ''}`}>
data-* 속성을 사용할 때 data-* 가 아닌 dataToggle 같은 이름으로 속성을 넣으면 적용이 되지 않습니다..!

2023-10-02 05:47 UTC, hyejun0228 commented on src/pages/Search/components/NotFoundPage/index.tsx
> +import img from 'assets/images/search/not-found-img.jpeg';
제가 코드 주인이 아니라 확실하진 않지만 svg는 간단한 로고나 아이콘을 사용할 때,  img는 복잡한 그림을 사용할때로 나누는경우가 많아 그 기준에 따라 분류한것으로 생각됩니다.

2023-10-02 06:47 UTC, hyejun0228 commented on src/pages/Search/index.tsx
> +  console.log('test', text);
넵 수정했습니다!

3581d11e9de93625d8ffbb25b15f417a28c340bc

2023-10-02 06:49 UTC, hyejun0228 commented on src/pages/Search/components/NotFoundPage/NotFoundPage.module.scss
> +}
넵 수정했습니다!

3581d11e9de93625d8ffbb25b15f417a28c340bc

2023-10-02 06:50 UTC, hyejun0228 commented on src/pages/Search/components/RelatedSearches/components/ToggleButton.module.scss
> +  &.active {
bem 구조로 하려고 고치다가 실수한것 같습니다..! 수정했습니다 
3581d11e9de93625d8ffbb25b15f417a28c340bc

2023-10-02 06:53 UTC, hyejun0228 commented on src/pages/Search/components/RelatedSearches/index.tsx
> +  const { query: auto } = useFetchAutoComplete(text ?? '') as unknown as ShopData;
아뇨..! 타입 단언 전체적으로 수정했습니다! 
3581d11e9de93625d8ffbb25b15f417a28c340bc

2023-10-02 06:55 UTC, hyejun0228 commented on src/pages/Search/components/RelatedSearches/RelatedSearches.module.scss
> +  z-index: 1;
넵 삭제했습니다! 7cde34d83b28fdb2da67587188a33b32587ed306

2023-10-02 06:59 UTC, hyejun0228 commented on src/pages/SearchDetails/hooks/useFetchAutoComplete.ts
> +  const options = {
`FetchAutoCompleteParams` -> `fetchAutoCompleteParams` 소문자로 수정했습니다..! 이부분 말씀하시는거 맞으실까요?!

2023-10-04 02:04 UTC, hyejun0228 commented on src/pages/Search/components/RelatedSearches/index.tsx
> +  const [toggle, setToggle] = useState(false);
넵 수정했습니다! f1d4c86fd87800c965d298c09c24c05d9ec7f940

2023-10-09 06:44 UTC, kimeodml approved these changes
@hyejun0228 뒤늦게 리뷰달아 죄송합니다! 이어서 리뷰하려고 했던 부분이 다 수정되어 있어서 고칠게 별로 없네욯ㅎㅎ 고생하셨습니다! 아래 몇가지만 수정하신 후에 머지해도 될것 같아요! 모바일은 다음 브랜치에서 진행하는 건 가요?

2023-10-09 06:44 UTC, kimeodml commented on src/pages/SearchDetails/hooks/useFetchAutoComplete.ts
> +  const options = {
정확하게 명시했어야 했는데 죄송해요ㅠ `OPTIONS` 값은 상수값이 라서 대문자 처리 부탁드립니다!

2023-10-09 06:44 UTC, kimeodml commented on src/pages/Search/components/RelatedSearches/RelatedSearches.module.scss
>    height: 100vh;
검색창 누르면 스크롤이 생기는 데 높이 부분 없애주세요!

2023-10-09 15:37 UTC, hyejun0228 commented on src/pages/Search/components/RelatedSearches/RelatedSearches.module.scss
>    height: 100vh;
모마일과 과거 검색 기능은 다음 PR에서 진행할 예정입니다! 
스크롤 height 수정 했습니다

d5c98b4ae65b5042da2790429faa6984f2f01555

2023-10-10 00:03 UTC, hanagertrudekim approved these changes

2023-10-10 00:06 UTC, merged

2023-10-10 12:42 UTC, ChoiWonBeen commented on src/api/search/entity.ts
> +  dist: 0,
number 겠져?

2023-10-10 12:43 UTC, ChoiWonBeen commented on src/api/search/index.ts
> +  };
이거 undefined면 요청이 x:undefined로 갈텐데 안되지 않을까요??
optional하면 안될듯!

2023-10-10 12:45 UTC, ChoiWonBeen commented on src/api/search/searchApiClient.ts
> +);
요거 반복 엄청 많을텐데 코인 Owner쪽 방식 채용하면 좋을거같아요
apiClient랑 accessClient였나? 뭐 그런 비슷한 이름의 뭔가 두가지로 구분한 거 있는데 다음에 리팩토링하는 PR올리면 좋을듯?

2023-10-10 12:45 UTC, ChoiWonBeen commented on src/pages/Search/components/NotFoundPage/index.tsx
> +          {' '}
불필요한 띄어쓰기같아욥

2023-10-10 12:46 UTC, ChoiWonBeen commented on src/pages/Search/components/RelatedSearches/components/ToggleButton.tsx
> +    <button type="button" onClick={onClick} data-toggle={isActive ? 'true' : 'false'} className={`${styles.ToggleButton} ${isActive ? styles.active : ''}`}>
그냥 isActive아닌가욥?

2023-10-10 12:47 UTC, ChoiWonBeen commented on src/pages/Search/components/RelatedSearches/index.tsx
> +          text === '' || !Array.isArray(auto)
auto가 뭔지 파악하기 힘들 것 같아요
요기 로직도 조금 복잡해보이는데 깔끔하게 정리할 수 있을듯!

2023-10-10 12:47 UTC, ChoiWonBeen commented on src/pages/Search/hooks/useSearching.ts
> +export default useSerching;
지워도 될것같아요

2023-10-10 12:48 UTC, ChoiWonBeen commented on src/pages/SearchDetails/hooks/useFetchAutoComplete.ts
> +  const options = {
그리고 밖으로 나가면 좋을거같아요~