Feature/#100 설정 페이지 추가 및 수정
BCSDLab/TEMP_PROJECT_FE pull request #106
Opened 2023-09-24 11:43 UTC by LUNA-KK

## [100] 설정 페이지 추가 및 수정
PC 설정 페이지를 추가하고 모바일 설정 페이지를 수정했습니다.
기존 모바일 페이지가 거의 완성되어 있는 상태라 유지하고 라우팅을 추가했습니다.

회원 탈퇴, 비밀번호 변경 기능을 추가했습니다.
SNS 사용자의 경우 비밀번호 변경 및 회원 탈퇴가 불가능합니다.

앱 버전을 확인하는 api가 없어서 우선 모달창만 구현했습니다.

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [ ] Docs updated for breaking changes

### Screenshot
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/110970349/c0f81b24-86dc-4969-9fbf-6fd98cf7e1e7)
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/110970349/5cc2f53a-9022-4db4-962a-9cd5e75151cd)

2023-09-25 03:06 UTC, hyejun0228 commented
고생하셨습니다! 

우선 pr제목을 다른 pr들 형식에 맞춰 수정해주세요.
수정이 필요해 보이거나 궁금한 사항 몇개 적어두었습니다.

2023-09-25 03:08 UTC, hyejun0228 reviewed
먼저 /Setting/PC 에서의 추가적인 폴더링이 필요할것 같은데 어떻게 생각하시나요?

2023-09-25 04:42 UTC, hanagertrudekim requested changes
수고하셨습니다!
우연히 들렀지만, 간단히 코멘트 할점이 보여서 적어두었으니 확인해주세요!

+`yarn.lock` 파일은 왜 수정이 되었는지 알수있을까요?

2023-09-25 04:42 UTC, hanagertrudeKim commented on src/pages/Follow/components/SearchPage.tsx
> +  const auth = useAuth() as User;
이곳에 타입 단언을 사용하신 이유가 있으신가요?

2023-09-25 04:42 UTC, hanagertrudekim commented on src/pages/Setting/PC/ManageAccount.tsx
> +      {isShowModal && <PasswordSuccessModal>변경된 비밀번호로 로그인 해주세요.</PasswordSuccessModal>}
password 완료 페이지에서만 쓰이는 모달인것같은데 굳이 children으로 해당 메시지를 넘겨주는 구조로 컴포넌트를 분리하신 이유가 있나요? 
(비슷한 구조로 분리하신 모달 컴포넌트들이 꽤 있는것같아서 질문드립니다)

2023-09-25 04:42 UTC, hanagertrudekim commented on src/pages/Setting/PC/ManageAccount.tsx
> +
필요없는 indent 분리는 없애주세요!

2023-09-25 04:42 UTC, hanagertrudekim commented on src/pages/Setting/PC/Service.tsx
> +        <div className={styles.service__contents}>
사소하지만 다른곳은 `content`로 네이밍이 되어있어 `content` 혹은 `contents` 둘 중 하나로 통일시키는게 좋을것같아요

2023-09-25 04:42 UTC, hanagertrudekim commented on src/pages/Setting/PC/hook/useModifyPassword.ts
> +
상수는 따로 파일 분리해주세요

2023-09-25 04:42 UTC, hanagertrudekim commented on src/pages/Setting/PC/hook/useModifyPassword.ts
> +  };
hook을 분리하는 이유중에 하나가, 관심사 분리도 있지만 동일한 구조의 state 호출을 줄이고 코드의 재활용성을 높인다는 관점도 있는것같습니다.
그러한 관점에서 본다면 위와 같은 코드는 hook이 아닌 그냥 함수 분리에 더 가까울것같아요.
구조상 custom hook으로 다시 정의하면 3번씩이나 동일한 구조의 함수를 정의할 필요도 없어지고, 해당 중복된 state호출도 줄어들것같습니다. 이에 대해서 어떻게 생각하시나요? 

(이번 기회에 hook을 분리하는 이유와, custom hook을 왜 쓰는지에 대해서도 고민해보시면 좋을것같아요 ㅎㅎ)

2023-09-25 04:42 UTC, hanagertrudekim commented on src/pages/Setting/PC/hook/useModifyPassword.ts
> +  };
`correctCheck`보다는 `passwordCorrectCheck` 처럼 명시적으로 바꿔주는것은 어떤가요?

2023-09-25 04:42 UTC, hanagertrudekim commented on src/pages/Setting/PC/hook/useTripleBlindCheck.ts
> +};
`useBooleanState()` 를 사용한다면 해당 hook을 정의할 필요는 없을것같습니다

2023-09-25 04:42 UTC, hanagertrudekim commented on src/pages/Setting/PC/index.tsx
> +        <div className={style.selectContainer}>
여기에만 camelCase로 className을 지정하신 이유가 잇나요?

2023-09-25 04:51 UTC, hyejun0228 requested changes
고생하셨습니다! 
우선 pr제목을 다른 pr들 형식에 맞춰 수정해주세요.
수정이 필요해 보이거나 궁금한 사항 몇개 적어두었습니다. 

+/Setting/PC 에서의 추가적인 폴더링이 필요할것 같은데 어떻게 생각하시나요? 

+전체적으로 버튼에 `cursor: pointer` 추가 부탁드립니다!

2023-09-25 04:51 UTC, hyejun0228 commented on src/pages/Setting/PC/Service.tsx
> +  const [isShowModal, setIsShowModal] = useState(false);
이 코드를 포함해서 전체적인 토글 형식들은 useBooleanState를 사용해 바꾸는게 어떨까요?

2023-09-25 04:51 UTC, hyejun0228 commented on src/pages/Setting/PC/Service.module.scss
> +  }
local 에서 확인했을 때 탈퇴하기 부분에 링크 표시가 남아있어, 수정이 필요할 것 같습니다.

2023-09-25 04:51 UTC, hyejun0228 commented on src/pages/Setting/PC/hook/useModifyPassword.ts
> +  Type_Error: '비밀번호는 문자, 숫자, 특수문자를 포함한 8~16 자리로 이루어져야 합니다.',
Type_Error 의 문자열이 figma에서는 두줄로 분리되어 나타나 있어서 메세지를 나눠서 선언해줘야할것 같습니다.

2023-09-25 04:51 UTC, hyejun0228 commented on src/pages/Setting/UserSetting/index.tsx
<img width="581" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/114041848/7ecf963f-1a67-463c-ba0c-a7e80d5f5cd3">

CSS 부분의 위치를 수정하는게 좋을것 같아요
figma와 비교해보니 계정관리, 서비스의 페이지가 밑으로 살짝 내려가있는것 같습니다!

2023-09-25 04:51 UTC, hyejun0228 commented on src/pages/Setting/UserSetting/index.tsx
설정 페이지를 만드시면서 컴포넌트 분리 기준을 어떤식으로 세우셨나요? 

제가 생각했을 때는 최소한 한 "view"를 기준으로 컴포넌트를 분리하는 것이 더 좋아보입니다! 
지금은 뷰에 따라 컴포넌트가 분리 되지 않고 있어 전체적인 코드 흐름을 파악하기 어려워보입니다. 
이번 기회에 컴포넌트를 어떤 기준을 가지고 분리를 할지 생각해 보시면 다음 PR에 도움이 되실것같아요.

2023-10-06 12:47 UTC, LUNA-KK commented on src/pages/Follow/components/SearchPage.tsx
> +  const auth = useAuth() as User;
SNS 로그인을 한 상태에서는 account가 필요 없기에 타입 단언을 사용했습니다.

2023-10-06 12:51 UTC, LUNA-KK commented on src/pages/Setting/PC/ManageAccount.tsx
> +      {isShowModal && <PasswordSuccessModal>변경된 비밀번호로 로그인 해주세요.</PasswordSuccessModal>}
모달의 UI가 동일해서 재사용성을 높이기 위해 이와 같은 구조를 사용했습니다.

2023-10-06 12:53 UTC, LUNA-KK commented on src/pages/Setting/PC/ManageAccount.tsx
> +
수정하겠습니다!

2023-10-06 12:53 UTC, LUNA-KK commented on src/pages/Setting/PC/Service.tsx
> +        <div className={styles.service__contents}>
content로 통일하겠습니다.

2023-10-06 13:00 UTC, LUNA-KK commented on src/pages/Setting/PC/hook/useModifyPassword.ts
> +
넵 수정하겠습니다!

2023-10-06 13:04 UTC, LUNA-KK commented on src/pages/Setting/PC/hook/useModifyPassword.ts
> +  };
전역상태관리를 사용하지 않고 한 파일 안에서 state를 용이하게 관리할 수 있기에 이와 같은 구조를 사용했습니다..!

2023-10-06 13:04 UTC, LUNA-KK commented on src/pages/Setting/PC/hook/useModifyPassword.ts
> +  };
수정하겠습니다!

2023-10-06 13:20 UTC, LUNA-KK commented on src/pages/Setting/PC/index.tsx
> +        <div className={style.selectContainer}>
BEM 사용에 미숙했던 것 같습니다. 수정하겠습니다!

2023-10-06 13:22 UTC, LUNA-KK commented on src/pages/Setting/PC/hook/useTripleBlindCheck.ts
> +};
너무 좋은 방법이네요!!
바로 적용했습니다.

2023-10-06 13:25 UTC, LUNA-KK commented
다른 branch를 merge 받고 필요한 라이브러리가 있어서 설치했습니다.
@hanagertrudekim

2023-10-06 13:33 UTC, LUNA-KK commented on src/pages/Setting/PC/Service.tsx
> +  const [isShowModal, setIsShowModal] = useState(false);
수정했습니다!

2023-10-06 13:39 UTC, LUNA-KK commented on src/pages/Setting/PC/Service.module.scss
> +  }
figma에 링크 표시가 있어서 넣었었습니다!
수정이 필요할까요?

2023-10-06 14:28 UTC, LUNA-KK commented on src/pages/Setting/UserSetting/index.tsx
수정했습니다!

2023-10-06 14:32 UTC, LUNA-KK commented on src/pages/Setting/UserSetting/index.tsx
한 view를 기준으로 분리하는 것이 더 용이해보이네요!
컴포넌트의 관심사를 고려해서 세분화해보도록 하겠습니다.

2023-10-06 14:37 UTC, LUNA-KK commented
PC, Mobile, hook, static 폴더로 나누어보았습니다.
더 세밀하게 파일을 분류할 필요가 있을까요?
+ pointer 추가했습니다!
@hyejun0228

2023-10-06 15:02 UTC, LUNA-KK commented on src/pages/Setting/PC/hook/useModifyPassword.ts
> +  Type_Error: '비밀번호는 문자, 숫자, 특수문자를 포함한 8~16 자리로 이루어져야 합니다.',
방법을 찾지 못해서 조금 더 고민해보겠습니다.

2023-10-07 03:36 UTC, hyejun0228 commented on src/pages/Setting/PC/Service.module.scss
> +  }
figma에 표시돼있는 밑줄과는 색상이 다른걸로 보아 링크 표시가 아닌 `text-decoration: underline;` 으로 보여집니다

2023-10-07 07:26 UTC, hanagertrudekim commented on src/pages/Follow/components/SearchPage.tsx
> +  const auth = useAuth() as User;
타입 단언이 어떤 값이 반환되는지에 상관없이 그냥 `User` 로 타입을 강제하는건데, 그러면 `useAuth()` 을 다른곳에서 쓸때도 `User`로 타입을 맞춰야하는 문제도 생기지않을까요?
(타입을 추론하지못하도록 강제시키는것은 정말 필요한 경우가 아니면 최대한 지양하는것이 좋다고 생각해요)

2023-10-10 12:49 UTC, ChoiWonBeen commented on src/api/user/entity.ts
> +export type Users = User | SNSUser;
User**s** 면 아래처럼 추론되어야 할 것 같은데 의도랑 다른가요?
```suggestion
export type Users = Array<User | SNSUser>;
```

2023-10-10 12:51 UTC, ChoiWonBeen commented on src/api/user/entity.ts
> +export type Users = User | SNSUser;
단수형이라면 아래처럼 쓰는것도?
```suggestion
export type User = EmailUser | SNSUser;
```

2023-10-10 13:02 UTC, ChoiWonBeen commented on src/pages/Follow/components/SearchPage.tsx
> +  const auth = useAuth() as User;
auth 가 `User | null`로 추론될텐데,
로그인이 된 상태로만 접근할 수 있는 페이지라면 여태까지는 조건문을 적었지만
런타임 assert 방식 << 요 키워드로 한번 검색해서 적용해보는걸 추천드려요
```ts
assert(auth !== null, "유저 정보가 없습니다);
// 여기서부터는 auth의 타입이 User로 추론됨
```

2023-10-10 13:04 UTC, ChoiWonBeen commented on src/pages/Setting/PC/LogoutModal.tsx
> +  return createPortal(
쓰는거 좋네요 👍

2023-10-10 13:06 UTC, ChoiWonBeen commented on src/pages/Setting/PC/ManageAccount.tsx
> +  } = useModifyPassword();
확장성이 상당히 조심스럽습니다만

관련 있는 기능들끼리 모으는건좋은데 다만 지금은 너무 응집된 것 같아요.
관련성 있는 애들끼리 모아서 추상화한다면 더 좋은 구조가 될 듯?
`handleNewPassword` << 이런건 변수명을 바꿔야 할 것 같구요 ㅋㅋㅋ

2023-10-10 13:08 UTC, ChoiWonBeen commented on src/pages/Setting/PC/ManageAccount.tsx
> +        <input className={style.account__input} value={auth && 'account' in auth ? auth.account : 'SNSLogin'} disabled />
요런것도 읽는입장에서는 도메인 지식이 없을 수 있으니 읽기 좋게 함수를 추가하는것도 방법인 것 같아요
```ts
const isEmailLogin = (auth) => 'account' in auth
```
```suggestion
        <input className={style.account__input} value={isEmailLogin(auth) ? auth.account : 'SNSLogin'} disabled />
```

2023-10-10 13:09 UTC, ChoiWonBeen commented on src/pages/Setting/PC/ManageAccount.tsx
> +                message === ERROR_MESSAGE.Current_Error || message === ERROR_MESSAGE.Type_Error,
요건 어디서 정의된거예요?
Current_Error << 이거 컨벤션이 혼자 특이한듯?

2023-10-10 13:12 UTC, ChoiWonBeen commented on src/pages/Setting/PC/hook/useModifyPassword.ts
> +  Type_Error: '비밀번호는 문자, 숫자, 특수문자를 포함한 8~16 자리로 이루어져야 합니다.',
#61 PR의 `src/pages/Search/static/recommend.tsx` 처럼 JSX로 구성하면 중간에 br태그를 넣을 수 있을거예욥

2023-10-10 13:13 UTC, ChoiWonBeen commented on src/pages/Setting/PC/hook/useModifyPassword.ts
> +  };
확장성 고려해주신다면 아마 쪼갤 필요가 있을거예요
한쪽으로 모인다고해서 꼭 보기좋은게 아닐 수도 있어요 👀

2023-10-10 13:18 UTC, ChoiWonBeen commented on src/pages/Setting/Withdrawal/useSecession.ts
> +  const { mutate: deleteAccount } = useMutation('secession', () => secession());
deleteAccount 라고 적었으면 통일해도..괜찮을듯?
아마 같은 프로젝트 내에서 탈퇴를 withdrawal인가로 적고있을거라 용어통일이 필요해보여욥

2023-10-10 13:19 UTC, ChoiWonBeen commented on src/store/auth.ts
> +const getAuth = async (): Promise<Users | null> => {
이거 추론되는거 아니예요?

2023-10-12 10:28 UTC, LUNA-KK commented on src/pages/Follow/components/SearchPage.tsx
> +  const auth = useAuth() as User;
auth가 현재 Users | null로 추론되고 있습니다!
Users가 아닌 User에 account가 있기 때문에 User로 추론되어야 합니다
이럴 경우 어떻게 해야 할까요..?

2023-10-12 10:35 UTC, LUNA-KK commented on src/api/user/entity.ts
> +export type Users = User | SNSUser;
사용자는 EmailUser 또는 SNSUSer 둘 중 하나로만 선택되는 단수형이기 때문에 인터페이스명 변경하도록 하겠습니다.

2023-10-12 13:41 UTC, ChoiWonBeen commented on src/pages/Follow/components/SearchPage.tsx
> +  const auth = useAuth() as User;
User.. Users.. 여기 용어때문에 헷갈려하시는 것 같은데 아래 리뷰 적용해 `User = EmailUser | SNSUser`로 적용했다면 어떻게 해석해야할까요?

2023-10-14 06:50 UTC, LUNA-KK commented on src/pages/Follow/components/SearchPage.tsx
> +  const auth = useAuth() as User;
38935f703c65d3483e4c851d422ec47dc93c8079 인터페이스명 변경했습니다!
useAuth가 User | null을 반환하기 때문에 현재 auth는 User | null로 추론되고 있습니다.
하지만 현재 페이지에서는 account가 필요하기 때문에 EmailUser로 추론되어야 합니다.
현재 유니온 타입으로 설정한 User를 어떻게 EmailUser로 추론되게 할 수 있나요???

2023-10-14 07:22 UTC, LUNA-KK commented on src/pages/Setting/PC/hook/useModifyPassword.ts
> +  };
f793f72e9ebdbc6a96d376f24db7edcd37242ef8
비밀번호 변경 state들을 custom hook으로 재정의하고,
setIsShowError와 setIsShowmodal을 useBooleanState로 대체하였습니다.

2023-10-14 07:52 UTC, LUNA-KK commented on src/pages/Setting/PC/ManageAccount.tsx
> +  } = useModifyPassword();
d223a63693277abf5d9ea508ecd0034579ebb391
변경 완료했습니다.

2023-10-14 08:15 UTC, LUNA-KK commented on src/pages/Setting/PC/Service.module.scss
> +  }
601ec765c5bbc9042b3d928f44e7e7856fd96539
수정했습니다.

2023-10-14 08:21 UTC, LUNA-KK commented on src/pages/Setting/PC/ManageAccount.tsx
> +                message === ERROR_MESSAGE.Current_Error || message === ERROR_MESSAGE.Type_Error,
37a94160eaac5fae497e11dc3cfb1d5052c9a07c
카멜케이스로 변경했습니다.

2023-10-14 08:22 UTC, LUNA-KK commented on src/store/auth.ts
> +const getAuth = async (): Promise<Users | null> => {
SNSUser로 추론되어 반환값을 써줬습니다.

2023-10-14 09:19 UTC, LUNA-KK commented on src/pages/Setting/PC/hook/useModifyPassword.ts
> +  Type_Error: '비밀번호는 문자, 숫자, 특수문자를 포함한 8~16 자리로 이루어져야 합니다.',
7430094768e67881275c15933a0fa3c68f910975
수정 완료했습니다!

2023-10-14 09:19 UTC, LUNA-KK commented on src/pages/Setting/Withdrawal/useSecession.ts
> +  const { mutate: deleteAccount } = useMutation('secession', () => secession());
37a94160eaac5fae497e11dc3cfb1d5052c9a07c
변수명 통일했습니다.

2023-10-22 12:58 UTC, ChoiWonBeen commented on src/pages/Follow/components/SearchPage.tsx
> +  const auth = useAuth() as User;
런타임 assert 방식을 적용하면 좋겠지만,
if문으로 단순 분기해서 컴포넌트의 return을 다르게 나눌 수도 있겠네요.
SNSUser인경우에는 다르게 분기가 되어야하는거잖아요?

2023-10-22 14:12 UTC, LUNA-KK commented on src/pages/Follow/components/SearchPage.tsx
> +  const auth = useAuth() as User;
0f191a7add8735127e4b3b80aa60748653d13466
수정했습니다. 감사합니다!

2023-10-22 14:12 UTC, LUNA-KK commented on src/pages/Setting/PC/ManageAccount.tsx
> +        <input className={style.account__input} value={auth && 'account' in auth ? auth.account : 'SNSLogin'} disabled />
46213688d3d4a0aa8cefbb3b44c3de1f4a976812
수정했습니다!

2023-10-22 15:47 UTC, hyejun0228 approved these changes

2023-10-22 15:50 UTC, hanagertrudekim approved these changes

2023-10-23 09:29 UTC, merged