[Map] 메인 페이지 지도 구현
BCSDLab/TEMP_PROJECT_FE pull request #107
Opened 2023-10-09 13:37 UTC by kimeodml

## [#102] request

- 마커 클러스터링 구현 및 모바일 디자인 수정했습니다.
- 몇가지 기능들을 추가 및 수정했습니다.
  - 로그인 시 사이드바에 프로필 이미지 표시
  - 마커에 표시되는 이미지를 상점 이미지로 변경
  - 검색바 클릭시 검색 페이지로 이동
  - 사이드바 펼쳐진 상태를 기본값으로 변경

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

### Screenshot
<img src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/88065770/910b3adf-a966-4a06-881f-874a54e8a3e8" width="100%" />
<img src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/88065770/e188b30f-e8e4-4ee8-abbf-2d17bf584963" width="30%" />

2023-10-10 06:39 UTC, chaeseungyun requested changes
고생하셨습니다!
제 환경에서 에러가 하나 있는데 확인 부탁드리겠습니다

2023-10-10 06:39 UTC, chaeseungyun commented on src/components/common/SideNavigation/index.tsx
> +                src={auth.profileImage.url || `${defaultImage}`}
현재 auth.profileImage가 undefined로 뜨는데 확인 부탁드립니다!

2023-10-10 12:17 UTC, ChoiWonBeen commented on src/api/shop/entity.ts
>    placeId: string;
전에는 string[]이었는데 그냥 string이 되어도 괜찮은건가요?

2023-10-10 12:18 UTC, ChoiWonBeen commented on src/api/user/entity.ts
> +  }
이거 없을 수도 있지 않나욥?
그냥 회원가입하면 기본이미지 들어가려나?

2023-10-10 12:20 UTC, ChoiWonBeen commented on src/components/common/SideNavigation/index.tsx
> +  const [visible, , , toggle, setValue] = useBooleanState(true);
마이너) setValue보단 적절하게 visible로 통일해도 좋을 것 같아요
```suggestion
  const [visible, , , toggle, setVisible] = useBooleanState(true);
```

2023-10-10 12:21 UTC, ChoiWonBeen commented on src/index.scss
> +/* stylelint-disable declaration-colon-newline-after */
이 규칙을 빼는것도 괜찮을 것 같아요? 전역으로

2023-10-10 12:23 UTC, ChoiWonBeen commented on src/pages/Home/Home.module.scss
> +  z-index: 1;
z-index를 상수파일로 모아두면 높이 관리가 좀 더 수월할 것 같은데 관리 방식 찾아보는것도? 괜찮을 것 같아요
쓰임새가 적절하다면 적용해보는것도 재밌겠네요 👀

2023-10-10 12:25 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/components/MarkerHtml/MarkerHtml.module.scss
> +  background-image: url("../../../../../../assets/images/home/location-marker.png");
요거 상대경로밖에 안되나용?? (진짜모름)

2023-10-10 12:26 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/components/MarkerHtml/index.tsx
> +export function MarkerHtml(photo:string, name:string) {
이런 값들은 조금 추상적으로 작성해도 문제없을 것 같아요
```suggestion
export function MarkerHtml(img:string, name:string) {
export function MarkerHtml(src:string, name:string) {
```

2023-10-10 12:27 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/components/MarkerHtml/index.tsx
> +        <img src=${photo || `${defaultImage}`} alt="사진" />
photo가 nullable하지 않은데 이러면 앞의 조건만 실행되지 않을까요?

2023-10-10 12:31 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/components/MobileOptions/index.tsx
> +          [styles['nav__icon--changed']]: filterNearbyState === 1 || filterScrapState === 1 || filterFriendState === 1,
boolean이라면 아래처럼 써도 괜찮을 것 같은데, 서버에서 1, 0을 쓴다고 저희도 1, 0으로 코드를 짤 필욘 없을 것 같아요(그냥 가독성을 위해서니깐 굳이 적용은 안해도 될 것 같아요 그냥팁)
```suggestion
          [styles['nav__icon--changed']]: filterNearbyState || filterScrapState || filterFriendState,
```

2023-10-10 12:33 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/components/MobileOptions/index.tsx
> +            <StoreFrontIcon />
Nearby로 통일해도 좋을 것 같네영 👀

2023-10-10 18:43 UTC, hyejun0228 requested changes
수고하셨습니다! 궁금한점 리뷰 달아놨습니다. 

+ 모바일 버전에서 오른쪽 밑에 있는 네이버 마크가 figma에는 없어서 수정해야할 것 같습니다.

2023-10-10 18:43 UTC, hyejun0228 commented on src/pages/Home/components/Map/components/MarkerHtml/index.tsx
>      <img src=${MarkerLogo}  class=${styles.marker} alt="marker" />
궁금해서 질문 남깁니다! 
지금까지 SCSS를 지정해줄때 `className={styles.어쩌구}` 이런식으로 지정해주곤 했는데, `class=${styles.container}` 이 방법과는 뭐가 다른건가요??

2023-10-11 09:40 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/components/MarkerHtml/index.tsx
>      <img src=${MarkerLogo}  class=${styles.marker} alt="marker" />
잘 보면 얜 JSX를 반환하지 않아요
(`) 백틱으로 감싸진 문자열을 반환하는데, 네이버 지도 라이브러리에 HTML 문자열을 보내줘야 해서 그런 것 같네요 ㅋㅋ

2023-10-17 13:24 UTC, kimeodml commented on src/api/shop/entity.ts
>    placeId: string;
반환값을 url string타입으로 넘겨줘서 괜찮습니다!

2023-10-17 13:27 UTC, kimeodml commented on src/api/user/entity.ts
> +  }
빈 이미지 값이 들어가서 프로필 상으로 기본 이미지 부분 추가했습니다. [3055ccd](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/107/commits/3055ccdb58ab307bd70a14eb6eedff0f8aba85fc)

2023-10-17 13:45 UTC, kimeodml commented on src/pages/Home/Home.module.scss
> +  z-index: 1;
구현이 우선인 것 같아서 이 부부분은 추후에 고려해 보겠습니다!!

2023-10-17 14:41 UTC, kimeodml commented on src/pages/Home/components/Map/components/MarkerHtml/index.tsx
> +        <img src=${photo || `${defaultImage}`} alt="사진" />
이미지가 null값으로 넘어갈 때에도 있어서 추가했습니다. 타입 부분도 수정하겠습니다!

2023-10-17 14:51 UTC, kimeodml commented on src/pages/Home/components/Map/components/MarkerHtml/index.tsx
>      <img src=${MarkerLogo}  class=${styles.marker} alt="marker" />
content 타입이 string이라 백틱을 사용했습니다.

2023-10-17 14:56 UTC, kimeodml commented on src/components/common/SideNavigation/index.tsx
> +                src={auth.profileImage.url || `${defaultImage}`}
수정했습니다. [c4f9d04](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/107/commits/c4f9d04e8bb26ba89ef84b81b56d8e95a61e4ed0)

2023-10-17 14:57 UTC, kimeodml commented on src/components/common/SideNavigation/index.tsx
> +  const [visible, , , toggle, setValue] = useBooleanState(true);
수정했습니다. [173232d](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/107/commits/173232d5fff93e1bed2ba0e39f5f37bf80144e47)

2023-10-17 14:57 UTC, kimeodml commented on src/pages/Home/components/Map/components/MarkerHtml/index.tsx
> +export function MarkerHtml(photo:string, name:string) {
수정했습니다. [6eb2187](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/107/commits/6eb2187578563785ac0975a002a12ac69e840efc)

2023-10-17 14:58 UTC, kimeodml commented on src/pages/Home/components/Map/components/MobileOptions/index.tsx
> +            <StoreFrontIcon />
수정했습니다. [9d610db](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/107/commits/9d610db445bce9b754555a5b33c51f45254b361c)

2023-10-17 15:05 UTC, kimeodml commented on src/pages/Home/components/Map/components/MobileOptions/index.tsx
> +          [styles['nav__icon--changed']]: filterNearbyState === 1 || filterScrapState === 1 || filterFriendState === 1,
이 부분도 추후에 수정하는 것으로 하겠습니다!

2023-10-17 15:53 UTC, kimeodml commented on src/pages/Home/components/Map/components/MarkerHtml/MarkerHtml.module.scss
> +  background-image: url("../../../../../../assets/images/home/location-marker.png");
오잉 되네요...?ㅎㅎ 수정했습니다. [cfe867a](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/107/commits/cfe867aebd0399b553e37618661f7c021a09e276)

2023-10-19 11:37 UTC, kimeodml commented on src/index.scss
> +/* stylelint-disable declaration-colon-newline-after */
근데 전역으로 비활성화 하는 것 보다 일관되게 유지하는 게 낫지 않나요...? 
예외처리 넣는 게 전역으로 빼는 것 보다 나을것 같아서요!

2023-10-19 11:39 UTC, kimeodml commented
> 수고하셨습니다! 궁금한점 리뷰 달아놨습니다.
> 
> * 모바일 버전에서 오른쪽 밑에 있는 네이버 마크가 figma에는 없어서 수정해야할 것 같습니다.

로고 제거 하는 옵션이 있었는데 현재는 그 기능을 빼 버렸더라고요. 그래서 네이버 마크는 유지해야합니다!

2023-10-20 07:13 UTC, hyejun0228 approved these changes

2023-10-23 08:56 UTC, chaeseungyun approved these changes

2023-10-23 10:49 UTC, merged