[FOLLOW] 친구 목록 페이지 UI 수정 및 에러 처리
BCSDLab/TEMP_PROJECT_FE pull request #108
Opened 2023-10-14 17:44 UTC by chaeseungyun

## [#104] request
pc버전 친구 목록 페이지 UI를 수정했고
모바일 버전에서 팔로우를 취소할 때의 모달창을 추가했습니다.

현재 서버에서 호출 횟수 초과로 인해 친구 프로필 페이지에 들어가면 500 에러가 발생합니다
따라서 당분간 친구 프로필 UI를 확인하지 못할 수 있습니다

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [ ] Docs updated for breaking changes

### Screenshot
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/101871802/d6be873c-ed21-430d-9ae0-6aee5df67104)
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/101871802/71f424c4-120b-4504-8f48-9fc3cf032dad)

2023-10-20 11:29 UTC, kimeodml requested changes
전체적으로 기능은 문제 없는 것 같아요! 근데 UI만 조금 수정하면 될듯..? 특히 모바일쪽이 PC 쪽이랑 유지되는 것들이 몇가지가 있어서 font-size 수정해주세요! 브랜치 최신화한 후에 수정 부탁드립니다!

2023-10-20 11:29 UTC, kimeodml commented on src/pages/Follow/index.tsx
>      <div className={style.template}>
화면 줄일때 왼쪽이 잘려서 수정 필요할것 같아요!
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/88065770/7d683692-417e-479b-8502-7c6fa41e6f40)

2023-10-20 11:29 UTC, kimeodml commented on src/pages/Follow/components/Follower.tsx
>        <img className={style.follower__image} src={defaultImage} alt="default" />
프로필쪽에 `cursor:pointer` 추가해 주세요.

2023-10-20 11:29 UTC, kimeodml commented on src/pages/Follow/components/ListReview.tsx
> +  const restArray = new Array<number>(5 - rate).fill(1);
요거 변수명이 조금 더 직관적이게 별과 관련된 변수명으로 수정하는 거 어떨까요? ex) `fillStarArray-emtyStartArray`

2023-10-20 11:29 UTC, kimeodml commented on src/pages/Follow/components/ListReview.tsx
> +import { ReactComponent as EmptyStar } from 'assets/svg/follow/empty-star.svg';
변수명 바꾸게 된다면 통일성 있게 rate.svg도 바꿔주세요!

2023-10-20 11:29 UTC, kimeodml commented on src/pages/Follow/components/ListReview.tsx
> +          </span>
저희 별점 X.5도 되지 않나요...?

2023-10-20 11:29 UTC, kimeodml commented on src/pages/Follow/components/FollowProfile.module.scss
> +  }
width: 100%라서 모바일 버전일 때 좌우 여백이 없는데 약간 줄이는 거 어떨까요?

2023-10-20 11:29 UTC, kimeodml commented on src/pages/Follow/index.tsx
>      <div className={style.template}>
모바일일때 스크롤 생기는 데 스크롤도 같이 없애주세요!

2023-10-20 11:29 UTC, kimeodml commented on src/pages/Follow/index.tsx
>      <div className={style.template}>
relative라서 요런듯...? 수정 필요해 보입니다!
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/88065770/b57430f1-fdde-42fd-baf8-7f79e838cec7)

2023-10-20 11:29 UTC, kimeodml commented on src/pages/Follow/components/MobileUnfollow.tsx
> +export default function MobileUnfollow({
모바일 -> PC로 전환될때 계속 유지돼서 isMobile 추가해야할듯 싶네요!
그리고 너무 커서 사이즈 조금 줄여보는 거 어떠세요...? svg 이미지가 깨지더라고요!

2023-10-20 14:55 UTC, hyejun0228 requested changes
고생하셨습니다! 리뷰가 너무 늦어졌네요..🥲

2023-10-20 14:55 UTC, hyejun0228 commented on src/pages/Follow/components/Follower.tsx
> +          [style['follower__button--request']]: followedType === 'NONE',
현재 버튼의 동작과 스타일을 결정하는 로직이 여러 번 반복되는 것 같습니다! 
followedType 값을 기반으로 밑의 코드와 같이 객체를 사용한다면 가독성이 더 좋아질 것 같은데.. 어떻게 생각하시나요? 

```typscript
const buttonConfigs = {
  NONE: {
    className: style['follower__button--request'],
    onClick: () => request(account),
    text: '팔로우'
  },
  REQUEST_SENT: {
    className: style['follower__button--cancel'],
    onClick: () => requestId && cancel(requestId),
    text: '요청됨'
  },
  // + FOLLOWED, REQUEST_RECEIVE 로직 추가
};

const config = buttonConfigs[followedType];

return (
  <>
    <button
      className={cn(config.className)}
      type="button"
      onClick={config.onClick}
    >
      {config.text}
```

2023-10-20 15:32 UTC, hyejun0228 requested changes
추가적으로 궁금한거 몇개더 적어봤습니다!

2023-10-20 15:32 UTC, hyejun0228 commented on src/pages/Follow/components/FollowProfile.tsx
>    };
이부분은 entity파일에서 이미 정의된 부분 아닌가요?? 👀

2023-10-20 15:32 UTC, hyejun0228 commented on src/pages/Follow/components/FollowProfile.tsx
> -          <img alt="img" src={defaultImage} className={style.user__profile} />
alt 에는 이미지에 대한 간단한 설명이 들어가는것이 좋을 것 같습니다! 
저도 어디서 들은거지만.. 나중에 회사에서는 이부분을 중요하게 본다고 하더라구요!

2023-10-20 15:32 UTC, hyejun0228 commented on src/pages/Follow/components/FollowProfile.tsx
>              >
`canDelete` 라는 표현은.. 이상한것 같습니다!

2023-10-20 15:33 UTC, hanagertrudekim requested changes
간단한 코멘트 몇가지 확인해주세요~

2023-10-20 15:33 UTC, hanagertrudekim commented on src/pages/Follow/components/MobileUnfollow.tsx
> +  del: UseMutateFunction<AxiosResponse<any, any>, unknown, string, unknown>;
굳이 `del` 라고 함축하지않고 `delete`로 써도 될것같아요.
(앞선 코드들에서도 `del`로 통일된것이 많이 보이니, 모두 수정해주세요)
또한, `AxiosResponse` 타입에서 특별한 이유가 없다면 `any`는 지양하는게 좋을것같아요.

2023-10-20 15:33 UTC, hanagertrudekim commented on src/pages/Follow/hooks/useGetFollowerReviewCount.ts
>  const useGetFollowerReviewCount = (followId: number) => {
사소하지만, 그냥 `id`로 명시하는것도 괜찮을것같네요ㅎㅎ

2023-10-20 15:33 UTC, hanagertrudeKim commented on src/pages/Follow/components/FollowProfile.tsx
>    };
`follow/entity.ts` 쪽에 정의된 타입들과 중복된 타입들이 꽤 있는것같은데, 이를 활용할수는 없을까요?

2023-10-22 14:22 UTC, LUNA-KK requested changes
수고하셨습니다. 궁금한 점 적어두었습니다!

2023-10-22 14:22 UTC, LUNA-KK commented on src/pages/Follow/components/Follower.tsx
> +  }
인터페이스에 해당 필드들은 왜 추가하신건가요?

2023-10-22 16:03 UTC, chaeseungyun commented on src/pages/Follow/index.tsx
>      <div className={style.template}>
수정완료했습니다!

2023-10-22 16:03 UTC, chaeseungyun commented on src/pages/Follow/components/Follower.tsx
>        <img className={style.follower__image} src={defaultImage} alt="default" />
추가했습니다!

2023-10-22 16:07 UTC, chaeseungyun commented on src/pages/Follow/components/ListReview.tsx
> +  const restArray = new Array<number>(5 - rate).fill(1);
넵 참고해서 수정했습니다

2023-10-22 16:08 UTC, chaeseungyun commented on src/pages/Follow/components/ListReview.tsx
> +import { ReactComponent as EmptyStar } from 'assets/svg/follow/empty-star.svg';
마찬가지로 수정했습니다

2023-10-22 16:10 UTC, chaeseungyun commented on src/pages/Follow/components/FollowProfile.module.scss
> +  }
반영했습니다

2023-10-22 16:12 UTC, chaeseungyun commented on src/pages/Follow/components/MobileUnfollow.tsx
> +export default function MobileUnfollow({
넵 확인했습니다
수정완료했습니다!

2023-10-22 16:20 UTC, chaeseungyun commented on src/pages/Follow/components/FollowProfile.tsx
>    };
넵 User 인터페이스로 대체했습니다

2023-10-22 16:21 UTC, chaeseungyun commented on src/pages/Follow/components/FollowProfile.tsx
> -          <img alt="img" src={defaultImage} className={style.user__profile} />
유저 프로필 이미지라고 간단하게 추가했습니다!

2023-10-22 16:24 UTC, chaeseungyun commented on src/pages/Follow/components/MobileUnfollow.tsx
> +  del: UseMutateFunction<AxiosResponse<any, any>, unknown, string, unknown>;
delete가 예약어라서 사용할 수 없는 것 같아요
그래서 del로 축약해서 적어보았습니다

2023-10-22 16:25 UTC, chaeseungyun commented on src/pages/Follow/hooks/useGetFollowerReviewCount.ts
>  const useGetFollowerReviewCount = (followId: number) => {
소중한 의견 감사합니다

2023-10-22 16:26 UTC, chaeseungyun commented on src/pages/Follow/components/FollowProfile.tsx
>    };
넵 이미 정의된 타입을 사용하는 것으로 수정했습니다

2023-10-22 16:28 UTC, chaeseungyun commented on src/pages/Follow/components/Follower.tsx
> +  }
게시물 수와 팔로워 수를 표시하기 위해 필요한 필드여서 새롭게 추가했습니다

2023-10-22 16:31 UTC, chaeseungyun commented on src/pages/Follow/components/FollowProfile.tsx
>              >
팔로우를 삭제하는 것이기 때문에 isFollowed라고 변경해보았습니다

2023-10-23 02:23 UTC, chaeseungyun commented on src/pages/Follow/components/ListReview.tsx
> +          </span>
그래요?

2023-10-23 03:09 UTC, LUNA-KK approved these changes

2023-10-23 06:42 UTC, chaeseungyun commented on src/pages/Follow/components/Follower.tsx
> +          [style['follower__button--request']]: followedType === 'NONE',
너무 좋은 아이디어네요
참고해서 적용했습니다

2023-10-24 10:52 UTC, chaeseungyun commented on src/pages/Follow/hooks/useGetFollowerReviewCount.ts
>  const useGetFollowerReviewCount = (followId: number) => {
d34bd777c467b2bc98b502520223277703c16b13
여기용

2023-10-24 10:52 UTC, hanagertrudekim approved these changes
수고하셨습니다~

2023-10-24 10:53 UTC, hyejun0228 approved these changes

2023-10-25 12:33 UTC, kimeodml reviewed
SNS 쪽만 해결해 주세요!

2023-10-25 12:33 UTC, kimeodml commented on src/pages/Follow/components/FollowProfile.tsx
> +                || (!isFollowed && request(state.account))}
SNS용 용은 따로 취급이 필요해 보여요! 이것만 해결하면 진짜...끝...!

2023-10-25 14:38 UTC, junghaesung79 commented on src/pages/Follow/index.tsx
>      <div className={style.template}>
`import style from './index.module.scss';`
`import styles from './Notice.module.scss';`
저희 쩝박 전체에서 styles 또는 style 키워드로 import 하는데 둘이 차이가 없는 것이 맞나요?
만약 차이가 없다면 통일하는 게 좋다고 생각합니다!

2023-10-25 14:40 UTC, junghaesung79 commented on src/pages/Follow/components/FollowProfile.tsx
>  import style from './FollowProfile.module.scss';
`import style from './index.module.scss';`
`import styles from './Notice.module.scss';`
저희 쩝박 전체에서 styles 또는 style 키워드로 import 하는데 둘이 차이가 없는 것이 맞나요?
만약 차이가 없다면 통일하는 게 좋다고 생각합니다!

2023-10-26 01:59 UTC, chaeseungyun commented on src/pages/Follow/components/FollowProfile.tsx
> +                || (!isFollowed && request(state.account))}
아 sns 로그인 말하는거죠????
넵 알겠습니다

2023-10-26 02:08 UTC, chaeseungyun commented on src/pages/Follow/components/FollowProfile.tsx
>  import style from './FollowProfile.module.scss';
넵
저는 style이라는 키워드로 통일했습니다
회의때 키워드 통일해봐요

2023-10-27 09:14 UTC, kimeodml reviewed
`useRequestAndUpdate`에서 account값을 활용해 팔로우 요청하더라고요. 근데 SNS 계정은 account가 없어서 따로 취급이 필요해 보여요! 리얼뤼 라스트...ㅎ

2023-10-27 09:14 UTC, kimeodml commented on src/pages/Follow/components/FollowList.tsx
>        {isShow && sended && sended.map((item) => (
map 함수에 key값 추가해주세요! 오류 생겼어요!

2023-10-29 08:06 UTC, chaeseungyun commented on src/pages/Follow/components/FollowList.tsx
>        {isShow && sended && sended.map((item) => (
그러면 sns 계정은 팔로우 신청을 못하나요???
account가 필수값이라 애매해요

2023-10-29 10:40 UTC, chaeseungyun commented on src/pages/Follow/components/FollowList.tsx
>        {isShow && sended && sended.map((item) => (
일단 sns 계정은 팔로우 신청을 할 수 없도록 변경했어요

2023-10-30 11:20 UTC, kimeodml commented on src/pages/Follow/components/FollowList.tsx
>        {isShow && sended && sended.map((item) => (
id 값으로는 불가능할까요?

2023-10-31 10:28 UTC, chaeseungyun commented on src/pages/Follow/components/FollowList.tsx
>        {isShow && sended && sended.map((item) => (
userAccount를 페이로드로 담아야합니다..

2023-11-14 04:50 UTC, kimeodml approved these changes
SNS 쪽만 다음 브랜치로 넘겨야 할것 같아요! 브랜치 최신화한 후에 머지부탁드립니다!
또한 아래의 이미지처럼 경로 추가 부탁드립니다!
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/88065770/3caa98c9-9d4a-49ff-9b06-03a2e7c852f1)

2023-11-14 19:59 UTC, ChoiWonBeen commented on package.json
> +    "@tanstack/react-query": "^5.8.3",
어라랏 #120 PR에서 한번에 전체 적용된 내용이라 confilct가 날 것 같아요
마지막 커밋 revert하고 develop 머지받으면 충돌 좀 줄어들듯?

2023-11-21 11:15 UTC, merged