[INQUIRY] 문의하기 UI 수정
BCSDLab/TEMP_PROJECT_FE pull request #109
Opened 2023-10-18 15:18 UTC by allOfCoder

## [#99] request

문의하기 페이지 UI 변경했고
전체 문의 보기 api 연결했습니다.
반응형 css 부분 구현 했습니다.

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [ ] Docs updated for breaking changes

### Screenshot
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/96577250/cad084cd-7678-4283-b271-fd35ae02cbe8)

2023-10-20 15:25 UTC, hyejun0228 requested changes
고생하셨습니다! 
우선, 앞선 다른분들의 코드 리뷰들을 정독해주시고 전체적으로 수정 부탁드립니다. 수정 이후 추가적인 코드리뷰 작성하겠습니다! 


- 정말 중요한것 몇가지만 언급하자면, BEM방식의 활용이나 파일 구조 분리, 카멜 케이스 등등 팀에서 이용하고 있는 여러 컨벤션들이 지켜지지 않아 일단 이부분을 집중해서 수정하셔야할것같습니다

2023-10-20 15:25 UTC, hyejun0228 commented on src/pages/Inquiry/Inquire/Inquire.module.scss
> +    width: 227px;
카멜케이스로 바꿔주세요!

2023-10-20 15:25 UTC, hyejun0228 commented on src/pages/Inquiry/Inquire/Inquire.module.scss
> +    }
BEM 방식에서는 `.header__navigation--navi-text ` 이런식으로 코드를 이어나갑니다. 
수정 부탁드립니다!

2023-10-20 15:25 UTC, hyejun0228 commented on src/pages/Inquiry/Inquire/index.tsx
> +  const explainSmallTitle = '확인 후 순차적으로 답변 드리겠습니다.';
상수는 따로 파일을 분리해주세요!

2023-10-20 15:25 UTC, hyejun0228 commented on src/pages/Inquiry/Inquire/index.tsx
> +          </div>
왜 button이 아닌 div 태그를 사용하셨나요?

2023-10-22 12:24 UTC, ChoiWonBeen commented on src/pages/Inquiry/Inquire/Inquire.module.scss
> +    }
`__title--small` 같은 방식이 적절할 것 같아요

2023-10-22 12:25 UTC, ChoiWonBeen commented on src/pages/Inquiry/Inquire/Inquire.module.scss
> +    width: 227px;
여기는 하이픈으로 통일하지 않났나여?

2023-10-22 14:54 UTC, kimeodml requested changes
고생하셨습니다. BEM 네이밍에 유의하면서 수정할 필요가 있어보여요!

2023-10-22 14:54 UTC, kimeodml commented on src/pages/Inquiry/Inquiry/components/DataTable/DataTable.tsx
> +  /* eslint-disable */
lint 예외처리의 경우 파일 최상단으로 표시해 주세요!

2023-10-22 14:54 UTC, kimeodml commented on src/pages/Inquiry/Inquiry/components/DataTable/DataTable.tsx
> +      const b = allData[allData.length - 1] === inquiryData.content[inquiryData.content.length - 1];
변수명 `b` 말고 명확하게 제시해 주세요~

2023-10-22 14:54 UTC, kimeodml commented on src/pages/Inquiry/Inquiry/components/DataTable/DataTable.tsx
> +  };
함수 선언식으로 표현하는 부분도 있고, 화살표 함수로 표현하는 부분도 있는데 함수 표현 통일해 주세요!

2023-10-22 14:54 UTC, kimeodml commented on src/pages/Inquiry/Inquiry/components/DataTable/DataTable.tsx
> +                  <ClampText text={item.title} />
`p` 태그 내부에 `div`가 있어서 오류가 생깁니다. 현재 `p`태그를 주로 사용하고 있는데 혹시 이유가 있을까요?
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/88065770/11967c21-b7d7-41e0-bcfa-7892e14774c6)

2023-10-22 14:54 UTC, kimeodml commented on src/pages/Inquiry/Inquiry/components/SearchBar/SearchInput.tsx
> +    </label>
요거 `search/SearchBar`폴더에 있는 것을 사용한 것 같은데 요 부분 `components` 폴더로 옮기는 거 어떨까요?

2023-10-22 14:54 UTC, kimeodml commented on src/pages/Inquiry/Inquiry/index.tsx
> +}
따로 파일로 분리해 주세요!

2023-10-22 14:54 UTC, kimeodml commented on src/pages/Inquiry/Inquiry/components/DataTable/DataTable.tsx
> +export default function DataTable({ typePath }: { typePath: string }): JSX.Element {
`components/DataTable`로는 못 쓰나요??

2023-10-22 14:54 UTC, kimeodml commented on src/pages/Inquiry/Inquiry/components/DataTable/DataTable.tsx
> +          allData.map((item) => (
요렇게 줄여도 될 것 같아요
```suggestion
      {allData && allData.length === 0 ? (
        <div className={styles.noData}>
          {noDataTitle}
        </div>
      ) : (
          allData.map((item) => (
```

2023-10-22 14:54 UTC, kimeodml commented on src/pages/Inquiry/Inquiry/components/DataTable/DataTable.tsx
> +
불필요한 빈 줄은 제거해 주세요~

2023-10-22 14:54 UTC, kimeodml commented on src/pages/Inquiry/Inquiry/components/DataTable/DataTable.tsx
> +}
이 부분도 파일로 분리해 주세요! 보통 파일명에 하나의 컴포넌트가 들어가는 이유가 파일을 통해 어떤 컴포넌트가 명시되어 있는지 파악하기 편해서 분리하는 것도 있고, 가독성 측면에서도 좋기 때문에 하나의 파일에는 되도록이면 하나의 컴포넌트만 넣어주세요!

2023-10-22 14:54 UTC, kimeodml commented on src/pages/Inquiry/Inquiry/index.tsx
> +  /* eslint-disable */
이 lint 예외처리도 파일 최상단에 선언해주세요!

2023-10-22 14:54 UTC, kimeodml commented on src/pages/Inquiry/Inquire/Inquire.module.scss
> +}
불필요한 css가 있어 보입니다~!

2023-10-22 14:54 UTC, kimeodml commented on src/pages/Inquiry/Inquiry/Inquiry.module.scss
> +  @media (max-width: 576px) { // 모바일 브레이크 포인트
미디어 쿼리 관련 함수 사용 부탁드립니다!
```suggestion
  @use "src/utils/styles/mediaQuery" as media;
  @include media.media-breakpoint-down(mobile) {
```

2023-10-23 02:51 UTC, chaeseungyun requested changes
고생하셨습니다!
참고할만한 내용 적어봤습니다

2023-10-23 02:51 UTC, chaeseungyun commented on src/api/inquiry/inquiryApiClient.ts
> +});
공용 api 인스턴스 같은 느낌이에요
inquiryApi를 나타내려면 baseURL에 /inquiry를 추가하면 더 좋지 않을까요

2023-10-23 02:51 UTC, chaeseungyun commented on src/pages/Inquiry/Inquiry/hooks/useInquiryList.ts
> +}
다른 곳에서도 사용하니 import받아서 쓰는건 어떨까요

2023-10-23 02:51 UTC, chaeseungyun commented on src/pages/Inquiry/Inquiry/hooks/useInquiryList.ts
> +  }
useQuery 세 번째 인자에 해당 함수를 넣을 수 있지 않나요?

2023-10-24 06:31 UTC, junghaesung79 commented on src/pages/Inquiry/Inquire/Inquire.module.scss
> +    width: 227px;
수정 했습니다. 앞으로 모듈화를 거치면서 더 나은 클래스네임으로 바꾸겠습니다.
413ee239aa5c350dfbb97ee7ffd4dcb35ddea1f0

2023-10-24 08:24 UTC, junghaesung79 commented on src/pages/Inquiry/Inquire/index.tsx
> +  const explainSmallTitle = '확인 후 순차적으로 답변 드리겠습니다.';
팀 관행을 찾아보려고 했는데 글을 태그 안에 바로 적은 방식이 대부분이어서 상수를 없애는 방식으로 수정했습니다.  6b1fc77c7c6a5b74eb15f1541720cbfb188abcac

2023-10-24 08:34 UTC, junghaesung79 commented on src/pages/Inquiry/Inquire/index.tsx
> +  const explainSmallTitle = '확인 후 순차적으로 답변 드리겠습니다.';
팀 관행을 찾아보려 했으나 글을 태그에 직접 넣는 것이 대부분이기 때문에 그에 맞춰 수정했습니다.
e87bf5fd5b8a1ea3e89c088ca37ea6a0b4ec1346

2023-10-25 05:13 UTC, hyejun0228 commented on src/pages/Inquiry/Inquire/index.tsx
> +  const explainSmallTitle = '확인 후 순차적으로 답변 드리겠습니다.';
상수는 보통 따로 해당 파일이 아닌 다른 파일을 만들어서 보관합니다. 따로 파일을 생성해서 `Inquire/index`컴포넌트에서 전달받아 사용해주세요!

2023-10-29 15:33 UTC, MinGu-Jeong reviewed
수고하셨습니다!!
쩝박 리뷰는 처음이여서 프로젝트 모든게 너무 낯서네요😅
익숙해지면 더욱 고급리뷰 남겨드리도록 할게요😄
코드만 보면서 약간 의문스러운 부분 리뷰남겨놨으니 확인 부탁드립니다!

2023-10-29 15:33 UTC, MinGu-Jeong commented on src/pages/Inquiry/Inquiry/components/DataTable/DataTable.tsx
> +                  <div className={styles.block__answerBox}>
scss파일 보면 
`&__answer-box`로 작성되어있는것으로 보이는데
지금 css 적용이 되고 있는게 맞나요..?
```suggestion
                  <div className={styles.block__answer-box}>
```

2023-10-29 15:33 UTC, MinGu-Jeong commented on src/pages/Inquiry/Inquiry/index.tsx
> +            <div className={styles['data__data-table--component']}>
`data__data-table`과 같은 네이밍 보다는
`data__table`와 같은 네이밍은 어떤가요??

2023-11-03 10:23 UTC, junghaesung79 commented on src/pages/Inquiry/Inquire/index.tsx
> +          </div>
여태까지 의미 있는 태그 사용에 큰 신경을 쓰지 않고 있었습니다. ul, a, button 등의 태그에 있는 기본 스타일을 수정하는 것이 번거로워서 그랬던 것 같습니다. 이번 기회에 태그의 의미와 기본 스타일을 억제하는 방법을 공부하고 문서를 수정했습니다. 위 부분은 다른 주소로 넘어가는 기능을 하기 때문에 Link 컴포넌트를 사용하도록 바꿨습니다.

2023-11-03 10:31 UTC, junghaesung79 commented on src/pages/Inquiry/Inquiry/components/DataTable/DataTable.tsx
> +  /* eslint-disable */
수정했습니다. f1b7e2af48b7b13b9ec57491d365549be66de9f8

2023-11-03 14:52 UTC, junghaesung79 commented on src/pages/Inquiry/Inquiry/components/DataTable/DataTable.tsx
> +                  <ClampText text={item.title} />
글이 들어가는 태그에 `p` 태그와 `div` 태그를  혼용해서 사용했었습니다. 현재는 글이 들어가는 곳에 `p`태그를 사용하도록 수정했습니다.

2023-11-03 16:28 UTC, junghaesung79 commented on src/pages/Inquiry/Inquiry/components/DataTable/DataTable.tsx
> +}
수정했습니다. f432f271f398bfc194256c741c3129b1009d4ee9

2023-11-03 16:29 UTC, junghaesung79 commented on src/pages/Inquiry/Inquiry/components/DataTable/DataTable.tsx
> +
넵

2023-11-03 16:49 UTC, junghaesung79 commented on src/pages/Inquiry/Inquire/Inquire.module.scss
> +}
container의 flex는 콘텐츠가 있는 부분을 가운데로 오게 하기 위함이고 box의 flex는 메뉴 라인과 작성부 라인을 나누기 위함입니다. 어떤 부분에서 불필요하거나 줄일 수 있을까요?

2023-11-03 20:47 UTC, junghaesung79 commented on src/pages/Inquiry/Inquiry/hooks/useInquiryList.ts
> +}
api/inquiry/entity에서 import하도록 수정하였습니다. a29063eb2ec589bdbb2ec0bc6d319793bcf70405

2023-11-03 22:05 UTC, junghaesung79 commented on src/pages/Inquiry/Inquiry/components/DataTable/DataTable.tsx
> +                  <div className={styles.block__answerBox}>
적용되지 않았던 것 같습니다. 컨벤션에 유의하여 클래스명을 수정하여 해결했습니다.

2023-11-03 23:16 UTC, junghaesung79 commented on src/pages/Inquiry/Inquiry/index.tsx
> +            <div className={styles['data__data-table--component']}>
다른 네이밍으로 수정했습니다.

2023-11-03 23:23 UTC, junghaesung79 commented on src/pages/Inquiry/Inquiry/components/SearchBar/SearchInput.tsx
> +    </label>
`src/components` 말씀하시는 건가요? 옮기는 목적을 알려주시면 그 목적에 맞게 수정할 수 있을 것 같습니다.

2023-11-03 23:26 UTC, junghaesung79 commented on src/pages/Inquiry/Inquiry/components/DataTable/DataTable.tsx
> +  };
수정했습니다. 626678dea6459952a5c7473bfc210715d77f41aa

2023-11-04 02:50 UTC, junghaesung79 commented on src/pages/Inquiry/Inquiry/components/DataTable/DataTable.tsx
> +      const b = allData[allData.length - 1] === inquiryData.content[inquiryData.content.length - 1];
alreadyExist로 변경했습니다. 44ad880d708d39fd6d1476aac4ab3cfe592d369b

2023-11-04 05:09 UTC, junghaesung79 commented on src/pages/Inquiry/Inquiry/Inquiry.module.scss
> +  @media (max-width: 576px) { // 모바일 브레이크 포인트
적용했습니다. 3defb199c7f7de89809121f2245a59c8388ebe2f

2023-11-06 00:42 UTC, LUNA-KK requested changes
수고하셨습니다!
참고하실 만한 몇 가지 적어두었습니다.

2023-11-06 00:50 UTC, LUNA-KK requested changes

2023-11-06 00:50 UTC, LUNA-KK commented on src/pages/Inquiry/Inquiry/components/DataTable/components/DataBlock/components/TextTruncation/index.tsx
> +      {isTruncated && '...'}
```css
text-overflow:ellipsis;
```
이걸로 css에서 적용하시면 변수하나 줄일 수 있을 것 같아요.

2023-11-06 00:50 UTC, LUNA-KK commented on src/pages/Inquiry/Inquiry/index.tsx
> +              className={styles['data-table__item']}
네이밍컨벤션 이슈 하나 찾아둘게요!

2023-11-10 08:38 UTC, kimeodml commented on src/pages/Inquiry/Inquiry/components/SearchBar/SearchInput.tsx
> +    </label>
SearchDetails 쪽에도 사용하고 있길래 `components`로 옮기면 어떨가 싶었습니다!

2023-11-10 09:14 UTC, kimeodml commented on src/pages/Inquiry/Inquire/Inquire.module.scss
> +}
box의 부모요소에 flex-direction을 이미 정의해 놓아서 box에서는 사용할 필요가 없어보여요! 물론 코드에서 그렇게 큰 영향을 미치지는 않는데 몇몇 scss를 보면 부모 요소로 인해 자식에 부여하지 않아도될 css가 있어보여서요!

2023-11-10 09:15 UTC, kimeodml reviewed
PC 버전에서도 `inquiry/all`로 변경 부탁드립니다!

2023-11-10 16:10 UTC, junghaesung79 commented on src/pages/Inquiry/Inquiry/index.tsx
> +  /* eslint-disable */
넵:smile:

2023-11-10 16:23 UTC, junghaesung79 commented on src/pages/Inquiry/Inquire/Inquire.module.scss
> +}
부끄럽지만 잊고 있었던 개념입니다.😂 수정하겠습니다! a5c80d8b81e6ce9d84f0c0b01227c622f0347a22

2023-11-20 09:43 UTC, junghaesung79 commented on src/pages/Inquiry/Inquiry/components/SearchBar/SearchInput.tsx
> +    </label>
좋은 생각인 것 같습니다!
fd5a64372bb83c7e3d8f3f897d2382c8dcc5a382
검색바를 공용 컴포넌트로 사용할 수 있도록 수정해봤습니다. 그런데 검색바를 사용하는 곳마다 너비 높이 폰트 사이즈가 제 각각이었습니다. props로 각각 값을 전달한다는 등의 방법을 써야 하는데 오히려 더 번잡할 것 같아서 각각 따로 쓰는 게 좋을 것 같습니다..😥
검색바를 수정하면서 좀 더 보기 좋게 리팩토링 했습니다. 한 번 확인해주시면 감사하겠습니다!😀

2023-11-20 23:24 UTC, junghaesung79 commented on src/pages/Inquiry/Inquiry/components/DataTable/components/DataBlock/components/TextTruncation/index.tsx
> +      {isTruncated && '...'}
dfef5de394d04f75d0bc54a24d7d7135c75600a4
감사합니다!

2023-11-21 01:49 UTC, LUNA-KK commented on src/pages/Inquiry/Inquiry/index.tsx
> +              className={styles['data-table__item']}
dash 하나 사용하는 것도 가능하다고 하네요!

2023-11-21 11:18 UTC, LUNA-KK approved these changes

2023-11-23 06:00 UTC, junghaesung79 commented on src/pages/Inquiry/Inquiry/hooks/useInquiryList.ts
> +  }
해당 함수를 삭제하고 같은 역할을 하는 옵션을 추가했습니다!
66652aa9454e703bf19a96113829b8b7065a7d87
reactQuery에 대한 공부를 안 되어 있었습니다.😢 이번 기회에 다른 옵션들도 공부하겠습니다!

2023-11-23 09:58 UTC, kimeodml commented on src/pages/Inquiry/Inquiry/components/SearchBar/SearchInput.tsx
> +    </label>
아하! 확인했습니다. 코드 깔끔하게 수정했네요..!

2023-11-23 09:58 UTC, kimeodml approved these changes

2023-11-23 09:59 UTC, kimeodml commented
아 근데 이거 브랜치 최신화 한 다음에 yarn lint하시면 오류 뜰 거예요...! 오류 해결한 후에 머지 가능할것 같습니다ㅠ

2023-11-24 05:01 UTC, junghaesung79 commented on src/pages/Inquiry/Inquiry/components/DataTable/DataTable.tsx
> +export default function DataTable({ typePath }: { typePath: string }): JSX.Element {
네😥 문의사항 페이지의 디자인이 변경되면서 화면에 표시하는 정보가 다릅니다. 제가 합류하기 이전에 남아있던 코드 위에서 작업을 시작해서 디자인이 바뀌기 전의 컴포넌트 명을 그대로 사용했어요. 그런데 지금 바뀐 디자인으로는 DataTable이 안 어울리는 것 같네요(표가 아니게 됨). InquiryList하고 InquiryBlock으로 바꾸겠습니다.
2af25873382afd5ec37c5f96dd64e5fcb3024a48

2023-11-24 06:24 UTC, junghaesung79 commented on src/pages/Inquiry/Inquiry/components/DataTable/DataTable.tsx
> +          allData.map((item) => (
d57128a45c02f4f3c74ea500d6b4736a5587c1ed

2023-11-25 10:09 UTC, chaeseungyun approved these changes

2023-11-26 05:46 UTC, hyejun0228 approved these changes

2023-11-28 13:35 UTC, merged