[SEARCH] 검색 결과 페이지 구현
BCSDLab/TEMP_PROJECT_FE pull request #112
Opened 2023-10-29 17:02 UTC by hyejun0228

## [#86 ] request

- 검색 결과 페이지 구현 
- 상점 검색 api 연결 
- 디바운스 훅 추가 및 연결

현재 검색 페이지 문제점 
 1. 음식점 종류가 figma와는 달리 api에 영어로만 존재 
 2. 전체 shop을 반환하는 api에서 전화번호가 나와있지 않음 

추후 백엔팀 및 UI/UX 팀과의 논의 후 최근 검색 식당 기능 PR에서 같이 수정하겠습니다. 
음식점 사진의 경우 figma 에서는 최대 3개까지의 처리가 가능하다고 나와있지만 api 상에서 최대 한개까지 존재해 코드를 그에 맞게 수정했습니다. 

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

### Screenshot
<img width="692" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/114041848/dcb32307-4c18-4c6c-85b0-30db984d1607">
<img width="688" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/114041848/94bd338b-1bf8-4c2a-80ed-8042ce0d44e2">

2023-10-30 16:08 UTC, kimeodml requested changes
고생하셨습니다!

2023-10-30 16:08 UTC, kimeodml commented on src/api/shop/index.ts
> +};
가독성을 위해 구현 방식을 변경한 것일까요?

2023-10-30 16:08 UTC, kimeodml commented on src/pages/Search/index.tsx
>  };
`SearchDetail`에서도 사용하는것 같은데 `utils>hooks`로 빼는 것은 어떨까요?

2023-10-30 16:08 UTC, kimeodml commented on src/pages/SearchDetails/index.tsx
>      <div>
불필요한 div태그는 제거해도 될것같아요!

2023-10-30 16:08 UTC, kimeodml commented on src/pages/SearchDetails/index.tsx
> +    return (shops || []).map((shop: Shop) => (
빈 배열이면 `/serach/not-found`로 넘어가야 하는 거 아닌가요?

2023-10-30 16:08 UTC, kimeodml commented on src/pages/SearchDetails/index.tsx
> +      return null;
useEffect를 활용해서 렌더링된 후에 페이지 이동이 적합할 것 같아요!
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/88065770/9de3802d-60f7-45f5-aed9-923b5899f986)

2023-10-30 16:08 UTC, kimeodml commented on src/pages/SearchDetails/index.tsx
> +      return null;
기본값이 빈 배열이라서 모바일로 넘어가변 `search/not-found`로 이동되네요!

2023-10-30 16:08 UTC, kimeodml commented on src/pages/Search/index.tsx
> +          {!isMobile && !isSearching && !entered && <RollingBanner />}
아래의 코드도 복잡해 보이려나요...?
```suggestion
          {!entered && (
              !isMobile && isSearching ? <RelatedSearches text={text} /> : <RollingBanner />
)}
```

2023-10-31 02:33 UTC, hyejun0228 commented on src/api/shop/index.ts
> +};
넵 제 생각으로는 해당 방식이 가독성이 좋다고 생각해 변경해줬습니다

2023-10-31 02:35 UTC, hyejun0228 commented on src/pages/SearchDetails/index.tsx
> +    return (shops || []).map((shop: Shop) => (
그럴경우 아예 검색 자체가 안되는 경우가 발생하더라구요.. 아직 그부분에 대한 이유를 모르겠어서 정상적으로 작동되는 해당 형식으로 작성해줬습니다. 
이유를 찾으면 추가로 댓글달겠습니다..!

2023-10-31 02:39 UTC, hyejun0228 commented on src/pages/Search/index.tsx
> +          {!isMobile && !isSearching && !entered && <RollingBanner />}
훨 좋은것 같습니다! 코드에서 삼항연산자를 이중으로 사용하면 오류가 발생할 때가 있던데.. 위의 코드는 잘 돌아가네요. 
혹시 기준을 아시나요?

2023-10-31 04:36 UTC, D0Dam reviewed
이제 프로젝트에도 참여할 생각이라 리뷰하러 와봤습니다~! 무언가 그냥 다 투정하는 듯한 욕심 가득한 글이 되머 버렸는데... 이해해주세요.. 이게 다 더 잘했으면 하는 마음에 그런 것이니..😇
혹시 리뷰 반영할 때 간단한 것만 반영하게끔 컨벤션이 되어있다면 한번 고냥 읽어만 보세여. 아니라면 찾고 고쳐나가면 물론 더 좋겠지만..
앞으로 잘 부탁 드리겠슴니다요.

2023-10-31 04:36 UTC, D0Dam commented on src/api/shop/entity.ts
>  }
제 생각에는요. Coords 와 ShopsCoords 를 나누는 건 부적절해 보여요. 그리고 이게  optional 한 값이라는것 까지..!!

자세한건 밑에서 이야기 해보도록하져!

2023-10-31 04:36 UTC, D0Dam commented on src/api/shop/entity.ts
> +}
(이게 분명 본인이 타입을 선언한게 아닐 수도 있지만.. 그냥 끄적여볼게요 일단..)

여기 보면 Coords 와 ShopsCoords 가 있네요. 물론 새롭게 interface 를 선언했다는건, Coords 로 해결이 안되니까 그런것이겠죠? 
그래도.. 분명 다른 방법이 있었을 것 같아요.

저였다면 Coords 의 각 키값에 undefined 타입을 주지 않고 사용했을 것 같아요. 만약 undefined와 같은 상황이 필요한 때는 optional 하게 사용한다거나 null 을 union 해서 썻을 것 같네요. 그리고.. 같은 Coords 인데 반해서 하나는 lat 이고 하나는 latitude 인것도 헷갈리구요..

제가 왜 이런 생각을 했는지 이야기 해볼게요.

Coords 라는 타입을 들었을 때 좌표가 과연 lat 과 lng 값이 비어있는 경우가 있다고 상상할 수 있을까요? 물론 맞다고 할 수 있겠지만 그런 경우는 아마 외부에서 누군가 이 좌표라는 타입을 사용할 때 결정해 주는 것이 맞는 것 같아요. (ex ShopParams 에서는 좌표가 없을 수도 있으니 optional 로 하자.) 기본적으로는 좌표라는 타입은 lat, lng 이 있다라고 가정하구요.
아니다! Coords 없을 수도 있지! 라고 한다면 좀 더 나아가서 ShopCoords 를 봤을 때 이 타입은 경도와 위도의 값이 필수적이라고 하고 있네요. 내부 컨벤션에 따라 다를 수도 있지만 Coords 타입도 경도, 위도가 필수값이 아닌데 왜 이 타입은 경도, 위도가 필수 값인지 헷갈리게 다가와요. 써놓고 보니 너무 주저리 주저리 같지만... 결론은 구체적인 타입을 명시하는 것은 좋지만, 그만큼 타입을 통합시킬 수 있는 건 통합시키는 것이 나중에 타입을 파악하면서 코드를 보기에 편안하다는 말을 하고 싶었어요.

ShopsCoords 를 사용하는 곳이 요기더라구요?
```
export interface ShopsParams {
  keyword: string;
  location?: ShopsCoords;
}
```

여기에서 보면 또 ShopsCoords는 optional 한 값이에요. 이렇게 되면 결국 Coords 와 다를게 없다구 보거든요.
그리고 location 이라고 하면 위치를 나타내는 말이라 그냥 더 정확한 네이밍은 Coords 로 네이밍을 가져갔어도 괜찮지 않았을까요?(이건 그냥 지극히 개인적으로..ㅎㅎ)
저였다면 아래와 같이 사용했겠네요.

```
interface Coords {
  lat: number;
  lng: number;
}

interface ShopPararms {
  keywords: string;
  location?: Coords;
}

// 기존의 Coords 를 살리고 싶다면

interface ShopPararms {
  keywords: string;
  location: Coords;
}

// 굳이 location이라는 네이밍을 두고 싶지 않다면

interface ShopPararms extends Coords{
  keywords: string;
}

// + 요건 위에꺼하고 무슨 차이일까요?

type ShopPararms = Coords & { keywords: string; }
```

물론 제가 자세히 아는 건 아니지만, 그냥 타입을 만들 때 타입의 네이밍과 범용성을 의식하면서 설계를 했으면 하는 맘에서 남겨보아요.

2023-10-31 04:36 UTC, D0Dam commented on src/api/shop/index.ts
> +};
`getfilterShops` 는 params 에 requesbody를 묶어주지 않고 있네요. 반면에 `fetchShops`는 params에 requestBody 를 묶어주고 있어요. 이러면 헷갈리지 않을까요?

2023-10-31 04:36 UTC, D0Dam commented on src/components/common/SideNavigation/index.tsx
>                />
이 친구는.. src 가 그럼 없이 화면에 출력되나요..? 이미지가 없을 경우의 처리가 되어 있는 것 같은데 어떤 문제가 생긴걸까요?

2023-10-31 04:36 UTC, D0Dam commented on src/pages/Search/index.tsx
>          </section>
세상에 ㅋㅋㅋㅋ 이렇게 보면 너무 헷갈리지 않나요? 아예 isMobile을 중심으로 return 값을 분기처리하는 건 어때요?

2023-10-31 04:36 UTC, D0Dam commented on src/pages/SearchDetails/components/SearchItem.tsx
> +      )}
요론 내부 이벤트 함수들은 외부로 빼주는 습관을 들여봅시다~!

2023-10-31 04:36 UTC, D0Dam commented on src/pages/SearchDetails/hooks/useFetchShops.ts
> +  }
허걱 이건 뭐죠..? { location } = useGeolocation(OPTIONS); 에서 location 이 있으면 이 location으로 useQuery 를 돌려주고 싶었던 건가요..?

그렇다면 그냥 밑에 params 를 전달할 때 분기 처리를 하는 게 좋아보이는데요..!!
밑에서 또 추가적으로 이야기 하겠습니다.

2023-10-31 04:36 UTC, D0Dam commented on src/pages/SearchDetails/hooks/useFetchShops.ts
> +  });
useQuery 의 key 로 location 이 들어가있는건 의도한 걸까요? 이렇게 되면 params가 변경되었을 때는 동작하지 않을텐데, 의도한 동작은 아닐 것 같아요. params를 키 값으로 주어도 되고 위에서 말한 것처럼 params와 location을 분기처리 한다면 location과 params를 둘 다 키값으로 넣어주는 것이 좋을 것 같아요!

2023-10-31 04:36 UTC, D0Dam commented on src/pages/SearchDetails/hooks/useFetchShops.ts
> +  }, [debouncedText, refetch]);
여기에서 refetch 함수를 의존성으로 준 것이 의도된 것일까요..? 왜 refetch가 의존성이 있는거죠..?

2023-10-31 04:36 UTC, D0Dam commented on src/pages/SearchDetails/index.tsx
> +  }, [text]);
setEntered 를 useEffect 에서 처리해줘야 할까요? 만약 text 가 변하면 setEntered가 false 가 되기를 바라는 것이었다면 handleChange에서도 처리해 줄 수 있을 것 같은데요?!

2023-10-31 04:36 UTC, D0Dam commented on src/pages/SearchDetails/index.tsx
> +  const [entered, setEntered] = useState(false);
제가 만든 useBooleanState 써주세요..🥲

2023-10-31 04:36 UTC, D0Dam commented on src/pages/SearchDetails/index.tsx
> +  const { isFetching, data: shops, count } = useFetchShops(text ?? '');
oh 어쩌다가 hook 의 반환값이 hook 의 인자로 들어가는 구조가..

2023-10-31 04:36 UTC, D0Dam commented on src/utils/hooks/useDebounce.ts
> +}
오.. 직접 만든건가? 성장했구만.. 이렇게 좀 더 타입을 잘 사용할 수 있을 듯 합니다. delay 는 대체적으로 500을 많이 써서 기본 값을 줘봤는데, 기존대로 안줘도 갠춘할 것 같슴니다.

```suggestion
function useDebounce<T>(value: T, delay?: number): T {
  const [debouncedValue, setDebouncedValue] = useState<T>(value)

  useEffect(() => {
    const handler = setTimeout(() => setDebouncedValue(value), delay || 500)

    return () => {
      clearTimeout(handler);
    }
  }, [value, delay]);

  return debouncedValue;
}
```

2023-11-01 15:16 UTC, hyejun0228 commented on src/pages/SearchDetails/index.tsx
>      <div>
넵 수정했습니다!

2023-11-01 15:19 UTC, hyejun0228 commented on src/components/common/SideNavigation/index.tsx
>                />
이부분은..브런치 최신화중에 오류가 뜬부분입니다. 일단 오류 부분만 주석처리 해놨고, 코드 담당자분이 수정하실것같습니다!

2023-11-01 15:21 UTC, hyejun0228 commented on src/pages/Search/index.tsx
>          </section>
오..! 너무 좋은것같습니다..이제와서보니 너무 복잡하네요..수정했습니다!
5a7413e4a89a3a6dcf349da6e9ca7b475e9ffa32

2023-11-01 15:22 UTC, hyejun0228 commented on src/pages/SearchDetails/index.tsx
> +  const [entered, setEntered] = useState(false);
앗..수정했습니다..! 
5a7413e4a89a3a6dcf349da6e9ca7b475e9ffa32

2023-11-01 15:29 UTC, hyejun0228 commented on src/utils/hooks/useDebounce.ts
> +}
오..제네릭..이번 자바에서 배운게..여기에서도 사용가능하군요..? 수정하겠습니다!

2023-11-01 16:31 UTC, hyejun0228 commented on src/pages/SearchDetails/components/SearchItem.tsx
> +      )}
넵! 수정했습니다! 
aba2f121ebc577cfa0d39ceeaee39bab4fd3e972

2023-11-01 16:40 UTC, hyejun0228 commented on src/api/shop/index.ts
> +};
개인적으로 `fetchShops`의 형식이 보기 쉽다고 생각해서 `getfilterShops` 도 형식에 맞춰 변경해줬습니다!
aba2f121ebc577cfa0d39ceeaee39bab4fd3e972

2023-11-01 16:44 UTC, hyejun0228 commented on src/pages/Search/index.tsx
>  };
확실히 재사용해줘야겠네용..
여기서 고민이 드는게.. utils>hooks 에 커스텀훅을 만들어주기에는 너무 `search`, `searchDetail` 에서만 사용되는 훅아닐까요..?

2023-11-01 16:47 UTC, hyejun0228 commented on src/pages/SearchDetails/index.tsx
> +      return null;
앗 수정했습니다

2023-11-01 16:59 UTC, hyejun0228 commented on src/pages/SearchDetails/hooks/useFetchShops.ts
> +  }
앗..location 값을 가지고 온다면 params 에 넣어주려고 했던 if문인데..
이미 제가 밑에서 이부분을 제어해주고 있었군요..!

```javascript
  const {
    isLoading, isError, data, refetch,
  } = useQuery(['shop', location], () => fetchShops(params), {
    enabled: !!location,
  });
  ```

2023-11-01 17:01 UTC, hyejun0228 commented on src/pages/SearchDetails/hooks/useFetchShops.ts
> +  });
위의 대답처럼 location부분이 확실하게 params로 필요한 부분이라 막아주고 if 문 삭제했습니다!

2023-11-01 17:05 UTC, hyejun0228 commented on src/pages/SearchDetails/index.tsx
> +  }, [text]);
`setEntered` 부분을 훅으로 교체하여 해당부분은 삭제했습니다!

2023-11-01 17:08 UTC, hyejun0228 commented on src/pages/SearchDetails/index.tsx
> +  const { isFetching, data: shops, count } = useFetchShops(text ?? '');
엇..어느부분 말씀하시는거죠..?!

2023-11-02 00:21 UTC, D0Dam commented on src/components/common/SideNavigation/index.tsx
>                />
제가 고쳤답니다🤗

2023-11-02 00:23 UTC, D0Dam commented on src/pages/Search/index.tsx
>          </section>
Oh 삼항연산자 말구 if 문으로 분기 처리 해보는거 어때요? Jsx 분량이 한줄 이상 넘어가면 삼항연산자로는 가독성이 많이 떨어지거든요!

2023-11-02 00:24 UTC, D0Dam commented on src/pages/SearchDetails/components/SearchItem.tsx
> +      )}
useCallback은 왜 해주었을까요?

2023-11-02 01:02 UTC, D0Dam commented on src/pages/Search/index.tsx
>  };
하는 역할 자체는 단순히 enter 로도 폼을 기록할 수 있게 해주는 거네요. 그렇다면 저라면 네이밍을 그냥 useInputForm 과 같이 바꿔줘서 공용 훅으로 뺄 것 같긴 한데... 그런데 보다보니까 이 훅은 input text 상태 정의하고 enter 를 이벤트로 추가해 준 느낌인데요..?
원래 form 태그를 쓰면 이 훅 없이도 구현 할 수 있지 않나요?

2023-11-02 04:27 UTC, hyejun0228 commented on src/pages/Search/index.tsx
>  };
form 태그를 사용해주면 `handleEnter` 대신 form 태그에 `onSubmit` 이벤트를 만들어줄 함수를 또 작성하게 되는데 코드상으로 봤을땐.. 비슷한 느낌 아닌가요..?! 

```javaScript  
// 기존 enter event 함수
const handleEnter = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter' && text) {
      setSubmittedText(text);
      toggle();
    }
  };
  // form태그를 사용해줬을 때 대체되는 event 함수
    const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    if (text) {
      setSubmittedText(text); 
      toggle();
    }
  };
```

2023-11-02 04:30 UTC, hyejun0228 commented on src/pages/SearchDetails/components/SearchItem.tsx
> +      )}
함수가 다시 선언을 되는걸 줄이게 만들 수 을것같아서 만들었는데 이제와서 생각해보니 그럴일이 없군요..? 수정하겠습니다..!

2023-11-02 04:40 UTC, hyejun0228 commented on src/pages/Search/index.tsx
>          </section>
48f514c7468f4f250e25827a6b4f5faf1075925c 
이런..느낌일까요??!?

2023-11-02 04:48 UTC, hyejun0228 commented on src/pages/SearchDetails/hooks/useFetchShops.ts
> +  }, [debouncedText, refetch]);
의도 된것은 아닙니다. 원래 해당 useEffect를 만들때 refetch를 의존성에 추가해줄 생각은 없었으나 error가 떴고 refetch를 의존성에 추가하면 해당 error가 사라졌습니다. refetch 를 의존성에 추가하고 말고가 코드상에 지장을 주는게 없어 추가하게됐습니다..! 밑의 코드로 변경해주는게 더 나은가요..?!
```javascript
  useEffect(() => {
    refetch();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [debouncedText]);
  ```

2023-11-02 04:51 UTC, D0Dam commented on src/pages/Search/index.tsx
>  };
handleEnter 대신 form 태그에 onSubmit 이벤트를 만들어주는거니 코드상 분량은 onSubmit 이 아주 살짝 더 적네요.
말대로 코드량은 비슷하잖아요? 그럼 둘중에 어느 방법이 더 좋을까요?

저는 후자가 좋은 것 같아요.
이름 자체도 use~~Form 이니 handleEnter 라는 이벤트보다 handleSubmit 이라는 이벤트가 있는게 더 자연스럽게 느껴지지 않나요? 왜냐하면 form을 트리거해서 발생시키는 이벤트가 submit 이니까요! 그리고 이렇게 되면 form 태그를 쓰게되니 자연스럽게 use~~Form 과의 연관성도 딱 드러나는 것 같아요.

2023-11-02 04:53 UTC, D0Dam commented on src/pages/Search/index.tsx
>          </section>
마자요 마자요!

여기서 딱 하나만 더...

```
        {!isEnter && <Recommendation />}
        {!isEnter
          ? (
            <>
              <SearchInput
                onChange={handleChange}
                onKeyDown={handleEnter}
                text={text}
              />
              {isSearching ? <RelatedSearches text={text} /> : <RollingBanner />}
            </>
          )
          : <SearchDetails />}
```

이거... 굳이 두개로 안나눠도 될 것 같은데요?

2023-11-02 05:19 UTC, hyejun0228 commented on src/pages/Search/index.tsx
>  };
오옹! 이제보니 확실히 후자가 자연스러운 코드인것 같습니다! 수정했습니다! 
c419b197baa10aa44a25851ef4a77ba85ae335a9

2023-11-02 06:14 UTC, hyejun0228 commented on src/pages/Search/index.tsx
>          </section>
헉 수정했습니다! d291ac3178b3baf9d8ecbb760884954987a6fc87

2023-11-02 17:03 UTC, hyejun0228 commented on src/api/shop/entity.ts
> +}
전체적으로 interface 통일해줬습니다..!! 의외로 간단한 부분을 고쳐주면 됐던건데.. 계속 막혀있었네요 
ab811d571c7923dea81704480d95eb5ca5ae729e

2023-11-03 01:18 UTC, D0Dam commented on src/pages/SearchDetails/hooks/useFetchShops.ts
> +  }, [debouncedText, refetch]);
ㅎㅎ 원래 밑에가 이상적인데 사실 useEffect가 필요가 없죠.
왠만해서는 useQuery에 있는 refetch를 쓸 일이 거의 없습니다. 특수한 경우에만 사용을 해요.(뭐 인자값으로 전달해야하는 상황이거나 ...)

그렇다면 어떻게 다시 fetch 해올 수 있을까요? 다음을 생각해보면 답이 나올 것 같아요.

- useQuery의 key 배열이 무슨 역할을 하는가?
- enabled는 왜 사용했는가?
- useQuery는 useEffect를 어느정도 대체할 수 없을까?

위의 내용을 꼭 생각해봐 주세요.
그러면 debouncedText 를 useQuery 의 key 값으로 주면 어떤 일이 발생할까요?
그리고 enabled를 제거한다면요?

2023-11-03 01:23 UTC, D0Dam commented on src/pages/Search/index.tsx
>          </section>
좋아요 ㅋㅋㅋ 계속 꼬리에 꼬리를 물어서 너무 죄송하지만, 밑에 useQuery 관련해서 다시 또 남겼으니 여기에도 하나만 더 남길게요. (이제 보여서...ㅠ)

삼항연산자를 분기 처리 할때 `!value ? A : B` 와 같이 값의 부정으로 삼항 연산을 하기 보다 `value ? B : A` 와 같이 긍정형으로 상항 연산을 하는것이 진짜 특수한 경우가 아니라면 좋습니다! 무슨 말인지 알죠?🙃

2023-11-03 01:37 UTC, D0Dam reviewed
밑에 리뷰로 남겼지만 이렇게 보다 저는 lat과 latitude를 둘다 되게 하거나 그냥 lat 만 쓰기를 바랬어요.

1. 그냥 lat lng 만 쓰기

```
interface Coords {
  lat: number;
  lng: number;
}

// 이렇게 되면 사용할 때 const { lat:latitude } = fetch(data); 식으로 쓸 수 있음.
```

2. lat과 latitude를 그냥 둘다 키값으로 쓰고 싶다면

```
type Coords = {
  lat: number;
  lng: number;
} | {
  latitude: number;
  longitude: number;
};
```

어떤가요?

2023-11-03 01:37 UTC, D0Dam commented on src/api/search/entity.ts
>  }
악 any 안돼요~! 🥲
any로 바꾼 이유가 있었나요?

2023-11-03 01:37 UTC, D0Dam commented on src/api/shop/entity.ts
>  }
근데 왜 Coords 타입이 두개나 있죠..? 하나는 제거하는게...

2023-11-03 17:25 UTC, hyejun0228 commented on src/api/shop/entity.ts
>  }
음..하나는 Search api 에 사용되는 interface이고 다른하나는 shop api 에 사용되는 interface입니다. 코드가 중복되긴하나..파일이 분리가 돼있어서요..! 이럴경우 분리해서 써주는게 맞지 않나요?

2023-11-03 17:28 UTC, hyejun0228 commented on src/api/search/entity.ts
>  }
억 아까는 이 코드가 아니면 돌아가지 않아 고쳐준걸로 기억이 나는데 any를 없애도 아무 오류가 뜨지않네요..? 수정했습니다..!!
3f82efdbf546bc6f133ee86524b0128c722cd73e

2023-11-03 17:36 UTC, hyejun0228 commented on src/pages/Search/index.tsx
>          </section>
오..!! 네! 전혀 신경을 못쓰고 있었는데 확실히 보기 편할것 같습니다!
e5e11327d14ac10aee1dd9e8bed451060f8cedf8

2023-11-03 18:27 UTC, hyejun0228 commented on src/pages/SearchDetails/hooks/useFetchShops.ts
> +  }, [debouncedText, refetch]);
오호 useQuery의 key값에 debouncedText를 넣어줘서 자동으로 쿼리를 업데이트 해줄 수 있겠군요..! 지금까지 사용하면서 제대로 인지하지 못하고 있었네용.. 
enabled는 location값을 필수로 받아와줘야해서 넣어줬습니다! 위치를 반환하지 못할 경우 api를 불러오고싶어도 불러와지지 않아서요!

2023-11-04 05:09 UTC, D0Dam commented on src/api/shop/entity.ts
>  }
음.. 저는 이런 형식으로 분리해 본 적이 없어서 애매하네요.. 이렇게 분리하게 되면 혼동을 빚을 수 있다고 생각하는데, 일단 이 부분은 좀 사례를 저도 찾아봐야겠어요. ㅎㅎ

2023-11-04 05:10 UTC, D0Dam approved these changes
제가 너무 시간을 끌었네요.😇
수고하셨습니다!

2023-11-04 05:11 UTC, hyejun0228 commented on src/api/shop/entity.ts
>  }
저도..다음 PR까지 고민해보겠습니다!

2023-11-05 13:10 UTC, kimeodml approved these changes
고생하셨습니다! mockup.ts는 제거해도 될 것 같아요!

2023-11-05 15:44 UTC, merged