[DETAIL] 상점 상세 페이지 구현
BCSDLab/TEMP_PROJECT_FE pull request #116
Opened 2023-11-07 08:30 UTC by D0Dam

## [#56]

기존과는 디자인 시안이 바뀌어 바뀐 걸로 적용했습니다.
디자인은 아래와 같습니다.

<img width="1021" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/51052049/65a2c60f-95f1-4b6f-95f2-ff425aef73c1">

구현 내용
- imageCarousel 구현
- 지도 및 리뷰 컴포넌트 구현
- 이외의 ui 구현
- NotFound 컴포넌트 구현

미적용 내용
- 북마크 등록 기능
- 리뷰의 전체보기 기능
- url 복사 기능
- 사진 전체 보기 기능

미적용 내용에 대해서는 추가적인 질문과 이해가 필요해서, 그리고 한번에 PR 내용이 너무 커서 2차 PR 로 처리하겠습니다.

### 구현 예시

파일이 하나도 안올라가서(크기가 넘 크니다..) 압축해서 올립니다.
 
[mock영상.zip](https://github.com/BCSDLab/JJBAKSA_FRONT_END/files/13277479/2023-11-07.4.51.04.zip)

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

2023-11-08 05:34 UTC, hyejun0228 requested changes
수고하셨습니다! 코드가 깔끔해 읽기 수월 했습니다ㅎㅎ
질문 몇개 달아놓겠습니다!

2023-11-08 05:34 UTC, hyejun0228 commented on src/pages/ShopDetail/components/Map/index.tsx
> +        button={{ name: 'URL 복사', handler: () => {} }}
해당 `handler` 함수는 왜 빈 함수인가요?!

2023-11-08 05:34 UTC, hyejun0228 commented on src/pages/ShopDetail/components/ReviewList/FriendReviewList.tsx
> +          button={totalElements > size ? { name: '전체보기', handler: () => {} } : undefined}
여기두요..! 다음 PR에 기능을 추가해주려고 임시로 함수를 비어둔건가요?

2023-11-08 05:34 UTC, hyejun0228 commented on src/pages/ShopDetail/components/ReviewList/MyReviewList.tsx
> +                <div className={styles['review-list__main__my-content']}>
className 을 `review-list__main--my-content` 로 변경해야할 것 같습니다!

2023-11-08 06:04 UTC, D0Dam commented on src/pages/ShopDetail/components/Map/index.tsx
> +        button={{ name: 'URL 복사', handler: () => {} }}
> 미적용 내용
>
> - 북마크 등록 기능
> - 리뷰의 전체보기 기능
> - url 복사 기능
> - 사진 전체 보기 기능

여기에서 리뷰의 전체보기 기능 및 사진 전체 보기 기능에 해당합니다!

2023-11-08 06:04 UTC, D0Dam commented on src/pages/ShopDetail/components/ReviewList/FriendReviewList.tsx
> +          button={totalElements > size ? { name: '전체보기', handler: () => {} } : undefined}
위의 코멘트로 대신하겠습니다..! [코멘트](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/116#discussion_r1386036308)

2023-11-08 07:34 UTC, D0Dam commented on src/pages/ShopDetail/components/ReviewList/MyReviewList.tsx
> +                <div className={styles['review-list__main__my-content']}>
헉 bem 구조를 헷갈렸네요! 짚어주셔서 감사합니다!
[2bceb21](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/116/commits/2bceb21b42cd609a146779d3e5102ad5cd005a67)

2023-11-09 01:41 UTC, hyejun0228 approved these changes

2023-11-10 07:14 UTC, ChoiWonBeen approved these changes

2023-11-10 07:14 UTC, ChoiWonBeen commented on .eslintrc.json
> +    "implicit-arrow-linebreak": "off",
요거 왜추가된건가요?? 궁금하네여

2023-11-10 07:14 UTC, ChoiWonBeen commented on src/api/review/entity.ts
> +  }[];
얜 서버에서 받는 이미지일까요? 바로 위에있는 reviewImages랑 동일한 이름인데 인터페이스가 달라서 다르게 처리하는게 좋지 않을까 싶어 여쭤봅니다

2023-11-10 07:14 UTC, ChoiWonBeen commented on src/api/shop/entity.ts
> +  scrap: any;
Object나 any는 어떤 애들이 들어와서 이렇게 정의해둔걸까용?

2023-11-10 07:14 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/components/MarkerHtml/index.tsx
> +  <a href='/shop/${id}'>
혹시 ClickedMarkerHtml을 쓰는 곳에서(마커를 세팅하는 곳에서) onClick같은 핸들러를 넘겨줄 수 있지 않을까요? 넘기면 csr장점을 활용하지 못하는 a태그를 쓰는게 아니라 routing을 해줄 수 있을 것 같아요 (안됨말고)

2023-11-10 07:14 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/hooks/useFilterShops.ts
> +import { getFilterShops } from 'api/shop';
😂

2023-11-10 07:14 UTC, ChoiWonBeen commented on src/pages/ShopDetail/components/ImageCarousel/index.tsx
> +  const next: React.ReactEventHandler<HTMLButtonElement> = () => {
이벤트를 안쓴다면 굳이 정의하지 않아도 될 것 같아요
```suggestion
  const handleNext(Click?) = () => {
```

2023-11-10 07:14 UTC, ChoiWonBeen commented on src/pages/ShopDetail/components/ImageCarousel/index.tsx
> +            <img src={url} alt={`${index}번 음식점`} />
한 상점의 이미지 목록 아닌가요?
'0번 음식점' ,'1번 음식점',,,, 이런 문구가 접근성적인 측면을 채워줄 수 없을 것 같아요

2023-11-10 07:14 UTC, ChoiWonBeen commented on src/pages/ShopDetail/components/ReviewList/FriendReviewList.tsx
> +  );
데이터 로딩중에 이 UI가 나올 것 같은데, 쓰는 입장에서 깜빡이는 경험을 하게될 것 같아요
+이런 화면이 필요하다면 Suspense를 쓰는게 더 쉽게 관리할 수 있지 않을까 생각합니당

2023-11-10 07:14 UTC, ChoiWonBeen commented on src/pages/ShopDetail/components/SectionHeader/SectionHeader.module.scss
> +  }
성능적 측면을 고려해서 가능하면 클래스이름을 지어주는게 좋다고 생각하는데, 혹시 이렇게 써야만 하는 이유가 있었을까요?

2023-11-10 07:14 UTC, ChoiWonBeen commented on src/pages/ShopDetail/components/SectionHeader/index.tsx
> +  };
버튼이 있을수도 있고 없을수도 있다면 hasButton등으로 표현하는건 어떨까요?
아니면 버튼을 ReactElement로 받아서 쓰는 쪽에서 UI나 기능 등을 정하는것도 괜찮아보여요

2023-11-10 07:14 UTC, ChoiWonBeen commented on src/pages/ShopDetail/index.tsx
> +      <div className={styles.container}>스켈레톤</div>
추후 추가 예정이겠죠? 주석으로 적어두는게 좋을 것 같아용

2023-11-10 07:14 UTC, ChoiWonBeen commented on src/pages/ShopDetail/index.tsx
> +        </header>
얘가 header를 내부적으로 갖고 있는게 어떨까요?
헤더 외에서 사용되는 일은 없을 것 같아요

2023-11-10 07:14 UTC, ChoiWonBeen commented on src/pages/ShopDetail/index.tsx
> +                  <span>{totalRating === -1 ? '0.0' : totalRating.toFixed(1)}</span>
-1이 들어오나요?
없을때 -1 이려나
조금 더 바운더리를 넓게 `<=` 로 처리하거나 여기도 주석이 포함되면 읽는 쪽에서 이해하기 쉬울 것 같아요

2023-11-10 08:17 UTC, D0Dam commented on .eslintrc.json
> +    "implicit-arrow-linebreak": "off",
이건 좀 코드를 보여주면서 설명해 주고 싶은데 이 두개의 lint 가 서로 중복 되면서 바로 return 하라고 하는걸 중괄호는 제외하고 바로 return 하면 라인당 글자수를 뚫어버리고.. 그런 문제가 생겨서 껏습니다.
사실 이거 끈거 제가 너무 마음에 안들어서 독자적으로 끈건데... 아무도 태클을 안걸더라구요..쩝..

2023-11-10 08:17 UTC, D0Dam commented on src/api/review/entity.ts
> +  }[];
서버 응답이 너무 길어서 좀 쪼개다보니 ReviewContent를 만들었는데, 음.. 말을 듣고 보니 헷갈릴만한 것 같네요 ㅎㅎ
그냥 ShopReviewsResponse 안에서 객체 배열로 표현해주도록 하겠습니다~!

2023-11-10 08:17 UTC, D0Dam commented on src/api/shop/entity.ts
> +  scrap: any;
아직 형식을 정확히 몰라서 다음과 같이 넣어두었는데 이걸 그냥 PR을 날렸었네요. ㅎ허허..🥲
백엔드 쪽에 해당 속성 타입을 물어봐서 수정해두도록 하겠습니다!

2023-11-10 08:17 UTC, D0Dam commented on src/pages/Home/components/Map/components/MarkerHtml/index.tsx
> +  <a href='/shop/${id}'>
좀 찾아보긴 했는데, onClick과 같이 핸들러를 넘겨주려면 여러모로 이쪽을 다 뜯어 고쳐야 되더라구요.
그래서 눈물을 머금고(?) 그냥 가장 쉬운 방법을... 택했습니다.

2023-11-10 08:17 UTC, D0Dam commented on src/pages/ShopDetail/components/ImageCarousel/index.tsx
> +  const next: React.ReactEventHandler<HTMLButtonElement> = () => {
오호! 습관처럼 쓰고 있었는데, 지적 감사합니다~!

2023-11-10 08:17 UTC, D0Dam commented on src/pages/ShopDetail/components/ImageCarousel/index.tsx
> +            <img src={url} alt={`${index}번 음식점`} />
으음.. 혹시 alt 를 위해서 특정 정보(음식점 이름 같이..? 여기에서는 좀 그렇지만)를 가져오기 위해서 props를 선언하는 것에 대해서는 어떻게 생각하나요?
그냥 간단하게 음식 이미지 정도의 alt를 가져가도 무방할까요?

2023-11-10 08:17 UTC, D0Dam commented on src/pages/ShopDetail/components/ReviewList/FriendReviewList.tsx
> +  );
맞아요... suspense도 해야하는데 아직 못했습니다. 이건 다음 PR 에서 하려고 합니다..(꾸벅)

2023-11-10 08:17 UTC, D0Dam commented on src/pages/ShopDetail/components/SectionHeader/SectionHeader.module.scss
> +  }
클래스 이름을 별도로 지어주는 것이 성능 향상에 도움이 되나요?! 몰랐습니다..

해당 디자인은 내부 스타일까지 굳이 알 필요가 없다고 생각했고, 각 태그에 네이밍적으로도 표현해주지 않아도 된다 판단해서 이렇게 두었습니다. (이게 편해서...)

성능 개선에 도움이 된다면 따로 분리하는 것도 좋다고 생각해요~!

2023-11-10 08:17 UTC, D0Dam commented on src/pages/ShopDetail/components/SectionHeader/index.tsx
> +  };
ui가 확실히 정해져 있는 부분이라 좀 더 ui를 강제하고 싶었습니다.
hasButton이라고 네이밍을 안지은 이유는 뭔가 has라는 prefix가 붙으면 타입이 boolean 값일 것 같기 때문이에요!

2023-11-10 08:17 UTC, D0Dam commented on src/pages/ShopDetail/index.tsx
> +        </header>
저도 그렇게 할려고 했는데  route 쪽에서 이걸 로그인 했을때나 안했을때 header를 다르게 주더라구요.
구조적으로 header 를 주는 로직이 이상해서 그냥 넣을 수 밖에 없었습니다.

2023-11-10 08:17 UTC, D0Dam commented on src/pages/ShopDetail/index.tsx
> +                  <span>{totalRating === -1 ? '0.0' : totalRating.toFixed(1)}</span>
네 -1을 주더라구요. 주석을 추가해 볼게요!

2023-11-10 08:17 UTC, D0Dam commented on src/pages/ShopDetail/index.tsx
> +      <div className={styles.container}>스켈레톤</div>
맞슴니다! suspense 넣으면서 들어갈거에요~!

2023-11-10 13:05 UTC, ChoiWonBeen commented on .eslintrc.json
> +    "implicit-arrow-linebreak": "off",
ㅋㅋㅋㅋㅋ 아하 좋아요 저도 찬성합니다

2023-11-10 13:08 UTC, ChoiWonBeen commented on src/pages/ShopDetail/components/SectionHeader/SectionHeader.module.scss
> +  }
중첩된 css는 해당 조건에 전부 해당하는지 트리를 완전탐색하기에 성능적 이슈가 생길 수 있어요(지금은 가볍지만..)
이를 해소하기 위해 css Modules를 쓴 감도 있기에, [이런 글들](https://hackernoon.com/ko/2023%EB%85%84%EC%9D%B4%EC%A7%80%EB%A7%8C-%EC%97%AC%EC%A0%84%ED%9E%88-CSS%EC%9D%98-%EC%A4%91%EC%B2%A9-%EC%8A%A4%ED%83%80%EC%9D%BC%EC%97%90-%EB%8C%80%ED%95%B4-%EC%9D%B4%EC%95%BC%EA%B8%B0%ED%95%B4%EC%95%BC-%ED%95%A9%EB%8B%88%EB%8B%A4.)을 참고해보시는것도 좋을 것 같아요. 구글 영상이 있었는데 못찾겠음..

2023-11-10 13:09 UTC, ChoiWonBeen commented on src/pages/ShopDetail/components/SectionHeader/index.tsx
> +  };
그렇다면 name과 handler보단 content, onClick은 어떨까 의견드려봅니당 😄

2023-11-10 13:09 UTC, ChoiWonBeen commented on src/pages/ShopDetail/index.tsx
> +        </header>
:아하:

2023-11-10 16:07 UTC, junghaesung79 approved these changes
고생하셨습니다! 궁금한 부분 몇 가지 적어 두겠습니다!

2023-11-10 16:07 UTC, junghaesung79 commented on src/components/StarRating/StarRatingPreview.tsx
> +          width={40}
Star로 불러온 svg에 height하고 viewBox도 있던데 width만 바꿔줘도 자동으로 비율이 조정되는 건가요??

2023-11-10 16:07 UTC, junghaesung79 commented on src/components/StarRating/StarRatingPreview.tsx
> +          fill={rate >= num ? '#ff7f23' : '#eee'}
#eeeeee를 #eee처럼 줄여서 쓸 수 있다는 것을 처음 알았습니다! 처음에 통일성을 생각하면 #eeeeee가 낫나 생각했는데 줄여서 쓸 수 있도록 만들어진 것을 보면 #eee를 사용하는 것이 좋은 것 같습니다.

2023-11-10 16:07 UTC, junghaesung79 commented on src/components/StarRating/StarRatingPreview.tsx
> +          className={styles.wrapper__star}
className을 rating 하고 rating_star이라고 하면 어떨까요? 의미도 전달 되고 간결할 것 같아요!

2023-11-10 16:07 UTC, junghaesung79 commented on src/pages/ShopDetail/components/ImageCarousel/index.tsx
> +    increment();
`if (currentIndex !== imageUrls.length - 3) increment();` 라고 적을 수도 있나요? 한 줄로 하면 '마지막 이미지가 아니라면 1 올린다.' 이런 식으로 읽을 수 있을 것 같은데 어떻게 생각하시나요?

2023-11-10 16:07 UTC, junghaesung79 commented on src/pages/ShopDetail/components/ImageCarousel/index.tsx
> +function ImageCarousel({ imageUrls }: Props) {
컴포넌트 이름을 Carousel이라고만 하면 의미 전달이 잘 안 되려나요? 만약 괜찮다면 밑에 className도 바로 crousel이라고 할 수 있을 것 같아요!

2023-11-10 16:07 UTC, junghaesung79 commented on src/pages/ShopDetail/index.tsx
> +                  <StarRatingPreview rate={totalRating} />
컴포넌트 이름에 Rating이 들어가니까 클래스 이름도 rating이라고 해도 좋을것 같은데 어떻게 생각하시나요?

2023-11-10 16:07 UTC, junghaesung79 commented on src/pages/ShopDetail/index.tsx
> +              </button>
이 부분도 분리하면 className 짓기에 더 편할 것 같아요:smile:

2023-11-14 04:41 UTC, D0Dam commented on src/pages/ShopDetail/components/SectionHeader/index.tsx
> +  };
좋아요~!

2023-11-14 04:45 UTC, D0Dam commented on src/components/StarRating/StarRatingPreview.tsx
> +          width={40}
네! 자동으로 조절이 됩니다!

2023-11-14 04:47 UTC, D0Dam commented on src/components/StarRating/StarRatingPreview.tsx
> +          className={styles.wrapper__star}
기존에 만들어진 컴포넌트(StarRating)의 jsx와 css를 재활용해서 만들었습니다!
그래서 기존에 merge 되어있는 클래스 명이라 다시 안 바꾸어도 된다고 생각해요!

2023-11-14 04:49 UTC, D0Dam commented on src/pages/ShopDetail/components/ImageCarousel/index.tsx
> +    increment();
되도록이면 `!` , `!==` 과 같은 부정형 연산을 피하는게 좋아요.
읽는데 부정형 표현이 많으면 그만큼 코드를 읽기가 불편해지거든요!

관련해서 클린코드를 참고해보면 좋을 것 같아요! (검색어 : 부정현 연산, 부정 조건문 등..)

2023-11-14 04:51 UTC, D0Dam commented on src/pages/ShopDetail/components/ImageCarousel/index.tsx
> +function ImageCarousel({ imageUrls }: Props) {
Carousel 이라고만 하기에는 컴포넌트 자체가 이미지만을 케러셀로 보여주려고 하기 때문에 Image 라는 말을 앞에 붙여주는게 좋다고 생각해요!
만약 이미지 이외에 컴포넌트나 문자열과 같은 데이터도 케러셀로 보여줄 수 있다면 Carousel로 네이밍을 지을 것 같네요~!

2023-11-14 04:52 UTC, D0Dam commented on src/pages/ShopDetail/index.tsx
> +                  <StarRatingPreview rate={totalRating} />
좋아요~! 통일성을 주면 좋겠네요!

2023-11-14 04:54 UTC, D0Dam commented on src/pages/ShopDetail/index.tsx
> +              </button>
음... 따로 컴포넌트를 분리해서 얻을 수 있는 이점을 모르겠어서 분리를 안했는데, 혹시 이걸 분리한다면 얻을 수 있는 이점이 className 작명 외에 다른 부분이 있을까요?

2023-11-14 05:00 UTC, junghaesung79 commented on src/pages/ShopDetail/components/ImageCarousel/index.tsx
> +    increment();
과연 그렇군요! 참고하겠습니다!

2023-11-14 05:04 UTC, junghaesung79 commented on src/pages/ShopDetail/index.tsx
> +              </button>
아뇨 그 부분 말고는 이점이 없는 것 같아요. 저는 분리하면 할 수록 좋은 줄 알았는데 확실히 어떤 이점이 있나 생각해보고 분리하는 것이 맞겠네요😃

2023-11-14 05:14 UTC, D0Dam commented on src/pages/ShopDetail/index.tsx
> +              </button>
style 때문에 분리를 하는것도 코드를 읽기 편하게 하기 위한 방면으로도 분리를 하는 경우가 있긴하죠!
이건 프로젝트 규칙이나 개인 성향에 따라서 나뉠 수 있다고 생각해요! 해성님의 의견도 맞다고 생각합니다~!

2023-11-14 05:17 UTC, merged