[공통] 검색 API 모킹
BCSDLab/TEMP_PROJECT_FE pull request #117
Opened 2023-11-09 12:26 UTC by kimeodml

## [#110 ] request

- msw를 활용해 `shops/` api 모킹 했습니다. 
- 추가적으로 검색의 useSearchForm을 전역 상태 관리로 변경하여 검색쪽 코드를 조금 수정했습니다.
- 그 외에 불필요한 console.log 및 주석 제거했습니다.

## Please check if the PR fulfills these requirements

- [X] It's submitted to `develop` branch, __not__ the `main` branch
- [X] The commit message follows our guidelines
- [X] There are no warning message when you run `yarn lint`
- [X] Docs updated for breaking changes

### Screenshot

2023-11-09 20:33 UTC, D0Dam requested changes
안녕하세요! 대의님은 거의 처음 리뷰해 보는 것 같네요! ㅎㅎ
msw 2.0 버전을 사용해 주셨네요! 정말 최신걸 사용해 주셨네요. 덕분에 저도 한 번 더 되짚어보고 갑니다! 뭔가 노드 버전 올린것도 msw 때문일까요? 아무튼.. msw 로직 관련해서 리뷰 남겨 놓았습니다! 확인 부탁드려요~!

2023-11-09 20:33 UTC, D0Dam commented on src/mocks/api/shopsResult.ts
> +}
undefined 를 꼭 써야만 했던 이유가 있을까요?
api 자체가 둘 중 한개가 undefined 라면 500 에러를 내보내기 때문에 애초에 undefined인 것을 타입 단에서 방지하면 어떨까요?

<img width="1400" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/51052049/4287b14e-e5c3-4426-bde9-9dfee24a1ca7">

```suggestion
interface RequestBody {
  lat: number;
  lng: number;
}
```

만약 현재와 같은 형태를 유지하려 한다면 아래와 같이는 못 가져갈까요?

```suggestion
interface RequestBody {
  lat?: number;
  lng?: number;
}
```

이후 외부 fetch 로직에서 보내주는 body에 lat이나 lng이 undefined이라면 RequestBody 타입에 맞지 않기 때문에 mocking된 api에서는 500에러를 보내주게끔 설계하면 될 것 같네요!

혹여 500 에러에 대한 ResponseBody를 구현하신다고 하면 다음과 같은 형태로 가져가면 될 것 같습니다.

<img width="1312" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/51052049/6a7af9f6-a708-4af2-9f01-2663da793191">

2023-11-09 20:33 UTC, D0Dam commented on src/mocks/api/shopsResult.ts
> +    const body = await request.json() as RequestBody;
1. mocking 된 api 이기 때문에 앞에 굳어 API_PATH 를 명시해주지 않아도 될 것 같습니다.
2. assertion 보다는 제네릭을 사용해 보면 좋을 것 같네요.

```suggestion
interface PathParams {
  keyword: string;
}

  http.post<PathParams, RequestBody>('/shops', async ({ request }) => {
    const body = await request.json();
```

2023-11-09 20:33 UTC, D0Dam commented on src/mocks/api/shopsResult.ts
> +    body.lng = 127.97;
다음과 같은 연산을 api 내부에서 해주면 안되지 않을까요..?
혹시 외부의 fetch 로직에서 body가 잘못되어도 실행시켜주게끔 하기 위한 로직이라면 제거하고, 외부에서 body를 제대로 넣는 쪽으로 가는 것이 좋을 것 같습니다!

mocking 된 api를 사용하는 목적 자체가 바로 server api를 사용할 수 있게 하는 역할이 큰데, 이러한 연산이 중간에 존재하면 이 장점을 잃어버려요.. 그래서 최대한 server api와 동작이 비슷하게 (비슷하게 구상할 수 없다면 fetch 로직에 대한 응답 형태가 올바르게만이라도) 가져가는 것이 좋다고 생각합니다!

2023-11-09 20:33 UTC, D0Dam commented on src/mocks/api/shopsResult.ts
> +    }
별건 아니지만 api 상에서는 이 경우 500에러가 나네요..!
겸사겸사 에러 응답도 같이 긁어와 봤습니다!

```
const ERROR_RESPONSE = {
  "className": "HttpMessageNotReadableException",
  "errorMessage": "JSON parse error: Unrecognized token 'undefined': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false');",
  "code": 0,
  "httpStatus": "INTERNAL_SERVER_ERROR",
  "errorTrace": "서버쪽 어느 경로"
} as const; // 따로 위에 선언
```

```suggestion
    if (typeof body.lat !== 'number' || typeof body.lng !== 'number') {
      return new HttpResponse(errorResponse, { status: 500 });
    }
```

2023-11-09 20:33 UTC, D0Dam commented on src/mocks/api/shopsResult.ts
> +    const filteredShops = shopsResultData.filter((shop) => shop.name.includes(keyword ?? ''));
`keyword ?? ''` 와 같이 해준 이유가 있나요?

api 자체가 keyword params가 꼭 존재해야 사용할 수 있는 것이기 때문에 그냥 `keyword` 로 사용해줘도 될 것 같아요. 아마 위의 코멘트대로 고친대로 한다면 제네릭 때문에 이럴 경우가 없겠지만, keyword가 nullish 한 경우는 에러로 빼는 것이 더 올바른 동작 같아요!

2023-11-09 20:33 UTC, D0Dam commented on src/mocks/api/shopsResult.ts
> +    });
```
{
  "pageToken": string | null,
  "shopQueryResponseList": Shop[]
}
```
 response body 의 형태가 이러하니 return 하는 객체 형태를 위와 맞게 해주는 것이 좋을 것 같아요!

```suggestion
    return HttpResponse.json({
       pageToken: null,
      shopQueryResponseList: filteredShops,
    });
```

2023-11-09 20:33 UTC, D0Dam commented on src/store/text.ts
> +const useSearchForm = () => {
혹시 search text 를 전역 상태로 분리한 이유를 들어 볼 수 있을까요?

2023-11-10 08:33 UTC, kimeodml commented
@D0Dam 요거 노드 버전을 올려도 계속 오류가 나는 것 같은데 다시 낮추는 게 나을까요?

2023-11-10 16:08 UTC, MinGu-Jeong commented
@kimeodml CI로 등록되어있는 Github Action workflow파일을 수정하면 될 것 같아요! 지금 16버전 쓰고있네여 😄 
<img width="1350" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/51395707/e37ea0f7-9e52-4a37-9680-a90b3402f6b0">

2023-11-11 14:28 UTC, D0Dam commented
밑에 민구 형님 말씀대로 가면 될 것 같습니다 ㅎㅎ

2023-11-14 10:00 UTC, kimeodml commented on src/mocks/api/shopsResult.ts
> +}
`useGeolocation`을 사용하려다 하드 코딩으로 변경한 것이었는데 그 과정에서 undefined가 남아버렸습니다. 하단의 리뷰처럼 server api와 유사한 형식으로 변경되게 `useGeolocation`을 활용하겠습니다!

2023-11-15 11:17 UTC, kimeodml commented on src/mocks/api/shopsResult.ts
> +}
무의식적으로 useGeolocation을 떠올려서 타입에 undefined도 추가했었네요. 타입을 단언하는 방식으로 변경하겠습니다.

2023-11-15 11:27 UTC, kimeodml commented on src/mocks/api/shopsResult.ts
> +    body.lng = 127.97;
넵 제외하겠습니다!

2023-11-15 12:01 UTC, kimeodml commented on src/mocks/api/shopsResult.ts
> +    const filteredShops = shopsResultData.filter((shop) => shop.name.includes(keyword ?? ''));
이전 코드에서 `keyword ?? ' '`로 되어 있어서 위와 같은 방식으로 처리했는데 keyword가 required였네요. 수정하겠습니다.

2023-11-16 12:55 UTC, kimeodml commented on src/mocks/api/shopsResult.ts
> +    }
500에러로 변경했습니다.[1141eab](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/117/commits/1141eab09c67ef5d62f21da7a3379c54b5333d63)

2023-11-16 12:58 UTC, kimeodml commented on src/store/text.ts
> +const useSearchForm = () => {
이전 코드에서 useSearchForm을 여러 파일에서 호출하거나 props로 넘겨준 컴포넌트에서 또 호출하는지 등 재사용성이 있을 것 같아서 전역 상태 관리로 변경했습니다.

2023-11-16 12:58 UTC, kimeodml commented on src/mocks/api/shopsResult.ts
> +    });
수정했습니다.[1141eab](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/117/commits/1141eab09c67ef5d62f21da7a3379c54b5333d63)

2023-11-16 13:00 UTC, kimeodml commented on src/mocks/api/shopsResult.ts
> +    const body = await request.json() as RequestBody;
이 부분 경로를 API_PATH로 명시해 주지 않으면 Service Worker랑 서버 api랑 동시에 발생돼서 수정하지 못 했습니다. 혹시 이유가 뭔지 알 수 있을까요...?

2023-11-16 19:55 UTC, D0Dam approved these changes
잘 반영해 주셔서 감사합니다~! 코멘트 다시 남긴것만 확인 부탁드려요~!

2023-11-16 19:55 UTC, D0Dam commented on src/mocks/api/shopsResult.ts
> +    const body = await request.json() as RequestBody;
음... 우선 지금 axios.create 를 사용해서 API_PATH를 base url 로 받고 있는게 문제 같네요.
전용 MSW 환경이 없어서 지금 API_PATH 를 위에서 지워버리게 되면 msw handler에서는 가로채지만, axios.create 로 만들어진 새 요청이 생겨버려요.
msw 환경을 이제 별도로 둘 수 있다고 하면 msw 환경에서는 API_PATH 를 '/' 로 두고 제가 전 코멘트에서 말한것처럼 삭제하고 쓰면 됩니다.

그런데 지금 문제가.. msw 코드가 이것 밖에 없다보니 절대 경로를 명시해줄 수 밖에 없는 것 같네요..
그래서 msw 전용으로 axios create 해 두는것도 좋을 것 같고, 우선 대의님처럼 두어도 절대 경로이긴 하니 괜찮을 것 같아요!
아래 예시도 첨부합니다.

<img width="604" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/51052049/1cfd1317-5e6b-4c77-8d6b-0f2b3bdd74c2">

2023-11-16 19:55 UTC, D0Dam commented on src/store/text.ts
> +const useSearchForm = () => {
아하! 그렇군요. 설명 감사합니다~!

2023-11-20 10:14 UTC, kimeodml commented
오호! 친절한 설명 감사합니다! 기존 코드로 진행하겠습니다.

2023-11-22 04:24 UTC, D0Dam commented
오호... 제 환경에서는 lint가 안뜨는데 ci를 할 때는 계속 lint 에러가 뜨네요.
확인을 좀 더 해보니까 eslint 버전이 해당 플러그인하고 맞지 않을 때 이런 에러가 뜬다고 해요.
혹시 eslint 버전을 올리고 플러그인 삭제 후 다시 깔아보는 게 어떨까요??

2023-11-28 10:57 UTC, merged