[AUTH]  아이디, 비밀번호 찾기 PC 버전 UI 추가
BCSDLab/TEMP_PROJECT_FE pull request #119
Opened 2023-11-10 08:18 UTC by LUNA-KK

## [#111] 아이디, 비밀번호 찾기 PC 버전 UI 추가

- 아이디, 비밀번호 찾기 PC 버전 UI만 추가했습니다.
- 기능은 다음 pr에서 구현하겠습니다.
- Error svg는 사용되는 부분에 일단 모두 삽입해두었습니다.

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [ ] Docs updated for breaking changes

### Screenshot
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/110970349/38927ed3-14c3-4e65-8851-a3adad4506f1)
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/110970349/1775c298-2f88-4064-ad68-69aea46cea8a)
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/110970349/0de59a36-cb3d-47af-b503-1305672e380a)

2023-11-10 09:16 UTC, MinGu-Jeong reviewed
수고하셨습니다!
`package-lock.json`이 생긴걸 보아 npm을 사용하신거 같은데 yarn을 사용해주세요🥲
사소한 리뷰 남겨놨어요!

2023-11-10 09:16 UTC, MinGu-Jeong commented on src/pages/Auth/FindIDPassword/index.tsx
> +export default function FindIDPassword({ type }: FindProp) {
다른 파일명과 일관성 있게 `FindIdPassword`는 어떤가요??

2023-11-10 09:16 UTC, MinGu-Jeong commented on src/pages/Auth/FindIDPassword/PC/index.tsx
> +      <div className={style.page}>
필요없는 공백은 없애주는게 보기 좋을것같아요!😄

2023-11-10 09:16 UTC, MinGu-Jeong commented on src/pages/Auth/FindIDPassword/index.tsx
> +export default function FindIDPassword({ type }: FindProp) {
폴더명도 수정하면 좋을 것 같아요!

2023-11-10 15:49 UTC, MinGu-Jeong commented on src/pages/Auth/FindIDPassword/index.tsx
> +export default function FindIDPassword({ type }: FindProp) {
파일, 폴더명 대소문자만 수정 시 git이 인식못하는 이슈가 있으니 파일, 폴더 삭제하고 커밋 후 다시 만들어야 한다고 하네요.

2023-11-10 17:25 UTC, junghaesung79 approved these changes
고생하셨습니다! 몇 가지 궁금한 점 질문할게요~

2023-11-10 17:25 UTC, junghaesung79 commented on src/pages/Auth/FindIDPassword/PC/ChangePassword.tsx
> +            <Error className={style.form__error} />
멍 때리면서 읽다가 Error 컴포넌트가 있나?? 하고 import를 올려 봤어요.😅 ErrorIcon 이라고 하는 건 어떨 것 같으세요?

2023-11-10 17:25 UTC, junghaesung79 commented on src/pages/Auth/FindIDPassword/PC/ChangePassword.tsx
> +import style from './index.module.scss';
[https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/108#discussion_r1372491936](url)
여기서도 같은 내용으로 리뷰를 한 적이 있는데요. 혹시 지난 회의들 중에 style과 styles의 키워드를 하나로 통일하는 것에 대한 언급이 있었나요? 제가 회의를 몇 번 빠졌어서요😅 참고로 저는 styles라고 적습니다.

만약 그동안 언급이 없었다면 다음 회의 때 말씀 꺼내주시면 감사할 것 같아요!

2023-11-10 17:25 UTC, junghaesung79 commented on src/pages/Auth/FindIDPassword/PC/ChangePassword.tsx
> +              placeholder="비밀번호를 입력하세요."
두 placeholder의 문장이 다른데 원래 이런 건가요? figma에서 확인하려고 했는데 비밀번호 마스킹으로 placeholder가 안 보여서 확인할 수 없네요😥

2023-11-10 17:25 UTC, junghaesung79 commented on src/pages/Auth/FindIDPassword/PC/ChangePassword.tsx
> +              [style.form__submit]: true,
두 라인의 위치를 바꾸는 것도 좋을 것 같은데 어떻게 생각하시나요? 바뀌지 않는 것을 먼저 읽고 변하는 것을 나중에 읽는 것이 가독성이 좋을 것이라는 게 제 생각입니다:smile:

2023-11-10 17:25 UTC, junghaesung79 commented on src/pages/Auth/FindIDPassword/mobile/index.tsx
> +import { EMAIL_REGEXP } from 'components/Auth/static/Regexp';
제가 static 키워드에 대한 이해가 떨어져서 그런데 static과 constant 중에 어느 것이 정규식과 더 어울릴까요?🤔

2023-11-10 17:25 UTC, junghaesung79 commented on src/pages/Auth/FindIDPassword/mobile/index.tsx
> +          <div className={style.form__center}>
제가 실행하지 않고 리뷰를 하고 있는데 form__center의 center는 어떤 요소인가용?

2023-11-13 05:47 UTC, chaeseungyun requested changes
고생하셨습니다
자잘한 몇개의 수정사항만 수정하면 될 것 같아요

2023-11-13 05:47 UTC, chaeseungyun commented on src/pages/Auth/FindIDPassword/PC/index.tsx
> +              })}
여기선 굳이 cn을 안써도 될 것 같아요

2023-11-13 05:47 UTC, chaeseungyun commented on src/App.tsx
>            <Route path="/find-password/change" element={<ChangePassword />} />
패스명을 pc, 모바일 통일해보는건 어떨까요?

2023-11-13 12:13 UTC, LUNA-KK commented on src/pages/Auth/FindIDPassword/PC/ChangePassword.tsx
> +import style from './index.module.scss';
네 알겠습니다

2023-11-13 12:17 UTC, LUNA-KK commented on src/pages/Auth/FindIDPassword/PC/ChangePassword.tsx
> +              placeholder="비밀번호를 입력하세요."
cca17c1201bc453b52775fde779180fb322472a7
figma에 보이는 문구로 통일했습니다.

2023-11-13 12:26 UTC, LUNA-KK commented on src/pages/Auth/FindIDPassword/mobile/index.tsx
> +import { EMAIL_REGEXP } from 'components/Auth/static/Regexp';
쩝박에서는 정규식을 static 폴더에서 사용하고 있습니다! 정적인 값을 관리하는데 static이 더 적합하지 않나 생각합니다.

2023-11-13 12:30 UTC, LUNA-KK commented on src/pages/Auth/FindIDPassword/mobile/index.tsx
> +          <div className={style.form__center}>
제가 작성한 코드는 아니지만, 버튼을 제외한 가운데 정렬할 요소들의 집합입니다.

2023-11-13 12:34 UTC, LUNA-KK commented on src/pages/Auth/FindIDPassword/PC/index.tsx
> +              })}
현재 버튼은 disable 상태를 나타내고 있습니다. 추후 기능 구현 시 active 상태를 추가하겠습니다.

2023-11-13 12:45 UTC, LUNA-KK commented on src/App.tsx
>            <Route path="/find-password/change" element={<ChangePassword />} />
b869ee3564d5bf771442aaaa19dc4b7301467610
경로명 변경했습니다.

2023-11-13 12:47 UTC, LUNA-KK commented on src/pages/Auth/FindIDPassword/PC/ChangePassword.tsx
> +              [style.form__submit]: true,
e61154c14d26474799508b16f357081be29aa387
좋은 방법인 것 같아요 수정했습니다!

2023-11-13 12:50 UTC, LUNA-KK commented on src/pages/Auth/FindIDPassword/PC/ChangePassword.tsx
> +            <Error className={style.form__error} />
f8ad58295261f5cd818fc8e4b618c3e6badc435e
가독성을 더 높힐 수 있겠네요 수정했습니다 :)

2023-11-13 13:04 UTC, LUNA-KK commented on src/pages/Auth/FindIDPassword/PC/index.tsx
> +      <div className={style.page}>
넵 수정했습니다!

2023-11-13 13:05 UTC, LUNA-KK commented on src/pages/Auth/FindIDPassword/index.tsx
> +export default function FindIDPassword({ type }: FindProp) {
a7f0768864b482bfaf4eaed01b69ef32e168c4ba
수정했습니다.

2023-11-14 05:10 UTC, D0Dam approved these changes
안녕하세요! 처음 @LUNA-KK  리뷰를 하게 되었네요~!
앞으로도 잘 부탁드려요~!
리뷰가 좀 늦어서 그냥 코멘트로만 남겨놓을게요! 반영하고 싶은 부분이 있다면 고민해보고 반영해 보았으면 좋겠어요.😆

2023-11-14 05:10 UTC, D0Dam commented on src/pages/Auth/FindIDPassword/PC/index.tsx
> +            )}
이거 id와 password 끼리 못 묶어주나요??

2023-11-14 05:10 UTC, D0Dam commented on src/pages/Auth/FindIDPassword/PC/ChangePassword.tsx
> +          </div>
이거 하나를 컴포넌트화해서 재활용하면 많은 부분에서 코드가 줄어들 것 같은데 한 번 추상화 해보는 것도 좋다고 생각해요!

2023-11-14 05:10 UTC, D0Dam commented on src/pages/Auth/FindIDPassword/PC/ChangePassword.tsx
> +            </div>
이런 input에 대한 설명을 `label`로 어떻게 못해볼까요?

2023-11-14 05:10 UTC, D0Dam commented on src/pages/Auth/FindIDPassword/PC/index.tsx
> +            onClick={() => type === 'password' && nav('/change-password-pc')}
함수를 이렇게 정의하는 것보다 외부로 꺼내서 집어넣는 게 더 좋을 것 같아요!
이렇게 jsx 안에 함수를 넣어놓으면 렌더링할 때마다 이 함수를 계속 다시 만들어서 좋지 않아요.

2023-11-14 05:10 UTC, D0Dam commented on src/pages/Auth/FindIDPassword/index.tsx
>      </div>
혹시 div 태그가 css 꼭 필요한걸까요? fragment로 안될까요?

2023-11-14 05:10 UTC, D0Dam commented on src/pages/Auth/FindIDPassword/mobile/index.tsx
> +      }
여기에서는 Error를 throw 하고 catch 문에서 Error Event를 받아서 set 해주는 flow가 더 좋을 것 같은데 어떻게 생각하시나요?

2023-11-16 13:03 UTC, LUNA-KK commented on src/pages/Auth/FindIDPassword/PC/index.tsx
> +            )}
삼항연산자 사용해서 묶으라는 말씀이실까요?

2023-11-16 13:59 UTC, chaeseungyun approved these changes

2023-11-16 13:59 UTC, LUNA-KK commented on src/pages/Auth/FindIDPassword/PC/ChangePassword.tsx
> +            </div>
b429ce7f94dbd5dc42ba4c842bed5897193a15ad
이런 방법도 있군요! ESlint 규칙도 수정하여 추가했습니다.

2023-11-16 14:18 UTC, LUNA-KK commented on src/pages/Auth/FindIDPassword/PC/index.tsx
> +            onClick={() => type === 'password' && nav('/change-password-pc')}
bea4333486a14ade93947e4d9918b0cc90a09cbe
커스텀훅을 사용해보았습니다!

2023-11-16 14:22 UTC, LUNA-KK commented on src/pages/Auth/FindIDPassword/index.tsx
>      </div>
ESLint 에러가 발생해서 div태그를 사용했습니다. 
ESLint 규칙을 수정하는게 낫다고 보시나요?

2023-11-16 14:31 UTC, LUNA-KK commented on src/pages/Auth/FindIDPassword/mobile/index.tsx
> +      }
가독성을 위해 flow를 전환시키라는 의미인가요?

2023-11-16 14:33 UTC, LUNA-KK commented on src/pages/Auth/FindIDPassword/PC/ChangePassword.tsx
> +          </div>
혹시 어떤 부분에서 재활용 할 수 있다고 보시나요?
이 구조는 다른 곳에서 쓰이고 있지 않은 것 같아요!

2023-11-16 14:38 UTC, merged