[AUTH] 아이디, 비밀번호 찾기 기능 추가
BCSDLab/TEMP_PROJECT_FE pull request #131
Opened 2024-01-06 08:56 UTC by LUNA-KK

## [#123 ] 아이디, 비밀번호 찾기 구현
아이디, 비밀번호 찾기 PC버전의 기능을 구현했습니다.

비밀번호 찾기를 하는 과정에서 아래 캡쳐 사진과 같은 에러가 발생하는데 기능적으로는 문제가 없어서 pr올립니다.
방법을 아시는 분들은 알려주시면 감사하겠습니다.

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [ ] Docs updated for breaking changes

### Screenshot
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/110970349/42ad137b-8f7a-44f9-877d-778c3f62a43e)
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/110970349/40f77223-60ae-4a31-82c0-04640a966861)

![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/110970349/9c730379-f1c8-4263-8ff0-f2da2ccafb63)
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/110970349/3832c756-f3d0-4e50-8d70-a716b438ddc7)

2024-01-06 14:11 UTC, junghaesung79 approved these changes
고생하셨습니다!
리뷰하면서 useForm을 포함해서 form에 대해서 더 생각해 볼 수 있었어요😀. 덕분에 공부가 됐어요.😊

2024-01-06 14:11 UTC, junghaesung79 commented on src/pages/Auth/FindIdPassword/PC/ChangePassword.tsx
> +              >
changeNewBlind()에서 change가 들어가 있어서 처음에 useBooleanState의  `return [value, setTrue, setFalse, toggle, setValue];` 중 setValue를 가져온 줄 알았어요.😅 toggleNewBlind 이런 이름은 어떤가요?😃

2024-01-06 14:11 UTC, junghaesung79 commented on src/pages/Auth/FindIdPassword/PC/ChangePassword.tsx
> +              >
그리고 클래스명을 생각해봤는데 `form__eye`는 어떤가요? 비밀번호를 보이거나 보이지 않게 하는 UI를 검색하니까 단순히 eye icon 이라고 하는 것 같더라구요.

2024-01-07 09:05 UTC, kimeodml requested changes, later dismissed
`user>userApiClient` 에서 `TODO: 백엔드단에서~` 부분이 아직 구현되어 있지 않은데 서버에서 지정한 오류코드(유효하지 않거나 토큰 만료 등)를 받을 시에 토큰 재발급이 이루어져야 하는데 이루어지지 않아서 계속 `Unknown promise rejection reason`이 발생하는 것 같습니다. 이 부분 추가 로직 구현해서 수정 부탁드립니다. axios Interceptor를 이용한 refreshToken 등으로 검색하시면 관련 정보 나올 거예요👊 또한 저희 FE 채널에서 이와 관련 이슈를 다룬적이 있습니다! 다만 status값은 동일할 지는 모르겠네요🤔

2024-01-07 09:05 UTC, kimeodml commented on src/pages/Auth/FindIdPassword/PC/index.tsx
> +  };
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/88065770/ed1019e9-0b50-4a83-bc37-cc982e8ecdda)
'이미 존재하는 ID입니다.'라는 409에러가 뜨는데 원래 존재하는 ID로 체크해야 하는데 이 오류가 왜 있어야 할까요...? 혹시 무슨 의미인지 짐작가시나요? 만약 불필요하다면 백엔드에게 수정 요청 드려야 할 수도 있을 것 같아요!👀

2024-01-07 09:05 UTC, kimeodml commented on src/pages/Auth/FindIdPassword/PC/ChangePassword.tsx
> +import { PasswordInfo } from '../entity';
저번 [pr](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/130)에서 제가 스타일을 제외하고 절대 경로로 호출하기로 결정해서 절대 경로로 바꿔주세요. 그리고 저희 회의에서 style import할 때 styles로 통일하기로 했습니다..! 이 또한 바꿔주세요🥲

2024-01-08 13:05 UTC, LUNA-KK commented on src/pages/Auth/FindIdPassword/PC/index.tsx
> +  };
아이디 유효성 검사를 위해 사용하여 중복체크로 에러를 반환하는게 자연스러운 흐름인 것 같아요!

2024-01-08 13:10 UTC, LUNA-KK commented on src/pages/Auth/FindIdPassword/PC/ChangePassword.tsx
> +import { PasswordInfo } from '../entity';
3d12a77f937144fad93f31f333a4b27cb8eb2b10
87fa3a7db9195cc56e6e264c14909974a81ce298
수정완료했습니다!

2024-01-08 13:26 UTC, LUNA-KK commented on src/pages/Auth/FindIdPassword/PC/ChangePassword.tsx
> +              >
838fdabd721744636aae82e78cd53878a9cdf10f
직관적인 네이밍 좋은 것 같아요 👍 
eye icon은 기존 회원가입페이지에서 사용한 네이밍 blind-icon으로 통일했습니다!

2024-01-09 05:37 UTC, chaeseungyun approved these changes
고생하셨습니다!
기능적인 문제 없이 잘 하신 것 같아요
궁금한 점 몇 개 적어두었습니다!

2024-01-09 05:37 UTC, chaeseungyun commented on src/pages/Auth/FindIdPassword/PC/ChangePassword.tsx
> +        sessionStorage.removeItem('accessToken');
여기서 accessToken을 지우는 이유는 무엇인가요?

2024-01-09 05:37 UTC, chaeseungyun commented on src/pages/Auth/FindIdPassword/PC/ChangePassword.tsx
> +                  <ShowIcon aria-hidden />
여기서 aria-hidden의 역할이 무엇인가요?

2024-01-09 07:27 UTC, hanagertrudekim approved these changes
다 수정하면 빠르게 머지해주세요!

2024-01-09 12:52 UTC, merged