#12 user apiClient, 타입 interface 정의
BCSDLab/TEMP_PROJECT_FE pull request #15
Opened 2022-09-16 18:20 UTC by ChoiWonBeen

## #12 request

- `user-controller`를 위한 userApiClient를 구현했습니다
  - `axios interceptor`를 활용해 accessToken을 재발급받을 수 있도록 구현했습니다.
- accessToken의 만료기간은 2일, refreshToken의 만료기간은 14일입니다.
  - accessToken은 sessionStorage에 저장했으며, 세션이 초기화되더라도 localStoarge에 저장한 refreshToken으로 재발급받습니다.
  - refreshToken도 만료되었다면, 각 스토리지를 초기화합니다.
- login, logout등의 동작은 먼저 완성될 #2 병합 이후 `react-query`로 custom hook을 만들어 예제를 작성할 예정입니다.
- user 관련 타입들을 `entity.ts` 파일에 정의했습니다.
- baseUrl에 `.env` 파일을 사용합니다. 스웨거에서 사용하는 API 링크를 사용하지만, 추후 문서화가 필요해보입니다. 
## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

2022-09-17 09:46 UTC, D0Dam requested changes
인증관련 로직을 처음봐서 머리가 헤롱헤롱 하네요..ㅋㅋㅋㅋㅋㅋㅋ
최대한 노력해서 제 궁금증과 개인적인 개선책을 제시해 보았습니다.
필수적으로 수정이 필요한 부분(오타)도 있어보이니 이는 수정 부탁드립니다.
수고하셨습니다!

2022-09-17 09:46 UTC, D0Dam commented on src/api/user/entity.ts
> +  accound: string;
9줄의 `accound` 라는 변수는 `account` 오타인 것 같습니다. 확인해주세요.

2022-09-17 09:46 UTC, D0Dam commented on src/api/user/entity.ts
> +  nickname: string;
`nickname`의 경우 IModifyParams에서 선택적으로 string 타입으로 선언 가능한 것으로 보입니다.
그렇다면 이 때 modify를 하지 않거나 modify 때 `nickname`을 설정해 주지 않으면 IUser에서 nickname이 정의되지 않을 텐데 이 경우는 `api/user/index.ts`에 정의된 `getMe()`를 사용할 때 제한이가지 않을까 생각해 봤습니다.
결론적으로 register단계에서라도 `nickname` 값을 필수적으로 받거나 `IUser` interface가 가지는 `nickname` 값이 선택적이어야 되지 않나 싶습니다.

2022-09-17 09:46 UTC, D0Dam commented on src/api/user/userApiClient.ts
> +    ? { authorization: accessToken }
`authorization`의 앞 글자는 대문자여야 되는 거로 아는데.. 아닌가요..? ㅎㅎ
그리고 `Authorization`을 정의할 때의 Syntax는 다음과 같습니다.

> Authorization : `<type>` `<credentials>`

이에 맞게 타입까지 정의한다면 어떨까 싶습니다.(jwt 구현에 bearer라는 type을 주로 쓰는 것 같네요..)

2022-09-17 09:55 UTC, ChoiWonBeen commented on src/api/user/userApiClient.ts
> +    ? { authorization: accessToken }
[소문자여도 괜찮습니다](https://stackoverflow.com/a/5259004)만, Bearer는 붙이는 것을 잊었네요 수정하겠습니다

2022-09-17 10:15 UTC, ChoiWonBeen commented on src/api/user/entity.ts
> +  nickname: string;
**어제 슬랙에서 얘기한대로**, 회원가입 API `[POST]/user/`는 **닉네임 필드를 필요로 하지 않게끔 수정될겁니다.**
서버에서의 구현에 따라 다르겠지만, 보통은 기본값을 넣어두게끔 만들고(회원가입 이후 닉네임 설정을 하지 않고 종료할 수 있으니), 바로 뒤에 닉네임만을 담은 modify를 보내게끔 설계할 겁니다.

patch 메소드는 DB상의 여러 키중 특정 키만 선택해서 수정할 수 있습니다. 
닉네임뿐만 아닌 비밀번호나 추후에 추가될 프로필사진에도 적용할 수 있기에 지금으로써는 적절하다고 판단했습니다.

2022-09-17 10:30 UTC, D0Dam commented on src/api/user/entity.ts
> +  nickname: string;
아 이게 서버에서의 구현도 따라가야 된다는 부분이 있군요... 슬랙 읽고 다시 보니 충분히 고려된 설계라고 보여집니다. ㅎㅎ
서버와의 소통 중요성을 다시 되새기고 갑니다!

2022-09-17 10:30 UTC, D0Dam approved these changes

2022-09-17 12:44 UTC, SimYunSup requested changes
APIClient를 도메인별로 나누는 발상은 좋았으나 이렇게 되면 코드 중복이 많이 일어날 것으로 보이네요.  재사용할 수 있는 도메인 별로 재사용하는 APIClient에 피상속할 수 있는 무언가가 필요할 것으로 보입니다.

2022-09-17 12:44 UTC, SimYunSup commented on src/api/user/userApiClient.ts
> +    ? { authorization: `Bearer ${accessToken}` }
`headers`의 값을 호출하는 함수가 따로 만들어져 userApi를 호출할 때마다 호출되어야 할 것으로 보입니다.
이를 위해서 userApi또한 `axios.create`로 만드는 것이 아닌 `axios.request`를 통한 함수로 만들어야 할 것으로 보이구요.

2022-09-17 12:44 UTC, SimYunSup commented on src/api/user/userApiClient.ts
> +const refreshAccessToken = () => userApi.post<IRefreshResponse>('/refresh')
`/refresh` 요청에 `refreshToken`을 따로 담지는 않나요?

2022-09-17 13:13 UTC, jaewoogwak commented
고생하셨습니다~~ 저도 인증 부분하고 인터셉터를 잘 몰랐던지라 리뷰하기 위해 열심히 찾아보면서 몰랐던 부분을 알게 됐네요👍 
궁금한 점 남겨놓겠습니다.

2022-09-17 13:15 UTC, ChoiWonBeen commented on src/api/user/userApiClient.ts
> +const refreshAccessToken = () => userApi.post<IRefreshResponse>('/refresh')
주석처리한대로 api가 아직 완전히 개발되지 않아 명세가 나오는대로 추가할 예정입니다.

2022-09-17 13:16 UTC, jaewoogwak reviewed
고생하셨습니다~~ 저도 인증과 인터셉터부분을 잘 몰라서 찾아보면서 많은 도움이 됐네요👍
궁금한 점 남겨놓겠습니다.

2022-09-17 13:19 UTC, ChoiWonBeen commented on src/api/user/userApiClient.ts
> +    ? { authorization: `Bearer ${accessToken}` }
😱 accessToken의 갱신이 되지 않았네요. 구조를 개선하겠습니다.

2022-09-17 13:21 UTC, jaewoogwak reviewed
고생하셨습니다~~ 저도 인증과 인터셉터부분을 잘 몰라서 찾아보면서 많은 도움이 됐네요👍
궁금한 점 남겨놓겠습니다.

2022-09-17 13:21 UTC, jaewoogwak commented on src/api/user/userApiClient.ts
> +userApi.interceptors.response.use(
보통 access token을 세션 스토리지에 저장하고 이후 서버에 요청 시 사용하는 것으로 알고있습니다.
이때 요청 인터셉터에서 토큰을 추가시켜서 요청 날리는 것으로 알고 있는데, 
요청 인터셉터는 따로 정의하지 않은 이유가 무엇인지 궁금합니다.

2022-09-17 13:21 UTC, jaewoogwak commented on src/api/user/index.ts
> +export const register = (param: IRegisterParams) => userApi.post<IUser>('/', param);
post 타입 명시한 제네릭 부분을 지워봐도 따로 에러가 발생하지 않긴하는데, 
axios post 요청 시 인터페이스와 제네릭을 위와 같이 반드시 명시해주어야만 하는지 궁금합니다.

2022-09-18 03:44 UTC, ChoiWonBeen commented on src/api/user/index.ts
> +export const register = (param: IRegisterParams) => userApi.post<IUser>('/', param);
추후에 각각의 api를 react-query의 fetcher로 담아 custom hook에서 사용할 예정입니다.
타입을 해당 쿼리에 작성해도 괜찮지만, 1개의 쿼리가 1개의 API에 매칭되지 않는다고 생각했기에, API에 타입정의를 미리 해두어 여러 쿼리에서 타입정의를 중복해서 하지 않게끔 작성했습니다.

2022-09-18 03:46 UTC, ChoiWonBeen commented on src/api/user/userApiClient.ts
> +userApi.interceptors.response.use(
오 생각해보니 request 인터셉터로 [위 header에 accessToken이 갱신되지 않는 문제](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/15#discussion_r973581361)를 개선할 수 있겠네요!
requset interceptor에 헤더 갱신 추가하겠습니다. 👍 👍

2022-09-18 04:52 UTC, jaewoogwak approved these changes

2022-09-18 08:22 UTC, pumpkiinbell commented on src/index.tsx
> +      staleTime: 5 * 60 * 1000,
서비스 초기엔 staleTime 을 길게 설정해도 괜찮아 보이지만, 사용자가 많아질 경우 해당 옵션 때문에 서버 상태와의 동기화가 잘 되지 않을 것으로 예상되네요

서비스마다 차이가 있을 수 있겠지만, 개인적으론 QueryClient 의 기본 옵션대로 놔두고 Server State 가 거의 변하지 않을 것으로 예상되는 쿼리에 명시적으로 staleTime option 을 주는것이 더 적합하단 생각이 듭니다 🤔

2022-09-18 08:28 UTC, ChoiWonBeen commented on src/index.tsx
> +      staleTime: 5 * 60 * 1000,
개발 시의 편의성만 생각하다보니 서버 상태의 변화를 너무 간과하고 있었네요.
좋은 의견 감사합니다!! 😊 👍

2022-09-18 08:30 UTC, pumpkiinbell commented on src/api/user/entity.ts
> +export interface ILoginParams {
엄청 사소하지만 I 를 접두어로 붙이는 특별한 이유가 있나 궁금하네요 ㅎㅎ
컨벤션이라면 I 를 접두어로 붙이는 것을 컨벤션으로 한 이유가 있나 궁금합니다

2022-09-18 08:36 UTC, ChoiWonBeen commented on src/api/user/entity.ts
> +export interface ILoginParams {
여러 레포지토리를 보면서 I를 붙인 경우가 가장 많아서 따라간 느낌이 큰거같아요.
타입스크립트를 이번 프로젝트에 처음 적용해보는 인원이 많다보니 가장 명시적이고 간편하다는 생각에 따라갔네요 ㅋㅋ

2022-09-18 08:45 UTC, SimYunSup commented on src/api/user/entity.ts
> +export interface ILoginParams {
추가적인 코멘트를 달자면 TypeScript를 만든 마이크로소프트의 다른 제품인 C#에서 I-접두사 변수를 많이 써왔던 이력이 있어서 따라가다보니 이렇게 되었던 것으로 보입니다(저 역시 그랬구요). 타입스크립트 관련해서 이 문제에 대해 찾아보니 I-prefix를 사용할 필요도 없고(자바스크립트에서는 해당 표기법을 사용하지 않기 때문에) 일관성을 파괴하기에 지양해야 한다고 하는군요. 처음 알게되었습니다. 이후의 네이밍을 할 때에는 주의해야겠네요.
[출처](https://github.com/microsoft/TypeScript-Handbook/issues/121)

2022-09-18 08:51 UTC, ChoiWonBeen commented on src/api/user/entity.ts
> +export interface ILoginParams {
PascalCase로만 작성해도 변수명이 겹칠일은 없겠지만 안정적인 자동완성이나, 명시적이라는점에서 문제점이라고 생각하지는 않았는데, 처음 참여하는 인원들이 "이렇게 네이밍해야한다"라고 생각하지는 않게끔 알고있어야겠습니다 🧐

2022-09-18 12:37 UTC, hanagertrudekim approved these changes

2022-09-18 13:44 UTC, SimYunSup approved these changes

2022-09-18 13:46 UTC, merged