Feature/#2
BCSDLab/TEMP_PROJECT_FE pull request #16
Opened 2022-09-21 14:36 UTC by kimeodml

## 2 로그인 페이지 추가
로그인 페이지 만들었습니다.
로고와 카피라이트는 회원가입과 공통부분이라 common 폴더에 따로 추가하였습니다.

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [ ] Docs updated for breaking changes

### Screenshot
![Honeycam 2022-09-21 23-35-24](https://user-images.githubusercontent.com/88065770/191533482-e7f5c918-dd35-4aee-a664-ceadccd17b75.gif)

2022-09-21 14:57 UTC, D0Dam reviewed
수고하셨습니다! 간단하게 코멘트 남겼습니다! 추후에 더 자세히 보고 더 코멘트 보내겠습니다.

2022-09-21 14:57 UTC, D0Dam commented on src/App.tsx
> -      <Route path="/" element={<DefaultLayout><Home /></DefaultLayout>} />
`<Route path="/" element={<DefaultLayout><Home /></DefaultLayout>} />`
이거 삭제하시고 그냥 
` <Route path="/" element={<Home />} />`
를 넣으셨는데, 이건 다시 복구 해야되지 않을까요..?

2022-09-21 14:57 UTC, D0Dam commented on src/index.scss
> +    min-width: 216px;
제가 알기로는 moblie device의 min width는 320px을 많이 주더라구요!`min-width`를 216px로 준 이유가 있을까요?

2022-09-21 15:58 UTC, kimeodml commented on src/App.tsx
> -      <Route path="/" element={<DefaultLayout><Home /></DefaultLayout>} />
바꿔 놓은지 몰랐네요 수정하겠습니다!

2022-09-21 15:59 UTC, kimeodml commented on src/index.scss
> +    min-width: 216px;
로그인 화면 기준에서 가장 너비가 긴 부분만을 생각해서 너비를 줬습니다. 모든 디자인이 나오지 않아서 최소 너비를 몇으로 설정해야 될지 모르겠지만, 현재로선 320px이 더 자연스러워 수정하겠습니다.

2022-09-22 01:29 UTC, jaewoogwak reviewed
고생하셨습니다~ 코멘트 남겨두었습니다!!

2022-09-22 01:29 UTC, jaewoogwak commented on src/pages/Auth/LoginPage/index.tsx
> +            <button type="submit" disabled={!isValid || !isDirty} className={styles.loginform__button}>
`isDirty`를 `disabled`에 함께 넣은 이유가 있나요?
`isDirty`는 사용자가 폼에 입력을 하나라도 했는지 안했는지에 따라 `true/false`를 리턴하는걸로 아는데, Submit을 비활성화 시키는데에 목적이 "폼이 비어있는지 여부"에 따르는거라면 `isValid` 하나만 사용해도 되지 않을까요?? 실제로 `isDirty`가 없어도 잘 작동합니다.

2022-09-22 01:29 UTC, jaewoogwak commented on src/pages/Auth/LoginPage/index.tsx
> +  } = useForm<IFormInput>({ mode: 'onChange' });
`mode`를 `onChange`로 준거는 추후에 매 입력마다 유효성 검사를 위함인가요??

2022-09-22 01:49 UTC, ChoiWonBeen requested changes
고생하셨어요~ 언급한 내용들 수정 부탁드릴게요.

2022-09-22 01:49 UTC, ChoiWonBeen commented on src/components/common/AuthTitle/index.tsx
> +function AuthTitle(): JSX.Element {
`components/common/` 은 모든 페이지에서 사용될 수 있는 컴포넌트를 모아둔 것이라 따로 구분해놓았습니다.
AuthTitle은 Auth관련 페이지에만 사용될테니, 폴더 구조를 바꾸는 게 좋아보이네요.

2022-09-22 01:49 UTC, ChoiWonBeen commented on src/components/common/AuthTitle/index.tsx
> +      <div className={styles.title__text}>쩝쩝박사</div>
이 요소가 페이지의 타이틀이라면, 헤딩 엘리먼트로 표현하는게 의미론적일 것 같네요.

2022-09-22 01:49 UTC, ChoiWonBeen commented on src/components/common/Copyright/Copyright.module.scss
> +  margin-top: 155px;
다른 Auth 관련 화면에서도 같은 하단 위치에 고정이 되어야할텐데, 회원가입, 계정찾기 등의 다른 UI들이 전부 같은 height값을 가진다고 보장할 수 없을 것 같네요.
마진으로 관리하기엔, 다른 페이지에서는 위로 올라가거나 하는 등의 문제가 있을겁니다.

2022-09-22 01:49 UTC, ChoiWonBeen commented on src/components/common/Copyright/index.tsx
> +      &nbsp;BY BCSDLab ALL RIGHTS RESERVED.
&nbsp는 왜 사용됐나요??
이미 `new Date.getFullYear()`를 출력하기 위한 중괄호를 만들어놨으니 앞뒤에 문자열로 띄어쓰기를 추가하는게 더 보기 좋을거같아요.

2022-09-22 01:49 UTC, ChoiWonBeen commented on src/pages/Auth/LoginPage/LoginPage.module.scss
> +}
body의 속성과 같은거같은데, 따로 지정한 이유가 있을까요?
height같은 경우엔 100%가 더 어울린다고 생각합니다. 상위태그가 같은값으로 지정이 되어있으니깐.

2022-09-22 01:49 UTC, ChoiWonBeen commented on src/pages/Auth/LoginPage/LoginPage.module.scss
> +    height: 57px;
구글, 카카오, 네이버 각 버튼이 겹치는 CSS가 정말 많을건데, 클래스를 묶어서 사용하는게 좋아보여요.
한 태그에 두 개 이상의 클래스를 줄 수 있다는 점을 활용하면 좋을듯하네요.

2022-09-22 01:49 UTC, ChoiWonBeen commented on src/pages/Auth/LoginPage/index.tsx
> +        {!isMobile && <Copyright />}
다른 모든 컴포넌트에서 모바일일때 Copyright이 없다면, isMobile이라는 state를 활용하는것보단, Copyright의 css에서 mediaquery를 이용해 `display: none`을 주는 것이 성능적으로도, 재사용하기에도 좋습니다.

2022-09-22 06:33 UTC, SimYunSup requested changes
생각해볼만한 것들을 추가로 리뷰했습니다.

2022-09-22 06:33 UTC, SimYunSup commented on src/pages/Auth/LoginPage/index.tsx
> +              <div className={styles.dot} />
**해당 리뷰는 둘 중에 하나를 선택해주세요**
해당 switch가 키보드 컨트롤에 걸리지 않습니다. 커스텀 checkbox(예는 이 switch가 있겠네요.)는 [다음](https://headlessui.com/react/switch)을 참고해서 컴포넌트로 만들어서 사용하는 것이 좋아보입니다.
input을 사용하지 않고 button을 사용하고 `role=switch`를 부여하고 관리하고, checked 상태를 리액트에서 관리하고, 비제어 컴포넌트로 감싸서 react-hook-form에 대응가능하도록 만들어야 합니다.(버튼을 사용할 경우 자동으로 키보드 컨트롤은 만들어집니다.)
 
키보드 사용보다는 구현이 우선이라면 `.dot`을 가진 div에 `aria-hidden`을 주세요.

2022-09-22 06:33 UTC, SimYunSup commented on src/pages/Auth/LoginPage/index.tsx
> +  } = useForm<IFormInput>({ mode: 'onChange' });
`onChange`로 굳이 바꾼 이유가 저도 궁금하네요. `onChange`로 바꿨을 때는 `react-hook-form`에서 `shouldRender`를 계속 [계산](https://github.com/react-hook-form/react-hook-form/blob/35bacba04380c937806588902e33f7f54694944c/src/logic/createFormControl.ts#L687)해서 성능 하락 이슈가 있을 수 있습니다. (7버전 초반대에서는 항상 재렌더링합니다)

하지만 모든 필드를 입력했을 때 submit 버튼을 활성화 하는 것을 꼭 넣어야 한다면 어쩔 수 없네요.

2022-09-22 06:33 UTC, SimYunSup commented on src/components/common/AuthTitle/index.tsx
> +function AuthTitle(): JSX.Element {
추가로 JSX.Element는 자동으로 추론되니 안 쓰셔도 됩니다.

2022-09-22 06:33 UTC, SimYunSup commented on src/pages/Auth/LoginPage/LoginPage.module.scss
> +.dot {
`cursor: pointer`를 넣는 것이 좋아보입니다.

2022-09-22 06:33 UTC, SimYunSup commented on src/pages/Auth/LoginPage/index.tsx
> +              <Link className={styles.social__google} to="/"><GoogleIcon /></Link>
`title`속성으로 대체 텍스트를 제공하는 것이 좋습니다.

2022-09-22 06:33 UTC, SimYunSup commented on src/pages/Auth/LoginPage/index.tsx
> +              <Link className={styles.social__google} to="/"><GoogleIcon /></Link>
https://stackoverflow.com/questions/69461305/how-to-add-alt-to-an-svg-imported-as-a-react-component-using-svgr `title`속성을 넣으면 svgr에서 알아서 title태그로 변환해줍니다.

2022-09-22 06:33 UTC, SimYunSup commented on src/pages/Auth/LoginPage/LoginPage.module.scss
> +    height: 57px;
해당 버튼이 `hover`했을 때, `focus`했을 때를 알려주는 CSS를 추가해주시면 더 좋습니다.

2022-09-22 15:09 UTC, kimeodml commented on src/pages/Auth/LoginPage/index.tsx
> +            <button type="submit" disabled={!isValid || !isDirty} className={styles.loginform__button}>
스택오버 플로우를 [참고](https://stackoverflow.com/questions/65255298/how-to-conditionally-disable-the-submit-button-with-react-hook-form)하다보니 불필요한 기능도 함께 넣었네요. 수정하겠습니다! 나중에 세세하게 기능 추가될 때 예를 들어 input에 값을 넣었다가 홈 버튼을 누를 때 alert 문을 넣고 싶으면 isDirty를 이용하는 데 그때 추가 한다든지 할 것 같네요.

2022-09-22 15:10 UTC, kimeodml commented on src/components/common/AuthTitle/index.tsx
> +function AuthTitle(): JSX.Element {
한 글자만 쳐도 로그인 버튼 활성화 되는 기능으로 디자인 되어 있어서 스택오버플로우를 [참고](https://stackoverflow.com/questions/65255298/how-to-conditionally-disable-the-submit-button-with-react-hook-form)하여 코딩했는데 혹시 다른 방법이 있을까요?

2022-09-22 15:12 UTC, kimeodml commented on src/pages/Auth/LoginPage/index.tsx
> +  } = useForm<IFormInput>({ mode: 'onChange' });
한 글자만 쳐도 로그인 버튼 활성화 되는 기능으로 디자인 되어 있어서 스택오버플로우를 [참고](https://stackoverflow.com/questions/65255298/how-to-conditionally-disable-the-submit-button-with-react-hook-form)하여 코딩했는데 혹시 다른 방법이 있을까요?

2022-09-22 15:13 UTC, kimeodml commented on src/components/common/AuthTitle/index.tsx
> +function AuthTitle(): JSX.Element {
수정하였습니다
[352d69a](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/16/commits/352d69ac9e4451131e987a1aa0c766a5c635c265)

2022-09-22 15:14 UTC, kimeodml commented on src/components/common/AuthTitle/index.tsx
> +      <div className={styles.title__text}>쩝쩝박사</div>
수정하였습니다
[476a062](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/16/commits/476a062713708ec62d841f02881a6fff433a1a9e)

2022-09-22 15:16 UTC, kimeodml commented on src/components/common/Copyright/index.tsx
> +      &nbsp;BY BCSDLab ALL RIGHTS RESERVED.
eslint에 어긋나서 특수문자를 넣었는데 띄어쓰기로 수정했습니다
[7342a79](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/16/commits/7342a79d210e78787ee0a9059268ed15c73d0b2c)

2022-09-22 15:17 UTC, kimeodml commented on src/pages/Auth/LoginPage/LoginPage.module.scss
> +}
몇몇 겹치는 css는 제거하고 기능 몇 가지 추가했습니다. min-height: 100%로 놓으면 가운데 정렬이 되지 않아 100vh로 유지했습니다.
[6482647](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/16/commits/64826476cb2d234355cbf6a549030df23aa92069)

2022-09-23 09:20 UTC, SimYunSup commented on src/pages/Auth/LoginPage/index.tsx
> +  } = useForm<IFormInput>({ mode: 'onChange' });
기능이 그렇다면 다른 방법은 없습니다.

2022-09-23 10:49 UTC, kimeodml commented on src/pages/Auth/LoginPage/index.tsx
> +              <div className={styles.dot} />
checkbox를 display:none으로 해 놓아서 컨트롤에 걸리지 않는것 같습니다. 이 외의 방법으로 absolute과 margin-left값을 이용해 dot에 가려지는 걸로 수정해도 될까요?

2022-09-23 10:50 UTC, kimeodml commented on src/pages/Auth/LoginPage/LoginPage.module.scss
> +    height: 57px;
수정했습니다
[9a34951](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/16/commits/9a34951b0832af7fdd43877fd259bea2c71aceb1)

2022-09-23 10:50 UTC, kimeodml commented on src/components/common/Copyright/Copyright.module.scss
> +  margin-top: 155px;
수정했습니다
[9a34951](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/16/commits/9a34951b0832af7fdd43877fd259bea2c71aceb1)

2022-09-23 11:22 UTC, kimeodml commented on src/pages/Auth/LoginPage/index.tsx
> +              <Link className={styles.social__google} to="/"><GoogleIcon /></Link>
수정했습니다
[0a03050](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/16/commits/0a030507152af23fd041695c53a92de59ea6ad47)

2022-09-23 11:22 UTC, kimeodml commented on src/pages/Auth/LoginPage/index.tsx
> +        {!isMobile && <Copyright />}
수정했습니다
[1f5edc2](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/16/commits/1f5edc26b8ba25271bee6a7406f16398d34c5645)

2022-09-23 11:23 UTC, SimYunSup commented on src/pages/Auth/LoginPage/index.tsx
> +              <div className={styles.dot} />
foucs 범위가 dot을 가리켜야 하므로 좋지 못한 방법입니다.

2022-09-24 10:16 UTC, kimeodml commented on src/pages/Auth/LoginPage/index.tsx
> +              <div className={styles.dot} />
수정했습니다
[3392f80](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/16/commits/3392f809e9be08d084f842c4f06305e4ca525b8f)

2022-09-24 10:17 UTC, kimeodml commented on src/pages/Auth/LoginPage/LoginPage.module.scss
> +.dot {
[3392f80](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/16/commits/3392f809e9be08d084f842c4f06305e4ca525b8f)
수정했습니다

2022-09-24 11:00 UTC, ChoiWonBeen approved these changes
최신 develop을 머지받지 않은 상태라 머지 후 충돌나면 해결한 뒤 푸시해주시요~

2022-09-24 11:09 UTC, SimYunSup commented on src/pages/Auth/LoginPage/index.tsx
> +                      arria-hidden="true"
오타가 있습니다.

2022-09-24 11:09 UTC, SimYunSup commented on src/pages/Auth/LoginPage/index.tsx
> +              <div className={styles.dot} />
`headless-ui`를 설치한 이유가 무엇인가요?

2022-09-24 11:12 UTC, SimYunSup requested changes
추가 리뷰 했습니다.

`headless-ui`를 참고해서 구현해야 합니다. `headless-ui`를 설치하는게 아니라요.

2022-09-24 11:12 UTC, SimYunSup commented on src/pages/Auth/LoginPage/index.tsx
> +            <input className={styles['login-input']} type="text" id="id" placeholder="아이디" {...register('id', { required: true })} />
만든다면 `login-input` 말고 `loginform__input`이 더 알맞아 보입니다.

2022-09-24 11:12 UTC, SimYunSup commented on src/pages/Auth/LoginPage/index.tsx
> +              <Link className={`${styles.social__icon} ${styles.social__naver}`} to="/"><NaverIcon title="네이버 계정 연동" /></Link>
`classname`함수를 활용해주세요.

2022-09-25 10:36 UTC, kimeodml commented on src/pages/Auth/LoginPage/index.tsx
> +              <Link className={`${styles.social__icon} ${styles.social__naver}`} to="/"><NaverIcon title="네이버 계정 연동" /></Link>
수정했습니다
[120cb89](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/16/commits/120cb89bdc3a04d285bef7f6a6247d9d8dbdef60)

2022-09-25 10:38 UTC, kimeodml commented on src/pages/Auth/LoginPage/index.tsx
> +              <Link className={`${styles.social__icon} ${styles.social__naver}`} to="/"><NaverIcon title="네이버 계정 연동" /></Link>
[ead802f](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/16/commits/ead802f7ac59d8c182872dcbe073c5cdcf09c934)

2022-09-25 10:40 UTC, kimeodml commented on src/pages/Auth/LoginPage/index.tsx
> +            <input className={styles['login-input']} type="text" id="id" placeholder="아이디" {...register('id', { required: true })} />
수정했습니다
[a8c1521](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/16/commits/a8c1521ddc8c6ab5667e27b4ed314ee50adfd0dc)

2022-09-25 10:42 UTC, kimeodml commented on src/pages/Auth/LoginPage/index.tsx
> +              <div className={styles.dot} />
구현을 우선으로 변경했습니다.
[ead802f](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/16/commits/ead802f7ac59d8c182872dcbe073c5cdcf09c934)
[9e23014](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/16/commits/9e2301411470443fca492b859a82f5e94271d59e)

2022-09-26 03:06 UTC, SimYunSup commented on src/pages/Auth/LoginPage/index.tsx
> +                <input type="checkbox" id="checkbox" aria-required="true" {...register('checkbox')} className={styles.checkbox} />
`aria-required`를 넣으신 이유가 궁금하네요. 자동로그인은 왜 밖으로 갔는지도 궁금하구요.

2022-09-26 06:30 UTC, kimeodml commented on src/pages/Auth/LoginPage/index.tsx
> +                <input type="checkbox" id="checkbox" aria-required="true" {...register('checkbox')} className={styles.checkbox} />
필수적인 내용물이 아니므로 제외하겠습니다. 스위치를 누르지 않고 label 범위내에서 클릭만 하면 스위치가 켜졌다 꺼졌다 해서 라벨 범위를 수정하였습니다.

2022-09-30 13:46 UTC, kimeodml commented on src/pages/Auth/LoginPage/index.tsx
> +              <div className={styles.dot} />
제거했습니다.

2022-09-30 13:49 UTC, kimeodml commented on src/pages/Auth/LoginPage/index.tsx
> +                <input type="checkbox" id="checkbox" aria-required="true" {...register('checkbox')} className={styles.checkbox} />
자동 로그인을 label 범위에 넣으면 checkbox외의 부분에서도 클릭이 되기 때문에 분리했습니다.
[3284eb1](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/16/commits/3284eb1ed1b14da274c49e5a485c59f6baacfb8b)

2022-09-30 13:49 UTC, kimeodml commented on src/pages/Auth/LoginPage/index.tsx
> +                      arria-hidden="true"
수정했습니다

2022-09-30 15:52 UTC, SimYunSup approved these changes

2022-09-30 16:04 UTC, merged