Feature/#5
BCSDLab/TEMP_PROJECT_FE pull request #18
Opened 2022-09-22 14:17 UTC by jaewoogwak

## [#5 ] request

검색 컴포넌트 구현했습니다.

검색어 리스트는 임의의 데이터입니다.

https://user-images.githubusercontent.com/62415600/191771507-885ae890-282f-4717-82ac-832b149cf911.mp4

검색어에 따른 요청 로직은 추후 API가 나오면 추가로 구현하겠습니다.

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [ ] Docs updated for breaking changes

### Screenshot

2022-09-22 14:22 UTC, ChoiWonBeen requested changes
`yarn lint` 린트 검사 후 다시올려주세요

2022-09-22 14:22 UTC, jaewoogwak commented
> `yarn lint` 린트 검사 후 다시올려주세요

넵 지금 수정하겠습니다

2022-09-22 14:23 UTC, jaewoogwak commented
> `yarn lint` 린트 검사 후 다시올려주세요

2022-09-23 03:08 UTC, ChoiWonBeen requested changes
고생하셨어요~ 코멘트 날린 부분 확인하고 수정해주시되, 나머지 부분에서도 `margin, padding`사이 관계와 BEM네이밍을 더 명확하게 작성할 필요가 있어보입니다.
추가로 [`commit-message-convention`](https://github.com/BCSDLab/JJBAKSA_FRONT_END/blob/develop/commit-message-convention.md)을 확인해보시면, `style :`은 CSS의 수정이 아닌, 코드 자체의 스타일 수정을 일컫습니다. (줄바꿈, 세미콜론 수정 등) 해당 컨벤션을 지켜주세요.

2022-09-23 03:08 UTC, ChoiWonBeen commented on src/App.tsx
> +    </QueryClientProvider>
이번 이슈, PR과 관련없는 변경점이고,
`src/index.tsx`에 이미 `<QueryClientProvider />`가 존재합니다.

2022-09-23 03:08 UTC, ChoiWonBeen commented on src/api/user/entity.ts
> +}
text? 보다는 searchQuery나 search, query등 변수명에 알맞는게 더 좋을 것 같아요.

2022-09-23 03:08 UTC, ChoiWonBeen commented on src/api/user/index.ts
> +export const querySeachText = (param : ISearchQueryParams) => searchApi.get(`/search/${param}`);
API관련 파일들 (entity, index, apiClient) 전부 관련해서, api를 각자 폴더로 분리해둔 상태입니다
`api/user/` 경로에는 백엔드 API의 `user-controller`에 해당하는 API의 사용처를 모아둔것이니, 분리가 필요합니다.

2022-09-23 03:08 UTC, ChoiWonBeen commented on src/pages/Search/Search.module.scss
> +    align-items: center;
아마 화면을 만들면서 느꼈을텐데, 스크롤이 필요없는 상황에 스크롤이 될겁니다.
모바일, PC 둘 다 불필요한 스크롤이 발생하는데, 최상단의 margin이 그 역할을 해낸 것 같네요.
**Container로부터 어느 정도 떨어져있는지**는 margin이 아닌, padding을 사용해야합니다.

2022-09-23 03:08 UTC, ChoiWonBeen commented on src/pages/Search/Search.module.scss
> +    &__not-found {
```suggestion
    &__not-found {
      work-break: keep-all;
```
해당 속성을 추가하면 보기에 더 좋을 것 같습니다.
> 관련 음
> 식점 

같은 상황을 피할 수 있습니다.

2022-09-23 03:08 UTC, ChoiWonBeen commented on src/pages/Search/Search.module.scss
> +    margin-left: 30px;
작은 모바일 기기의 너비 360px로 봤을때 문장이 끊어집니다.
그리고 컨테이너와 컨텐츠 사이의 여백은 padding을 사용해야합니다.

2022-09-23 03:08 UTC, ChoiWonBeen commented on src/pages/Search/index.tsx
> +            <b className={styles['search__trend-banner__tag-list__tag']}>{hash_tag.map((tag) => tag.text).join(' ')}</b>
`<b />` 태그는 문장을 bold처리할 때 쓰이는데, [사용하지 말라고 권장](https://developer.mozilla.org/ko/docs/Web/HTML/Element/b)합니다. 그리고 해당 텍스트의`font-weight`을 400으로 줄여놓았으니, 더더욱 의미를 잃습니다.

그리고 BEM표기법에서, Block__Element__Element는 옳은 구조가 아닙니다.

2022-09-23 03:08 UTC, ChoiWonBeen commented on src/pages/Search/index.tsx
> +          <LensIcon className={styles.search__bar__icon} />
BEM표기법에서 Block__Element__Element 구조는 잘못된 구조입니다.
`search-bar`를 Block으로 구분하는게 맞지 않을까요?

2022-09-23 03:08 UTC, ChoiWonBeen commented on src/pages/Search/index.tsx
> +            {' '}
```suggestion
            {` ${text} `}
```
더욱 간결하게 작성할 수 있습니다.

2022-09-23 03:08 UTC, ChoiWonBeen commented on src/pages/Search/index.tsx
> +  };
로직을 컴포넌트에서 분리해, Custom hook으로 작성해주세요.

2022-09-23 03:08 UTC, ChoiWonBeen commented on src/pages/Search/index.tsx
> +function Search({ currentMode = 'trending' } : ICurrentMode): JSX.Element {
currentMode를 props로 받아오는 이유가 있나요?

2022-09-23 03:08 UTC, ChoiWonBeen commented on src/pages/Search/index.tsx
> +        </button>
button onClick > svg 보단,
`<a />`태그를 확장한 `<Link />`태그를 쓰는게 더 적절할 것 같습니다.

2022-09-23 03:08 UTC, ChoiWonBeen commented on src/pages/Search/Search.module.scss
> +  }
PC화면이 아직 만들어지진 않았지만, 현재 검색페이지를 봤을때 중앙정렬이 안된채로 왼쪽에 고정된 길이만큼 치우쳐 있는것은 옳지 않아보여요.

2022-09-23 06:21 UTC, jaewoogwak commented on src/App.tsx
> +    </QueryClientProvider>
수정 완료했습니다. [9a110cc](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/18/commits/9a110cc01fc42146d18faf557d0182a01e2aded6)

2022-09-23 06:31 UTC, jaewoogwak commented on src/api/user/index.ts
> +export const querySeachText = (param : ISearchQueryParams) => searchApi.get(`/search/${param}`);
Search 컴포넌트가 존재하는 디렉터리로 api 분리했습니다. [90ae680](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/18/commits/90ae680cda7c0b5a3db60452c8a119886db08a01)

2022-09-23 06:39 UTC, jaewoogwak commented on src/pages/Search/Search.module.scss
> +    &__not-found {
이런 속성이 있었네요.....😮 배워갑니다!

2022-09-23 06:42 UTC, jaewoogwak commented on src/pages/Search/Search.module.scss
> +    margin-left: 30px;
word-break : keep-all 속성으로 끊어지지 않게 처리하고 margin은 padding으로 수정하겠습니당

2022-09-23 07:09 UTC, jaewoogwak commented on src/pages/Search/index.tsx
> +            <b className={styles['search__trend-banner__tag-list__tag']}>{hash_tag.map((tag) => tag.text).join(' ')}</b>
<b> 태그는 아무런 의미가 없군요 시멘틱하지 않은 태그네요 수정하겠습니당

추가로 Block_Element_Element 구조도 수정할게여

2022-09-23 07:12 UTC, ChoiWonBeen commented on src/pages/Search/Search.module.scss
> +    margin-left: 30px;
`min-width`인 320px에서 깨지는 길이라면, `keep-all`로 단어단위 줄바뀜이 될 때, 나머지 요소들이 내려가게끔 만들어야해서 height등의 조정이 많이 필요할텐데, 고민을 더 해봐야할 것 같습니다. 아예 두 줄 밑으로 안내려가게 만드는것도 방법입니다.

2022-09-23 07:24 UTC, jaewoogwak commented on src/pages/Search/index.tsx
> +            {' '}
SCSS 수정 완료했습니다 [eaab6ff](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/18/commits/eaab6ffedd0cf92a2bca85adf3ce5cfe7442d1e3)

2022-09-23 07:27 UTC, jaewoogwak commented on src/pages/Search/index.tsx
> +function Search({ currentMode = 'trending' } : ICurrentMode): JSX.Element {
검색 컴포넌트의 경우 초기 상태가 포커싱이 되지 않은 상태(롤링배너, 추천문구가 보임)인데 다른 컴포넌트에서 검색 아이콘을 클릭해서 검색 컴포넌트로 이동하는 경우가 있습니다. 이때는 포커싱이 된 상태로 보여주어야 합니다. 그래서 props을 전달함으로써 다른 컴포넌트에서 검색 컴포넌트가 보여지는 상태를 제어할 수 있게 하였습니다.

2022-09-23 07:53 UTC, ChoiWonBeen commented on src/pages/Search/index.tsx
> +function Search({ currentMode = 'trending' } : ICurrentMode): JSX.Element {
Search가 라우팅에 존재하고, `App.js` 에서 라우팅 설정을 해뒀습니다. 
그럼 메인화면에서 검색창을 클릭해서 '/search'로 이동한다면 어떻게 props를 'search' 로 줄 생각인가요?
그리고 가능하다고 하면 currentMode의 type은 `currentMode ?: string` 보다는 `currentMode: 'trending' | 'search'`가 더 어울릴 것 같습니다.

2022-09-23 08:29 UTC, jaewoogwak commented on src/pages/Search/index.tsx
> +function Search({ currentMode = 'trending' } : ICurrentMode): JSX.Element {
우선은 현재 2가지 케이스가 존재합니다. App.js에서 Search가 존재하고 이때는 롤링배너, 추천문구가 보이는 상태인 `'trending'`을 currentMode로 props로 넘겨줍니다. 

다음은 메인화면에서 검색창을 클릭해서 /search로 이동하는 경우인데요, 이때는 말씀하신것처럼 props를 주는게 어렵습니다. 가능은하다고 해도 로직이 복집해질것으로 보입니다. 그래서 Search 컴포넌트의 currentMode default 값을 `'search'`로 주는건 어떤가요?
그러면 메인화면에서 검색창을 클릭해서 이동해도 `search`가 유지되고 App.js에서 라우팅한것은 props를 줄 수 있기에 `trending`이 가능합니다.

2022-09-23 08:40 UTC, ChoiWonBeen commented on src/pages/Search/index.tsx
> +function Search({ currentMode = 'trending' } : ICurrentMode): JSX.Element {
다른 컴포넌트에서 검색창을 호출할때는 `navigate('/search'), <Link to='/search'/>`를 쓰지 않나요?
라우팅으로 이동하는 페이지는 결국 App.js에 담은 props대로 들어갈거고, 결국 고정 변수를 쓴 것과 다른게 없습니다.

같은 라우팅에서 다른 효과를 주고싶다면, url에 searchParam을 담아 `/search?mode="trending"`처럼 쓰거나,
react-router-dom에서 제공하는 routing에 state를 담는 방법으로 해결할 수 있을 것 같습니다.

2022-09-23 08:43 UTC, jaewoogwak commented on src/pages/Search/index.tsx
> +function Search({ currentMode = 'trending' } : ICurrentMode): JSX.Element {
[후자의 경우](https://9x211x2.tistory.com/22)가 더 간단하고 보기 편하지 않나 싶습니다. 괜찮으면 routing에 state를 담는쪽으로 갈게요

2022-09-23 08:46 UTC, ChoiWonBeen commented on src/pages/Search/index.tsx
> +function Search({ currentMode = 'trending' } : ICurrentMode): JSX.Element {
하지만 말하고 나니깐 해당 state를 변화시키려고 state를 한개 더 만들어 동기화시키고 할 생각을 해보니...
차라리 `useSearchParams`를 활용하는 쪽이 더 좋을 것 같아요. 😅

2022-09-23 09:17 UTC, SimYunSup requested changes

2022-09-23 09:17 UTC, SimYunSup commented on src/pages/Search/Search.module.scss
> +      &--previous-button {
previous만 있는 것이 네이밍에 더 적합합니다.

2022-09-23 09:17 UTC, SimYunSup commented on src/pages/Search/Search.module.scss
> +      width: 32px;
단순 텍스트를 width를 제한하는 것은 좋지 않습니다. 
텍스트가 수정되었을 때 & 폰트가 다운로드가 안 되었을 때 깨진 UI를 보여줍니다.
없애주세요.

2022-09-23 09:17 UTC, SimYunSup commented on src/pages/Search/index.tsx
> +        </div>
`aria-label`을 과도하게 사용했습니다. 생각하기에 필요 없는 속성은 지워주세요.
https://www.accessibility-developer-guide.com/knowledge/aria/bad-practices/#adding-redundant-semantics

2022-09-23 09:17 UTC, SimYunSup commented on src/pages/Search/index.tsx
> +          <div role="presentation" className={styles['search-query-list__text--not-found']}>
`role="presentation"` 속성은 왜 사용했는지 궁금하네요.

2022-09-23 09:39 UTC, jaewoogwak commented on src/pages/Search/index.tsx
> +function Search({ currentMode = 'trending' } : ICurrentMode): JSX.Element {
navigate에 state 담아서 써보려다가 너무 복잡해져서 useSearchParam으로 구현했네요 ㅋㅋㅋ... 
확실히 쿼리스트링 활용하는게 편하네요 쿼리스트링이 라우팅에 영향주는것도 아니니..

구현 결과는 
/search : (쿼리스트링 없을때) -> `setSearchParams.get('mode')`가 null이라서 커스텀 훅에 mode를 `trending`으로 넘깁니다 (default)
/search?mode=search : (쿼리스트링 존재, 다른 컴포넌트에서 기존 /search 경로에 `?mode=search` 만 추가해서 넘겨주면 됨) -> 이때는 `setSearchParams.get('mode')`가 search라서 커스텀 훅에 mode를 'search'로 넘깁니다

일단 변경사항 적용해볼게요 문제 있으면 코멘트 부탁드립니다

2022-09-23 09:44 UTC, jaewoogwak commented on src/pages/Search/Search.module.scss
> +      &--previous-button {
오 생각해보니 button이 중복되네요.. 아래 icon도 previous로 수정하겠습니다~

2022-09-23 09:47 UTC, jaewoogwak commented on src/pages/Search/Search.module.scss
> +      width: 32px;
위의 네이밍 수정도 같이 했습니다. [23dcb1c](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/18/commits/23dcb1c39ba7ecb020f3ee1353ac95c993c04966)

2022-09-23 09:48 UTC, jaewoogwak commented on src/pages/Search/index.tsx
> +function Search({ currentMode = 'trending' } : ICurrentMode): JSX.Element {
변경 사항입니다. [a3511c1](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/18/commits/a3511c12a2ca86ef9a2ac8c1190c7ba57d6d5fab)

2022-09-23 10:12 UTC, ChoiWonBeen requested changes

2022-09-23 10:12 UTC, ChoiWonBeen commented on src/pages/Search/index.tsx
> +import RECOMMEND_TEXT from './static/recommend';
두 static 데이터의 네이밍 차이가 있는 이유가 있나요?

2022-09-23 10:12 UTC, ChoiWonBeen commented on src/pages/Search/useSearch.ts
> +  const textHandler = (e: { target: { value: SetStateAction<string> } }) => {
```suggestion
  const textHandler:ChangeEventHandler<HTMLInputElement> = (e) => {
  const textHandler = (e: ChangeEvent<HTMLInputElement>) => {
```
두 방식 중 하나로 타입을 지정하는 것이 더 적절합니다.

2022-09-23 10:15 UTC, ChoiWonBeen commented on src/pages/Search/index.tsx
> +            {' '}
?? 다른 곳에 작성한 변경내용인가요?

2022-09-23 13:49 UTC, jaewoogwak commented on src/pages/Search/index.tsx
> +          <div role="presentation" className={styles['search-query-list__text--not-found']}>
아 이전에 개발할때 onClick 속성을 넣으려다가 작동하지 않아서 role을 줬었습니다. 지금은 없으니 제거하겠습니다

2022-09-23 14:04 UTC, jaewoogwak commented on src/pages/Search/index.tsx
> +        </div>
수정했습니다! [a7a91ae](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/18/commits/a7a91ae7230220cc2cc141f81967e1eb4b6436ec)

2022-09-23 14:05 UTC, jaewoogwak commented on src/pages/Search/index.tsx
> +import RECOMMEND_TEXT from './static/recommend';
아뇨.. 따로 없습니다 snake case로 통일하겠습니당 [ccbfea6](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/18/commits/ccbfea69b5d0af529e7bba7201bbfc9adc2668dc)

2022-09-23 14:28 UTC, jaewoogwak commented on src/pages/Search/useSearch.ts
> +  const textHandler = (e: { target: { value: SetStateAction<string> } }) => {
수정했습니다 [9707cf6](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/18/commits/9707cf670d90309fcb8e359ec926fd121cbabca4)

2022-09-24 11:25 UTC, SimYunSup requested changes

2022-09-24 11:25 UTC, SimYunSup commented on src/pages/Search/Search.module.scss
> +    }
`outline:none;`을 한 이유가 무엇인가요?

2022-09-24 11:25 UTC, SimYunSup commented on src/pages/Search/index.tsx
> +  } = useSearch(curMode ? curMode as 'trending' | 'search' : 'trending');
CurrentMode의 type을 따로 만들어주세요.

2022-09-24 11:25 UTC, SimYunSup commented on src/pages/Search/useSearch.ts
> +  };
general한 네이밍으로 만들어주세요. (ex. `changeSearchMode`..)

2022-09-24 11:25 UTC, SimYunSup commented on src/pages/Search/useSearch.ts
> +  const textHandler = (e : ChangeEvent<HTMLInputElement>) => {
textHandler는 무슨 뜻인지 판단하기 힘듦니다. 길더라도 알 수 있는 네이밍으로 해주세요.

2022-09-24 11:25 UTC, SimYunSup commented on src/pages/Search/index.tsx
> +            <span aria-label="" className={styles['search-banner__tag']}>{hash_tag.map((tag) => tag.text).join(' ')}</span>
필요없는 속성은 제거해주세요.

2022-09-24 11:25 UTC, SimYunSup commented on src/pages/Search/index.tsx
> +          <ul className={styles['search-banner__tag-list']}>
ul태그의 자식요소가 왜 li가 아닌가요?

2022-09-24 11:25 UTC, SimYunSup commented on src/pages/Search/index.tsx
> +        <label aria-label="검색창" className={styles['search-bar']} htmlFor="searchBarInput">
필요없는 `aria-label`입니다.

2022-09-24 11:25 UTC, SimYunSup commented on src/pages/Search/index.tsx
> +        <div aria-label="맛집 트렌드 해시태그 리스트" className={styles['search-banner']}>
필요없는 `aria-label`입니다.

2022-09-24 11:25 UTC, SimYunSup commented on src/pages/Search/index.tsx
> +          <PreviousIcon className={styles['search-nav__icon--previous']} />
`title` 속성으로 어떤 아이콘인지 표시가 필요합니다.

2022-09-24 11:25 UTC, SimYunSup commented on src/pages/Search/index.tsx
> +          {text === '' ? null : list?.filter((item) => item.title.includes(text)).map((item) => <li key={item.title} className={styles['search-query-list__item']}>{item.title}</li>)}
ul, ol태그가 없는데 왜 li태그를 사용하나요?

2022-09-25 04:43 UTC, jaewoogwak commented on src/pages/Search/Search.module.scss
> +    }
검색창을 클릭하면 input이 포커스되어 파란색 border가 생겨서 해당 속성을 넣었습니다!

2022-09-25 06:04 UTC, jaewoogwak commented on src/pages/Search/index.tsx
> +  } = useSearch(curMode ? curMode as 'trending' | 'search' : 'trending');
수정했습니다. [200c924](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/18/commits/200c9242770d2dbb5ed3635254a850333d736901)

2022-09-25 06:15 UTC, jaewoogwak commented on src/pages/Search/useSearch.ts
> +  const textHandler = (e : ChangeEvent<HTMLInputElement>) => {
위의 핸들러 함수 네이밍도 함께 수정 완료했습니다 [e7b7933](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/18/commits/e7b7933820433bda6a2baea8229f32485bf0c685)

2022-09-25 06:20 UTC, jaewoogwak commented on src/pages/Search/index.tsx
> +        <div aria-label="맛집 트렌드 해시태그 리스트" className={styles['search-banner']}>
div 태그는 의미가 없어서 추가했는데 Trending이란 문구로 충분한가요?? 일단 수정하겠습니다.

2022-09-25 06:25 UTC, jaewoogwak commented on src/pages/Search/index.tsx
> +          <ul className={styles['search-banner__tag-list']}>
li로 수정하겠습니다!

2022-09-25 06:26 UTC, jaewoogwak commented on src/pages/Search/index.tsx
> +          {text === '' ? null : list?.filter((item) => item.title.includes(text)).map((item) => <li key={item.title} className={styles['search-query-list__item']}>{item.title}</li>)}
부모 태그에 menu를 사용했었는데, 다시 생각해보니 menu 태그를 쓸거면 자식 태그에 menuitem을 쓰는게 더 적절하겠네요
부모 태그를 menu에서 ul로 수정하겠습니다

2022-09-25 08:20 UTC, ChoiWonBeen commented on src/pages/Search/Search.module.scss
> +    }
그런 이유라면 focus가 아닌 input 자체에 넣는게 더 어울릴 것 같아요.

2022-09-25 08:24 UTC, jaewoogwak commented on src/pages/Search/Search.module.scss
> +    }
@ChoiWonBeen 넵 수정하겠습니당

2022-09-25 08:56 UTC, SimYunSup requested changes

2022-09-25 08:56 UTC, SimYunSup commented on src/pages/Search/index.tsx
> +type ICurrentMode = string | null;
헝가리안 표기법을 지양하기로 하였습니다.

2022-09-25 08:56 UTC, SimYunSup commented on src/pages/Search/index.tsx
> +          <input className={styles['search-bar__input']} id="searchBarInput" onFocus={changeSearchMode} onBlur={changeTrendingMode} placeholder="검색어를 입력해주세요" value={text} onChange={(event) => changeS
`onChange`에 함수를 또 만들지 마시고 매개변수를 React.ChangeEvent로 바꾼 뒤 함수만 넣으세요.
자세한건 합성 이벤트를 찾아보세요.

2022-09-25 08:56 UTC, SimYunSup commented on src/pages/Search/index.tsx
> +            <PreviousIcon title="previousIcon" className={styles['search-nav__icon--previous']} />
title에는 대체 텍스트가 될 만한걸 적어주세요.

2022-09-25 08:56 UTC, SimYunSup commented on src/pages/Search/index.tsx
> +          <LensIcon title="lensIcon" className={styles['search-bar__icon']} />
title에는 대체 텍스트가 될 만한걸 적어주세요.

2022-09-25 08:59 UTC, SimYunSup commented on src/pages/Search/Search.module.scss
> +    }
`focus`에서 `outline`이 필요한 이유는 `focus`되었을 때 이 input이 focus되었다는 것을 알려주기 위한 시각적인 정보입니다. outline을 없앨거면 focus되었을 때  focus되었다는 것을 알려주기 위한 처리가 필요합니다.

2022-09-25 11:24 UTC, jaewoogwak commented on src/pages/Search/Search.module.scss
> +    }
@SimYunSup 현재 input 포커싱하면 검색창이 상단으로 올라가면서 커서가 나옵니다. 이외에도 focus 되었다는 시각적인 정보를 나타내려면, 검색창 아래부분에 그림자가 생기도록 `box-shadow` 같은 속성을 주는것은 어떤가요?

2022-09-25 13:46 UTC, jaewoogwak commented on src/pages/Search/index.tsx
> +          <LensIcon title="lensIcon" className={styles['search-bar__icon']} />
> `onChange`에 함수를 또 만들지 마시고 매개변수를 React.ChangeEvent로 바꾼 뒤 함수만 넣으세요. 자세한건 합성 이벤트를 찾아보세요.

요 부분까지 적용 했습니다. [41ef5a2](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/18/commits/41ef5a24a50b1bb33441b26d466b13266ce7e606)

2022-09-25 14:05 UTC, jaewoogwak commented on src/pages/Search/index.tsx
> +        </button>
수정 완료했습니다. [6cd6dd8](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/18/commits/6cd6dd8ed24948aecc68a6133d376ac7eff3fbdb)
button > Link 변경 부분은 이전 커밋에 존재해서 링크 해두겠습니다 https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/18/commits/200c9242770d2dbb5ed3635254a850333d736901

2022-09-26 02:47 UTC, SimYunSup commented on src/pages/Search/Search.module.scss
> +    }
https://stackoverflow.com/questions/52589391/css-box-shadow-vs-outline 
outline을 아예 없애는 것은 좋지 못한 선택입니다.

2022-09-26 03:30 UTC, jaewoogwak commented on src/pages/Search/Search.module.scss
> +    }
그럼 outline 추가하도록 하겠습니당

2022-09-26 03:43 UTC, jaewoogwak commented on src/pages/Search/Search.module.scss
> +    }
[023e289](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/18/commits/023e289259eb7b50b89507d3401289dd1e64858a)

2022-09-26 10:51 UTC, D0Dam requested changes
수고하셨습니다. 개인적으로 궁금한점이나 수정 되었으면 하는점을 남겨봅니다.

2022-09-26 10:51 UTC, D0Dam commented on src/pages/Search/Search.module.scss
> +    max-width: 767px;
`max-width`를 `767px`로 설정한 특별한 이유가 있을까요?

2022-09-26 10:51 UTC, D0Dam commented on src/pages/Search/Search.module.scss
> +      &--previous {
위 코드에서
```
 &__button--previous { ...
```
이러한 형식 대신
```
 &__button {
      &--previous { ...
```
이러한 형식으로 작성한 이유가 있을까요? 이건 bem이 두번째 방식을 선호하나 갑자기 궁금해져서 질문 납깁니다.

2022-09-26 10:51 UTC, D0Dam commented on src/pages/Search/Search.module.scss
> +    font-style: normal;
css 코드를 보면 `font-style: normal;`이 많이 쓰이는데 font-style의 기본값이 normal이라 없어도 될 것 같은데 작성해 놓은 이유가 있을까요?

2022-09-26 10:51 UTC, D0Dam commented on src/pages/Search/index.tsx
> +          {list?.filter((item) => item.title.includes(text)).length === 0
* 검색어 리스트가 moblie 화면 기준으로 검색 값이 10개 이상이 넘어가면 모바일창에 스크롤이 생깁니다. 이 스크롤을 리스트에 생기게끔 만들면 좋을 것 같습니다.
* 또한 검색어 입력 후 focus를 해제했을 때 밑에 검색 값이 출력되는 것이 의도된것인지 궁금합니다.

문제 설명을 돕기 위해 gif 첨부하겠습니다.
![Sep-26-2022 19-46-51](https://user-images.githubusercontent.com/51052049/192258578-7e3ef235-0992-445b-b6ef-e0c87c64b1b1.gif)

2022-09-27 00:10 UTC, jaewoogwak commented on src/pages/Search/Search.module.scss
> +    max-width: 767px;
보통 가로모드 모바일 디바이스를 위한 조건을 767px로 많이 설정해서 그렇게 했습니다.

2022-09-27 00:16 UTC, jaewoogwak commented on src/pages/Search/Search.module.scss
> +      &--previous {
딱히 특별한 이유는 없고 Element와 Modifier를 분리해서 생각하면서 코드를 작성하다보니 그렇게 작성하였습니다.

2022-09-27 00:21 UTC, jaewoogwak commented on src/pages/Search/Search.module.scss
> +    font-style: normal;
figma에 존재하는 폰트 속성을 가져오면서 같이 넣은거 같네요..! 필요없는 속성은 제거하였습니다. [0b11c0f](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/18/commits/0b11c0f1a1ab4a2bfaa4bef548f66cea67002bcc)

2022-09-27 00:21 UTC, ChoiWonBeen commented on src/pages/Search/Search.module.scss
> +    max-width: 767px;
오..가로모드..오호.. 
모바일 가로모드를 고려할 생각은 안해봤네요.
사실 body에 준 min-width가 조금 과하다는 생각은 있었는데 전체적인 레이아웃을 정할때도 생각해보면 좋을거같네요

2022-09-27 03:08 UTC, D0Dam commented on src/pages/Search/Search.module.scss
> +    max-width: 767px;
@ChoiWonBeen  @jaewoogwak 

이렇게 하면 가로모드일때와 세로모드일때 ui가 서로 달라질 수 있는 경우가 생길 수 있다고 생각합니다.(위의 경우 ui가 정상적으로 나옵니다만...)
나중에 태블릿모드일 때도 고려해야겠지만, 추후에 이 mediaQuery를 보강시킬 때 가로모드를 따로 설정할 수 있도록 하면 좋을 것 같습니다.

2022-09-27 03:16 UTC, D0Dam requested changes
추가적으로 수정하면 좋을 것 같은 부분을 리뷰 해 놓았습니다.

2022-09-27 03:16 UTC, D0Dam commented on src/pages/Search/index.tsx
> +            {` ${text} `}
해당 텍스트가 길어지는 경우 width가 길어져 가로 스크롤이 생기는 현상이 있습니다.
검색 창에 입력할 수 있는 텍스트 최대 길이를 지정하거나 해당 텍스트 출력 방식을 변경해 주어야 할 것 같습니다.
![Sep-27-2022 12-13-32](https://user-images.githubusercontent.com/51052049/192423449-7e96e93c-eb26-4471-b1fa-267d1e5a802d.gif)

2022-09-27 13:13 UTC, jaewoogwak commented on src/pages/Search/index.tsx
> +            {` ${text} `}
해당 내용은 디자인팀과 협의하고 해결해보도록 하겠습니다. 

저는 일단 '배민' 앱처럼 관련 검색어가 존재하지 않을 경우 적절한 문구를 출력하는 식의 방법을 생각중입니다.

2022-09-27 14:45 UTC, jaewoogwak commented on src/pages/Search/index.tsx
> +          {list?.filter((item) => item.title.includes(text)).length === 0
1. 적용했습니다!
2. 의도하지 않았고, 포커스 해제 시 검색리스트가 출력되지 않는것이 UX적인 측면에서 더 낫다고 판단하여 포커스 해제 시 관련 검색어 리스트가 보이지 않게 하였습니다.

[603bca4](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/18/commits/603bca4270e9c1d69eaa6388242540549fa1f864)

2022-09-27 15:37 UTC, D0Dam commented on src/pages/Search/index.tsx
> +          {list?.filter((item) => item.title.includes(text)).length === 0
@jaewoogwak 

아 너무 좋은데요? 제가 원하던 UI였습니다👍

2022-09-28 14:54 UTC, jaewoogwak commented on src/pages/Search/index.tsx
> +          {list?.filter((item) => item.title.includes(text)).length === 0
1. 현재 기본적으로 스크롤 라인이 출력되지 않습니다.
2. 이 부분도 상점 리스트가 길어졌을때만 나옵니다.

현재 상태로 보기엔 위 문제가 발생하지 않습니다. 정확하게 어떤 부분일까요?

2022-09-29 04:12 UTC, SimYunSup commented on src/pages/Search/useSearch.ts
> +  };
굳이 as를 쓰지 않아도 `React.ChangeEvent`를 `React.ChangeEvent<HTMLInputElement>`로 바꾸면 됩니다.

2022-09-29 08:00 UTC, jaewoogwak commented on src/pages/Search/useSearch.ts
> +  };
오 그렇겠네요! 이벤트 객체 명시한거 수정할게욥

2022-09-29 13:15 UTC, ChoiWonBeen requested changes
다 좋은데 입력 공간이 조금 바뀌면 좋을거같아요.
왼쪽은 Input을 감싸는 컴포넌트에 padding-left가 들어가야 할 것 같고, 아이콘과의 간격이 조금 있어야겠죠?
<img width="393" alt="image" src="https://user-images.githubusercontent.com/50780281/193041230-013cdf9b-2061-4774-ab35-a71e91451714.png">

2022-10-01 02:45 UTC, ChoiWonBeen commented on src/App.tsx
> -      <Route path="/login" element={<LoginPage />} />
이건 없어지면 안될 것 같아요

2022-10-01 06:08 UTC, jaewoogwak commented on src/App.tsx
> -      <Route path="/login" element={<LoginPage />} />
아 충돌해결하다가 잘못 지웠네욥 수정할게요

2022-10-01 06:21 UTC, jaewoogwak commented on src/App.tsx
> -      <Route path="/login" element={<LoginPage />} />
수정했습니다~ [5da704c](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/18/commits/5da704c6321206bf0d640ac3e00fa201215f429f)

2022-10-01 13:51 UTC, ChoiWonBeen reviewed
키보드 접근성이 고려된 상태라 아쉬운 점인데, 검색 리스트를 키보드로 접근할 수 없는게 아깝네요.
다음 상세페이지 기능을 추가하며 추가해도 괜찮다고는 생각하는데 어떤 것 같나요?

그리고 통일성을 위해 useSearch는 재사용된다면 hook/ 폴더를 만들거나, 그렇지 않다면 페이지 컴포넌트 상단에 정의하는 게 좋아보여요.

2022-10-04 14:01 UTC, SimYunSup approved these changes
label에 title 속성이 있는 것은 처음 알았네요.
고생하셨습니다.

2022-10-04 14:14 UTC, ChoiWonBeen approved these changes
키보드 접근성은 다음에 챙겨보죠 😅

2022-10-04 14:58 UTC, D0Dam approved these changes
수고하셨습니다!

2022-10-04 15:08 UTC, merged