Feature/#4
BCSDLab/TEMP_PROJECT_FE pull request #19
Opened 2022-09-25 03:06 UTC by chaeseungyun

## [#4] 아이디 비밀번호 찾기 UI 추가

아이디, 비밀번호 찾기 컴포넌트를 만들었습니다.
인증번호를 입력하는 컴포넌트는 공통으로 사용한다고 생각했습니다.
실제 이메일을 입력받고 인증번호를 전송하는 로직은 나중에 api가 추가되면 수정하겠습니다

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [ ] Docs updated for breaking changes

### Screenshot

2022-09-25 04:31 UTC, jaewoogwak commented
lint 에러 수정하고 다시 푸시해주세요!

2022-09-25 06:35 UTC, ChoiWonBeen requested changes
여러모로 남겨야 할 코멘트가 많은데, 대부분은 다른 사람들의 PR에 이미 있던 내용들입니다.
KOIN_RECODE와 여기 레포지토리에 closed된, 혹은 open상태인 리뷰들을 정독해주세요.

1. state의 초기값이 있으면 타입 추론이 되어 불필요합니다.
2. state가 과하게 많습니다. form을 다루는 다른 PR들에서 힌트를 얻어주세요.
3. 로직이 hook으로 분리되지 않아 읽기 힘듭니다.
4. 변수명이 의미론적이지 못합니다. pw보다는 password를, pwch보다는 passwordCheck를 써주세요.
5. 페이지 이름도 ChangePassword가 더 적절합니다.
6. ~ing 형태를 변수명에 쓰지 않습니다. javascript camelCase convention을 확인해주세요.
7. BEM 적용이 안돼있습니다. Block__Element--modifier를 이해하고 써주세요.
8. useEffect에 의존성이 없어 모든 렌더링에 실행되는 함수는 상태관리가 안된거라고 생각이 듭니다.
9. className이 두 단어 단위일때는  modal-button 처럼 사용합니다. undersocre가 아닙니다.
10. ModalFor~~ 컴포넌트는 충분히 재사용의 단위가 됩니다. 둘의 상태가 많이 다른 것 같지도 않습니다.
11. 폴더 단위가 이상합니다. `pages/페이지종류/`에 들어가야지, Components와 Section 두 depth 모두 어울리지 않습니다.

이거 말고도 필요한 변경사항이 상당히 많은데, 다른 PR을 한번씩 읽고, 다른 사람들이 Request Change로 남긴 부분이 무엇이 문제였는지, 어떻게 해결했는지를 확인해주세요.

또한 커밋 메시지 컨벤션을 확인하고, PR에 기본적으로 담겨있는 4개의 checkbox는 PR을 올리기 전에 확인하는 부분입니다. 스스로 검사한 뒤 올려주세요.

2022-09-26 05:40 UTC, crazy-oung requested changes, later dismissed
코멘트 남겼습니다. 컴포넌트 재사용성과 네이밍에 대해 좀 더 고민해보시면 좋을 것 같습니다.

2022-09-26 05:40 UTC, crazy-oung commented on src/pages/Components/Section/ModalForID.tsx
> +export default function ModalForID() {
저라면 Id 알림 전용 모달이 필요하다는 가정하에 IdModal 로 이름을 지었을거 같습니다. 따로 For를 넣어서 길게 지으신 이유가 따로 있으실까용

2022-09-26 05:40 UTC, crazy-oung commented on src/pages/Components/Section/ModalForPW.tsx
> +        <div>재설정된 비밀번호로 다시 로그인 해주세요.</div>
위 ModalForID 에서도 그렇고 컼포넌트 만들때나 이름을 지으실 때 좀 더 고민해보셨다면 더 낫지않았을까 하는 아쉬움이 있습니다.
 특히 이 컴포넌트는 ModalForID 컴포넌트와 다른점이 설명 문 밖에 없어 보여서 재사용이 가능해 보이는데 같은 파일을 두개 만들 필요가 없어보입니다. 
모달은 사용될 때 대부분의 화면에서 같은 디자인으로 사용 되기 때문에 설명문이나 제목을 value 값을 받아서 사용 한다면 재사용이 가능하게 만들 수 있습니다.

2022-09-26 15:58 UTC, pumpkiinbell commented on src/pages/Components/Section/ChangePW.tsx
> +  const [pwch, setPwch] = useState<string>('');
pwch 라는 네이밍을 보면 어떤 의미를 내포하고 있는지 잘 떠오르지 않는것 같아요
본인만 아는 약어를 사용하는 것은 지양하는 것이 좋을것 같습니다.

2022-09-26 15:58 UTC, pumpkiinbell commented on src/pages/Components/Section/ChangePW.tsx
> +  const [pw, setPw] = useState<string>('');
이런 정적인 요소들은 컴포넌트 밖이나, 아예 새로운 모듈로 만들어서 import 해올 수 있을것 같아요.

```suggestion
const pattern = /^.*(?=^.{2,16}$)(?=.*\d)(?=.*[a-zA-Z])(?=.*[!@#$%^&+=]).*$/;

export default function ChangePW() {  
  const [pw, setPw] = useState<string>('');
```

2022-09-26 15:58 UTC, pumpkiinbell commented on src/pages/Components/Section/ChangePW.tsx
> +  const [Valid, setValid] = useState<string>('initial');
일반적으로 PascalCase 는 컴포넌트에 사용하지, 상태에는 잘 사용하지 않는것 같아요.
다른 상태와 네이밍 컨벤션을 맞춰주세요

2022-09-26 15:58 UTC, pumpkiinbell commented on src/pages/Components/Section/ChangePW.tsx
> +  };
개발하시는 도메인을 몰라 확실하진 않지만 아래로 충분하지 않나요?

```suggestion
  const checkEmpty = () => { 
    setIsEmpty(pw === '' || pwch === '');
  };
```

2022-09-26 15:58 UTC, pumpkiinbell commented on src/pages/Components/Section/ChangePW.tsx
> +  };
로직이 알아보기 너무 힘드네요 😭 아래와 같이 수정하면 충분해보여요 (혹시 다르나 확인 바랍니다)
그리고 preventdefault 에 대해 더 학습하시면 좋을것 같아요

```suggestion
  const checking = (e: React.MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    
    if (pw === '' || pwch === '') {  
      setIsEmpty(true);
      return;
    } 
    
    if(pw !== pwch){
      setValid('different');
      return;
    }
    
    if(!pattern.test(pw)){
      setValid('patternError');
      return;
    }
    
    setValid('initial');
    setIsSuccess(true);
  };
```

2022-09-27 10:51 UTC, chaeseungyun commented on src/pages/Components/Section/ModalForID.tsx
> +export default function ModalForID() {
더 간편하게 적겠습니다
제가 창의력이 부족합니다..

2022-09-27 10:52 UTC, chaeseungyun commented on src/pages/Components/Section/ModalForPW.tsx
> +        <div>재설정된 비밀번호로 다시 로그인 해주세요.</div>
모달창 재사용하겠습니다!

2022-09-27 10:52 UTC, chaeseungyun commented on src/pages/Components/Section/ChangePW.tsx
> +  const [pwch, setPwch] = useState<string>('');
정확한 변수명으로 교체하겠습니다

2022-09-27 10:52 UTC, chaeseungyun commented on src/pages/Components/Section/ChangePW.tsx
> +  const [pw, setPw] = useState<string>('');
오 좋은 정보 참고하겠습니다

2022-09-27 10:53 UTC, chaeseungyun commented on src/pages/Components/Section/ChangePW.tsx
> +  };
이런 생각을 못했습니다..
하나 배워갑니다!

2022-09-27 10:53 UTC, chaeseungyun commented on src/pages/Components/Section/ChangePW.tsx
> +  const [Valid, setValid] = useState<string>('initial');
네이밍 컨벤션 지키겠습니다

2022-09-27 10:54 UTC, chaeseungyun commented on src/pages/Components/Section/ChangePW.tsx
> +  };
넵 참고하겠습니다
추가적으로 부족한 부분도 더 공부하겠습니다

2022-10-05 03:39 UTC, jaewoogwak reviewed
고생하셨어요~~ 계속해서 코드 수정 진행되고 있는데 힘 냅시다 ㅎㅎ 코멘트 남겨둘게요

2022-10-05 03:39 UTC, jaewoogwak commented on src/pages/SearchPage/InputNumber.tsx
> +interface Itype {
여기에는 헝가리안 표기법을 사용하고 다른 곳에는 파스칼 표기법을 사용했던데 파스칼 표기법으로 통일하는게 좋을듯합니다 (헝가리안 표기법을 지양하는 방향이니)

2022-10-05 03:39 UTC, jaewoogwak commented on src/pages/SearchPage/Search.tsx
> +export default function Search({ search }: Isearch): JSX.Element {
풀 받아서 봤는데 아직 App 컴포넌트에 라우팅 추가를 하지 않은건가요? 따로 렌더링되는게 없어서요😲

2022-10-05 03:39 UTC, jaewoogwak commented on src/pages/SearchPage/Search.tsx
> +export default function Search({ search }: Isearch): JSX.Element {
다른 브랜치처럼 index.tsx를 만들어서 컴포넌트를 렌더링하는 것이 좋을듯합니다

2022-10-05 03:39 UTC, jaewoogwak commented on src/pages/SearchPage/Search.tsx
> +          <div className={style.back_icon}>
back_icon이 하나의 Block이면 back-icon이 맞지 않을까요?

Block__Element 구조라면 back__icon이 될거구요

2022-10-05 03:39 UTC, jaewoogwak commented on src/pages/SearchPage/hook/useInputCheck.ts
> +    if (e.target.value.length > e.target.maxLength) {
`e.target` 부분 destructuring 할 수 있으면 해주면 좋을거같아요

https://ko.javascript.info/destructuring-assignment#ref-526

2022-10-06 07:52 UTC, chaeseungyun commented on src/pages/SearchPage/InputNumber.tsx
> +interface Itype {
파스칼 표기법으로 수정하겠습니다~

2022-10-06 07:53 UTC, chaeseungyun commented on src/pages/SearchPage/Search.tsx
> +export default function Search({ search }: Isearch): JSX.Element {
네 라우팅 추가를 아직 안했습니다.
라우트 추가 하겠습니다...

2022-10-06 07:54 UTC, chaeseungyun commented on src/pages/SearchPage/Search.tsx
> +          <div className={style.back_icon}>
bem에 대해 더 알아보고 올바르게 수정하겠습니다!

2022-10-06 07:54 UTC, chaeseungyun commented on src/pages/SearchPage/hook/useInputCheck.ts
> +    if (e.target.value.length > e.target.maxLength) {
오.. 참고하겠습니다

2022-10-10 06:08 UTC, hanagertrudekim reviewed
수고하셨습니다! 리뷰를 늦게나마 드려봤는데, 수정할것이 있다면 수정해주세요! 😊

2022-10-10 06:08 UTC, hanagertrudeKim commented on src/pages/SearchPage/InputNumber.tsx
> +        />
이 input들의 경우엔 1,2,3,4와 같은 일정 위치의 숫자와, register의 name만 바뀌니까 컴포넌트로 분리해 재사용성을 고려해봐도 괜찮을것같습니다. 이 [링크](https://react-hook-form.com/get-started#Integratinganexistingform) 의 형식처럼 해봐도 될거같아요!

2022-10-10 06:08 UTC, hanagertrudeKim commented on src/pages/SearchPage/ChangePassword.tsx
> +        <form className={style.form} onSubmit={handleSubmit((data) => passwordConfirm(data))}>
react-hook-form 에서의 handleSubmit은 마지막에 form 제출을 위한것으로 알고있습니다. 만약, password 일치를 확인해야한다면 제출 전에 하는것이 맞다고 생각하기 때문에 저 위치는 알맞지 않은것같습니다.

2022-10-10 06:08 UTC, hanagertrudekim commented on src/pages/SearchPage/ChangePassword.tsx
> +  };
굳이 함수를 정의하지 않아도 react-hook-form 의 [기능](https://react-hook-form.com/api/useform/register)중의 하나인 validate 를 사용하면 매 입력마다 자동으로 validation 검사를 할 수 있도록 설정할수있습니다. 참고하시면 좋을것같습니다....!

2022-10-10 15:22 UTC, chaeseungyun commented on src/pages/SearchPage/ChangePassword.tsx
> +        <form className={style.form} onSubmit={handleSubmit((data) => passwordConfirm(data))}>
앗 수정하겠습니다

2022-10-10 15:23 UTC, chaeseungyun commented on src/pages/SearchPage/ChangePassword.tsx
> +  };
validate를 써봤을때 제대로 동작이 안되었던것 같아서 일부러 함수를 만들었는데 다시 시도해보겠습니다

2022-10-11 01:54 UTC, hanagertrudekim commented on src/pages/SearchPage/ChangePassword.tsx
> +  };
비밀번호에 대한 비밀번호 확인을 validate할때 저같은 경우에는 비밀번호를 watch로 구독한 값을 통해 값을 받아와 확인했던것같습니다. 그런 방법도 참고해서 하시면 도움이 될것같아요!

2022-10-12 16:33 UTC, daepan requested changes
전체적으로 코드의 수정이 필요합니다.
다른 인원들이 폴더링하는 것 처럼 ~~.tsx가 사용하는 scss 파일은 묶는 것이 좋아 보입니다.
또한 폴더링이 왜 section 과 hook으로 나눈지 잘 모르겠습니다. 다른 인원들과 코드 통일성이 너무 떨어져 보입니다.
차라리 컴포넌트면 컴포넌트폴더로 분리하면 좋을 것 같습니다.
그리고 SearchPage는 조금 뭐랄까 너무 포괄적이라고 해야하나 네이밍에 신경 써주시면 감사하겠습니다.

2022-10-12 16:33 UTC, daepan commented on src/pages/SearchPage/index.tsx
> +          <button type="submit" disabled={isSubmitting} className={isValid ? style.active : style.inactive}>인증번호 보내기</button>
className 함수 활용해서 처리해주세요

2022-10-12 16:33 UTC, daepan commented on src/pages/SearchPage/index.module.scss
> +
absoulute 사용은 자제 바랍니다 아마 이거의 경우에는 제가 예시를 올려드리면
![absolute를 지양해야하는 이유](https://user-images.githubusercontent.com/50792467/195396190-0eaaef6e-76b5-4840-9039-baf428f28ddc.gif)
이렇습니다. 확인해주시고 수정해주세요

2022-10-12 16:33 UTC, daepan commented on src/pages/SearchPage/section/ChangePassword.tsx
> +const pattern = /^.*(?=^.{2,16}$)(?=.*\d)(?=.*[a-zA-Z])(?=.*[!@#$%^&+=]).*$/; // 비밀번호 형식 패턴
상수 값 네이밍컨벤션을 지켜주세요

2022-10-12 16:33 UTC, daepan commented on src/pages/SearchPage/section/InputNumber.module.scss
> +
@use "src/utils/styles/mediaQuery" as media;를
사용하기로 통일하기로 한 걸로 아는데 확인하고 수정바랍니다

2022-10-12 16:33 UTC, daepan commented on src/pages/SearchPage/section/InputNumber.tsx
> +        handleSubmit((data: FormData) => console.log('data: ', data))
eslint 에러로 나옵니다 yarn lint 확인해주세요

2022-10-12 16:33 UTC, daepan commented on src/pages/SearchPage/section/InputNumber.tsx
> +            required: true,
계속 같은 코드가 반복되고 변하는 건 first second랑 1,2,3 뿐 인 것 같은데, 이런 상수들 배열화한 다음에
반복문으로 처리하면 코드가 깔끔할 것 같습니다.
고민 한번 해보시면 좋을 것 같습니다 :)

2022-10-16 14:40 UTC, chaeseungyun commented on src/pages/SearchPage/index.module.scss
> +
모바일 화면에서 키보드가 생겼을 때 인증번호 보내기 버튼이 보이도록 설계하고 싶었습니다..
일단 absolute는 사용 자제하겠습니다

2022-10-16 14:40 UTC, chaeseungyun commented on src/pages/SearchPage/section/InputNumber.module.scss
> +
수정하겠습니다!

2022-10-16 14:40 UTC, chaeseungyun commented on src/pages/SearchPage/section/ChangePassword.tsx
> +const pattern = /^.*(?=^.{2,16}$)(?=.*\d)(?=.*[a-zA-Z])(?=.*[!@#$%^&+=]).*$/; // 비밀번호 형식 패턴
수정하겠습니다..

2022-10-16 14:40 UTC, chaeseungyun commented on src/pages/SearchPage/section/InputNumber.tsx
> +        handleSubmit((data: FormData) => console.log('data: ', data))
에러는 아니고 warning으로 떠서 push했는데 다시 수정하겠습니다

2022-10-16 14:42 UTC, chaeseungyun commented on src/pages/SearchPage/section/InputNumber.tsx
> +            required: true,
고민 많이 해봤지만 잘 안돼서 그냥 남겨두었던 부분입니다
다시 생각해보겠습니다

2022-10-22 11:49 UTC, ChoiWonBeen requested changes
아래 변경사항에 추가로, PreviousButton이 생겼으니 `prev-icon.svg`파일은 삭제해야 할 것 같습니다.

2022-10-22 11:49 UTC, ChoiWonBeen commented on src/pages/Auth/SearchIDPassword/component/Modal.tsx
> +export default function Modal({ modal }: IModal): JSX.Element {
컴포넌트명이 공용스러운 것에 비해 보여주는 내용은 재로그인에 불과합니다.
React는 `createPortal`메소드를 활용해 더 재사용하기 용이한 구조의 모달을 만들 수 있는데, 적용해보면 좋을 것 같네요.

2022-10-22 11:49 UTC, ChoiWonBeen commented on src/pages/Auth/SearchIDPassword/index.tsx
> +export default function SearchPage({ search }: ISearch): JSX.Element {
저희가 검색 페이지가 있어서 Search라는 이름이 겹치는데, Find라는 이름이 적절해보입니다.
아이디 비밀번호 "찾기"지 검색하기는 아니니깐요

2022-10-22 11:49 UTC, ChoiWonBeen commented on src/pages/Auth/SearchIDPassword/page/DistinctionNumber.tsx
> +export default function DistinctionNumber():JSX.Element {
이 컴포넌트 명도 어색한 느낌이 많이 드는데, 더 좋은 표현이 있을 것 같아요. 
예제를 찾아보면 건질만한 게 있을 것 같네요 ㅋㅋ

2022-10-22 11:49 UTC, ChoiWonBeen commented on src/pages/Auth/SearchIDPassword/page/InputNumber.module.scss
> +}
`::-webkit-inner-spin-button`은 위아래 화살표버튼 같은데 `outer` 는 어떤건가요??

2022-10-22 11:49 UTC, ChoiWonBeen commented on src/pages/Auth/SearchIDPassword/page/InputNumber.tsx
> +}
타입 네이밍에 헝가리안 표현식을 지양하기로 했습니다.
그리고 어떤 타입을 말하는지 알 수 없으니 이름을 바꿀 필요가 있어보이네요.

2022-10-23 13:35 UTC, chaeseungyun commented on src/pages/Auth/SearchIDPassword/component/Modal.tsx
> +export default function Modal({ modal }: IModal): JSX.Element {
넵 적용해보겠습니다

2022-10-23 13:35 UTC, chaeseungyun commented on src/pages/Auth/SearchIDPassword/index.tsx
> +export default function SearchPage({ search }: ISearch): JSX.Element {
수정하겠습니다

2022-10-23 13:36 UTC, chaeseungyun commented on src/pages/Auth/SearchIDPassword/page/InputNumber.tsx
> +}
수정하겠습니다

2022-10-23 13:42 UTC, chaeseungyun commented on src/pages/Auth/SearchIDPassword/page/InputNumber.module.scss
> +}
필요에 의해 검색 후 가져다 쓴거라 조사해보지 않았습니다..
알아보겠습니다

2022-11-02 16:01 UTC, ChoiWonBeen requested changes
마무리로 아래 요소들만 수정해주세요!
1. 컴포넌트 이름은 Find~~ 로 바뀌었지만, 폴더명이`SearchIdPassword` 입니다.
2. 디벨롭에 머지된 기능이랑 연결되도록, 로그인 화면에 해당 추가한 기능 라우팅 추가해주세요.
3. 화면의 height이 넓을 때는, 가운데로 오도록 하는게 좋아보입니다. 가장 바깥쪽 태그가 `grid`인것 보다는, `flex`로 center를 맞춰주는게 알맞을 것 같네요.
4. 비밀번호 재설정 페이지 입력칸들 사이의 여백이 안맞습니다.
5. 에러메시지 쪽 아이콘과 글자 사이 간격이 너무 좁고, 높낮이가 안맞습니다. 아이콘과 글자를 묶는 태그에 flex, align center를 맞춰주면 해결될 것 같네요.

거의다왔어요! ㅋㅋㅋㅋ 마무리 고생해주세요

2022-11-06 04:29 UTC, ChoiWonBeen approved these changes
고생했어요~ 추가적인 수정은 API를 붙이면서 해도 될 것 같네여.

2022-11-07 05:23 UTC, SimYunSup approved these changes

2022-11-09 12:37 UTC, chaeseungyun commented
@daepan 
scss 스타일 수정 완료했습니다

2022-11-09 12:38 UTC, daepan approved these changes
고생하셨습니다 ^^

2022-11-10 03:48 UTC, merged