Feature/#3
BCSDLab/TEMP_PROJECT_FE pull request #20
Opened 2022-09-25 15:00 UTC by hanagertrudekim

## [#3] request

**- 회원가입 페이지 구현**

=> 이용약관, 회원가입, 완료 페이지로 구성되어있습니다.
react-hook-form 라이브러리를 사용하였고, 필요한 hook은 따로 분리해두었습니다.

---

- 이용약관 페이지

<img width="434" alt="image" src="https://user-images.githubusercontent.com/101982606/192149246-01f811a1-3646-4b4c-8985-9119bfc66ad4.png">

- 회원가입 form

<img width="417" alt="image" src="https://user-images.githubusercontent.com/101982606/192149276-ea2cae15-f167-4216-b4a8-f6d22903d11a.png">

-에러시 버튼 비활성화 & 에러메시지
<img width="397" alt="image" src="https://user-images.githubusercontent.com/101982606/192149314-7e9bb54c-6046-404e-83e8-2ffe5cfe8678.png">

- 회원가입 완료 페이지

<img width="486" alt="image" src="https://user-images.githubusercontent.com/101982606/192149667-fae6fbf8-1bd1-4fc6-8e18-cdb41dc4eef2.png">

## Please check if the PR fulfills these requirements

- [✅] It's submitted to `develop` branch, __not__ the `main` branch
- [✅] The commit message follows our guidelines
- [✅ ] There are no warning message when you run `yarn lint`
- [✅] Docs updated for breaking changes

### Screenshot

2022-09-25 23:44 UTC, ChoiWonBeen requested changes
고생하셨어요~~ 아래 추가하지 못한 사항들 말씀드리자면,
1. 🎉 는 svg가 아니라 이모지입니다. 이모지는 글자라서 따로 추가할 필요가 없구요. svg는 보통 다양한 색상을 담지 않습니다 ㅋㅋ
2. yarn.lock에 불필요한 변화가 많을 것 같은데, 이번 변경에는 제외시켜도 괜찮을 것 같습니다. 같은 패키지를 사용하는 다른 PR이 먼저 머지될테니깐 해당 내용을 사용하면 될 것 같아요.
3. 모바일에서는 이메일 정규식 체크가 안되고, 에러 메시지 표시의 디자인이 깨집니다. 디자인처럼 상단에만 에러메시지를 표시할 수 있도록 바꿔주세요.

2022-09-25 23:44 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/Complete.module.scss
> +}
`src/index.scss`에 정의되어있는 속성이라 불필요합니다.

2022-09-25 23:44 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/static/signUp.ts
> +  ['password-check']: string;
passwordCheck처럼 쓰지 않은 이유가 있나요? 유독 눈에 띄네요 ㅋㅋ

2022-09-25 23:44 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/Complete.module.scss
> +    }
디자인보다 여백이 넓습니다. 요소 사이 간격은 디자인과 맞춰주세요.

2022-09-25 23:44 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/SignUp.module.scss
> +@use "./TermsOfService.module.scss" as terms-of-service;
mixin의 정의가 `TermsOfService.scss`파일에 정의되어있을 필요가 없을 것 같아요.
믹스인 파일을 만들어 모아놓고 활용하는게 좋을거같아요.

2022-09-25 23:44 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/SignUp.module.scss
> +@forward "src/styles/fonts.scss";
`@forward`를 왜 추가하셨나요?

2022-09-25 23:44 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +              </div>
`error-text`가 스크린 리더 접근성을 가지려면 어떻게 해야할까요?

2022-09-25 23:44 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +                },
이건 무슨 로직인가요?
다른 변수들과 다르게 checkPw라고 줄여 쓴 이유도 궁금합니다.

2022-09-25 23:44 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/TermsOfService.tsx
> +            onClick={() => navigate('/signup', { state: { termsCheck: true } })}
navigate에 state를 두어 직접라우팅을 막은 건 좋네요 👍 
그런데 뒤로가기 / 앞으로가기는 해당 state를 유지합니다.
replace를 추가해서 회원가입 완료 후 뒤로가기를 막아 다시 회원가입을 오는 등의 행위를 막을 수 있을 것 같아요.

2022-09-25 23:44 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/hooks/useRouteCheck.ts
> +    const state = location.state as any;
any보다 더 적절한 타입 정의가 있을 것 같은데, [매핑된 타입](https://www.typescriptlang.org/ko/docs/handbook/2/mapped-types.html)을 찾아보세요!

2022-09-25 23:44 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/static/privacy.ts
> +const privacy: Privacy[] = [
상수니 다른 파일에 있는 상수처럼 SNAKE_CASE로 작성하는게 좋을 것 같아요.
그리고 디자인에 새로 올라온 이용약관으로 수정해주세요~

2022-09-26 00:26 UTC, D0Dam requested changes
수고하셨습니다. 원빈이가 리뷰를 잘 해줬는데 이외에 필요하다 싶은 수정사항 남겨놉니다.

2022-09-26 00:26 UTC, D0Dam commented on src/pages/Auth/SignUpPage/Complete.module.scss
> +  }
다른 scss 파일에도 mediaQuery가 이렇게 중복되어 작성되어있는데 이는 `src/index.scss`의 `body`에 추가하면 중복을 피할 수 있습니다.

2022-09-26 00:26 UTC, D0Dam commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +  const Reg = /^(?=.*[0-9])(?=.*[a-zA-z])(?=.*[!@#$%^&*+=]).{2,16}$/;
정규식이 `(`와`)`를 특수문자로 읽지 못합니다. 두 문자도 특수문자로 읽을 수 있게 수정해주세요.

2022-09-26 00:57 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/Complete.module.scss
> +}
수정하겠습니다!

2022-09-26 01:05 UTC, hanagertrudeKim commented on src/pages/Auth/SignUpPage/static/signUp.ts
> +  ['password-check']: string;
지금보니 passwordCheck가 훨씬 깔끔할거같아 수정했습니다. 
9bcbda0c539b1a4a7be61e689b4b09cc16779a11

2022-09-26 01:18 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/Complete.module.scss
> +    }
수정했습니다

2022-09-26 01:19 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/SignUp.module.scss
> +@use "./TermsOfService.module.scss" as terms-of-service;
따로 모아놓는게 훨씬 깔끔할거같네요..! 수정하겠습니다.

2022-09-26 01:51 UTC, daepan commented
가장 최근 PR에 저의 애로사항을 적어봅니다.
1. github에서 recently activity에 Feature/#~~ 이라고 제목으로 쓰면 알아보기가 힘듭니다. 아마 기본적으로 저렇게 나오는 것 같은데 조금 귀찮겠지만 바꿔주면 어떤 기능인지 직관적으로 써주면 좋겠습니다.(이슈 제목을 긁어오는 깃헙 템플릿을 수정하면 베스트)
2. 로그인이랑 회원가입하면서 UI만 보고 느꼈는데 제가 맥북 13인치를 써서 그런지 상하단 스크롤바가 생기더군요. 
저도 해당 UI는 기획이니깐 하고 넘길까 했지만, 17인치 width와 height을 기준으로 미디어쿼리를 사용해 margin값을 조절하거나 calc()를 이용했었습니다.
그때는 잘 모르던 때라 코드도 더럽고 난잡했지만 사용자와 의사소통하는 프론트엔드 입장에서 해당 UI 조절은 의미를 갖고 있다고 생각합니다.
이거는 한번 저도 해결해보고 싶은 문제군요ㅎ
3. 커밋은 누구는 영어로 누구는 한글로 하는데 통일하는 건 어떨까요?

위에 적힌 것은 단순한 애로사항이며, 여러분들이 고민해보면 좋을 것 같아 적어봅니다.

2022-09-26 02:44 UTC, SimYunSup requested changes
간단하게 리뷰해보았습니다. 더 리뷰할 부분은 원빈이가 리뷰한 부분이 고쳐지면 해보겠습니다.

2022-09-26 02:44 UTC, SimYunSup commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +                {errors.id?.message}
error 메세지 맨 위에 하나만 필요해보이는데 input마다 모두 할당한 이유가 무엇인가요?

2022-09-26 02:44 UTC, SimYunSup commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +                  // eslint-disable-next-line prefer-regex-literals, no-useless-escape
ESLint를 비활성화 한 이유를 듣고싶네요.

2022-09-26 02:44 UTC, SimYunSup commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +  const [isPwchBlind, setIsPwchBlind] = useState(false);
두 값은 hooks로 분리해주세요.

2022-09-26 02:44 UTC, SimYunSup commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +            onClick={() => (isDirty && isValid ? navigate('/signup/complete', { state: { signUpCheck: true } }) : navigate(''))}
복잡한 로직일 경우 한줄코딩하려 하지 마시고 custom hooks로 분리해주세요.

2022-09-26 02:44 UTC, SimYunSup commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +            </select>
해당 부분은 GUI 부분하고 다릅니다.

2022-09-26 02:44 UTC, SimYunSup commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +        // eslint-disable-next-line react/jsx-props-no-spreading
해당 eslint 속성은 eslintrc에서 비활성화해주세요.

2022-09-26 02:44 UTC, SimYunSup commented on src/pages/Auth/SignUpPage/TermsOfService.tsx
> +  const allCheck = useMemo(() => !checkedList.some((checked) => !checked), [checkedList]);
useMemo를 사용한 이유가 궁금합니다. 성능 비교는 해보셨는지요.

2022-09-26 02:44 UTC, SimYunSup commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +                },
뭐 설명을 하자면 react-hook-form만의 로직입니다. validate에는 `string | true`를 반환하는 함수를 value로 갖는 객체를 가질 수 있습니다. validate할 경우 이 객체의 value들을 순회하면서 validate하는거죠. 그 다음 string이 반환되면 error인 것을 알 수 있습니다.

2022-09-26 03:51 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/SignUp.module.scss
> +@forward "src/styles/fonts.scss";
필요하지않을것같아 삭제했습니다. e142bc830a4200283822bef7c8982665af045b95

2022-09-26 08:34 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +              </div>
[참고문서](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-errormessage) 에 따르면 두가지 속성이 필요합니다. aria-invalid 가 true 이고, aria-errormessage 로 에러 메시지를 설정해주면 스크린 리더 접근성을 가질수있습니다. 모든 에러 메시지가 접근성을 가지도록 수정하였습니다. f0c2d7c9608e0a499ed79cc506f7f751d2d3c13c

2022-09-26 08:39 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +                  // eslint-disable-next-line prefer-regex-literals, no-useless-escape
처음에 정규식표현을 바로 넣기위해 ESlint를 비활성화하였지만, 위에 따로 변수로 빼두었으니 굳이 그부분에 ESlint 비활성화가 필요하지 않을것같습니다! 수정했습니다 f0c2d7c9608e0a499ed79cc506f7f751d2d3c13c

2022-09-26 09:07 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +              </div>
`role=alert` 를 사용하는 방법을 생각했는데 처음 보는 속성이네요? 배워갑니다 ㅋㅋ 위 방법도 알아보시면 좋을거같아요.

2022-09-26 09:12 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +              </div>
그런데 `aria-invalid` 속성이 저렇게 쓰는게 맞나요? valid 여부를 판단하고, invalid할 경우 에러메시지를 input을 읽으며 제공할 때 쓰는 것 같은데 지금같은 상태라면 input을 읽는 순간 invalid해서 에러메시지를 읽을 것 같네요. 값이 제대로 들어가도말이죠.

2022-09-26 11:28 UTC, hanagertrudeKim commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +              </div>
아 그렇다면 invalid 조건에 에러 조건이 똑같이 들어가야할거같네요ㅎㅎ 
수정했습니다! 0f9d4396db2c38a924909f89fd4024146cc60cf9

2022-09-26 11:56 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +              </div>
한가지 더, `aria-errormessage`는 메시지를 담는 것이 아닌, 열리는 [엘리먼트의 ID값을 가져야 하네요](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-errormessage).
[이 링크](https://github.com/lezhin/accessibility/blob/master/aria/README.md#aria-errormessage)를 참조해서 적절하게 바꿔 사용해야 할 것 같습니다. 위에서 언급한 `role=alert`은 [관련 속성의 값을 true로 만들어주어](https://github.com/lezhin/accessibility/blob/master/aria/README.md#alert) 사용하기 쉬운 속성이라고 하네요.

2022-09-26 12:19 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/TermsOfService.tsx
> +            onClick={() => navigate('/signup', { state: { termsCheck: true } })}
일단 말씀하신대로 replace를 추가해두었습니다! a3055c0d499861daaaca39bb313010fc8b1b566a 
하지만 한가지 의문점이 뒤로가기를 눌렀을때 replace 되는 위치가  브라우저의 아예 처음 위치로 돌아가게되는데 (예를들면 크롬의 기본창)  이 부분이 UX적으로 문제가 없는지 여쭤보고싶습니다

2022-09-26 12:23 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/TermsOfService.tsx
> +            onClick={() => navigate('/signup', { state: { termsCheck: true } })}
시작 위치를 로그인창에서 하지 않았나요?
`/` 에서 `/termsofservice`로 이동한 뒤, 회원가입 과정을 마치고 뒤로가기를 해보시면 적절하다고 생각이 들거예요.

2022-09-26 12:43 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/TermsOfService.tsx
> +            onClick={() => navigate('/signup', { state: { termsCheck: true } })}
아하.. 시작위치를 '/' 에서 시작하니 그위치로 돌아가네요ㅎㅎ 답변 감사합니다

2022-09-26 12:54 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/hooks/useRouteCheck.ts
> +    const state = location.state as any;
boolean을 반환하도록 변경했습니다! 515fc1206bf1644bff9e85689a8804460e984603

2022-09-26 12:55 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/TermsOfService.tsx
> +            onClick={() => navigate('/signup', { state: { termsCheck: true } })}
그런데 `/signup/complete` 에서 `/`로 돌아갈때도 replace가 필요합니다. 
반대로 `/signup` 으로 가는 경우에는 replace가 필요하지 않죠.
왜 이렇게 변경해야하는지 경험하면서 수정해주세요 ㅋㅋ

2022-09-26 13:04 UTC, hanagertrudeKim commented on src/pages/Auth/SignUpPage/Complete.module.scss
> +  }
말씀하신 `src/index.scss` 에 추가하면 모든 페이지에 적용되는것인가요?
제가 알기론 미디어쿼리의 min-width를 다르게 설정하신분도 계신것같아서 공통적으로 적용해도 되는건지 여쭤보고싶습니다.

2022-09-26 13:12 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +  const Reg = /^(?=.*[0-9])(?=.*[a-zA-z])(?=.*[!@#$%^&*+=]).{2,16}$/;
혹시 정규식 기능적으로 문제가 발생하는건가요, 아니면 코드상에서 에러가 나는건가요?
`new RegExp() ` 생성자를 이용하지않고 리터럴 형식으로 써도 에러가 나지않아 후자의 방법을 택했는데, 문제가 있다면 변경이 필요할것같아서요.

2022-09-26 13:15 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +                {errors.id?.message}
웹페이지 UI상에는 에러메시지가 모든 input 마다 다르게 뜨기때문에 모두 할당해두었습니다! 
하지만 모바일 UI를 확인하니 error 메시지가 맨 위에 하나만 뜨기때문에 이부분은 css수정이 필요할것같습니다...ㅠㅠ

2022-09-26 13:23 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +  const [isPwchBlind, setIsPwchBlind] = useState(false);
`useBlindCheck` hooks로 따로 분리해두었습니다! def3000aea424ba716840a7812f30494c0ea81d3

2022-09-26 13:24 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/static/privacy.ts
> +const privacy: Privacy[] = [
수정하였습니다! def3000aea424ba716840a7812f30494c0ea81d3
그리고 디자인데 새로 올라온 이용약관이 제가 알기론 모바일 버전에 들어있는 이용약관같은데, 확인해보니 이용약관의 전체가 들어있지않습니다. 아직까지 요청한 이용약관 변경이 되지 않았기에 추후 변경이 되면 수정하도록 하겠습니다!

2022-09-26 13:26 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +  const Reg = /^(?=.*[0-9])(?=.*[a-zA-z])(?=.*[!@#$%^&*+=]).{2,16}$/;
생성자 방식과는 관계가 없습니다. 정규식 특수문자 리스트에 괄호가 빠져있는데, 소괄호뿐아니라`[],{},",'`등등의 문자도 포함되지 않는데, 보편적으로는 **숫자키와 관련된 특수문자만 허용**하니 `-, _, +, =, (, )`까지 추가되면 이상적이겠네요.

2022-09-26 13:30 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +            onClick={() => (isDirty && isValid ? navigate('/signup/complete', { state: { signUpCheck: true } }) : navigate(''))}
custom hooks로 분리하여 더 깔끔하게 코드 수정했습니다 cdd79510bc331174e51e9df06f7e342390a30e84

2022-09-26 13:57 UTC, D0Dam commented on src/pages/Auth/SignUpPage/Complete.module.scss
> +  }
1. 네 `src/index.scss`에 추가하면 공통 적용됩니다.
2. 아마 추후에 가장 먼저 머지되는 기능에 맞추어 body에 moblie의 min-width이 통일될 것입니다. 그래도 지금 확인해보니 모두 320px로 통일한 것으로 보이니 320px 그대로 사용하셔도 될 것 같습니다.

2022-09-26 14:07 UTC, D0Dam commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +  const Reg = /^(?=.*[0-9])(?=.*[a-zA-z])(?=.*[!@#$%^&*+=]).{2,16}$/;
제가 정규식을 잘 작성한지는 모르겠는데
```
const Reg = /^(?=.*[0-9])(?=.*[a-zA-z])(?=.*[!@#$%^&*+=]).{2,16}$/
```
위 정규식을
```
const Reg = /^(?=.*[0-9])(?=.*[a-zA-z])(?=.*[!@#$%^&*+=**()_-**]).{2,16}$/;
```
이런식으로 바꿔주시면 해당 특수기호를 포함시켜줄 수 있습니다.

2022-09-26 14:38 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +  const Reg = /^(?=.*[0-9])(?=.*[a-zA-z])(?=.*[!@#$%^&*+=]).{2,16}$/;
아 특수기호 괄호를 말씀하시는거군요....! ㅎㅎ 수정하겠습니다 감사합니다!

2022-09-27 00:46 UTC, ChoiWonBeen requested changes
같은 관심사를 가진 두 상태(보이는지, 안보이는지 상태를 가지고, toggle기능만 가진 상태)를 더욱 보기좋게 관리할 방법이 있을겁니다.
return하는 변수명을 반드시 hook내에서 쓰는 변수명 그대로 객체화시켜서 보낼 필요도 없죠. 
useState가 반환하는 방식인 배열 반환이나, 메소드를 품거나 메소드 그 자체인 단일 변수 반환도 생각해볼 수 있습니다.

2022-09-27 00:46 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/static/signUp.ts
> +interface IDomain {
헝가리안 표기법을 지양하기로 결정했으니, 타입 정의에서 접두사 `I`를 제외해주세요.

2022-09-27 00:46 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/static/signUp.ts
> +const domain: IDomain[] = [
다른 상수처럼 네이밍 컨벤션을 맞춰주세요.

2022-09-27 00:46 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/hooks/useRouteCheck.ts
> +    if (!state || !(checkValue in state)) {
state.[hasOwnProperty](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty)(checkValue) 처럼 쓸 수도 있네요.
in 과의 차이점은, hasOwnProperty가 상속된 속성은 [제외한다는 점](https://masteringjs.io/tutorials/fundamentals/hasownproperty) 덕분에 명확할 것 같네요.
이번 state에 대해선 상속될만한 프로퍼티를 담지 않았지만? 알아두면 좋을 것 같아요.

2022-09-27 00:46 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/hooks/useBlindCheck.ts
> +  };
두 변수가 공통 로직을 갖고있지 않나요?
이러한 방식은 hook으로 분리하는 이점이 없습니다.
KOIN_RECODE의 `utils/useBoolean`을 보면 이해가 되지 않을까 싶네요.

2022-09-27 01:31 UTC, SimYunSup commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +              // eslint-disable-next-line jsx-a11y/aria-props
스펠링이 틀려서 생긴 오류입니다. 스펠링 체크하시고 disable 풀어주세요.

2022-09-27 01:35 UTC, SimYunSup commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +                {errors.id?.message}
제가 안드로이드 부분을 보고 착각했네요. 죄송합니다. 따로 모바일 버전으로 수정하지 않아도 됩니다.

2022-10-02 15:10 UTC, hanagertrudekim commented
> 고생하셨어요~~ 아래 추가하지 못한 사항들 말씀드리자면,
> 
> 1. 🎉 는 svg가 아니라 이모지입니다. 이모지는 글자라서 따로 추가할 필요가 없구요. svg는 보통 다양한 색상을 담지 않습니다 ㅋㅋ
> 2. yarn.lock에 불필요한 변화가 많을 것 같은데, 이번 변경에는 제외시켜도 괜찮을 것 같습니다. 같은 패키지를 사용하는 다른 PR이 먼저 머지될테니깐 해당 내용을 사용하면 될 것 같아요.
> 3. 모바일에서는 이메일 정규식 체크가 안되고, 에러 메시지 표시의 디자인이 깨집니다. 디자인처럼 상단에만 에러메시지를 표시할 수 있도록 바꿔주세요.
> 4. 약관동의 부분에서 체크박스의 너비가 detail이 열리기 전 / 후 조금씩 달라집니다. width를 계산하는 방식을 바꿀 필요가 있어보이네요.
> 5. 전체동의 글자도 가능하면 label로 바꿔 눌리면 select되도록 바꿔주세요.


---
1. 이모지로 수정했습니다. 다만 제 경우엔 윈도우여서 이모지의 모양이 시안의 ui와는 달라지는데 이 부분에 대해서는 환경에 따라 다르게 가도되는건지 체크해보고싶습니다. dabbc6850ff7cbbd69107661900f10cfbda5bed1
<img width="182" alt="image" src="https://user-images.githubusercontent.com/101982606/193461138-7f540d4f-06f5-46b9-a5ac-3570b7abe191.png">

2. 확인했습니다..! 

3. 모바일에 경우 상단에만 한가지의 에러메시지가 뜨도록 되어있는데 이를 구현하기 위해서 아예 한개의 에러메시지만 렌더링되도록하는 hook을 따로 만들었습니다 5838b598b3ccbadd4458010460a0b474df38af64

4. / 5.  모두 수정했습니다 658f7a5288a68e38a36dd28e750202300d5c3413

2022-10-02 15:15 UTC, ChoiWonBeen commented
굿굿 👍 👍 1번 관련해서는 UI팀과 얘기해보면 좋을 것 같습니다. 해당 이미지를 고수해야한다고 하면, 이미지 파일을 추가하는게 좋아보이네요. (가능하면 이전에 언급했던 webp를 사용해서?)
아직 남아있는 리뷰들까지도 고생해주세요~

2022-10-02 15:19 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/TermsOfService.tsx
> +            onClick={() => navigate('/signup', { state: { termsCheck: true } })}
네 알겠습니다..! 추후 더 고민해보도록 하겠습니다 ㅎㅎ

2022-10-02 15:23 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/Complete.module.scss
> +  }
넵 수정했습니다! 35954e72661fd53505d640a3808ee60100a87133

2022-10-02 15:27 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +        // eslint-disable-next-line react/jsx-props-no-spreading
eslintrc 파일에서 비활성화했습니다! b57192a24381f8a552bef08153b9a795bdcad139

2022-10-02 19:42 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/hooks/useBlindCheck.ts
> +  };
재사용성을 최대한 고려해서 hook 다시 수정했습니다..! 6d346800303141853a21164a90b436704cac6507

2022-10-02 19:43 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/hooks/useRouteCheck.ts
> +    if (!state || !(checkValue in state)) {
네 알겠습니다 차이점과 함께 잘 알아두겠습니다..!

2022-10-02 19:44 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/static/signUp.ts
> +const domain: IDomain[] = [
네이밍 컨벤션에 맞게 수정했습니다 2ad417ca0e327707f829e41a114329b43a0b7193

2022-10-02 19:45 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/static/signUp.ts
> +interface IDomain {
수정했습니다 ! 2ad417ca0e327707f829e41a114329b43a0b7193

2022-10-03 11:35 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +              // eslint-disable-next-line jsx-a11y/aria-props
네 수정했습니다 2ad417ca0e327707f829e41a114329b43a0b7193

2022-10-03 12:00 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +              </div>
수정하였습니다! 이 [링크](https://github.com/lezhin/accessibility/blob/master/aria/README.md#aria-errormessage) 를 참고하였는데, `aria-errormessage` 가 에러 메시지를 읽어내도록 id 값을 추가하였고 `role=alert`의 속성도 추가했습니다.  다만 제시해주신 두가지 방법을 모두 사용해보았는데,  혹시나 중복의 위험이 있을까요...?

2022-10-03 12:28 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +              </div>
ㅋㅋㅋㅋㅋ 두 속성 모두 `aria-live`를 바꿔준다고 하는데, 해당 속성이 스크린 리더의 실시간 내용 갱신을 담당하네요.
이미 하나하나 변경해둔 채라서 이런말하기가 죄송하지만 `role="alert"` 면 충분할 것 같아요 😭 ㅋㅋㅋㅋ

2022-10-04 03:48 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/TermsOfService.tsx
> +  const allCheck = useMemo(() => !checkedList.some((checked) => !checked), [checkedList]);
`allCheck `로직의 의존성이 `checkedList`에 있고, `checkedList`는 배열로 각각의 `boolean` 값이 담겨있기 때문에 바뀔때마다 렌더링된다면 상태 관리가 복잡해지고 중복될수도있겠다고 처음에 생각해 `useMemo`를 썼던것같습니다. 
하지만 useMemo를 쓸때 10000배 정도?의 복잡성이 아니면 쓰지않을때보다 쓸때 더 많은 비용이 발생한다는 사실을 알고 실제 제 로직이 그 정도의 복잡성을 가지고있는지 확인해본 결과 그정도의 복잡성은 가지지않고있는것을 확인했습니다. 실제 렌더링 속도도 비교해보았는데, 오히려 `useMemo`를 쓰지 않았을때 더 빠르다는것을 알게되었습니다... 
다음부터는 `useMemo`나 `useCallback`을 쓸때 주의하여 적절한 곳에 사용해야할것같습니다 😳

2022-10-04 03:56 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +              </div>
아하 그렇군요ㅎㅎ 수정하겠습니다! ㅎㅎ

2022-10-04 06:25 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/SignUp.tsx
> +            </select>
수정하였습니다! 해당 부분의 구현을 위해 component 와 hook을 따로 만들어 빼두었습니다. 9bfe34591b0cdacb31132874715a5977371033ed

2022-10-04 13:00 UTC, SimYunSup requested changes
1. 전체적인 파일 구조를 통일해주세요(ex. 옳지 않은 components 폴더 위치, static 폴더 위치, 중첩된 Page 폴더 구조).
2. 리눅스 컴퓨터나 맥북을 빌려서 표기법에 맞지 않는 폴더/파일을 바꿔주세요.
3. 이전에 댓글에 마지막에 말했듯이 모바일 UI는 PC UI의 축소판이면 됩니다. 따로 가려가면서 바꾸지 말아주세요. 이 부분은 잘못 말씀드린 점 죄송합니다.

2022-10-04 13:00 UTC, SimYunSup commented on src/pages/Auth/SignUpPage/hooks/useSelect.ts
> +  };
1. 해당 네이밍은 일반적이지 않습니다. 일반적으로 바꿔주세요.
2. any 지양해주세요.
3. 직접 입력 누르고 글자 입력하고 다른 걸로 바꾸면 작동 안합니다.

2022-10-04 13:00 UTC, SimYunSup commented on src/pages/Auth/SignUpPage/hooks/useFirstErrorMessage.ts
> +}
굳이 안드로이드 UI에 맞출 필요 없습니다. 모바일 UI는 PC UI를 줄인 UI로 해주세요.

2022-10-04 13:00 UTC, SimYunSup commented on package.json
> +    "react-hook-form": "^7.36.0",
7.36.1 버전으로 업데이트 해주세요.

2022-10-04 13:00 UTC, SimYunSup commented on src/pages/Auth/SignUpPage/signUpPage/components/PasswordCheckInput.tsx
> +        : <BlindIcon className={styles['form__blind-icon']} onClick={changeBlind} aria-hidden /> }
svg에 바로 onClick 두지 마세요. Button으로 감싸주세요.

2022-10-04 13:52 UTC, ChoiWonBeen requested changes
몇가지 고려할 사항들 추가합니다~
1. 현재 로그인에서 회원가입을 누르면 `/signup` -> `termsOfService`로 이동합니다. 로그인창을 병합했으니 링크를 수정해서 올리는게 좋아보이네요.
2. login과 다른 페이지를 보면 로고 위치나, 하단바 위치가 맞지 않습니다. 어느 한 쪽으로 통일시킬 필요가 있어보이네요.

2022-10-04 13:52 UTC, ChoiWonBeen commented on src/App.tsx
>        <Route path="/login" element={<LoginPage />} />
통일성을 위해 `<Login />` 으로 바꿔주면 좋을 것 같아요.

2022-10-04 13:52 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/hooks/useFirstErrorMessage.ts
> +  return errorList[0]?.message;
이 훅은 이름을 알아보기도, 반환되는 값도 예상하기 좋아보여요. 👍 
한가지 아쉬운 점은, 함수가 undefined를 반환할 수 있다는 것을 이해하기 어려울 것 같아요.
가독성을 위해 아래처럼 써보는 것은 어떨까요??
```suggestion
  return errorList.length ? errorList[0].message : undefined;
```

2022-10-04 13:52 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/hooks/useRouteCheck.ts
> +      navigate(route);
지금 로그인창에서 회원가입을 가면
`/login` -> `/signup` -> `termsOfService` 순서로 이동합니다.
이렇게 들어간 termsOfService창에서 뒤로가기를 누르면 다시 `/signup`을 갔다 다시 `/termsOfService`로 돌아오는 버그가 있어요

2022-10-04 13:52 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/hooks/useSelect.ts
> +  };
이 훅의 이름과, 각 리턴 값들이 무슨 역할을 하는지 알기 어렵고, 실제 Domain select가 동작하지 않습니다.

2022-10-04 13:52 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/signUpPage/components/PasswordInput.tsx
> +const Reg = /^(?=.*[0-9])(?=.*[a-zA-z])(?=.*[!@#$%^&*+=()]).{2,16}$/;
위에서부터 Reg라는 변수가 이름이 겹치고 정말 많은데, static 폴더에 모아두고 각각을 이름짓는건 어떨까요?
`PASSWORD_REGEXP` 처럼 말이죠

2022-10-04 13:52 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/termsOfServicePage/TermsOfService.tsx
> +            onClick={() => navigate('/signup', { state: { termsCheck: true }, replace: true })}
여기 replace는 지워야 할 것 같아요. 왜 그럴까요? ㅋㅋㅋ

2022-10-04 13:52 UTC, ChoiWonBeen commented on src/App.tsx
> +import TermsOfService from 'pages/Auth/SignUpPage/termsOfServicePage/TermsOfService';
폴더이름이나 파일이름(`index.tsx`)같은 파일들을 통일시켜야 할 것 같아요. 경로가 많이 길어지네요 😭

2022-10-04 13:52 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/signUpPage/SignUp.module.scss
> +  &__id-check-button {
디자인 상 PC랑 모바일이 다른데 색상이 있는 디자인이 더 이쁜 것 같아요!
그리고 해당 속성 추가해주시면 버튼 글자가 약간 위로 올라가는 걸 방지할 수 있습니다.
```suggestion
  &__id-check-button {
    line-height: 12px;
```

2022-10-05 00:37 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/hooks/useFirstErrorMessage.ts
> +}
이 부분에 대해서는 조율이 좀 필요할것같습니다.

2022-10-05 01:06 UTC, hanagertrudekim commented on package.json
> +    "react-hook-form": "^7.36.0",
업데이트했습니다! c1ee928c6914e712beac234619154834ed64c2e8

2022-10-05 01:06 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/signUpPage/components/PasswordCheckInput.tsx
> +        : <BlindIcon className={styles['form__blind-icon']} onClick={changeBlind} aria-hidden /> }
수정했습니다! c1ee928c6914e712beac234619154834ed64c2e8

2022-10-05 01:07 UTC, hanagertrudekim commented on src/App.tsx
>        <Route path="/login" element={<LoginPage />} />
수정했습니다! b8a6102b1de6980312e0f22023608e679ca5c7b9

2022-10-05 01:09 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/hooks/useFirstErrorMessage.ts
> +  return errorList[0]?.message;
수정했습니다 ! b8a6102b1de6980312e0f22023608e679ca5c7b9
한가지 궁금한점이 혹시 왜 조건값의 속성을 `length`로 주셨는지 여쭤봐도 될까요..??

2022-10-05 01:11 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/hooks/useRouteCheck.ts
> +      navigate(route);
수정했습니다..! a7e85a04b45b328b8fecf5ac68d990e1b33cc13a
아마도 로그인창에서 회원가입의 경로가 `/signup`으로 설정되어서 그런 오류가 발생한것같습니다

2022-10-05 01:13 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/termsOfServicePage/TermsOfService.tsx
> +            onClick={() => navigate('/signup', { state: { termsCheck: true }, replace: true })}
`/signup`에서 뒤로가기를 눌렀을시 `/terms-of-service`가 아니라 초기 페이지로 이동하기 때문에 해당 raplace는 삭제하는것으로 수정했습니다...! 33152721425be75aeefb9ac5b738ff12c60214f9

2022-10-05 01:35 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/hooks/useFirstErrorMessage.ts
> +  return errorList[0]?.message;
`Object.values()` 메소드는 객체의 각 프로퍼티 값으로 이루어진 배열을 반환합니다.

error가 없다면 배열의 길이도 0일테니, 배열이 있을 땐 0번째 값을 준다고 명시적으로 표현할 수 있어요.

2022-10-05 01:37 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/hooks/useRouteCheck.ts
> +      navigate(route);
`useRouteCheck` 훅 내에서의 리다이렉트에 replace를 추가하면 예기치 않은 위와 같은 상황을 방지할 수 있습니다.

2022-10-05 06:00 UTC, D0Dam commented on src/pages/Auth/SignUpPage/hooks/useSelect.ts
> +  };
음.. 저는 추가적인 코멘트 달 만한게 없어서 이것만 짚고 넘어가겠습니다.
`e: any`를 한 이유가 아마 `innerText`가 안되서 인것 같은데 원래 event.target 이벤트에는 `innerText` 속성이 없습니다. innerText는 HTMLElement의 속성이므로 다음과 같이 수정하면 좋을 것 같네요.

```
  const selectDomain = (e: React.MouseEvent<HTMLLIElement, MouseEvent>) => {
    const input = e.target as HTMLElement;
    if (input.innerText !== '직접 입력') {
      isSelectValue(input.innerText);
    } else {
      isSelectValue('');
    }
    setIsOpen(!isOpen);
  };
```

2022-10-05 09:29 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/hooks/useSelect.ts
> +  };
@D0Dam `currentTarget`을 쓰면 비교적 간단하고 정확하게 해당 이슈를 해결할 수 있습니다.
``` tsx
  const selectDomain = (e: React.MouseEvent<HTMLLIElement>) => {
    if (e.currentTarget.innerText !== '직접 입력') {
      isSelectValue(e.currentTarget.innerText);
    } 
```

2022-10-06 00:21 UTC, kimeodml requested changes, later dismissed

2022-10-06 00:21 UTC, kimeodml commented on src/pages/Auth/SignUpPage/termsOfServicePage/TermsOfService.tsx
> +                    <Arrow className={styles.checkbox__icon} />
Arrow 아이콘에 `cursor: pointer` 기능을 넣어주면 좋을것 같습니다!

2022-10-06 00:21 UTC, kimeodml commented on src/pages/Auth/SignUpPage/termsOfServicePage/TermsOfService.module.scss
> +  margin-top: 265px;
`margin-bottom`을 추가해주세요. 회원가입 부분도 마찬가지 입니다.

2022-10-06 00:21 UTC, kimeodml commented on src/pages/Auth/SignUpPage/signUpPage/components/IdInput.tsx
> +      </div>
input을 설명할 경우 `div`보단 `label` 태그로 감싸주는 것을 추천드립니다! 아니면 혹시 `div`를 사용한 이유가 있을까요..?

2022-10-06 00:21 UTC, kimeodml commented on src/pages/Auth/SignUpPage/signUpPage/components/IdInput.tsx
> +      </div>
또한 회원가입 부분에서 input의 placeholder 부분과 button 부분이 폰트 적용이 되질 않는것 같습니다.

2022-10-06 05:42 UTC, jaewoogwak reviewed
고생하셨습니다~ 코멘트 남겼고 추가할 점 있으면 추후 코멘트 남길게요

2022-10-06 05:42 UTC, jaewoogwak commented on src/pages/Auth/Signup/CompletePage/Complete.tsx
> +            disabled={nicknameValue === undefined || nicknameValue === ''}
닉네임에 대해 정규식도 있었으면 좋겠네요 `$#@#@$` 와 같은 특수문자를 입력해도 현재는 허용합니다.

2022-10-06 05:47 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/hooks/useFirstErrorMessage.ts
> +  return errorList[0]?.message;
아하... 이해했습니다 감사합니다!

2022-10-06 05:50 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/hooks/useRouteCheck.ts
> +      navigate(route);
그럼 혹시 다른 분들이 코드를 작성할때 회원가입 페이지 이동을 `/signup` 으로 설정할것을 염두해두고 코드를 수정해야할까요?

2022-10-06 06:20 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/hooks/useRouteCheck.ts
> +      navigate(route);
네. 강제적인 redirect에 replace가 추가되는건 오류를 방지해줄거라고 생각합니다. 뒤로가기 기능을 망치는 주범이예요.

2022-10-06 06:21 UTC, ChoiWonBeen commented on src/pages/Auth/SignUpPage/termsOfServicePage/TermsOfService.tsx
> +                    <Arrow className={styles.checkbox__icon} />
그러고보니 전체동의 라벨에도 포인터가 추가되면 좋겠네요.

2022-10-06 16:49 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/hooks/useRouteCheck.ts
> +      navigate(route);
넵! 추가적으로 알려주셨던 chorme과 safari 에서는 자동으로 그 histroy를 지워주긴 합니다.  하지만 파이어폭스나 다른 환경에서는 그 기능의 지원이 안되기때문에 혹여나 경로를 `/signup`으로 바로 들어간다고 해도 tos로 강제 이동 후 뒤로 가기를 누른다하면 거기에 무한적으로 갇히는 오류가 발생합니다. 
따라서 `useRouteCheck` 에 경로 이동을 시켜줄때 replace 를 추가해 그 오류를 해결(방지)했습니다 8fd467da9b98fd9fe7a180de593d070ee4acd3dd

2022-10-06 17:23 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/hooks/useSelect.ts
> +  };
수정했습니다 2086751758e4d9b8d8fb882942892ba0e5af6cd4

2022-10-06 17:35 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/hooks/useSelect.ts
> +  };
감사합니다..! 덕분에 많이 배웁니다ㅎㅎ 

훅의 이름을 `useDropdown` 을 바꾸었고, 로직도 재사용이 가능한 형태로 개선했습니다! 
`useDropdown` 에는 
- `selectValue`
  select option 중에서 value를 선택할수있도록 하는 함수 
- `changeValue`
"직접 입력" 과 같은 경우를 위해 value를 직접적으로 변경할수있도록 하는 함수

를 정의해주었습니다.  2086751758e4d9b8d8fb882942892ba0e5af6cd4, 1c94e411635a22ce05545b0bc85f17af84b3c76f

2022-10-07 16:38 UTC, hanagertrudekim commented on src/pages/Auth/Signup/CompletePage/Complete.tsx
> +            disabled={nicknameValue === undefined || nicknameValue === ''}
아직 pc UI가 정확히 나오지 않아 nickname 에러메시지를 추가하지는 못했습니다..... ㅠㅠ
정규식을 일단 추가하긴했는데, 추후 UI 수정사항이 생기면 다시 수정하겠습니다! 99cbbbcb4939b5adba739ad72028edb2ccab9fd5

2022-10-07 16:40 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/signUpPage/components/PasswordInput.tsx
> +const Reg = /^(?=.*[0-9])(?=.*[a-zA-z])(?=.*[!@#$%^&*+=()]).{2,16}$/;
넵 변경하였습니다! 99cbbbcb4939b5adba739ad72028edb2ccab9fd5

2022-10-07 16:48 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/signUpPage/SignUp.module.scss
> +  &__id-check-button {
넵 수정하였습니다! 5c5727fc957b2d7717da58e6973e9e2cd9f15c08

2022-10-07 16:48 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/termsOfServicePage/TermsOfService.tsx
> +                    <Arrow className={styles.checkbox__icon} />
네 수정하였습니다! ㅎㅎ 5c5727fc957b2d7717da58e6973e9e2cd9f15c08

2022-10-07 16:55 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/termsOfServicePage/TermsOfService.module.scss
> +  margin-top: 265px;
넵 추가했습니다! c20514523def0f904f0107d8d1e1bd6be0cd2f05

2022-10-09 08:51 UTC, hanagertrudekim commented on src/pages/Auth/SignUpPage/signUpPage/components/IdInput.tsx
> +      </div>
`label`태그로 수정했습니다..! 사실 그 `label`태그 안에 에러아이콘과 에러 메시지가 있어서 일단은 `div`로 묶어놓았던것같습니다..ㅎㅎ

2022-10-09 10:26 UTC, hanagertrudekim commented on src/App.tsx
> +import TermsOfService from 'pages/Auth/SignUpPage/termsOfServicePage/TermsOfService';
넵 변경하였습니다ㅎㅎ 593f733bcfbda807aece7d32a1f3cae3b88b33cb

2022-10-10 13:38 UTC, ChoiWonBeen approved these changes
고생했어요!

2022-10-12 13:26 UTC, SimYunSup approved these changes

2022-10-13 00:31 UTC, D0Dam approved these changes
수고하셨습니다.

2022-10-15 09:05 UTC, merged