Feature/#6 [Post] 글쓰기 에디터 추가
BCSDLab/TEMP_PROJECT_FE pull request #22
Opened 2022-09-26 10:27 UTC by D0Dam

## #6  request

글쓰기 에디터를 추가했습니다.
* 위지윅 구현을 위해 [tui editor 라이브러리](https://github.com/nhn/tui.editor)를 사용하였습니다.
* 글쓰기의 경로를 `/post`로 했습니다.
* `+`버튼을 누르면 검색 후 상점 이름을 가운데 띄우는데, 이는 검색 기능이 추가되면 추가하겠습니다.
* 상점 이름과 별점이 있다면 저장 버튼이 활성화됩니다.
* 저장 및 사진의 경우 back-end 측에서 api가 나오면 추가하겠습니다.
* 일단 사진의 경우 url을 받아 랜덤한 사진을 출력하는 것으로 구현해 놓았습니다.

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

### Screenshot
![Sep-26-2022 19-19-01](https://user-images.githubusercontent.com/51052049/192253015-f2026ca5-bbc7-4484-a474-b10813f68a8b.gif)

2022-09-26 12:18 UTC, ChoiWonBeen requested changes
고생하셨습니다! 언급하지 못한 몇가지를 말하면,
1. [`CONTRIBUTE.md`](https://github.com/BCSDLab/JJBAKSA_FRONT_END/blob/develop/CONTRIBUTE.md) 문서에 작성했듯이, yarn을 쓰는 프로젝트고, package-lock.json은 존재하면 안됩니다. 지워주시고 yarn으로 관리해주세요.
2. `rating/StartContainer/` 레포지토리 구성은 다른 레이팅 방법이 있을거라 추가한건가요? 기획상 점수를 메기는 것은 별점뿐이니 아예 컴포넌트 이름을 Rating으로 구성하는게 더 좋지 않을까 생각합니다.
3. 아래 warning이 발생하는데 해결할 방법은 없나요?
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/50780281/192273886-99b6f2da-e289-4d03-92cc-3c30a603d4df.png">
4. 별점을 선택하는것이 별에 달려있어서 별 사이를 오갈때 깜빡입니다. 이를 감싸는 Container에 EventHandler를 두고 width의 비율로 관리하는것이 적절하지 않나 의견 제시해봅니다.

2022-09-26 12:18 UTC, ChoiWonBeen commented on src/pages/Post/index.tsx
> +    </div>
특정 상점에 추가하는 글쓰기라면 어떤식으로 props를 전달할 지 추가되면 좋을거같네요.

2022-09-26 12:18 UTC, ChoiWonBeen commented on src/components/rating/StarContainer/index.tsx
> +  };
앞선 모든 PR에 같은 내용이 있을겁니다.
기능은 hook으로 분리해주세요.

2022-09-26 12:18 UTC, ChoiWonBeen commented on src/components/editor/Wysiwyg/index.tsx
> +import 'tui-editor-plugin-font-size/dist/tui-editor-plugin-font-size.css';
Wysiwyg.css가 있으면 해당 파일에서 import하는건 불가능한가요?
그리고 Wysiwyg.scss로 쓰지 않은 이유도 궁금합니다.

2022-09-26 12:18 UTC, ChoiWonBeen commented on src/components/editor/TextEditor/index.tsx
> +  };
custom hook으로 분리해주세요.

2022-09-26 12:18 UTC, ChoiWonBeen commented on src/components/editor/TextEditor/index.tsx
> +import React, { useEffect, useRef, useState } from 'react';
React의 불필요한 import가 포함된 것 같네요

2022-09-26 12:18 UTC, ChoiWonBeen commented on src/components/editor/TextEditor/TextEditor.module.scss
> +  .save__button {
save는 Block인가요?
save를 포함한 다른 Element가 없어서 부적절하지않을까? 싶습니다.

2022-09-26 12:18 UTC, ChoiWonBeen commented on src/components/editor/Wysiwyg/index.tsx
> +        initialValue="내용을 입력해 주세요."
initialValue에 적절하지 않을 것 같습니다.
시작하자마자 글을 지워야하는건 상당히 불편한 UX같네요

2022-09-26 13:00 UTC, D0Dam commented
> 고생하셨습니다! 언급하지 못한 몇가지를 말하면,
> 
> 1. [`CONTRIBUTE.md`](https://github.com/BCSDLab/JJBAKSA_FRONT_END/blob/develop/CONTRIBUTE.md) 문서에 작성했듯이, yarn을 쓰는 프로젝트고, package-lock.json은 존재하면 안됩니다. 지워주시고 yarn으로 관리해주세요.
> 2. `rating/StartContainer/` 레포지토리 구성은 다른 레이팅 방법이 있을거라 추가한건가요? 기획상 점수를 메기는 것은 별점뿐이니 아예 컴포넌트 이름을 Rating으로 구성하는게 더 좋지 않을까 생각합니다.
> 3. 별점을 선택하는것이 별에 달려있어서 별 사이를 오갈때 깜빡입니다. 이를 감싸는 Container에 EventHandler를 두고 width의 비율로 관리하는것이 적절하지 않나 의견 제시해봅니다.
> 4. 글자 크기를 바꿨을 때 원래 사이즈로 돌아갈 방법은 없네요? 이 부분도 UX측과 얘기가 된 부분인가요?
> 5. 아래 warning이 발생하는데 해결할 방법은 없나요?
> 
> <img alt="image" width="1039" src="https://user-images.githubusercontent.com/50780281/192273886-99b6f2da-e289-4d03-92cc-3c30a603d4df.png">

이에 대해 답변하자면,
1.  넵 알겠습니다.
2. 생각해보니 그런 것 같습니다. 컴포넌트 이름을 Rating으로 통일하겠습니다.
3.  자세히 보니 진짜로 깜빡이네요..🥲 width 비율로 한번 고쳐보겠습니다.
4. 네 놀랍게도 원래 사이즈로 돌아갈 방법이 없습니다... 이건 따로 이야기를 해보겠습니다.
5.  저 warning을 해결해볼려고 여러 시도를 해봤었는데.. 추가적으로 더 시도 해보겠습니다.

2022-09-26 13:03 UTC, D0Dam commented on src/pages/Post/index.tsx
> +    </div>
글을 쓰는 구조가 검색 창에서 상점을 검색 후 특정 상점을 클릭하면 해당 상점 명으로 글쓰기 타이틀이 정해집니다. 따라서 shop의 속성을 string | undefined로 주어서 기존에는 undefined로 유지하다가 특정 상점을 클릭하면 해당 props에 string 값을 읽어오도록 할 것입니다.
그래서 검색 기능이 머지 되면 이는 바로 구현해 놓겠습니다..!

2022-09-26 13:10 UTC, D0Dam commented on src/components/editor/Wysiwyg/index.tsx
> +import 'tui-editor-plugin-font-size/dist/tui-editor-plugin-font-size.css';
1. 해당 파일에서 import 할때 쓰는 경로가 tsx에서 작성하는 path로 작성하면 실행이 되지 않습니다.. module에 직접 접근해야만 import가 되는 형식이길래 안전하게 tsx 파일에 import 했습니다.
2. 
3. Wysiwyg에 기본적으로 css 파일이 적용되어 있습니다. 그래서 형식을 일부러 css 파일로 맞추어 줬습니다...만 Wysiwyg.scss로 수정 할 수 있습니다.

2022-09-26 13:13 UTC, D0Dam commented on src/components/editor/TextEditor/TextEditor.module.scss
> +  .save__button {
음.. 저도 마찬가지로 이 save 버튼의 네이밍을 어떻게 할까 고민하다 내린 결론이었습니다.. `item__button--save`와 같은 경우도 생각해 보았는데 modifer의 경우 active로 css를 조정할 필요가 있다고 생각해서 다음과 같이 네이밍 했습니다.
우선 지속적으로 일단 고민해보겠습니다..

2022-09-26 13:17 UTC, D0Dam commented on src/components/editor/Wysiwyg/index.tsx
> +        initialValue="내용을 입력해 주세요."
해당 initialValue는 UI/UX측이 이렇게 정해줘서 쓰긴 했습니다. 다만 focus를 활용해 위지윅안으로 들어오면 initialValue가 삭제되게 구상해보았을 때  문제가 있었습니다. 라이브러리 상으로 focus했을 때 비워주는 로직을 작성하게 되면 위지윅을 들어오고 나갈 때마다 안에 있는 글들이 다 삭제되어버려 위와 같이 유지했습니다. 따라서 UI/UX 측과 상의해서 안의 내용을 아예 비우는 쪽으로 협의해 보겠습니다.

2022-09-26 13:28 UTC, ChoiWonBeen commented on src/pages/Post/index.tsx
> +    </div>
검색 기능으로 들어온다 해도, 검색기능에서 POST로 이동하는 방법은 라우팅일겁니다. URL접근을 허용하기 위해 searchParam을 쓸 것 같으니, searchParam을 사용해 추가해두면 좋을 것 같네요.

2022-09-26 13:29 UTC, ChoiWonBeen commented on src/components/editor/Wysiwyg/index.tsx
> +import 'tui-editor-plugin-font-size/dist/tui-editor-plugin-font-size.css';
stylelint의 적용범위가`.scss`파일뿐인지라, 린트 적용을 위해 추가할 필요가 있어보이네요.

2022-09-26 13:30 UTC, ChoiWonBeen commented on src/components/editor/TextEditor/TextEditor.module.scss
> +  .save__button {
그냥 `save-button`이라는 선택지도 있습니다.

2022-09-26 13:31 UTC, D0Dam commented on src/components/editor/Wysiwyg/index.tsx
> +import 'tui-editor-plugin-font-size/dist/tui-editor-plugin-font-size.css';
[d5def24](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/22/commits/d5def24e04752d9c1449823fb720c66a0016d2e3) scss로 확장자 변경했습니다.

2022-09-26 13:31 UTC, ChoiWonBeen commented on src/components/editor/Wysiwyg/index.tsx
> +        initialValue="내용을 입력해 주세요."
커스텀한 placeholder의 구현이 어렵다면 focus시 위지윅 내 value를 확인해서 initialValue와 같을 경우 지우는 방법으로 구현이 가능할 것 같습니다.

2022-09-26 13:42 UTC, D0Dam commented on src/components/editor/Wysiwyg/index.tsx
> +        initialValue="내용을 입력해 주세요."
그렇게라면 가능하겠네요! 한번 커스텀 placeholder를 시도해보다가 안되겠다 싶으면 다음과 같이 구현하겠습니다.

2022-09-26 13:42 UTC, D0Dam commented on src/pages/Post/index.tsx
> +    </div>
넵 알겠습니다.

2022-09-26 13:43 UTC, D0Dam commented on src/components/editor/TextEditor/TextEditor.module.scss
> +  .save__button {
아 그렇게 해도 괜찮군요... `save-button`으로 수정하겠습니다!

2022-09-26 15:49 UTC, pumpkiinbell commented on src/components/StarRating/index.tsx
> +          onClick={() => clickHandler(num)}
`clickHandler` 라는 함수를 새롭게 만드신 이유가 궁금합니다.

2022-09-26 15:49 UTC, pumpkiinbell commented on src/components/editor/Wysiwyg/index.tsx
> +      }
사소하지만, optional chaining 으로 로직을 개선할 수 있어 보여요

```suggestion
      editorRef.current?.getInstance().exec('addImage', { imageUrl: 'https://picsum.photos/200/300' });
```

2022-09-26 15:49 UTC, pumpkiinbell commented on src/components/editor/TextEditor/index.tsx
> +  }, [shop]);
props 로부터 derived 될 수 있는 값을 상태로 다시 선언하는 것은 리액트의 대표적인 안티패턴입니다.

```suggestion
  const [isRate, setIsRate] = useState(false);
  const navigate = useNavigate();
  const wysiwygRef = useRef<WysiwygRef>(null);
```

2022-09-26 15:49 UTC, pumpkiinbell commented on src/components/editor/TextEditor/index.tsx
> +        { isShopExist && <StarRating rating={rating} /> }
앞선 상태를 제거하고 다음과 같이 수정할 수 있어 보입니다.

```suggestion
        { shop == null ? 
          <Plus 
              type="button" 
              className={styles['header__button--add']} 
              onClick={getShop} 
            />
          : (
          <> 
            <div className={styles.header__shopname}>{ shop }</div>
            <StarRating rating={rating} />
          </>
          )
        }
```

2022-09-26 15:49 UTC, pumpkiinbell commented on src/components/editor/TextEditor/index.tsx
> +          disabled={!isRate && !isShopExist}
여기도요 🙂 

```suggestion
          disabled={!isRate && shop != null}
```

2022-09-26 15:49 UTC, pumpkiinbell commented on src/components/StarRating/index.tsx
> +function StarContainer({ rating }: StarRatingProps) {
props 의 네이밍이 컴포넌트와 달라야 할 이유가 있을까요...? 간단히 Props 로도 충분해보여요

```suggestion
interface Props {
  rating: () => void;
}

function StarContainer({ rating }: Props) {
```

2022-09-26 15:49 UTC, pumpkiinbell commented on src/components/StarRating/index.tsx
> +  rating: () => void;
rating 이라는 네이밍을 보면 함수를 기대하기 어려울것 같아요.
onClick 이 더 일반적인 네이밍 인것 같습니다.
```suggestion
  onClick?: () => void;
```

2022-09-26 15:49 UTC, pumpkiinbell commented on src/components/StarRating/index.tsx
> +          onClick={() => clickHandler(num)}
개인 차이는 있을 수 있겠지만 오히려 가독성을 해친다고 느껴집니다.
앞선 Props 를 수정한다면 다음과 같이 수정할 수 있을것 같아요

```suggestion
          onClick={() => {
            setClick(num);
            onClick?.();
          }}
```

2022-09-26 15:57 UTC, D0Dam commented on src/components/StarRating/index.tsx
> +          onClick={() => clickHandler(num)}
아 그렇군요..! 🥲 그럼 이번에 커스텀 훅`useRate`로 상태를 모두 옮겨주게 되었는데 이 경우에도 setClick과 onClick을 담는 함수를 반환해서 사용하는것이 아니라, setClick과 onClick를 모두 반환시켜 Star컴포넌트의 onClick함수를 구현하는 것이 가독성이 더 높다고 보시나요?

2022-09-26 15:59 UTC, D0Dam commented on src/components/editor/Wysiwyg/index.tsx
> +      }
아 그렇네요.. 수정하겠습니다. 감사합니다!

2022-09-26 16:02 UTC, D0Dam commented on src/components/editor/TextEditor/index.tsx
> +  }, [shop]);
넵 해당내용은 수정해보겠습니다🫠

2022-09-26 16:04 UTC, pumpkiinbell commented on src/components/StarRating/index.tsx
> +  } = useRate({ rating });
정말 죄송하지만... 이렇게 만드실거면 굳이 훅을 만드는 의의가 없어보여요
`useRate` 라는 네이밍을 가진 훅을 호출하면 `rate` 나 rate 관련 메서드를 반환해야 할것 같은데
rate.hover, rate.fixStartCount, rate.countStarHover 같은 메서드가 하는 역할이 잘 상상이 안가요.

오히려 이 코드를 유지보수할 사람은 이 훅이 뭔지 다시 파악하는데 시간을 더 쓸 것 같아요
사실 저는 이 컴포넌트를 만든다면 애초에 훅을 안 만들었을 것 같아요... 이전 로직이 가독성 면에서 훨씬 나아보여요

2022-09-26 16:04 UTC, D0Dam commented on src/components/editor/TextEditor/index.tsx
> +        { isShopExist && <StarRating rating={rating} /> }
아 이렇게 하면 되는군요..! 바로 이해가 되었습니다! 감사합니다!

2022-09-26 16:04 UTC, pumpkiinbell commented on src/components/StarRating/index.tsx
> +          onClick={() => clickHandler(num)}
훅 만드신걸 늦게 봤네요 😅 코멘트 남겼습니다 https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/22#discussion_r980240732

2022-09-26 16:05 UTC, D0Dam commented on src/components/StarRating/index.tsx
> +function StarContainer({ rating }: StarRatingProps) {
아 네이밍을 최대한 신경써 봤는데 그냥 Props로 줘도 괜찮군요..! 배워갑니다!

2022-09-26 16:05 UTC, pumpkiinbell commented on src/components/editor/TextEditor/index.tsx
> +        { isShopExist && <StarRating rating={rating} /> }
넵 ㅎㅎ react 상태의 Single Source of Truth 를 지키도록 노력해주세요 😄 https://reactjs.org/docs/lifting-state-up.html#lessons-learned

2022-09-26 16:06 UTC, pumpkiinbell commented on src/components/StarRating/index.tsx
> +function StarContainer({ rating }: StarRatingProps) {
외부에 노출시킨다면 보다 추상적인 props 네이밍을 고민해볼 수 있겠지만 위 케이스는 그렇지 않은것 같네요 😄

2022-09-26 16:09 UTC, D0Dam commented on src/components/StarRating/index.tsx
> +  } = useRate({ rating });
이번 프로젝트가 이런 모든 상태를 훅으로 넘겨주는 것을 원칙으로 하는 것 같아(위의 원빈이 request를 확인하자면..) 이렇게 전부 넘겨 줬습니다... Editor의 훅도 마찬가지로 이렇게 전부 넘겨줬었는데 정말 생각이 짧았습니다..ㅠㅠ

해당 네이밍에 맞는 관련 메서드를 넘겨줄 수 있도록 훅을 수정하고 나머지 상태는 굳이 훅은 만들라고 권장한다면 새로운 hook을 만들어 새롭게 네이밍하겠습니다..! 이 방법은 괜찮을까요??

그리고 이렇게 조언 해주셔서 정말 감사합니다! 덕분에 많이 배웁니다🙇🏻‍♂️

2022-09-26 16:09 UTC, D0Dam commented on src/components/StarRating/index.tsx
> +  rating: () => void;
네 수정하겠습니다!

2022-09-26 16:12 UTC, pumpkiinbell commented on src/components/StarRating/index.tsx
> +  } = useRate({ rating });
이 훅이 다른 컴포넌트에서 재사용 될 수 있음이 상상이 되시나요?? 
저는 훅을 만들때 아래 조건들을 한번쯤 생각해보는 것 같아요.

- 컴포넌트 내부에 여러 관심사가 존재하는가? 그렇지 않다면 훅을 만듦으로써 가독성을 해칠 수 있다.
- 훅에 여러 관심사가 존재하지 않는가? 만약 그렇다면, 각자의 문맥을 가진 훅으로 쪼갠다.
- 다른 컴포넌트에서도 사용될 수 있도록 훅을 순수하게 만들 수 있는가?
- 훅의 반환값 네이밍은 사용하기 쉽게 만들어지는가?

2022-09-26 16:17 UTC, pumpkiinbell commented on src/components/StarRating/index.tsx
> +  } = useRate({ rating });
> 이번 프로젝트가 이런 모든 상태를 훅으로 넘겨주는 것을 원칙으로 하는 것 같아(위의 원빈이 request를 확인하자면..) 이렇게 전부 넘겨 줬습니다... Editor의 훅도 마찬가지로 이렇게 전부 넘겨줬었는데 정말 생각이 짧았습니다..ㅠㅠ
> 
> 해당 네이밍에 맞는 관련 메서드를 넘겨줄 수 있도록 훅을 수정하고 나머지 상태는 굳이 훅은 만들라고 권장한다면 새로운 hook을 만들어 새롭게 네이밍하겠습니다..! 이 방법은 괜찮을까요??
> 
> 그리고 이렇게 조언 해주셔서 정말 감사합니다! 덕분에 많이 배웁니다🙇🏻‍♂️

아하 그렇군요 ... 만약 훅을 만들어 사용하는 것이 더 적합하다고 판단되시면 그렇게 하시면 됩니다 ㅎㅎ
다만 저라면 앞서 언급했던 고민들을 미루어 봤을 때 굳이 훅을 만들지 않을것 같아요

2022-09-26 16:18 UTC, D0Dam commented on src/components/StarRating/index.tsx
> +  } = useRate({ rating });
이 컴포넌트 훅의 경우는 

> 훅에 여러 관심사가 존재하지 않는가? 만약 그렇다면, 각자의 문맥을 가진 훅으로 쪼갠다.

이에 해당이 되겠군요. 감사합니다.훅을 쪼개서 관리하는쪽으로 가보겠습니다!

그리고 추가적으로 질문드리고 싶은 점이 있는 점이 있는데 위와 같이 재사용성이 낮다라고 판단이 됨에도 불구하고 훅을 문맥별로 끊어 각자의 문맥을 가진 훅으로 만들어 관리하는 방식도 주로 이용하는 방법인가요?

2022-09-26 16:20 UTC, pumpkiinbell commented on src/components/StarRating/index.tsx
> +  } = useRate({ rating });
직관적인 네이밍에 대해서 잘 감이 안오실것 같아 추가적인 코멘트 남깁니다 ㅎㅎ...

`const history = useHistory();` 라는 훅을 호출하면, router 는 다음과 같은 메서드를 사용할 수 있어요.
`history.push, history.pop, ...` 

이런 훅은 사용하기 좋은 인터페이스를 가지고 있고, 어떤 컴포넌트에서든 사용하기 좋게 순수하게 만들어져있으므로 좋은 훅이라 생각합니다.

2022-09-26 16:23 UTC, pumpkiinbell commented on src/components/StarRating/index.tsx
> +  } = useRate({ rating });
> 그리고 추가적으로 질문드리고 싶은 점이 있는 점이 있는데 위와 같이 재사용성이 낮다라고 판단이 됨에도 불구하고 훅을 문맥별로 끊어 각자의 문맥을 가진 훅으로 만들어 관리하는 방식도 주로 이용하는 방법인가요?

네... 가독성 면에서 선언적인 훅을 만듦으로써 문맥을 구분하는 방식은 자주 사용하는것 같아요.
대신에 저는 이런 경우, 상위 모듈이 아닌 최대한 낮은 hierarchy 에 hook 을 만드려고 해요.

가령,,, 위의 케이스는 우선 `src/components/StarRating/hooks.ts` 에 만들었을거예요.
그러나 이 훅이 재사용된다면 좀 더 상위 계층의 모듈로 훅을 이동시켜줄거예요.

2022-09-26 16:26 UTC, D0Dam commented on src/components/StarRating/index.tsx
> +  } = useRate({ rating });
아.. 이런 느낌이군요.. 기존에 만들어진 유명한 훅을 좀 살펴 보고 직관적이라는 것에 좀 익숙해질 필요가 있겠네요🫠 감사합니다!

2022-09-26 17:52 UTC, D0Dam commented on src/pages/Post/index.tsx
> +    </div>
일단 useSearchParams로 shop이라는 쿼리값을 읽어오게끔 구현해 두었습니다. shop이라는 값이 읽히면 글쓰기 제목이 되고 별점 기능이 활성화 됩니다.

이를 위해서는 검색페이지에 이 함수를 넘겨줘야할 것 같아 일단 게시물 추가 button의 onClick 이벤트에 넣어두었습니다.
추후에 게시물 추가 버튼에 링크를 달아 검색 페이지로 이동할 수 있게끔 하고 shop 쿼리값을 읽어오는 함수를 전달해 쿼리값을 가져올 예정입니다.

2022-09-26 18:04 UTC, D0Dam commented
> 5. 아래 warning이 발생하는데 해결할 방법은 없나요?
> 
> <img alt="image" width="1039" src="https://user-images.githubusercontent.com/50780281/192273886-99b6f2da-e289-4d03-92cc-3c30a603d4df.png">

해당 문제에 관해 해결법을 알아왔는데 해당 js파일이 ts에 적용이 안되서 일어나는 소스맵 에러로 보입니다. 이에 대한 [해결책](https://stackoverflow.com/questions/70599784/failed-to-parse-source-map)이 2가지 있습니다.
1. .env 파일을 생성하고 `GENERATE_SOURCEMAP=false`를 추가해준다.
2. 아래 코드와 같이 package.json의 키가 `scripts`인 값에 `GENERATE_SOURCEMAP=false`를 추가해준다.
```
"scripts": {
    "start": "GENERATE_SOURCEMAP=false react-scripts start",
``` 
1번의 경우를 채용할 경우 각자가 local에서 .env 파일을 만들어 해당 속성을 넣어주어야합니다.
2번의 경우 package.json을 직접적으로 수정하게 됩니다.
이 둘중에 뭐가 더 나을지 의견을 받고자 합니다.

2022-09-26 22:58 UTC, ChoiWonBeen commented
빌드 파일 자체에 에러가 나는 것은 아니니 .env파일에 추가해도 괜찮을 것 같네여

2022-09-26 23:58 UTC, D0Dam commented
> 빌드 파일 자체에 에러가 나는 것은 아니니 .env파일에 추가해도 괜찮을 것 같네여

그럼 따로 .env 파일 만들어 추가 하겠습니다.

2022-09-27 01:19 UTC, SimYunSup requested changes
간단하게 리뷰 마쳤습니다.
훅을 분리할 경우 직관적으로(한 번에 알아볼 수 있게), 그리고 일반적인 이름으로 변경하는 것이 좋겠네요.
Rating 구현의 경우 [MUI](https://mui.com/material-ui/react-rating/), [ant design](https://ant.design/components/rate/)을 참고해 변수 네이밍이나 접근성을 어떻게 살렸는지 확인하면 좋습니다.

2022-09-27 01:19 UTC, SimYunSup commented on src/components/StarRating/index.tsx
> +          fill={(hover >= num) || (click >= num) ? '#ff7f23' : '#eeeeee'}
hover가 click보다 적은 경우에는 click 값을 보이게 됩니다. 사용자가 UX에서 혼란을 겪을 수 있으므로 hover했을 때는 hover했을 때의 값을 보여주게 해주세요.

2022-09-27 01:19 UTC, SimYunSup commented on src/components/StarRating/index.tsx
> +          onMouseLeave={() => starHoverLeave(num)}
hover시에 해당 Star를 `scale`해주었으면 좋겠네요.
ex. https://ant.design/components/rate/

2022-09-27 01:19 UTC, SimYunSup commented on src/components/editor/TextEditor/TextEditor.module.scss
> +        }
scss에는 for loop문을 사용할 수 있습니다.
https://sass-lang.com/documentation/at-rules/control/for

2022-09-27 01:19 UTC, SimYunSup commented on src/components/editor/TextEditor/hooks/useEditor.ts
> +  };
앞에서도 다른 리뷰어분들이 말씀하셨겠지만 직관적이고 일반적인 이름으로 바꿔주세요.

2022-09-27 01:19 UTC, SimYunSup commented on src/components/editor/Wysiwyg/Wysiwyg.scss
> +}
해당 클래스는 나중에 문제가 될 수 있습니다. CSS Module을 사용하거나 네이밍을 바꿔주세요.

2022-09-27 01:19 UTC, SimYunSup commented on src/components/editor/TextEditor/TextEditor.module.scss
> +    background-color: #c4c4c4;
`cursor: pointer`를 넣어주세요.

2022-09-27 01:19 UTC, SimYunSup commented on src/components/editor/TextEditor/TextEditor.module.scss
> +        line-height: 20px;
`cursor: pointer`를 넣어주세요.

2022-09-27 01:59 UTC, ChoiWonBeen commented on src/components/editor/TextEditor/hooks/useEditor.ts
> +  };
+ navigate는 포함될 이유가 없어보이네요.

2022-09-27 03:19 UTC, D0Dam commented on src/components/editor/TextEditor/hooks/useEditor.ts
> +  };
훅은... 모두 다 뒤엎고 새로 구상하겠습니다🫠

2022-09-27 04:17 UTC, D0Dam commented on src/components/editor/Wysiwyg/Wysiwyg.scss
> +}
`rateContainer`로 수정하겠습니다.

2022-09-27 04:26 UTC, D0Dam commented on src/components/StarRating/index.tsx
> +          fill={(hover >= num) || (click >= num) ? '#ff7f23' : '#eeeeee'}
> hover가 click보다 적은 경우에는 click 값을 보이게 됩니다. 
이는 의도된 것입니다. 
click을 하게되면 별점을 고정하는 형식이라 hover로 별점을 수정할 수 없게 하기 위해 다음과 같이 코드를 구성했습니다.
hover는 click을 하기 전에 UX적으로 hover된 곳까지 별의 색이 변하게 하기 위한 효과의 수단으로 넣었습니다.
그래서 hover로도 값을 보여주는 것이 저는 UX적으로 혼란을 야기한다고 생각했는데 이에 대해 추가적인 설명 해주셨으면 합니다!

2022-09-27 04:33 UTC, D0Dam commented on src/components/StarRating/index.tsx
> +          onMouseLeave={() => starHoverLeave(num)}
scale 효과는 추가하겠습니다.

2022-09-27 04:34 UTC, D0Dam commented on src/components/StarRating/index.tsx
> +          fill={(hover >= num) || (click >= num) ? '#ff7f23' : '#eeeeee'}
아니면 이 부분은 UX 쪽에서 어느 것을 의도한것인지 별도로 물어보고 수정하겠습니다..!

2022-09-27 22:35 UTC, D0Dam commented on src/components/editor/TextEditor/hooks/useEditor.ts
> +  };
@D0Dam 
test

2022-09-30 02:23 UTC, pumpkiinbell commented on src/components/StarRating/index.tsx
> +  click: (num: number) => void;
아래 이름이 더 좋지 않을까 싶어요 핸들러를 내려주는 거니깐요

```suggestion
  handleMouseEnter: () => void;
  handleMouseLeave: () => void;
  handleClick: (num: number) => void;
```

2022-09-30 02:23 UTC, pumpkiinbell commented on src/components/StarRating/index.tsx
> +  const [mouseEnter, setMouseEnter] = useState(false);
mouseEnter 가 boolean 타입을 가질 수 있을까요...? 전 아니라 생각합니다
차라리 isMouseEnter 가 낫겠다 싶네요

2022-09-30 02:23 UTC, pumpkiinbell commented on src/components/StarRating/index.tsx
> +}
Props 의 타입 선언과 사용하는 쪽의 코드의 거리가 멀어서 코드를 파악하기 힘드네요

2022-09-30 02:23 UTC, pumpkiinbell commented on src/components/StarRating/index.tsx
> +          onClick={() => {
이 코드들이 위에 선언되어있고 사용하는 쪽이 아래이다 보니깐 코드를 위아래로 계속 보게 되는것 같아요

이건 스타일 문제긴 하지만, 저였으면 StarRating 아래로 뺄것 같아요
아니면 차라리 다른 모듈로 선언해서 import 하는게 좋아보여요

2022-09-30 02:23 UTC, pumpkiinbell commented on src/components/StarRating/index.tsx
> +  }), [setActive]);
setActive 가 뭔가 싶었는데... click 이벤트 trigger 시에 호출해주는 애였네요.
차라리 onClick 으로 바꾸고 아래처럼 하는게 나아보여요

```suggestion
  const value = useMemo(() => ({
    handleMouseEnter: () => setMouseEnter(true),
    handleMouseLeave: () => setMouseEnter(false),
    handleClick: (num: number) => {
      setRating(num);
      onClick?.()
    },
  }), [onClick]);
```

2022-09-30 02:23 UTC, pumpkiinbell commented on src/components/StarRating/index.tsx
> +      )}
사소하지만 굳이 true 여부를 체크하지 않아도 괜찮겠네요
```suggestion
      {isMouseEnter ? (
        <EnterStarRateContainer rating={rating} />
      ) : (
        <LeaveStarRateContainer rating={rating} />
      )}
```

2022-09-30 02:23 UTC, pumpkiinbell commented on src/components/editor/TextEditor/hooks/useChckRate.ts
> +export default function useCheckRate() {
모듈이름이랑 선언한 훅의 이름을 맞춰주세요

2022-09-30 02:23 UTC, pumpkiinbell commented on src/components/editor/TextEditor/hooks/useChckRate.ts
> +  return {
다시봐도 정말 별로인것 같아요... 굳이 훅을 만들어야 하나요?

2022-09-30 02:23 UTC, pumpkiinbell commented on src/components/editor/TextEditor/hooks/useTextTool.ts
> +}
이것도 굳이 훅을 만들어야 하나요?

2022-09-30 02:23 UTC, pumpkiinbell commented on src/utils/hooks/useContext.ts
> +  if (!state) throw new Error('Provider not found');
엄격히 분기문을 처리하는 것이 좋아보여요

```suggestion
  if (state == null) {
    throw new Error('ContextValue.Provider 가 존재하지 않습니다.');
  }
```

2022-09-30 02:23 UTC, pumpkiinbell commented on src/utils/hooks/useContext.ts
> +export default function useStarContainerContext<Type>(
이 훅이 굳이 utils/hooks 에 존재해야 할까요?
다른 컴포넌트에서 쓰이지 않는다면 최대한 낮은 hierarchy 에 위치하는게 좋을것 같아요

2022-09-30 02:23 UTC, pumpkiinbell commented on src/components/StarRating/index.tsx
> +  const [starNum, setStarNum] = useState(rating);
아래 네이밍은 어떤가요?

```suggestion
  const [currentRating, setCurrentRating] = useState(initialRating);
```

2022-09-30 02:23 UTC, pumpkiinbell commented on src/components/StarRating/index.tsx
> +  }), [setActive]);
StarRating 이 setActive 라는 prop 을 받는게 어색하게 느껴지네요.
onClick 을 받도록 이름을 수정해주세요

2022-09-30 05:42 UTC, ChoiWonBeen commented on src/components/editor/TextEditor/hooks/useTextTool.ts
> +}
앞에 리뷰를 포함해서 이렇게 분리만 하는 건 훅이라고 볼 수 없겠죠?
제가 생각했던 훅으로의 분리는, boolean상태값을 다루는것이 중복되니, `useToggleState`나, `useBoolean`같이 상태에 대한 명칭을 알아볼 수 있고, 컴포넌트 내에서 setState의 사용을 바꾸길 바랬어요.

여기에 두 커스텀 훅 모두 [state, setTrue, setFalse, toggle] 을 제공하는 식으로 사용하는 컴포넌트에선 알맞게 변수명을 정해 재사용이 가능할텐데, 사용하는 입장에서 깔끔하게 분리될거라 생각했네요. 적어도 setState를 사용하는것보단 명시적이면서 오류를 줄일 수 있을테니 말이죠.

컴포넌트의 로직을 분리하라는 말이 그냥 떼어내서 위로 올리는거라면 불필요한게 맞습니다..

2022-09-30 06:19 UTC, ChoiWonBeen commented on src/components/editor/TextEditor/hooks/useTextTool.ts
> +}
음 추가로, 페이지 단위에서는 로직과 View의 분리가 필수라고 생각하는 건 동일하지만, 작은 단위로 쪼개진 컴포넌트 내에서는 기능을 억지로 추상화할 필요가 없어보이네요. 이 점은 다른 사람들한테도 전달하겠습니당

2022-09-30 06:24 UTC, ChoiWonBeen commented on src/utils/hooks/useContext.ts
> +export default function useStarContainerContext<Type>(
useContext라는 이름으로 보아 context를 추상화한 훅이라면 괜찮아 보이는데(하지만 Reaxt에서 기본으로 제공하는 useContext와 네이밍이 겹칩니다), 내부 함수가 star에 대한 내용이네요.

완전히 추상화를 해서 사용하거나, 계층을 낮게 유지하도록 변경이 필요해 보이네요

2022-09-30 09:30 UTC, D0Dam commented on src/components/StarRating/index.tsx
> +  }), [setActive]);
아 두 함수 모두 Click이벤트 발생시에 일어나는거니 묶어줄 수 있었네요! 감사합니다

2022-09-30 09:42 UTC, D0Dam commented on src/utils/hooks/useContext.ts
> +export default function useStarContainerContext<Type>(
@ChoiWonBeen
useContext 훅 자체는 자신이 원하는 타입에 맞게끔 사용할 수 있도록 커스텀 하려 했습니다..추가적으로 null검사도 해줘서 null인지 확인하는 코드를 따로 작성안해도 되게끔 말이죠! 그런데 지금 보니 제가 훅은 종속되게 해 놓았네요.... 이건 제 실수 입니다.. 완전 추상화 해 놓겠습니다.

추가적으로 네이밍 관련해서 useContext 라는 이름을 중복적으로 사용하기 그렇다면 어떤네이밍으로 하실 것 같은지 의견 들어볼 수 있을까요?

2022-09-30 09:52 UTC, D0Dam commented on src/components/StarRating/index.tsx
> +  const [starNum, setStarNum] = useState(rating);
@pumpkiinbell

음.. currentRating이라고 하기에 이 상태는 마우스 호버 시에 별의 색깔이 몇개 바뀌는지 읽는 상태라고 생각했슴니다. 
이 상태가 최근 별점을 받는다면 말이 맞겠지만 이 상태는 별점에 영향을 끼치지 못합니다.
예를 들어, 별점 4점에 클릭을 해 고정시켜놓고 2점으로 호버 했다고 가정합니다. 그렇다면 currentRating이 2가 되는 것인데 이 경우에도 별점은 클릭하기 전에는 4점 고정입니다. 마우스를 바깥으로 빼도 그렇구요! currentRating이라는 네이밍이 이러한 점에서 어색하게 다가올 것 같습니다.

그래서 저 같은 경우에는 단순히 별의 순번을 읽는 상태라고 보았습니다.그래서 starNum이라는 네이밍을 주었습니다. 이건 다른 팀원들의 생각도 들어보고 싶네요..!

2022-09-30 09:53 UTC, D0Dam commented on src/components/StarRating/index.tsx
> +  const [starNum, setStarNum] = useState(rating);
다만 인자값을 initialRating으로 가져가는 것은 좋은 것 같습니다!

2022-09-30 09:56 UTC, D0Dam commented on src/components/editor/TextEditor/hooks/useTextTool.ts
> +}
제가 아직 안 고친 부분들도 있지만 이 부분에 대해서는 저도 잘못생각하고 있는 부분이 많다는걸 느껴서 수정하려 했습니다..! 미리 수정해놓았으면 이렇게 두 번 이야기 하시지 않게 할 수 있었는데.. 늦어버렸네요.. 죄송합니다..ㅠㅜ 최대한 공통 분모를 만들어 훅을 짜보겠습니다.

2022-09-30 10:12 UTC, ChoiWonBeen commented on src/utils/hooks/useContext.ts
> +export default function useStarContainerContext<Type>(
useWrappingContext..? 근데 요기 왜 Context로 관리했는지 물어봐도 될까여?

2022-09-30 11:35 UTC, D0Dam commented on src/utils/hooks/useContext.ts
> +export default function useStarContainerContext<Type>(
아 이거는 저도 종호 형에게 추천받은건데 이런 스타일로도 요즘 많이 쓴다고 하더라구요! 일단 여기서 쓴 좀  결정적인 이유는 더욱 직관적이고 통일감을 주기 위한 부분이 있습니다. 코드를 살펴보면 알겠지만 `EnterStarRateContainer`에서는 부모에서 `handleMouseLeave`, `handleClick`만을 가져옵니다.(물론 컨텍스트 개념이지만 그냥 props처럼 가져왔다고 이야기할게요.) `LeaveStarRateContainer`에서는 `handleMouseEnter`를 가져왔구요. 각자 부모는 같은데 가져온 props가 다 제각각이다보니 이 props를 포함해서 분기를 나누어주는 코드를 작성하니까 보기 안이쁘고 한눈에 잘 안들어오더라구요. 그래서 2가지 방식을 추천받았었는데 이게 그 방법중 하나였습니다.

나머지 하나의 방식은 useReducer로 이벤트를 관리하는 방식이었는데 이 방식도 괜찮지만 action할 타입이 딱 3개이기도 했고, 무엇보다 action 로직 자체가 간단해서 useReducer까지의 필요성을 못 느꼈습니다..(action이 좀더 복잡했거나 useEffect가 포함 되었다던지.. 했다면 이 방법을 채택했을 거에요.)

다시 본론으로, 이걸 그냥 컨텍스트로 묶어줌으로써 `StarRating`에서는 click, mouseEnter, mouseLeave라는 함수를 사용할거야! 라고 위에서 말하고 난 뒤에 분기문을 처리하니까 확실히 깔끔하더라구요. 대신 컨텍스트에서 정의한 함수들을 `LeaveStarRateContainer`와 `LeaveStarRateContainer`에서 사용할 때 다른 사람이 이 함수의 원형을 찾아보지 않고도 직관적으로 알 수 있을 정도로 해 놓았습니다. 예를 들어 컨텍스트의 `handleMouseEnter`는 함수의 원형을 굳이 찾아보지 않아도 마우스를 Enter했다고 조작하라는 handler인게 딱 눈에 보이게끔 말이죠! 이렇게하면 함수 로직 자체가 간단하면 함수를 모아서 보기도 편하고 굳이 함수 원형을 안봐도 컨텍스트로 값을 전달받는 컴포넌트를 쉽게 이해할 수 있었습니다.

나름 많은 고심끝에 남기기로 했는데.. 이게 좋게 보였으면 좋겠네요..

아! 참고로 컨텍스트를 안썻다면 다음과 같이 작성되었을겁니다. 빨리 작성하다보니 lint는 무시하고 쓴점은 양해 바랍니다..ㅎㅎ
<img width="508" alt="스크린샷 2022-09-30 오후 8 35 23" src="https://user-images.githubusercontent.com/51052049/193261162-053aa129-278e-43d4-8b80-b37062e7e017.png">

2022-09-30 13:12 UTC, ChoiWonBeen commented on src/utils/hooks/useContext.ts
> +export default function useStarContainerContext<Type>(
아하 context value에 setState를 넘겨주는게 인상적이네요. 
목적에 맞게 썼다면 useReducer가 더 적합해보이긴 한데 코드량만 늘어서 오히려 보기 더 불편했을 것 같아요 ㅋㅋㅋ

2022-10-02 00:54 UTC, D0Dam commented on src/components/StarRating/index.tsx
> +  const [starNum, setStarNum] = useState(rating);
@pumpkiinbell 

고민을 좀 더 해보았는데 네이밍으로 starAmount를 추천해 주셨는데 amount가 셀수 없는 양을 표현할때 주로 사용하는 말이라 적합하지 않다고 판단했습니다. 대신, quantity라고하는 셀수 있는 양을 표현한 명사가 있길래 starQuantity로 네이밍을 변경하겠습니다.

2022-10-02 02:10 UTC, D0Dam commented on src/components/editor/TextEditor/hooks/useChckRate.ts
> +  return {
useBoolean으로 대체하였습니다!

2022-10-05 00:36 UTC, jaewoogwak reviewed
추가된 addImage.tsx 부분입니당

2022-10-05 00:36 UTC, jaewoogwak commented on src/components/editor/TextEditor/AddImage.tsx
> +      prev && prev.map((item, i) => (
`i`만으로는 뜻을 한번에 유추하기 힘든거 같아요 `itemIndex` 같은 네이밍을 사용하면 좋겠네요

2022-10-05 01:35 UTC, D0Dam commented on src/components/editor/TextEditor/AddImage.tsx
> +      prev && prev.map((item, i) => (
구조를 대대적으로 뜯어 고쳐서 이제는 없는 함수가 되었지만.. 놓치고 지나갔었네요. 의견 감사합니다😄

2022-10-05 09:01 UTC, ChoiWonBeen approved these changes
👍 기능상 문제도 없네요. 고생하셨어요.
PC UI가 너무 작아서 문제가 될 것 같긴 한데... ㅋㅋㅋ 이건 UI팀과 추후에 협의해보죠

2022-10-05 11:02 UTC, SimYunSup approved these changes
고생하셨습니다.
Star 컴포넌트의 트랜지션이 인상깊네요.

2022-10-05 13:42 UTC, merged