fix: 연관검색어 UI, 로직 수정
BCSDLab/TEMP_PROJECT_FE pull request #230
Opened 2024-01-23 12:47 UTC by junghaesung79

## [#226] request

연관검색어가 나오고 들어가는 조건 로직과 UI를 수정하였습니다.

검색 파트 전반적인 리팩토링 진행했습니다.
사용하지 않는 코드들을 삭제했습니다.

이후 검색 이슈 계속 해결해나갈 예정입니다.

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

### Screenshot
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/96577250/48e2bee4-a815-46ee-85f5-2c839beb207a)
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/96577250/5d3ef960-e327-4ac3-9424-cbd97fb2cea0)

### Precautions (main files for this PR ...)

2024-01-23 15:05 UTC, hanagertrudekim requested changes
수고하셨습니다~ 다음에는 대소문자 유의해서 리팩토링 진행해주세요 🥲

2024-01-23 15:05 UTC, hanagertrudeKim commented on src/pages/Search/hooks/useSearchingMode.ts
> +  }, [isText, isFocused]);
1. node 가 무엇을 뜻하는지 잘 모르겠어요.
2. `handleValueChange` 보단 `handleInputChange` 라는 말이 더 정확한 것 같습니다.
3. isSearching, isText, isFocused로나누지 않고 isSearching 이라는 상태 하나로 핸들링할 수 있을것같아요.
4. `handleValueChange` , `handleFocus` , `handleBlur` 가 밖에서 동작하도록 useEffect에서 꺼내면 좋을 것 같아요.
5. 현재 useEffect의 관심사를 둘로 분명히 나누면 좋을것같아요. 
첫번째 관심사는 MutationObserver를 사용하여 input 값의 변경을 감지하고
두번째는 Event listeners를 활용하여 input 값의 변경, focus, blur 이벤트를 처리하는 식으로?

2024-01-23 15:05 UTC, hanagertrudekim commented on src/pages/Search/components/ToggleButton/index.tsx
> +          aria-label="토글"
`aria-label` 속성을 사용할 때, 좀 더 명확하고 토글에 대한 정보를 담은 문구를 제공하는 것이 필요해요.
(Ex. 검색 토글이라면, 검색 모드 전환: 활성화됨/비활성화됨)
스크린 리더 사용자가 사용하기에 불편함이 없도록 하면 좋을 것 같습니다.

2024-01-23 15:26 UTC, junghaesung79 commented on src/pages/Search/components/ToggleButton/index.tsx
> +          aria-label="토글"
"자동완성 활성화/비활성화"로 변경했습니다.
ece3908367b52116667aeae3b4b73e9247aa2b29

2024-01-23 15:41 UTC, junghaesung79 commented on src/pages/Search/hooks/useSearchingMode.ts
> +  }, [isText, isFocused]);
1. node는 SearchInput에 있는 input 태그입니다. 알아보기 편하도록 inputTag로 바꿨습니다. cd32e4f63ed82d7c3d095f0cdc73e0ff15c412fa
2. 확실히 그렇네요. 수정했습니다. 5e72f81b4d9c0ad7fa90e860f928ae78a46431fb

2024-01-23 15:57 UTC, junghaesung79 commented on src/pages/Search/hooks/useSearchingMode.ts
> +  }, [isText, isFocused]);
3. isText, isFocused로 분리한 이유는 두 상태들이 차집합일 때(input에 글이 있지만 화면 밖을 클릭해서 focus가 꺼졌을 때, input에 focus 되었지만 글자가 없을 때)에도 연관 검색어 창이 켜지도록 하기 위함이었습니다. 만약 isSearching 한 가지 상태로 연관 검색어가 표시될 상태를 표현한다고 하면 ui의 변경 지점은 어떻게 나누는 것이 좋을까요?

2024-01-23 16:02 UTC, junghaesung79 commented on src/pages/Search/hooks/useSearchingMode.ts
> +  }, [isText, isFocused]);
4. useEffect에서 꺼냈을 때의 이점이 무엇인가요? 제가 세 함수들을 useEffect 안에 넣은 이유는(성능 차이는 아주 작을 것임) 계층 구조로 가독성을 올리는 것과 스코프를 한정시키는 것입니다. 밖에서 동작하도록이 어떤 의미인지 잘 모르겠어요.

2024-01-23 16:17 UTC, junghaesung79 commented on src/pages/Search/hooks/useSearchingMode.ts
> +  }, [isText, isFocused]);
5. 앗.. 지금 보니까 제가 같은 동작의 코드를 두 번 적은 것 같아요. 지정하신 범위에서 첫 번째 훅이 맞는 코드고 두 번째 코드가 없애야 할 코드에요. 원래 두 번째 코드 방식으로 만들었다가 x 버튼에서의 상태 변경을 추적하지 못 해서 MutationObserver를 사용하는 방식으로 바꿨어요. 그런데 문제를 해결하고 테스트한 후에 바로 커밋해버린 것 같아요.

2024-01-23 16:24 UTC, junghaesung79 commented on src/pages/Search/hooks/useSearchingMode.ts
> +  }, [isText, isFocused]);
두 번째 useEffect 블록 삭제했습니다! b392ab507b15275c9d08d40cf2cb983f0c3d3a56
참고로 두 번째 훅이 실패한 이유는 input에 전달되는 value={text} 가 자신 하나의 상태가 아니라 useSearchForm에서 얻은 객체의 속성이라서 추적이 어려웠기 때문입니다. text: searchForm.text

2024-01-24 01:22 UTC, hanagertrudekim approved these changes

2024-01-24 03:22 UTC, merged