fix: 탭/패드 사이즈에서 컨텐츠 가려지는 문제
BCSDLab/TEMP_PROJECT_FE pull request #265
Opened 2024-02-18 08:18 UTC by junghaesung79

## [] request

반응형 테스트 시 탭/패드 사이즈에서 컨텐츠 SideNavigation에 가려지는 문제를 해결했습니다.

Outlet 컴포넌트를 감싸는 main 태그를 만들고 `width: calc(100% - 90px)`를 적용했습니다.

이후 DefaultLayout의 Outlet 으로써 존재하는 컴포넌트는 `width: 100%`을 적용하여 SideNavigation이 가리지 않는 부분만을 차지하도록 할 수 있습니다.

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

### Screenshot
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/96577250/f92acfe2-5075-474c-b852-a507cec853cf)

### Precautions (main files for this PR ...)

2024-02-19 06:29 UTC, kimeodml requested changes
고생하셨습니다!! 추가적으로 검색창에서 화면을 줄이면 최근 검색한 식당이 가려지더라고요. width가 고정되어 있는 것 같은데 이 부분도 수정이 필요할 것 같아요. 물로 기능 구현이 우선이면 그 부분 해결한 후에 UI 적인 부분을 추후에 수정하셔도 괜찮을 것 같아요!
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/88065770/9595ed1b-12a8-424c-af04-a5428aa4f8a3)

2024-02-19 06:29 UTC, kimeodml commented on src/pages/Follow/index.module.scss
>    margin-left: 100px;
margin-left:100px 없애야할 것 같아요. 팔로우 부분 우측으로 치우쳐져 있거든요!

2024-02-19 06:29 UTC, kimeodml commented on src/pages/Setting/PC/PcSetting.module.scss
>  .setting {
formContainer 태그에 padding-left: 10px만 추가해도 좋을 것 같아요. padding이 없으니까 화면 줄이면 너무 붙어 있어서 이상해 보이거든요. 근데 여기 많이 깨지네요. 이 부분 그냥 padding-left만 추가해 주세요! @LUNA-KK
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/88065770/e2272499-fef1-431e-bb4e-eaa36de4cf04)

2024-02-20 06:44 UTC, hanagertrudeKim commented on src/pages/Setting/PC/PcSetting.module.scss
>  .setting {
저거 카피라이트 겹치는 것도 확인해주면 좋을듯해요 👍

2024-02-23 07:06 UTC, junghaesung79 commented on src/pages/Setting/PC/PcSetting.module.scss
>  .setting {
5b86096ec104a0676cbbbf8a2daea37c0517844b
글자에 nowrap 적용했습니다!

2024-02-23 07:11 UTC, junghaesung79 commented on src/pages/Follow/index.module.scss
>    margin-left: 100px;
ac3ecffccf972d2718a7f9dd9e9e2fef2f363e01
수정했습니다!

2024-02-23 07:18 UTC, junghaesung79 commented
최근 본 가게들에 대한 수정사항은 #262에서 수정하였습니다!

2024-02-25 15:15 UTC, hanagertrudekim approved these changes

2024-02-26 07:59 UTC, kimeodml approved these changes

2024-02-26 11:40 UTC, merged