Feature/#6 [Post]이미지 추가 기능 개편 및 뒤로가기 컴포넌트 적용
BCSDLab/TEMP_PROJECT_FE pull request #30
Opened 2022-10-19 12:49 UTC by D0Dam

## request

글쓰기 데이터에서 사용하는 사진 추가 기능을 전면 개편하였습니다.
* useBooleanList 훅을 삭제하였습니다.
* useOnClickOutside라는 훅을 새로 만들어 적용하였습니다.
  * 이 훅은 공용 훅으로 `utils`에 넣어두었습니다.
* 훅을 적용하면서 컴포넌트를 일부 분리 하였습니다.
* 이외에 `scss`를  BEM 형식에 맞게 일부 수정하였습니다.

공용 뒤로가기 컴포넌트를 적용하였습니다.
* 이에 따라 일부 `scss`가 변경되었습니다.

## feature difference

달라진 기능은 **Bold** 처리 해놓았습니다.
* 사진 추가 버튼으로 사진을 추가합니다.
  * 현재 사진은 랜덤한 동물 사진입니다.
* 사진을 클릭하면 삭제를 할 수 있는 버튼이 나타납니다.
* **사진 외부를 클릭하면 삭제를 할 수 있는 버튼이 사라집니다.**
* 삭제 버튼을 누르면 사진이 리스트레서 삭제됩니다.
* 사진이 추가되었는지 여부에 따라 텍스트 에디터의 길이가 변화합니다.
* **글쓰기 페이지의 뒤로가기 버튼을 공용 컴포넌트로 교체하였습니다.**

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

### Screenshot
![Oct-19-2022 21-39-52](https://user-images.githubusercontent.com/51052049/196694631-697b1af4-0002-4655-8c2e-eac03b2fa3cd.gif)

2022-10-19 16:13 UTC, pumpkiinbell commented on src/components/editor/TextEditor/AddImage/ImageItem.tsx
> +  removeImage: (value: string) => void,
removeImage 보단 onRemove 가 어떨까... 싶습니다. (이것도 별로 좋아보이진 않네요)

```suggestion
  onDelete : (value: string) => void,
```

2022-10-19 16:13 UTC, pumpkiinbell commented on src/components/editor/TextEditor/AddImage/ImageItem.tsx
> +  const [buttonOpened, setButtonOpened] = useState(false);
여기 레포에 `useBooleanState` 가 있지 않나욤!?
고걸 사용하면 좀더 가독성이 높아질것 같아요

```suggestion
  const [opened, open, close] = useBooleanState(false);
  const imageRef = useRef<HTMLInputElement>(null);
  
  useOnClickOutside(imageRef, close);

  return (
    <>
      {opened && (
        <button
          type="button"
          aria-label="trash"
          className={styles.imageContainer__button}
          onClick={() => removeImage(value)}
        >
          <Trash />
        </button>
      )}
      <input
        type="image"
        className={styles.imageContainer__image}
        src={value}
        alt="이미지"
        ref={imageRef}
        onClick={open}
      />
    </>
```

2022-10-19 16:13 UTC, pumpkiinbell commented on src/components/editor/TextEditor/AddImage/index.tsx
> +  }, [imageList, active, inActive]);
(사소...한듯)

active, inActive props 가 JSX 를 위한 props 가 아닌 훅의 결과값을 위한 props 인 점이 걸리네요 ... 
저였으면 AddImage 를 렌더링하기 전에 useImageList 를 호출해서 imageList 만 props 로 주입했을 것 같긴 합니다

2022-10-24 05:54 UTC, D0Dam commented on src/components/editor/TextEditor/AddImage/ImageItem.tsx
> +  removeImage: (value: string) => void,
onDelete로 적용했습니다.

2022-10-24 05:55 UTC, D0Dam commented on src/components/editor/TextEditor/AddImage/ImageItem.tsx
> +  const [buttonOpened, setButtonOpened] = useState(false);
적용했습니다!

2022-10-24 06:41 UTC, D0Dam commented on src/components/editor/TextEditor/AddImage/index.tsx
> +  }, [imageList, active, inActive]);
useImageList는 AddImage에 속해 있어야 된다고 생각한 것이 컷습니다. 최우선적으로 props 를 넘기 않고서도 해결할 수 있는지 탐색해보고, 힘들면 useImageList를 외부에서 호출해서 prop로 받아오는 식으로 진행하겠습니다.

2022-10-26 12:21 UTC, kimeodml requested changes
고생하셨습니다~

2022-10-26 12:21 UTC, kimeodml commented on src/components/editor/TextEditor/AddImage/ImageItem.tsx
> +        </button>
사용자 입장에선 이미지를 누르지 않는 이상  휴지통 버튼을 모를 수 있기 때문에 mouseover시 휴지통 버튼이 나타나게 하면 어떨까요?

2022-10-26 14:47 UTC, D0Dam commented on src/components/editor/TextEditor/AddImage/ImageItem.tsx
> +        </button>
@kimeodml 
아 저도 고려를 안해본 것은 아니지만 UI/UX 측에서 클릭 시 휴지통 버튼이 나타나도록 기능을 요구했습니다. 그래서 요구 사항에 맞추어 기능을 만들었습니다🙂

2022-11-01 13:23 UTC, ChoiWonBeen requested changes
요정도 먼저 확인해주세요~

2022-11-01 13:23 UTC, ChoiWonBeen commented on src/components/editor/TextEditor/TextEditor.module.scss
>    overflow: scroll;
이게 `overflow-scroll` 속성은 의도치 않은 UI를 만드는데 엄청 기여해요.
1. Safari로 보게되면 스크롤 박스가 우측 하단에 생깁니다.
2. 트랙패드를 벗어난 환경에서 스크롤을 관리하면, 스크롤 영역이 생기면서 모든 Padding이 생기며 밀리게됩니다.
그래서 overflow값은 보통 오버플로우가 발생하는 방향으로, (여기서는 `overflow-x`) `auto`값을 줘야합니다.
스크롤 할 게 없어도 스크롤바가 생겨있거든요 ㅋㅋ

그리고 이 스크롤이 생기는 컨테이너의 태그가 `span`인 것도 수정이 필요해보여요.

2022-11-01 13:23 UTC, ChoiWonBeen commented on src/components/editor/TextEditor/index.tsx
>            저장
저장버튼이 UI상 모바일에서 오른쪽에 여백이 없는데 의도된 것은 아닐거같아요!

2022-11-01 13:23 UTC, ChoiWonBeen commented on src/components/editor/TextEditor/AddImage/ImageItem.tsx
> +        alt="이미지"
불필요한 alt값인 것 같네요.
스크린리더는 `type=image`를 보고 "이미지"를 뒤에 붙이기 때문에 "이미지이미지" 처럼 읽히는 문제가 발생할겁니다.

2022-11-01 13:23 UTC, ChoiWonBeen commented on src/components/editor/TextEditor/index.tsx
> +import AddImage from './AddImage/index';
음? 요건 왜 추가된건가요?

2022-11-08 15:30 UTC, D0Dam commented on src/components/editor/TextEditor/index.tsx
> +import AddImage from './AddImage/index';
앗.. 삭제하겠습니다.

2022-11-08 15:32 UTC, D0Dam commented on src/components/editor/TextEditor/AddImage/ImageItem.tsx
> +        alt="이미지"
아 그렇군요.. 그렇다면 eslint 때문에 alt값을 주기는 해야하니 일단 빈 공간의 alt 값을 선언해 놓아야겠네요.😢

2022-11-08 15:39 UTC, D0Dam commented on src/components/editor/TextEditor/index.tsx
>            저장
@ChoiWonBeen 
오른쪽에 여백이 없다는 게 어떤 말일까요? 지금 확인해보니 여백은 있지만 문제는   moblie으로는 모든 UI를 확인 할 수 있게, 스크롤이 안생기게끔 구현해 놓았었는데, 수정을 하면서 스크롤이 생겨서 모든 UI를 한 화면에 보여주지 못하는 문제를 확인했습니다. 이 부분 수정하면서 다시 한번 확인해 볼게요.

2022-11-08 16:02 UTC, D0Dam commented on src/components/editor/TextEditor/TextEditor.module.scss
>    overflow: scroll;
이게 다시 확인해보니 문제가 좀 심각하네요.. 애초에 이 방법으로 슬라이드를 하게 되면 사진이 overflow가 되면 스크롤바가 생겨서 사진이 전부 위로 조금씩 밀려나게 됩니다. 제 기준에서는 이것도 굉장히 불편하네요.. `display: none`을 해버리면 까끔해지기는 하네 트랙패드 이외의 환경에서 조절할 수 없다는 것이 또 문제가 되구요. 일단 사진이 밀려나지 않게끔 수정을 해보도록 하겠습니다.

2022-11-20 08:50 UTC, ChoiWonBeen commented on src/components/editor/TextEditor/index.tsx
>            저장
다시 보니 문제 없네요. 스크롤때문이었던거같아요 👍

2022-11-20 09:37 UTC, ChoiWonBeen requested changes
몇가지 더 리뷰했어요~
거의 다 완료된 것 같네요 ㅋㅋ

2022-11-20 09:37 UTC, ChoiWonBeen commented on src/components/editor/TextEditor/AddImage/index.tsx
> +      <div className={styles.imageContainer}>
다른 기능들은 전부 `image-container` 처럼 `kebab-case`로 작성했을거예요. 이부분 확인해서 수정해주세요~

2022-11-20 09:37 UTC, ChoiWonBeen commented on src/components/editor/TextEditor/SlideToolBox.tsx
> +  const [showed, show, hide] = useBooleanState(false);
뭔가 `showed`라는 표현이 어색한 것 같아요 ㅋㅋ
`visible`같은 표현은 어떨까요?

2022-11-20 09:37 UTC, ChoiWonBeen commented on src/components/editor/TextEditor/hooks/useImageList.ts
> +    else setImageList((prev) => prev && [...prev, data?.data.message]);
이부분이 목업 로직이라 수정할 필요는 없겠지만, `refetch()`직후 `setState`가 바로 적용되지 않을거라 보이는 화면과 state가 다를 것으로 예상되네요.
Network 탭을 확인해보면, 시작과 동시에 `random`을 호출합니다.
보이는 것이 state보다 한개 더 적은 상태인거죠.
`imageList` 가 1개일 때 0개의 사진이 보이고, `addImage()`를 호출해 2개가 되었을 때 1개가 보일 거예요.

2022-12-16 13:06 UTC, hanagertrudekim reviewed
궁금한점 하나 리뷰했는데 확인부탁드립니다 ㅎㅎ

2022-12-16 13:06 UTC, hanagertrudeKim commented on src/utils/hooks/useBooleanState.ts
>    const toggle = useCallback(() => setValue((x) => !x), []);
개인적으로 useCallback을 적용하시게 된 기준점이 무엇인지 궁금합니다

2022-12-30 13:39 UTC, D0Dam commented on src/utils/hooks/useBooleanState.ts
>    const toggle = useCallback(() => setValue((x) => !x), []);
`useCallback`은 함수를 재사용한다는 특징이 있습니다.
이 당장으로써는 눈에 띄는 최적화는 없을 수 있지만, 컴포넌트 초기화에 있어서 함수를 재사용하는 것은 성능 향상에 꼭 필요합니다.
컴포넌트에서 `props`가 바뀌지 않았으면리액트의 가상 돔에 새로 렌더링 하는 작업을 배제할 수 있게 됩니다.
이를 통해서 컴포넌트의 결과물 자체를 재사용하기도 하고, 이 최적화 과정을 이뤄내기 위해서는 해당 컴포넌트에서 함수를 재활용하는 것이 필수적입니다.

컴포넌트가 꼭 재사용이 된다는 보장이 없다면 무의미한 코드일 수 있으나, `useBooleanState`를 사용하게 되는 컴포넌트가 다양할 것이라고(그만큼 범용적일 것이다)판단했고, 재사용 가능한 컴포넌트를 만들 때 충분히 사용될 수 있다고 판단하여 `useCallback`을 씌워 주었습니다.

2023-01-02 01:32 UTC, hanagertrudekim commented on src/utils/hooks/useBooleanState.ts
>    const toggle = useCallback(() => setValue((x) => !x), []);
재사용이 많이 될수록 `useCallback`의 장점을 보니, `useBooleanState`의 경우 적용점이 적절하다고 생각이 드네요. 답변 감사합니다 ㅎㅎ

2023-01-02 02:42 UTC, D0Dam commented on src/components/editor/TextEditor/hooks/useImageList.ts
> +    else setImageList((prev) => prev && [...prev, data?.data.message]);
우선, `refetch()`를 `setState`를 한 이후에(해당 함수의 마지막에) 하는 것으로 수정을 하겠습니다.
현재 목업으로 가지고 온 서비스가 종료되서 503 에러가 발생하고 있는데, 이는 해당 api가 나오면 대입하면서 추가적으로 손을 봐야할 것 같습니다.

2023-01-02 03:24 UTC, ChoiWonBeen approved these changes
고생하셨어요~ 짜잘한 수정 한가지 변경하고 병합해주셔도 될것같아요.
다음작업으로는 `ImageApi`라고 이름지어진 부분을 실제 File Input으로 변경하면서 + 서버의 파일업로드 API를 활용해 이를 변환하는 선작업을 해두면 적절할 것 같은데, 아직 파일업로드 API가 없는 것 같아서..
백엔드쪽에 오늘 주간회의동안 요청드려볼게요.

2023-01-02 03:24 UTC, ChoiWonBeen commented on src/components/editor/TextEditor/SlideToolBox.tsx
> +          onClick={visible ? hide : show}
`useBooleanState` 에 toggle을 만들어두신 만큼 활용하는 편이 좋아보여요.

```suggestion
          onClick={toggle}
  // ...선언부에 추가
  // const [visible, show, hide, toggle] = useBooleanState(false);
```

2023-01-03 01:00 UTC, hanagertrudekim approved these changes

2023-01-03 01:09 UTC, kimeodml approved these changes

2023-01-03 01:11 UTC, merged