Origin/feature/#28 [Auth] 로그인 & 회원가입 UI 수정
BCSDLab/TEMP_PROJECT_FE pull request #31
Opened 2022-10-23 14:25 UTC by kimeodml

## [Copy here issue number] request

- 로그인과 회원가입의 `margin`을 노트북 화면에 맞게 수정했습니다.
- 따라서 figma에 나와있는 값과 다를 수가 있습니다.  

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [ ] Docs updated for breaking changes

### Screenshot
![image](https://user-images.githubusercontent.com/88065770/197393915-ebf6b269-3a57-4b2d-b352-45833b942c96.png)
![image](https://user-images.githubusercontent.com/88065770/197393939-edc4aaf4-e75f-4dde-ba82-ea2edc5ed123.png)
![image](https://user-images.githubusercontent.com/88065770/197393958-b0daa1ab-d904-4ca3-ae4f-42e4c79a03ce.png)

2022-10-28 08:04 UTC, D0Dam approved these changes
수고하셨습니다.

2022-10-28 14:05 UTC, hanagertrudekim reviewed
이번 이슈에 대해 저도 통일되어야한다는 필요성을 느꼈었는데 잘 해결해주셨네요 :)  
혹시 피그마에 나와있는 기준이 아니라면 노트북의 어떤 기준에 맞추었는지 알수있을까요?

2022-11-02 11:42 UTC, kimeodml commented
> 이번 이슈에 대해 저도 통일되어야한다는 필요성을 느꼈었는데 잘 해결해주셨네요 :) 혹시 피그마에 나와있는 기준이 아니라면 노트북의 어떤 기준에 맞추었는지 알수있을까요?

죄송합니다! 커밋 지금 확인했네요. 제 노트북 15인치를 기준으로 잡고 했습니다. 버튼이나 input과 같이 고정된 높이를 가진 부분은 수정하지 않고 margin만을 수정하면서 전체적으로 봤을 때 괜찮은지를 기준으로 놓고 했습니다.

2022-11-02 16:05 UTC, ChoiWonBeen requested changes
오 변경하니 깔끔하고 좋네요.
근데 맨 하단 Copyright의 하단 마진이 필요해보여요. 확대하고 보니 딱 붙는게 어색하네요.
적당히 20px정도만 넣어줘도 훨씬 깔끔할 것 같아요~
그리고 PR 컨텐츠의 제목 부분도 신경써주세요!`[Copy here issue number] request`

2022-11-03 04:17 UTC, kimeodml commented
> 오 변경하니 깔끔하고 좋네요. 근데 맨 하단 Copyright의 하단 마진이 필요해보여요. 확대하고 보니 딱 붙는게 어색하네요. 적당히 20px정도만 넣어줘도 훨씬 깔끔할 것 같아요~ 그리고 PR 컨텐츠의 제목 부분도 신경써주세요!`[Copy here issue number] request`

추가했습니다. [cebd739](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/31/commits/cebd73911b2c7f6edd122252419c4bb2f5b02dcf)

2022-11-03 04:25 UTC, ChoiWonBeen approved these changes

2022-11-03 12:31 UTC, merged