Feature/#10
BCSDLab/TEMP_PROJECT_FE pull request #32
Opened 2022-10-30 16:05 UTC by jaewoogwak

## [feature/#10 검색 컴포넌트 리팩터링] request

**기능의 변화는 없고, 각 요소를 컴포넌트로 분리했습니다.** 

---

검색 컴포넌트 내에서 UI 단위로 컴포넌트를 구분하였습니다.

처음 검색 컴포넌트를 설계할때는 다른 곳에서 재사용되지 않을거라고 생각해서 `index.tsx`에 모든 로직을 작성했습니다.

그러다가 컴포넌트 설계에 있어 생각이 점점 바뀌었고 가독성 등의 요소를 고려하여 UI 단위로 컴포넌트 분리했습니다.

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [ ] Docs updated for breaking changes

### Screenshot

2022-10-31 05:13 UTC, D0Dam reviewed
수고하셨습니다. 제 개인적인 의견을 적어놓았는데 참고만 해주세요!

2022-10-31 05:13 UTC, D0Dam commented on src/pages/Search/components/SearchInput.tsx
> +        placeholder="검색어를 입력해주세요"
사소한 부분이긴 하지만 `placeholder`의 문구 마지막에 마침표를 찍어주시면 좋을 것 같습니다!

2022-10-31 05:13 UTC, D0Dam commented on src/pages/Search/index.tsx
>    } = useSearchForm(currentMode || 'trending');
지극히 개인적인 의견이지만 부모에서 `useSearchForm` 값들을 props로 전달해가면서 관리하기 보다 useSearchForm을 좀 더 추상화된 훅으로 나누어 각각의 파일에 훅을 정의해 사용할  것 같습니다.  그렇게 되면 각각의 컴포넌트가 좀 더 재활용성이 높아질 것도 같고요!

2022-10-31 07:02 UTC, jaewoogwak commented on src/pages/Search/components/SearchInput.tsx
> +        placeholder="검색어를 입력해주세요"
피그마에서 확인해보니 마침표가 있네요 수정하겠습니당

2022-10-31 07:07 UTC, jaewoogwak commented on src/pages/Search/index.tsx
>    } = useSearchForm(currentMode || 'trending');
좋은 의견이네요 useSearchForm에서 mode와 text로 훅을 나눠보겠습니다

2022-10-31 07:13 UTC, jaewoogwak commented on src/pages/Search/index.tsx
>    } = useSearchForm(currentMode || 'trending');
음 근데 현재 검색 컴포넌트에서 (onFocus, onBlur로 구현한) 검색어 관련 리스트를 클릭하면 상세 페이지로 넘어가는 부분에서 제대로 작동하지 않는 현상이 있어서 이부분을 먼저 고쳐야할듯 하네요

일단 현재 PR은 컴포넌트만 나눈 것이니 머지하고 이후 상세 페이지 구현 부분에서 해결하고 추상화 부분도 적용해야할듯 싶네요

2022-11-02 08:57 UTC, ChoiWonBeen requested changes

2022-11-02 08:57 UTC, ChoiWonBeen commented on .gitignore
> +.env
아래 `.env`가 이미 있는데 따로 추가하신 이유가 있나요??

2022-11-02 08:57 UTC, ChoiWonBeen commented on src/pages/Search/components/Recommend.tsx
> +function Recommend() {
컴포넌트로 나눠서 가독성을 올린것은 좋은데, `Recommend` 라는 이름이 자꾸 걸리네요 ㅋㅋ
나중에 추천친구 같은 부분도 있을거고, 뭔가 더 나은 이름이 있을 것 같다는? 생각이 드네요 ㅋㅋ gitignore 지우면서 고민해보시면 좋을거같아요.

2022-11-02 12:51 UTC, jaewoogwak commented on .gitignore
> +.env
앗 못 보고 위에 추가해버렸네요 수정하겠습니다~

2022-11-02 12:58 UTC, jaewoogwak commented on src/pages/Search/components/Recommend.tsx
> +function Recommend() {
RecommendationText도 뭔가 맘에 안들어서... ㅋㅋㅋ 일단 Recommendation으로 바꾸고 적용했습니다~ 계속 고민해보고 떠오르는 이름 있으면 적용해볼게요

2022-11-02 13:57 UTC, ChoiWonBeen approved these changes

2022-11-02 13:58 UTC, merged