Feature/#11
BCSDLab/TEMP_PROJECT_FE pull request #38
Opened 2022-12-05 14:50 UTC by jaewoogwak

## [Feature#11] 검색 상세 페이지 추가

검색 상세페이지 추가했습니다.

상세 페이지에서 먼저 검색어에 따른 상점 렌더링부터 구현했습니다. 다른 기능은 향후 추가할 예정입니다.
관련 검색어는 백엔드 API가 아직 구현되지 않아서 임의의 정적 데이터 사용하였습니다.

주요 변경 사항으로는
- 검색 상세 페이지 추가에 따른 `useFetchShops` 훅 추가
-  `useFetchShops`는 좌표 정보를 필요로 하기 때문에 `useGeolocation` 훅도 추가
- 향후 좌표 정보가 `/` 경로에서 필요하기 때문에 `useGeolocation` 훅은 변경될 수 있음
- 파일 위치 변경: `/pages`에 `/Search/index.tsx`와 스타일시트만 남기고 컴포넌트는 `/components` 폴더로 이동했습니다.

폴더 위치 변경으로 수정된 파일이 많아서 `SearchQueryItemList`와 `useFetchShops` 위주로 봐주시면 될듯합니다. 

다른 변경사항 피드백도 환영입니다~

### Screenshot
<img width="863" alt="image" src="https://user-images.githubusercontent.com/62415600/205664171-a94d613c-11dd-4549-acd1-9bfd94bc2897.png">

![searchDetailGIF](https://user-images.githubusercontent.com/62415600/205666193-65348bee-9fa6-43a3-af30-4b8fff74bfec.gif)

2022-12-06 07:17 UTC, ChoiWonBeen requested changes
수고했어요. 수정사항 남겼으니 확인해주세요~

2022-12-06 07:17 UTC, ChoiWonBeen commented on src/api/search/searchApiClient.ts
> +const AUTH_TOKEN = sessionStorage.getItem('accessToken') || '';
테스트해보셨을테지만, 호출을 전역으로 해버려서 로그인 직후 해당 값을 갱신하지 못하고 에러가 납니다.
`user`쪽 참고하셔서 함수의 호출 시간에 accessToken을 확인할 수 있도록 바꿔주세요.

2022-12-06 07:17 UTC, ChoiWonBeen commented on src/api/search/index.ts
> +}
React-Query를 사용해 만든 hook에 `~Query`라는 명칭을 꼭 붙이진 않아도 될 것 같아요.
Hook을 사용하는 입장에서는 Trendings를 받아오는 것만이 중요하니, `useTrandings`나 `useTrandingList`는 어떨까요?

2022-12-06 07:17 UTC, ChoiWonBeen commented on src/api/search/index.ts
> +}
기존의 useQuery가 반환하는 값에서 더 한정시켜서 얻을 수 있는 장점이 없어보여요.
그리고 user쪽이랑 비교하게 되는데, 그쪽은 함수 표현식으로 작성이 되어있네요? `utils/hooks`는 또 선언식이고..
컨벤션을 정할 필요가 있어보이네요 ㅋㅋ 
아, 그리고 Query Key가 누락됐다고 생각해요.
```suggestion
export const useShopQuery = (place_id: string) => useQuery(['shop', place_id], () => searchApi.get(`/shop?place_id=${place_id}`));
```

2022-12-06 07:17 UTC, ChoiWonBeen commented on src/components/Search/components/RollingBanner.tsx
> +        <li className={styles['search-banner__tag']}>{trendings.map((tag) => `#${tag}`).join(' ')}</li>
TRENDING이 클릭이 되면 해당 키워드로 검색되게 만드는 것은 안될까요? ㅋㅋㅋ

2022-12-06 07:17 UTC, ChoiWonBeen commented on src/components/Search/components/SearchQueryItem.tsx
> +const DEFAULT_URL = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQMAAADCCAMAAAB6zFdcAAAAYFBMVEXDw8MAAABwcHDHx8eKioqkpKS8vLzGxsatra3KysqQkJCenp6AgIB3d3dra2u3t7dZWVlMTEyysrIsLCxTU1NDQ0OUlJQhISEyMjJl
이건.. 바꿔야 할 것 같네요 ㅋㅋㅋ
assets에 담거나, 백엔드에 물어봐서 S3에 업로드가 가능하다면 url을 받아서 사용하는게 좋을거예요.

2022-12-06 07:17 UTC, ChoiWonBeen commented on src/components/Search/components/SearchQueryItem.tsx
> +  const { data } = shop;
뭔가 좀 이상한걸요?
```suggestion
function SearchQueryItem(props : Props) {
  const defaultImage = DEFAULT_URL;
  const { shop } = props;
```

2022-12-06 07:17 UTC, ChoiWonBeen commented on src/components/Search/components/SearchQueryItemList.tsx
> +              : data?.data.content.map((shop: Props) => <SearchQueryItem key={shop.shopId} data={shop} />)}
props를 다른 이름으로 줄 필요가 없을 것 같아요.
```suggestion
              : data?.data.content.map((shop: Props) => <SearchQueryItem key={shop.shopId} shop={shop} />)}
```

2022-12-06 07:17 UTC, ChoiWonBeen commented on src/components/Search/components/SearchQueryItemList.tsx
> +
불필요한 여백은 지워주세요~

2022-12-06 07:17 UTC, ChoiWonBeen commented on src/components/Search/components/SearchQueryItemList.tsx
> +              : data?.data.content.map((shop: Props) => <SearchQueryItem key={shop.shopId} data={shop} />)}
lint를 반드시 지워야 할 문장 길이는 아닐거라고 생각해요.
```suggestion
          {isFetching
            ? <LoadingView />
            : data?.data.content.map((shop: Props) => (
              <SearchQueryItem key={shop.shopId} data={shop} />
            ))}
```

2022-12-06 07:17 UTC, ChoiWonBeen commented on src/pages/Search/index.tsx
> +import Navigation from '../../components/Search/components/Navigation';
되도록 절대경로를 사용해주세요~
```suggestion
import Suggestion from 'components/Search/components/Suggestion';
import Navigation from 'components/Search/components/Navigation';
```

2022-12-06 11:03 UTC, jaewoogwak commented on src/api/search/index.ts
> +}
확실히 `~Query`가 없는게 낫네요 👍 

반영하겠습니다~

2022-12-06 11:15 UTC, jaewoogwak commented on src/components/Search/components/SearchQueryItem.tsx
> +const DEFAULT_URL = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQMAAADCCAMAAAB6zFdcAAAAYFBMVEXDw8MAAABwcHDHx8eKioqkpKS8vLzGxsatra3KysqQkJCenp6AgIB3d3dra2u3t7dZWVlMTEyysrIsLCxTU1NDQ0OUlJQhISEyMjJl
svg로 뺀다는걸 잊었네요 하하.. `assets`에 svg로 담았고 추후 S3 업로드가 가능하면 url 받아서 사용하도록 하겠습니다~

2022-12-06 11:20 UTC, jaewoogwak commented on src/components/Search/components/SearchQueryItemList.tsx
> +              : data?.data.content.map((shop: Props) => <SearchQueryItem key={shop.shopId} data={shop} />)}
이렇게 해보려고 했는데 자꾸 빨간줄을 긋길래 우선 lint 지웠었는데
 확인해보니 `<div>` 바깥에 불필요한 중괄호가 있었네요 ㅋㅋㅋ😅

수정하겠습니다~

2022-12-06 11:30 UTC, jaewoogwak commented on src/pages/Search/index.tsx
> +import Navigation from '../../components/Search/components/Navigation';
여기 말고도 다른 부분도 상대경로로 임포트하는게 많았네요 😂 
다른 파일도 전부 절대경로로 적용하겠습니다~

2022-12-06 11:44 UTC, jaewoogwak commented on src/components/Search/components/SearchQueryItem.tsx
> +  const { data } = shop;
shop 받는게 이상하네요...ㅋㅋㅋㅋ 수정하겠습니다

2022-12-06 11:45 UTC, jaewoogwak commented on src/components/Search/components/SearchQueryItemList.tsx
> +              : data?.data.content.map((shop: Props) => <SearchQueryItem key={shop.shopId} data={shop} />)}
위에 코멘트랑 같이 수정했습니다~

2022-12-06 11:56 UTC, jaewoogwak commented on src/components/Search/components/RollingBanner.tsx
> +        <li className={styles['search-banner__tag']}>{trendings.map((tag) => `#${tag}`).join(' ')}</li>
ㅋㅋㅋㅋ 이부분은 열심히 고민 좀 해봐야할듯 합니다..ㅜㅜ

2022-12-06 13:18 UTC, SimYunSup requested changes, later dismissed
컴포넌트 분리 방식과 파일 구조에 대해 다시 생각해보심이 좋습니다.
`static`폴더는 `components` 안에 있는 이유를 다시 생각해보시고, style과 component가 따로 분리되어있는 현재 상태를 재구성해야 할 것 같습니다.
컴포넌트 분리가 너무 잘게 되어있습니다. 아토믹 패턴을 적용할 때는 좋은 분리 방식이 될 수도 있겠지만 현재 아토믹 패턴을 적용하고 있지 않고 이는 코드 가독성에 큰 영향을 줍니다. 한 번 다시 생각해보세요.

2022-12-06 13:18 UTC, SimYunSup commented on src/api/search/index.ts
> +    isLoading, isError, trendings,
```suggestion
    isLoading, isError, data: trendings,
```
이름은 일반적으로 지어주세요.

2022-12-06 13:18 UTC, SimYunSup commented on src/api/search/searchApiClient.ts
> +  baseURL: `${API_PATH}:443`,
포트번호 빼도 됩니다.

2022-12-06 13:18 UTC, SimYunSup commented on src/components/Search/RollingBanner.tsx
> +    </div>
component 이름은 `RollingBanner`인데 Block이름은 `search-banner`인 이유가 있나요?

2022-12-06 13:18 UTC, SimYunSup commented on src/components/Search/SuggestionItem.tsx
> +    <Link to={`/search/${item.title}`} style={{ color: 'black', textDecoration: 'none' }}>
style로 css를 대체한 이유라도 있을까요?

2022-12-06 13:18 UTC, SimYunSup commented on src/utils/hooks/useGeolocation.ts
> +    navigator.geolocation.getCurrentPosition(setLocation, onGeoError, options);
success callback을 간단하게 두어 중첩 객체를 저장해야 할 필요가 있었나요?

2022-12-06 13:18 UTC, SimYunSup commented on src/api/search/index.ts
> +    isFetching, isError, data, refetch,
data를 중첩 객체에서 꺼내도 되지 않을까요?

2022-12-06 13:18 UTC, SimYunSup commented on src/components/Search/SearchQueryItemList.tsx
> +export default SearchQueryItemList;
해당 컴포넌트가 모두 나눠져 있어서 보기도 힘들고 굳이 나누어진 이유를 찾지 못하겠습니다. 파일 구조에 대해 다시 생각해보시죠.

2022-12-07 01:30 UTC, jaewoogwak commented on src/utils/hooks/useGeolocation.ts
> +    navigator.geolocation.getCurrentPosition(setLocation, onGeoError, options);
아하 현재 좌표만 필요하니 중첩 객체 내부의 latitude/longitude 값만 빼내도록 로직을 추가하란 것인가요?

2022-12-07 01:31 UTC, jaewoogwak commented on src/utils/hooks/useGeolocation.ts
> +    navigator.geolocation.getCurrentPosition(setLocation, onGeoError, options);
`location`을 받아와서 위도, 경도 값을 뻬올 생각만 했는데, 훅에서 처리해줄 생각을 안했네요..!

2022-12-07 01:42 UTC, jaewoogwak commented on src/api/search/index.ts
> +    isLoading, isError, trendings,
data로 수정하니 확실히 롤링배너 컴포넌트에 넘길때 이전 `trending=trendings`보다 `trendings=data`가 낫네요
그런데 나중에 `{isLoading, data}`처럼 값을 destructuring 하는 훅이 추가될 경우 일반적인 이름인 `data`가 겹치게 될텐데 이런 경우는 어떻게 대처하면 좋을까요?

2022-12-07 01:46 UTC, jaewoogwak commented on src/components/Search/RollingBanner.tsx
> +    </div>
다른 컴포넌트의 블록 네이밍을 `search-`로 하다보니 그렇게 했습니다. 
search-banner는 확실히 롤링 배너의 느낌을 주진 못하네요.

2022-12-07 01:52 UTC, jaewoogwak commented on src/components/Search/SuggestionItem.tsx
> +    <Link to={`/search/${item.title}`} style={{ color: 'black', textDecoration: 'none' }}>
따로 없습니다..  컴포넌트 만들면서 스타일을 바로 적용하고 수정하지 않았네요😅

우선 수정하고 좀 더 적절한 BEM 네이밍을 고민해봐야겠네요

2022-12-07 01:53 UTC, jaewoogwak commented on src/components/Search/SearchQueryItemList.tsx
> +export default SearchQueryItemList;
넵 컴포넌트가 많이 분리되어 있어서 구분이 힘들다고 느꼈습니다. 

이 부분에 대해선 다시 고민해보도록 하겠습니다

2022-12-07 03:11 UTC, ChoiWonBeen commented on src/api/search/index.ts
> +    isLoading, isError, trendings,
저는 보통 사용하는 쪽에서 필요한 이름으로 바꿔서 써왔어요.
```tsx
    const { data: isTrendingList, isLoading } = useTrandingList();
```

2022-12-07 04:02 UTC, jaewoogwak commented on src/api/search/index.ts
> +    isLoading, isError, trendings,
@ChoiWonBeen  오호 훅이 여러개로 되면 사용하는 쪽에서 `data`의 이름을 바꿔서 쓰면 되겠네요 👍

2022-12-10 14:39 UTC, kimeodml commented on src/pages/Search/components/RelatedSearches/RelatedSearches.tsx
> +          <RelatedItem key={item.id} item={item} />
현재 빈칸이 아닐 경우 `map`을 이용해 item들을 다 불러오는데 `filter`를 이용해 일치하는 값만 불러냈으면 좋겠습니다

2022-12-11 09:42 UTC, ChoiWonBeen requested changes

2022-12-11 09:42 UTC, ChoiWonBeen commented on src/pages/SearchDetails/index.tsx
> +function SearchDetailList() {
`./SearchDetails.tsx` 파일과 동일한 파일이 남아있네요. 파일 복사하다가 지우는 걸 잊은 것 같습니다.
그리고 컴포넌트 이름도 파일 / 레포지토리명과 일치한지 한번씩 확인해야 할 것 같아요.

2022-12-11 09:42 UTC, ChoiWonBeen commented on src/pages/Search/components/NavBar/NavigationBar.tsx
> +export default function NavigationBar({ searchQuery = '검색' }: Props) {
`/NavBar` 폴더 안에 있기때문에 파일명을 일치시키고, `index.tsx`로 작성을 통일하는 게 좋아보여요. 이 컴포넌트를 import하는 부분에서 파일명이 어색할거예요.

2022-12-11 09:42 UTC, ChoiWonBeen commented on src/pages/SearchDetails/SearchItems.tsx
> +import { ReactComponent as DefaultImage } from 'assets/svg/search/default-image.svg';
svg파일을 보니깐 좀 과하네요.
svg는 선과 점으로 그래픽을 표현한 방식이라 지금 받아오는 다양학 색의 이미지같은 경우는 코드량이 수천줄을 넘어갈겁니다.
svg가 아닌, 이미지로 저장해주세요.

2022-12-11 12:10 UTC, jaewoogwak commented on src/pages/Search/components/RelatedSearches/RelatedSearches.tsx
> +          <RelatedItem key={item.id} item={item} />
이 부분은 아직 백엔드 측에서 연관검색어 관련 API 개발이 되지 않아서 우선 임의의 데이터를 모두 보여주도록 했는데요 나중에 API 연결하면 문제가 되는 코드가 되겠네요😲 `filter` 메서드로 변경하겠습니다~

2022-12-11 12:13 UTC, jaewoogwak commented on src/pages/SearchDetails/index.tsx
> +function SearchDetailList() {
동일한 파일이 남아있었군요.. 삭제하겠습니다~~

2022-12-11 12:19 UTC, jaewoogwak commented on src/pages/Search/components/NavBar/NavigationBar.tsx
> +export default function NavigationBar({ searchQuery = '검색' }: Props) {
현재 `NavigationBar`가 `components/NavBar` 폴더 안에 있어서 `/NavBar` 폴더 안에 `index.tsx`로 작성해야하는데, `NavigationBar`를 `/components` 경로 바로 아래로 빼는게 어떨까요? 아래 `/RelatedSearches`안의 `RelatedItem`, `RelatedSaerches`도 마찬가지구요 

`/Auth`를 보니 `FindIDPassword`, `Login` 같이 페이지 단위로 구분했다고 느꼈는데, 검색 컴포넌트의 경우 `NavigationBar`나 `RelatedItem`은 검색 페이지 안에 속하는 컴포넌트니깐 `/Search/components`로 빼는게 좋아보이는데 어떤가요?

2022-12-11 12:23 UTC, ChoiWonBeen commented on src/pages/Search/components/NavBar/NavigationBar.tsx
> +export default function NavigationBar({ searchQuery = '검색' }: Props) {
지금 이미 `/Search/components` 안에 있지 않나요?
폴더로 만드는 이유는 따로 해당 파일에 적용해야할 스타일링을 같이 넣기 폴더로 구분하는게 깔끔할 수 있다는 생각이 들어요.
`Search/components/NavigationBar/index.tsx`
`Search/components/NavigationBar/NavigationBar.module.scss`
처럼 생각했죠.

저는 폴더명이 `NavBar`임에 반해, 컴포넌트명이 `NavigationBar`였던 점을 주로 언급한거기도 하구요.

2022-12-11 12:25 UTC, ChoiWonBeen commented on src/pages/Search/components/NavBar/NavigationBar.tsx
> +export default function NavigationBar({ searchQuery = '검색' }: Props) {
지금 생각해보니 style파일도 `index.module.scss`여도 될 것 같긴 하네요.
왜 컴포넌트명으로 시작했지...ㅋㅋㅋㅋ 아무튼 깔끔하게 통일되고 정리된 느낌을 줄 수 있다면 환영입니다.

2022-12-11 12:28 UTC, jaewoogwak commented on src/pages/Search/components/NavBar/NavigationBar.tsx
> +export default function NavigationBar({ searchQuery = '검색' }: Props) {
> 지금 이미 /Search/components 안에 있지 않나요?
폴더로 만드는 이유는 따로 해당 파일에 적용해야할 스타일링을 같이 넣기 폴더로 구분하는게 깔끔할 수 있다는 생각이 들어요.

넵 저도 이렇게 생각해서 분리했는데 `Auth`를 보니 뭔가 페이지 단위로 분리한거 같다고 생각해서 그랬네요
`/components` 하위 폴더들 각각 `index.tsx`로 변경하겠습니다~

2022-12-11 12:51 UTC, jaewoogwak commented on src/pages/Search/components/NavBar/NavigationBar.tsx
> +export default function NavigationBar({ searchQuery = '검색' }: Props) {
> 지금 생각해보니 style파일도 `index.module.scss`여도 될 것 같긴 하네요. 왜 컴포넌트명으로 시작했지...ㅋㅋㅋㅋ 아무튼 깔끔하게 통일되고 정리된 느낌을 줄 수 있다면 환영입니다.

오 그리고 이 부분은 이슈 만들어서 추진해도 괜찮을거같아요 style 파일 경로 작성을 좀더 쉽게 해주지 않을까싶네요

2022-12-11 13:18 UTC, jaewoogwak commented on src/pages/SearchDetails/SearchItems.tsx
> +import { ReactComponent as DefaultImage } from 'assets/svg/search/default-image.svg';
수정했습니다~ asset 폴더에 image가 아직 없어서 폴더 새로 생성했습니다

[cafe515](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/38/commits/cafe515af657a332c47a6f24801a38ec1dd46d72)

2022-12-12 03:05 UTC, jaewoogwak commented on src/api/search/searchApiClient.ts
> +const AUTH_TOKEN = sessionStorage.getItem('accessToken') || '';
`interceptors`로 요청할 때 accessToken 확인하도록 수정했습니다~
추후 검색 컴포넌트에서 요청은 토큰이 필요하지 않을 예정이기 때문에 해당 변경사항 적용되면 인터셉터도 제거하도록 하겠습니다

[b2d9a8a](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/38/commits/b2d9a8afb29099a379894092ac5601252b0bc5e0)

2022-12-12 04:09 UTC, jaewoogwak commented on src/api/search/index.ts
> +}
맞네요 `/shop` 요청은 하나의 상점에 대한 요청이라 상점의 `place_id`가 변하면 새로운 요청을 해줘야 하니... 
쿼리 키에 대해 다시 공부하는 좋은 시간이었습니다 ㅋㅋㅋ 
쿼리 키 추가하겠습니다~~~

2022-12-14 09:11 UTC, jaewoogwak commented on src/api/search/index.ts
> +    isFetching, isError, data, refetch,
중첩 객체 꺼내는 로직 추가했습니다. 컴포넌트에서 중첩 객체를 풀어줄 필요가 없으니 컴포넌트가 사용할 데이터만 훅에서 주면 되겠네요👍

2022-12-14 14:16 UTC, ChoiWonBeen requested changes
fetcher와 타입 정의 / fetcher를 가져와 useQuery로 데이터 가공 /  해당 훅을 활용하는 단계가 모호한 것 같아요. 이번에 PR올린 회원가입 관련 로직을 살펴봐주세요

2022-12-14 14:16 UTC, ChoiWonBeen commented on src/pages/SearchDetails/index.tsx
> +  const { isFetching, data: shops } = useFetchShops(searchQuery as string);
`string | undefined` 타입을 `string`으로 강제하는 것보다, Non-null assertion operator(말이 길지 그냥 느낌표)를 통해 nullish 하지 않다고 단언할 수 있습니다.
```suggestion
  const { isFetching, data: shops } = useFetchShops(searchQuery!);
```

2022-12-14 14:16 UTC, ChoiWonBeen commented on src/pages/SearchDetails/index.tsx
> +            : shops.map((shop: Props) => (
`shop`의 타입을 지정하기보다, shops가 이미 `Props[]`로 이루어져 있어야 할 것 같습니다.
근데 보고나니 Props라는 이름도 어울리지 않네요. 얜 props가 아니니깐요.

2022-12-14 14:16 UTC, ChoiWonBeen commented on src/api/search/index.ts
> +export const useFetchShops = (searchQuery: string) => {
이 파일은 fetcher를 모아두는 파일이지, hooks를 모아두는 파일이 아닙니다.
fetcher를 분리해 타입과 에러 핸들링을 정의하고, 여기에 모아둔 fetcher를 통해 useQuery를 사용한 hook을 각각으로 만들면 될 것 같아요. `../user/index.ts` 파일을 참고해주세요.

2022-12-14 14:16 UTC, ChoiWonBeen commented on src/pages/SearchDetails/components/SearchItems.tsx
> +              <div className={styles['search-item__status--distance']}>내 위치로부터 23m</div>
해당 정보들은 API의 Response를 받아다 써야 할 것 같은데 shop list response에 해당 프로퍼티를 추가해달라고 요청하셨나요?

2022-12-14 14:16 UTC, ChoiWonBeen commented on src/pages/SearchDetails/components/SearchItems.tsx
> +      <img alt="가게 이미지 없음" src={DefaultImage} />
이미지도 Response와 조건에 맞춰 구분되게끔 작성되어야 할 것 같아요.

2022-12-14 14:16 UTC, ChoiWonBeen commented on src/pages/Search/index.tsx
> +  const currentMode : CurrentMode = searchParams.get('mode') || MODE.trending;
searchParams를 쓰는 코드가 없어보이는데 어디서 사용하고, `MODE` 상수는 각각 무엇을 의미하나요?

2022-12-14 14:16 UTC, ChoiWonBeen commented on src/pages/Search/index.tsx
> +    document.addEventListener('click', changeMode);
`as` 로 타입을 단언하는 것이 오류를 불러올 수 있다고 생각합니다. 
해당 함수는 document의 click 이벤트에 추가되는데 target의 id가 'searchBarInput'이라는 조건도 잘 모르겠네요. 무슨 로직인가요?
mode가 `search`일때의 조건이 없어 더욱 이해하기 힘든 것 같아요

2022-12-17 16:39 UTC, jaewoogwak commented on src/pages/Search/index.tsx
> +  const currentMode : CurrentMode = searchParams.get('mode') || MODE.trending;
searchParams는 /post에서 검색으로 넘어왔을 때 `search` 모드로 열리도록 하기 위해 쿼리스트링 값을 가져오기 위함입니다
우선 /post에서 검색으로 넘어오는 기능이 완전히 구현되지 않은것으로 보여서 이 부분은 /post 개발이 진행되면 변경이 필요해보입니다

`MODE.trending`은 `trendings`를 의미합니다.  `MODE.search`도 마찬가지구요. 사용하는 곳이 여러 군데라서 `search`, `trending` 문자열을 상수로 치환해서 사용해보려 했습니다

2022-12-17 16:42 UTC, jaewoogwak commented on src/pages/SearchDetails/index.tsx
> +            : shops.map((shop: Props) => (
수정했습니다~ [61c53eb](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/38/commits/61c53ebf16c0e64edd487d1d43b8967193c162b4)

2022-12-18 12:07 UTC, jaewoogwak commented on src/pages/Search/index.tsx
> +    document.addEventListener('click', changeMode);
해당 로직은 검색창을 클릭하면 추천 문구와 롤링배너를 숨기고 검색창을 위로 포커스합니다. (네이버 모바일에서 가운데 검색창을 클릭하면 위로 올라가는 것과 비슷합니다) 클릭 영역에 따라 동작을 분기하려고 `event.target.id`를 써 보려 했습니다.

2022-12-18 12:14 UTC, jaewoogwak commented on src/pages/Search/index.tsx
> +  const currentMode : CurrentMode = searchParams.get('mode') || MODE.trending;
우선 사용할일이 없는 코드니 제거하고 추후 필요해지면 추가하도록 하겠습니다~

2022-12-18 13:32 UTC, jaewoogwak commented on src/pages/SearchDetails/components/SearchItems.tsx
> +      <img alt="가게 이미지 없음" src={DefaultImage} />
response로 이미지 경로가 있을 때는 해당 경로의 이미지를 보여주고 없으면 default image를 보여주어야겠네요

일단 이미지 URL이 response에 없어서 플젝 채널에 요청했고 반영되면 적용하겠습니다~

2022-12-18 13:34 UTC, jaewoogwak commented on src/pages/SearchDetails/components/SearchItems.tsx
> +              <div className={styles['search-item__status--distance']}>내 위치로부터 23m</div>
넵 요청했고 프로젝트 채널에서 회의 진행 후 결과에 맞춰 변경하도록 하겠습니다

2022-12-22 10:03 UTC, ChoiWonBeen requested changes

2022-12-22 10:03 UTC, ChoiWonBeen commented on src/pages/SearchDetails/index.tsx
> +  const { isFetching, data: shops }: Props = useFetchShops(keyword!);
Props가 뭘까요??
컴포넌트의 attribute로 내려져오는 값들 아닌가요?
얜 props로 받는 값이 아닌데..

useQuery의 반환값은, Fetcher의 타입을 따라가므로 굳이 작성할 필요가 없습니다.

2022-12-22 10:03 UTC, ChoiWonBeen commented on src/utils/hooks/useGeolocation.ts
> +  const onGeoError = () => {};
어떤걸 추가할 계획인가요?

2022-12-22 10:03 UTC, ChoiWonBeen commented on src/pages/SearchDetails/components/SearchItem.tsx
> +import DefaultImage from 'assets/images/search/default-image.png';
컴포넌트가 아니므로 camelCase로 작성해주세요~

2022-12-22 10:03 UTC, ChoiWonBeen commented on src/pages/Search/index.tsx
> +  const { isLoading, data } = useTrendingList();
hook에서 리턴하는 값은 `data`로 일반적인 것이 좋지만, 이를 활용하는 컴포넌트에서도 일반적인 이름을 쓰는건 중복의 위험이 있어보여요.
```suggestion
  const { isLoading, data: trendings } = useTrendingList();
```

2022-12-22 10:03 UTC, ChoiWonBeen commented on src/pages/Search/index.tsx
> +    text, handleText,
text를 핸들링한다는것보단, `handleChange`같은 명칭이 더 적절하겠네요.

2022-12-23 00:58 UTC, jaewoogwak commented on src/pages/SearchDetails/index.tsx
> +  const { isFetching, data: shops }: Props = useFetchShops(keyword!);
Fetcher의 반환 타입을 정의해주면 useQuery 반환타입을 정의해줄 필요가 없군요... 

새로 알아갑니다👍

2022-12-23 01:03 UTC, jaewoogwak commented on src/pages/Search/index.tsx
> +  const { isLoading, data } = useTrendingList();
data: trendings로 표현하는건 좋다고 생각합니다. 그런데 자식 컴포넌트의 props로 넘길때는 자식 컴포넌트에서 받는 프로퍼티 이름과 같아지게 되는데 
ex) `<RollingBanner trendings={trendings} />` 처럼 말이죠
이렇게 겹치는 경우는 상관 없는건가요? 뭔가 이름이 중복된다는 느낌이 들어서요.

2022-12-23 01:05 UTC, jaewoogwak commented on src/pages/Search/index.tsx
> +    text, handleText,
수정했습니다! [f3a3bd3](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/38/commits/f3a3bd3ee8e7496a23eb120a1e42f0009b750338)

2022-12-23 06:14 UTC, ChoiWonBeen commented on src/pages/Search/index.tsx
> +  const { isLoading, data } = useTrendingList();
자식 컴포넌트에서 해당 훅을 호출하는 방법도 있습니다 :D

2022-12-23 14:03 UTC, jaewoogwak commented on src/utils/hooks/useGeolocation.ts
> +  const onGeoError = () => {};
`getCurrentPosition`이 반드시 성공, 실패 콜백함수를 필요로 해서 일단 `onGeoError`를 비워둔 상태인데 
어떤걸 추가할 계획은 아직 없습니다.

2022-12-28 12:28 UTC, ChoiWonBeen approved these changes

2022-12-28 12:29 UTC, merged