Feature/#39 [Auth] 회원가입 기능 추가
BCSDLab/TEMP_PROJECT_FE pull request #42
Opened 2022-12-12 17:12 UTC by ChoiWonBeen

## [#39] request

회원가입 페이지에 필요한 API를 연결했습니다.

- 회원가입 API 추가
- 아이디 중복확인을 검사했는지 확인하기위한 `useIdDuplicateCheck` hook 추가
- 서버 입력 필드 변경에 맞춰 비밀번호 최소 8자리로 변경
- 로그인 / 회원가입 시 비밀번호 sha256 암호화 제거

마지막 닉네임 변경은 프로젝트 채널에서 이슈가 해결된다면 마저 진행하겠습니다.

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

### Screenshot
![signup](https://user-images.githubusercontent.com/50780281/207107397-0688bfdf-e23c-47ce-a2bc-8849e4905b48.gif)

## precautions
`useIdDuplicateCheck`의 31~33 라인이 불편하다고 생각이 드는데, 해결법을 잘 모르겠습니다.

문제상황은 ID duplicate check **실행 이후** React-Query가 반환하는 `status` 값에 따라 **validation trigger**가 되길 원했는데, `duplicateCheck` -> `trigger` -> `status`의 setState 순으로 진행이 되어 validation이 올바르게 트리거되지 않습니다.

나름 React-Query의 `onSuccess` 콜백을 활용해보고, 프라미스도 추가해보고 했지만 해결되지 않아 결국 `useEffect`의 의존성 배열에 추가하게 되었는데 더 나은 방안이 떠오른다면 알려주세요. (아직까지는 `onSuccess` 콜백에 `setTimeout`을 10ms정도로 주는거밖에 떠오르지 않네요..)

2022-12-14 01:13 UTC, SimYunSup requested changes
간단한 기능임에도 많은 것을 고려한 것이 보이네요. 다음 기능도 잘 만들어주세요 :)

2022-12-14 01:13 UTC, SimYunSup commented on src/pages/Auth/Signup/SignupPage/components/IdInput.tsx
> +  const { trigger } = useFormContext<SignUpFormData>();
`useFormContext`를 두번 사용할 이유가 있었나요?

2022-12-14 01:13 UTC, SimYunSup commented on src/pages/Auth/Signup/SignupPage/components/IdInput.tsx
> +  const { status } = useQuery(['idDuplicate', id], () => checkIdDuplicate({ account: id }), {
id를 굳이 밖에서 가져올 필요 없이 파라미터 첫번째인 `context`에서 가져오면 됩니다.
```suggestion
  const { status } = useQuery(['idDuplicate', id], ([_,account]) => checkIdDuplicate({ account }), {
```
위와 같이 되겠네요.

2022-12-14 04:31 UTC, ChoiWonBeen commented on src/pages/Auth/Signup/SignupPage/components/IdInput.tsx
> +  const { trigger } = useFormContext<SignUpFormData>();
헉 수정하다가 생긴 실수네요 ㅋㅋ

2022-12-14 04:32 UTC, ChoiWonBeen commented on src/pages/Auth/Signup/SignupPage/components/IdInput.tsx
> +  const { status } = useQuery(['idDuplicate', id], () => checkIdDuplicate({ account: id }), {
queryFn 콜백함수의 인자로 쿼리키를 갖고오는군요! 👍

2022-12-14 04:44 UTC, ChoiWonBeen commented on src/pages/Auth/Signup/SignupPage/components/IdInput.tsx
> +  const { status } = useQuery(['idDuplicate', id], () => checkIdDuplicate({ account: id }), {
적용하려고 하니 타입이 맞지 않아 문서 타입을 참고했는데, 쿼리에 대한 정보를 객체로 받아 `queryKey`라는 key로 접근할 수 있습니다. 
아래처럼 적용해야 할 것 같은데, 어떻게 생각하시나요?
```tsx
const { status } = useQuery(['idDuplicate', id], ({ queryKey }) => checkIdDuplicate({ account: queryKey[1] }), {
```

2022-12-14 07:22 UTC, SimYunSup commented on src/pages/Auth/Signup/SignupPage/components/IdInput.tsx
> +  const { status } = useQuery(['idDuplicate', id], () => checkIdDuplicate({ account: id }), {
```suggestion
  const { status } = useQuery(['idDuplicate', id], ({queryKey: [_, account]}) => checkIdDuplicate({ account }), {
```
로 바꿀 수 있겠네요. Context를 갖고온다는 사실을 까먹고 있었네요.

2022-12-14 08:02 UTC, ChoiWonBeen commented on src/pages/Auth/Signup/SignupPage/components/IdInput.tsx
> +  const { status } = useQuery(['idDuplicate', id], () => checkIdDuplicate({ account: id }), {
수정했습니다~

2022-12-15 02:24 UTC, SimYunSup approved these changes

2022-12-20 11:31 UTC, merged