Feature/#14 [Auth] 로그인 에러 변경
BCSDLab/TEMP_PROJECT_FE pull request #43
Opened 2022-12-14 13:00 UTC by kimeodml

## [#14[https://github.com/BCSDLab/JJBAKSA_FRONT_END/issues/33]] request

로그인 에러 메세지를 디자인에 맞게 변경했습니다.

- 디자인상에서 로그아웃 버튼의 위치가 정해지지 않았기에 추후에 추가하겠습니다.

## Please check if the PR fulfills these requirements
- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

### Screenshot
![캡처](https://user-images.githubusercontent.com/88065770/207601279-a970059f-3466-4cdc-ae5d-108f5ffc408a.PNG)

2022-12-14 14:40 UTC, ChoiWonBeen requested changes
[이슈](https://github.com/BCSDLab/JJBAKSA_FRONT_END/issues/33#issuecomment-1345564854)에서 언급했듯, 비밀번호 조건이 숨겨져 있는건 나쁜 UX라고 생각해요. 
충분히 프론트측에서 비밀번호 입력에 validation check를 할 수 있고, 불필요한 API호출도 줄일 수 있을거예요.

Response 타입 정의는 Network탭을 유심히 보며 익숙해지면 될 부분이라고 생각이 들긴 하는데 왜 바꾼건지 단순하게 궁금하긴 하네요. 고생했습니다~

2022-12-14 14:40 UTC, ChoiWonBeen commented on src/api/user/entity.ts
> +  user: User;
POST: `/user/login` Response에 해당 변수가 안들어오는데 왜 추가됐나요?

2022-12-14 14:40 UTC, ChoiWonBeen commented on src/api/user/entity.ts
> +  password: string;
GET: `/user/me`가 반환하는 **내 정보**에 대한 객체를 User로 정의해둔 것이고, 해당 API의 Response에도 `password`를 제공하지 않습니다.

2022-12-14 14:40 UTC, ChoiWonBeen commented on src/pages/Auth/Login/index.tsx
> +  const submitLogin = useLoginRequest({ onError: setError });
`useBoolean` util hook을 만들어두었습니다.
```suggestion
  const { value: error, setTrue: catchError } = useBoolean(false);
  const submitLogin = useLoginRequest({ onError: catchError });
```

2022-12-14 14:40 UTC, ChoiWonBeen commented on src/pages/Auth/Login/index.tsx
> +                  />
통일되지 않은 띄어쓰기와, 가독성을 해칠 수 있는 불필요한 줄바꿈이라고 생각해요.
```suggestion
              {error && (
                <>
                  <ErrorIcon aria-hidden />
```

2022-12-16 02:14 UTC, hanagertrudekim requested changes
수고하셨습니다ㅎㅎ 리뷰했으니 확인해주세요!  리뷰가 많이 늦었네요ㅜㅜ

2022-12-16 02:20 UTC, hanagertrudekim requested changes
위에 약간 오류가 뜬것같은데.. 저거는 무시하시고 리뷰 확인 부탁드려요..! ㅎㅎ 리뷰가 많이 늦엇네요ㅜ

2022-12-16 02:20 UTC, hanagertrudekim commented on src/pages/Auth/Login/index.tsx
> +                  className={styles.checkbox}
이부분 classname 만 `checkbox`인데 `autologin_checkbox`로 바꿔도 될것같아요!

2022-12-16 02:20 UTC, hanagertrudeKim commented on src/pages/Auth/Login/index.tsx
> +              id="pw"
진짜 사소하긴한데, id 를 `password`풀네임으로 바꾸는게 더 좋을것같아요..!

2022-12-20 08:36 UTC, kimeodml commented on src/api/user/entity.ts
> +  user: User;
스웨거에 없어서 제거하려고 했는데 깜빡했습니다. 수정했습니다. [82cb446](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/43/commits/82cb446e07080322d1e4751c86065bba61ba7451)

2022-12-20 08:36 UTC, kimeodml commented on src/api/user/entity.ts
> +  password: string;
[82cb446](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/43/commits/82cb446e07080322d1e4751c86065bba61ba7451)

2022-12-20 08:37 UTC, kimeodml commented on src/pages/Auth/Login/index.tsx
> +  const submitLogin = useLoginRequest({ onError: setError });
수정했습니다.[48c82af](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/43/commits/48c82afba5c6f5ea99b127595f871316215cbfec)

2022-12-20 08:37 UTC, kimeodml commented on src/pages/Auth/Login/index.tsx
> +                  />
수정했습니다. [48c82af](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/43/commits/48c82afba5c6f5ea99b127595f871316215cbfec)

2022-12-20 08:37 UTC, kimeodml commented on src/pages/Auth/Login/index.tsx
> +                  className={styles.checkbox}
수정했습니다. [73b9b02](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/43/commits/73b9b02840cba18790029ba645299ec352fc0996)

2022-12-20 08:38 UTC, kimeodml commented on src/pages/Auth/Login/index.tsx
> +              id="pw"
수정했습니다 [73b9b02](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/43/commits/73b9b02840cba18790029ba645299ec352fc0996)

2022-12-20 11:32 UTC, ChoiWonBeen approved these changes
남은 Approve처리랑 변경된 develop 충돌 해결되면 다음 머지할게여~

2022-12-20 11:53 UTC, kimeodml commented
@ChoiWonBeen 비밀번호 오류 문구 추가했습니다. [fb80b76](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/43/commits/fb80b769655ff58498cd8a9448387f14baeabfa7)

2022-12-20 12:39 UTC, ChoiWonBeen reviewed
비밀번호 형식에 맞지 않아도 요청을 보내는데요?
요청 자체를 블락하게끔 수정할 수는 없을까요?

2022-12-20 12:54 UTC, ChoiWonBeen requested changes
<img width="467" alt="image" src="https://user-images.githubusercontent.com/50780281/208671992-faee65bd-6649-4dd0-8b60-955fcf6e1f5d.png">
+ 바꾸면서 맥에서 글자가 아쉽게 두 줄로 보이는데 letter-spaceing을 아주 조금만 음수로 처리해주면 좋을거같아요

2022-12-20 13:17 UTC, kimeodml commented
@ChoiWonBeen 수정했습니다! [86bba95](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/43/commits/86bba95a8ec950989331efc3eeed8e9eaf32f3ce) [1782cb3](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/43/commits/1782cb3541a120941e9f87c0991570cea4c4b863)

2022-12-20 13:24 UTC, ChoiWonBeen requested changes

2022-12-20 13:24 UTC, ChoiWonBeen commented on src/pages/Auth/Login/index.tsx
> +const PATTERN = /^(?=.*[0-9])(?=.*[a-zA-z])(?=.*[!@#$%^&*+=()]).{2,16}$/;
`src/Auth/SignUp/static` 에 해당 값과 똑같은 변수가 있습니다.
hierarchy를 낮추고 Auth에서 공용으로 관리하게 바꾸면 좋을 것 같아요.

그리고 회원가입 기능추가 PR에서 해당 정규식이 최소 8자~16자로 변경되어 적용시킨 적 있으니 dev머지받으면서 잘 적용되나 확인해주세요.

2022-12-20 14:14 UTC, kimeodml commented on src/pages/Auth/Login/index.tsx
> +const PATTERN = /^(?=.*[0-9])(?=.*[a-zA-z])(?=.*[!@#$%^&*+=()]).{2,16}$/;
수정했습니다. [78348c2](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/43/commits/78348c27a94951e1520c8d45a0e1004b03294c38)

2022-12-20 14:50 UTC, ChoiWonBeen approved these changes
dev머지받고 충돌만 해결해주세요~

2022-12-23 09:17 UTC, hanagertrudekim approved these changes

2022-12-23 10:50 UTC, merged