Feature/#40 [Auth] 아이디 찾기 API 연결
BCSDLab/TEMP_PROJECT_FE pull request #48
Opened 2023-01-04 08:11 UTC by chaeseungyun

아이디 찾기 API를 연결했습니다.
비밀번호 찾기 API연결은 추후 스웨거가 수정되는대로 진행하겠습니다.
동시에 interface를 한 파일에 합치고 api 폴더를 만들어 조금 더 보기 좋게 정리했습니다.

submit하는 순간 이메일을 보내거나, 인증 번호 유효성을 확인하기 때문에 useQuery를 사용하는데 제한을 느꼈습니다.
useQuery 없이 구현했는데 부족한 부분 있으면 조언 부탁드립니다.
api 중복 호출이 되는 경우는 form에 에러 발생시 버튼을 disable하는 방식으로 구현했습니다.

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [ ] Docs updated for breaking changes

### Screenshot

2023-01-04 16:31 UTC, ChoiWonBeen requested changes
고생하셨어요~ 기능들과 에러처리는 전부 문제가 없는데, React-Query를 사용하지 않은 점이 뭔가 통일되지 않는 느낌이 들어서 약간 아쉬운 부분이 있네요 😅
`sendEmail`같이 단순 POST는 쓰지 않아도 될 수 있는데, 다른 함수엔 사용하는편이 좋아보여서 이번 수정 중에 적용할 수 있다면 바꿔서 적용하셔도 좋은 경험이 될 수 있을 것 같아요.

일단 develop 브랜치 머지하셔서 충돌점들 해결주시고, 파일 구조나 변수이름, 짜잘한 수정사항들 모아두었으니 수정하면서 dev에 생긴 다른 기능들과 비교하며 같이 확인해주세요 :D

2023-01-04 16:31 UTC, ChoiWonBeen commented on src/pages/Auth/FindIDPassword/api/index.ts
> +export const getAccount = (param: { email: string, code: string }) => userApi.get(`/account?email=${param.email}&code=${param.code}`);
진짜 사소한데, 4번라인이랑 다르게 6번라인에서는 타입을 직접 지정한 이유가 있나요?

2023-01-04 16:31 UTC, ChoiWonBeen commented on src/pages/Auth/FindIDPassword/index.tsx
>  const EMAILPATTERN = /^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*\.[a-zA-Z]{2,3}$/i; // 이메일 형식 유효성 검사 패턴
`Auth/static/regexp.ts` 파일에 Auth관련 정규식들 모아놨으니 가져다가 사용하는걸로 바꿔주세요.

2023-01-04 16:31 UTC, ChoiWonBeen commented on src/pages/Auth/FindIDPassword/page/VerifyCode.tsx
> +        </Modal>
여기 UI가 깨지는데 신경써줄 필요가 있어보여요!
<img width="319" alt="image" src="https://user-images.githubusercontent.com/50780281/210588008-8cf9a380-f127-4493-bf4d-197966d446ca.png">

2023-01-04 16:31 UTC, ChoiWonBeen commented on src/pages/Auth/FindIDPassword/page/VerifyCode.tsx
>  const NAME: ['first', 'second', 'third', 'fourth'] = ['first', 'second', 'third', 'fourth'];
`as const`를 키워드를 활용해 타입을 완전상수화 시킬 수 있습니다.
근데 NAME이라는 이름이 어울리나 싶긴 하네요?
```suggestion
const NAME = ['first', 'second', 'third', 'fourth'] as const;
```

2023-01-04 16:31 UTC, ChoiWonBeen commented on src/pages/Auth/FindIDPassword/index.tsx
> +              아이디 찾을 때
"아이디**를** 찾을 때"의 오타인 것 같죠?

2023-01-04 16:31 UTC, ChoiWonBeen commented on src/pages/Auth/FindIDPassword/page/VerifyCode.tsx
> +        NextStep();
이 함수는 컴포넌트가 아니므로 camelCase로 통일해주세요

2023-01-04 16:31 UTC, ChoiWonBeen commented on src/pages/Auth/FindIDPassword/hook/useInputCheck.ts
>    useEffect(() => inputRef.current[0]?.focus(), []);
이부분도 입력할때는 편한 UX로 잘 만들어졌는데, 한번 잘못입력해서 지워봤는데 지울때가 엄청 불편하네요.
지우는 경우의 UX도 맞춰주시면 좋을 것 같아요!

2023-01-04 16:31 UTC, ChoiWonBeen commented on src/pages/Auth/FindIDPassword/entity.ts
> +  fourth: string
이 타입이 Input 각각의 값이라면 `number`형태가 맞지 않나요?

2023-01-04 16:31 UTC, ChoiWonBeen commented on src/pages/Auth/FindIDPassword/component/Input.tsx
> +  const inputRefCopy = inputRef;
이 변수는 왜 필요한건가요?

2023-01-04 16:31 UTC, ChoiWonBeen commented on src/pages/Auth/FindIDPassword/component/Input.tsx
> +  register, name, inputRef, preventOverLength, n, index,
`n` 이라는 변수의 의도를 파악하기 너무 힘들어보여요

2023-01-04 16:31 UTC, ChoiWonBeen commented on src/pages/Auth/FindIDPassword/hook/useInputCheck.ts
> +  });
해당 상태는 form과 연관된게 아닌가요?
순수 state말고 ReactHookForm에 기반한 상태를 쓰는건 어떨까 싶어서..

2023-01-04 16:31 UTC, ChoiWonBeen commented on src/pages/Auth/FindIDPassword/index.tsx
> +        <form className={style.form} onSubmit={handleSubmit(nextPage)}>
`nextPage`라는 함수명보다 더 적절한 표현이 있을 것 같아요!

2023-01-04 16:31 UTC, ChoiWonBeen commented on src/pages/Auth/FindIDPassword/index.tsx
>  export default function FindIdPassword({ find }: FindProp): JSX.Element {
`find`보다는 `type`같은 표현이 더 어울릴 것 같아요.
`find == 'id'`라는 표현이 어색해보이네요 ㅋㅋ

2023-01-04 16:31 UTC, ChoiWonBeen commented on src/pages/Auth/FindIDPassword/page/VerifyCode.tsx
> +export default function VerifyCode({
이 파일과 더불어서, `./page`에 해당하는 파일들 모두 상위 뎁스에서 폴더로 모아두는게 좋아보여요.
이미 `src/pages/`안에 들어온 파일들이잖아요?
아마 다시 확인해보면 이 폴더구조가 좀 이상하다고 느낄 것 같아요.

2023-01-04 16:31 UTC, ChoiWonBeen commented on src/pages/Auth/FindIDPassword/api/index.ts
> +import userApi from 'api/user/userApiClient';
api와 entity의 폴더는 `src/api`에서 관리하고 있습니다. 폴더 위치를 통일해주세요~

2023-01-04 16:34 UTC, ChoiWonBeen commented on src/pages/Auth/FindIDPassword/entity.ts
> +  fourth: string
+ 타입 뒤에 세미콜론으로 통일해주세요!

2023-01-07 08:50 UTC, chaeseungyun commented on src/pages/Auth/FindIDPassword/index.tsx
>  const EMAILPATTERN = /^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*\.[a-zA-Z]{2,3}$/i; // 이메일 형식 유효성 검사 패턴
수정 완료했습니다

2023-01-07 08:51 UTC, chaeseungyun commented on src/pages/Auth/FindIDPassword/page/VerifyCode.tsx
> +        </Modal>
모달 내용 가운데 맞춤 완료 했습니다

2023-01-07 08:55 UTC, chaeseungyun commented on src/pages/Auth/FindIDPassword/hook/useInputCheck.ts
> +  });
api 호출 결과를 사용하기 때문에 ReactHookForm의 상태를 가져다 사용하기가 애매했습니다.
그래서 내린 결론은 새로운 state를 만들고 여기에 저장하는 것이었습니다.

2023-01-07 08:56 UTC, chaeseungyun commented on src/pages/Auth/FindIDPassword/index.tsx
> +              아이디 찾을 때
오타 수정 완료했습니다

2023-01-07 08:58 UTC, chaeseungyun commented on src/pages/Auth/FindIDPassword/index.tsx
>  export default function FindIdPassword({ find }: FindProp): JSX.Element {
추천 해주신 대로 변경했습니다

2023-01-07 09:00 UTC, chaeseungyun commented on src/pages/Auth/FindIDPassword/api/index.ts
> +export const getAccount = (param: { email: string, code: string }) => userApi.get(`/account?email=${param.email}&code=${param.code}`);
그냥 손이 가는 대로 적다가 생긴 실수인 것 같습니다.
AccountInfo 라는 새로운 인터페이스를 만들고 적용했습니다

2023-01-07 09:07 UTC, chaeseungyun commented on src/pages/Auth/FindIDPassword/api/index.ts
> +import userApi from 'api/user/userApiClient';
api와 관련된 인터페이스와 코드는 src/api로 이동 했습니다

2023-01-07 09:10 UTC, chaeseungyun commented on src/pages/Auth/FindIDPassword/page/VerifyCode.tsx
> +export default function VerifyCode({
pages 안에 page 폴더에 묶어둔 게 이상하다는 말이죠?
상위 폴더에 모아두는 걸로 변경했습니다

2023-01-07 09:16 UTC, chaeseungyun commented on src/pages/Auth/FindIDPassword/page/VerifyCode.tsx
>  const NAME: ['first', 'second', 'third', 'fourth'] = ['first', 'second', 'third', 'fourth'];
CODE라는 이름으로 완전상수화 시켰습니다.
좋은 정보 감사합니다

2023-01-07 09:19 UTC, chaeseungyun commented on src/pages/Auth/FindIDPassword/index.tsx
> +        <form className={style.form} onSubmit={handleSubmit(nextPage)}>
checkEmail이라는 함수명으로 변경해보았어요

2023-01-07 14:57 UTC, ChoiWonBeen commented on src/pages/Auth/FindIDPassword/page/VerifyCode.tsx
> +        </Modal>
로그인 하단 마진도 너무 부족한 것 같은데 이부분도 같이 처리해야될것같아요! @chaeseungyun

2023-01-07 15:14 UTC, chaeseungyun commented on src/pages/Auth/FindIDPassword/page/VerifyCode.tsx
> +        </Modal>
하단 마진 처리 완료했습니다

2023-01-07 15:18 UTC, chaeseungyun commented on src/pages/Auth/FindIDPassword/page/VerifyCode.tsx
> +        NextStep();
네 수정완료했습니다

2023-01-07 15:21 UTC, chaeseungyun commented on src/pages/Auth/FindIDPassword/entity.ts
> +  fourth: string
숫자는 input의 maxLength 속성을 사용할 수 없어서 문자로 처리했습니다.
문자열 크기를 제한할 때 사용하는 charAt도 리터럴한 것만 사용할 수 있었습니다

2023-01-07 15:25 UTC, chaeseungyun commented on src/pages/Auth/FindIDPassword/component/Input.tsx
> +  const inputRefCopy = inputRef;
아래에서 함수 inputRef 매개변수를 바로 사용할 수 없어서 Copy본을 만들고 작성했습니다.
eslint 문제입니다

2023-01-07 15:27 UTC, chaeseungyun commented on src/pages/Auth/FindIDPassword/component/Input.tsx
> +  register, name, inputRef, preventOverLength, n, index,
몇 번째 자리인지 알 수 있게 number로 수정했습니다

2023-01-07 15:41 UTC, ChoiWonBeen commented on src/pages/Auth/FindIDPassword/entity.ts
> +  fourth: string
오...그런 이유가! 배워갑니다 👍

2023-01-07 15:48 UTC, chaeseungyun commented on src/pages/Auth/FindIDPassword/hook/useInputCheck.ts
>    useEffect(() => inputRef.current[0]?.focus(), []);
엄청 불편하긴 하네요
좀 더 수정하기 쉽게 수정해봤습니다

2023-01-07 17:19 UTC, ChoiWonBeen commented on src/pages/Auth/FindIDPassword/api/index.ts
> +export const getAccount = (param: { email: string, code: string }) => userApi.get(`/account?email=${param.email}&code=${param.code}`);
다른 파라미터의 타입들은 ~~Params로 네이밍이 되어있으니 통일해주면 더 좋을거같아요!

2023-01-07 17:24 UTC, ChoiWonBeen requested changes

2023-01-07 17:24 UTC, ChoiWonBeen commented on src/api/user/index.ts
> +export const sendEmail = (param: EmailInfo) => userApi.post(`/email?email=${param.email}`);
지금 회원가입부분 만들면서 생긴 문젠데, 
회원가입 인증용 이메일을 발송하는 API도 있어서, 해당 API의 이름을 바꿔야할 것 같아요.

2023-01-08 12:12 UTC, chaeseungyun commented on src/pages/Auth/FindIDPassword/api/index.ts
> +export const getAccount = (param: { email: string, code: string }) => userApi.get(`/account?email=${param.email}&code=${param.code}`);
통일 완료했습니다

2023-01-08 12:16 UTC, chaeseungyun commented on src/api/user/index.ts
> +export const sendEmail = (param: EmailInfo) => userApi.post(`/email?email=${param.email}`);
sendRegisterEmail을 참고하여
sendFindEmail로 수정했습니다.

2023-01-08 16:23 UTC, ChoiWonBeen commented on src/pages/Auth/FindIDPassword/component/Input.tsx
> +  const inputRefCopy = inputRef;
그런 문제라면 린터에 걸리는 것을 피하기 위해 회피패턴을 쓰는 것 보단, 해당 규칙을 비활성화 시키는 것이 좋을 것 같아요.
저 복사가 진행되는것이 실제 변수의 레퍼런스에 영향을 주지도 않고, 아무 의미도 없잖아요?
해당 규칙을 잘 확인해보고 한 줄에 대해서만 비활성화할지, 앱 전체에 대해 비활성화할지 생각해보는것도 좋을 것 같아요.

2023-01-08 16:23 UTC, ChoiWonBeen commented on src/pages/Auth/FindIDPassword/component/Input.tsx
> +  register, name, inputRef, preventOverLength, n, index,
몇 번째 자리라는 의미는 index가 맡고있는게 아닌가요?
아니라면 두 변수의 네이밍을 다 생각해볼 필요가 있어보여요.

2023-01-09 00:36 UTC, chaeseungyun commented on src/pages/Auth/FindIDPassword/component/Input.tsx
> +  register, name, inputRef, preventOverLength, n, index,
인덱스는 0부터 시작하고 다음  number는 자리수를 의미합니다

2023-01-09 02:17 UTC, chaeseungyun commented on src/pages/Auth/FindIDPassword/component/Input.tsx
> +  const inputRefCopy = inputRef;
매개변수에 참조값이 오는 경우 그 값이 바뀔 우려가 있기 때문에 이러한 경우를 방지하기 위해, 저희가 타입 스크립트를 사용하고 있기도 하고, 한 줄에 대해서만 비활성화하는게 좋다고 생각해요

2023-01-09 02:21 UTC, ChoiWonBeen commented on src/pages/Auth/FindIDPassword/component/Input.tsx
> +  const inputRefCopy = inputRef;
참조값이니깐 변수 주소를 옮겨도 같은 참조값이겠죠? 그래서 저 패턴을 썼을 때와 아닐 때 변하는 게 없을거예요.

ref를 props로 넘길땐 보통 `forwardRef`를 사용하니 왜 쓰는지를 알아보고 적용해봐도 좋을 것 같아요.

2023-01-09 11:25 UTC, chaeseungyun commented on src/pages/Auth/FindIDPassword/component/Input.tsx
> +  const inputRefCopy = inputRef;
forwardRef를 함수선언식으로 사용할 수 있나요?
함수선언식에 관한 예제를 못찾았습니다..
참조값에 대해 말해주신 조언은 잘 알아들었습니다

2023-01-09 12:01 UTC, ChoiWonBeen commented on src/pages/Auth/FindIDPassword/component/Input.tsx
> +  const inputRefCopy = inputRef;
아래처럼 쓸 수 있어용
```tsx
const Input = forwardRef(function Input(props, ref) {
  return <input type="text" ref={ref} />;
});
```

2023-01-17 07:37 UTC, chaeseungyun commented on src/pages/Auth/FindIDPassword/component/Input.tsx
> +  const inputRefCopy = inputRef;
forwardRef를 사용하는데 null 관련 처리가 어려워서 아직 적용할 수 없었습니다.
eslint rule을 무시하는 방향으로 간다면 기존의 inputRef를 전달하는 방식으로 간단하게 사용할 수 있었습니다.
확인 부탁드립니다

2023-01-18 11:43 UTC, ChoiWonBeen approved these changes
Favicon 진행 이후 ForwardRef 다시 진행해보죠!

2023-01-18 11:43 UTC, merged