Feature/#47 [Auth] 회원가입 & 인증 관련 이슈 처리
BCSDLab/TEMP_PROJECT_FE pull request #49
Opened 2023-01-08 12:32 UTC by ChoiWonBeen

## [#47] request

- refresh token이 만료된 경우 (유효하지 않은 경우) 에러가 catch되지 않아 멈춰버리는 오류를 수정했습니다.
  - `<ErrorBoundary />`를 고려해볼 법도 싶은데, 이건 추후에 생각해보겠습니다.
- 회원가입 요청에 이메일 인증을 보내도록 추가했습니다.
- 회원가입 요청 중 이메일이 중복된 경우 에러메시지를 화면에 출력하게 변경했습니다.
- 로그인 요청시 서버에서 제공하는 에러메시지를 UI에 출력하도록 변경했습니다.
  - 이메일 미인증
  - 아이디&비밀번호 틀린 경우
    - 현재는 유효하지 않은 접근이라고 메시지가 출력되는데, 서버측과 상의해 알맞은 메시지로 변경해준다고 하여 추후에 적용될 예정입니다.

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

### Screenshot
<img width="643" alt="image" src="https://user-images.githubusercontent.com/50780281/211195282-0176a400-5656-4f35-ad47-5b179929ff65.png">

### Precautions
catch한 에러의 타입을 `AxiosError`로 변경하는 과정을 유심히 확인해주세요! 아마 사용할 일들이 많을 것 같아요.
또한 `useSignUp` 훅이 잘 분리되어있다가 폼 내 `EmailInput`에게 에러를 전파하기 위해 rhf의 `setError`와 결합을 갖게 되는데... 이 부분이 불편하네요. 두 곳 위주로 리뷰해주시면 감사하겠습니다.

2023-01-09 11:32 UTC, chaeseungyun reviewed
고생하셨습니다!!
궁금한 점이 몇 개 있어서 적어보았습니다..

2023-01-09 11:32 UTC, chaeseungyun commented on src/pages/Auth/Login/index.tsx
> +          onError?.(serverError.response?.data.errorMessage ?? '서버가 응답하지 않습니다.');
옵셔널 체이닝 뒤에 괄호는 어떨때 사용할 수 있나요?

2023-01-09 11:32 UTC, chaeseungyun commented on src/pages/Auth/Login/index.tsx
> +          const serverError = error as AxiosError<{ errorMessage: string; }>;
인터페이스를 만들지 않은 이유가 무엇인가요?

2023-01-09 11:32 UTC, chaeseungyun commented on src/api/user/userApiClient.ts
> +    return null;
여기서 null을 반환하는 이유는 무엇인가요?

2023-01-09 11:42 UTC, ChoiWonBeen commented on src/api/user/userApiClient.ts
> +    return null;
`Promise.reject()` 는 기본적으로 에러로 처리되어 catch가 되어야 해당 에러를 핸들링할 수 있습니다.
refreshToken이 있을 경우 `refreshAccessToken`함수를 실행하는데,`refresh`요청의 성공/실패에 따라 할 수 있는 동작이 명확하므로 상위 콜스택에 에러를 throw할 필요 없이 해당 함수에서 처리하는게 낫다고 생각했습니다.

2023-01-09 11:43 UTC, ChoiWonBeen commented on src/pages/Auth/Login/index.tsx
> +          const serverError = error as AxiosError<{ errorMessage: string; }>;
이부분은...중복되는 곳도 있으므로 isAxiosError 함수를 래핑하면서 수정해보겠습니다.

2023-01-09 11:45 UTC, ChoiWonBeen commented on src/pages/Auth/Login/index.tsx
> +          onError?.(serverError.response?.data.errorMessage ?? '서버가 응답하지 않습니다.');
`onError(serverError.response?.data.errorMessage ?? '서버가 응답하지 않습니다.')`와 같습니다.
onError에 의존하지 않을 수 있다고도 생각해 이렇게 만든 것 같아요.

2023-01-09 12:44 UTC, ChoiWonBeen commented on src/pages/Auth/Login/index.tsx
> +          const serverError = error as AxiosError<{ errorMessage: string; }>;
interface도 추가했고, 에러처리를 하는곳마다 `axios`와 `AxiosError`를 import하지 않아도 되도록 함수화시켜봤어요 [a2be74f](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/49/commits/a2be74ff6fe697a7a83b87c8cf6e6920a72b858f)

2023-01-18 09:58 UTC, kimeodml requested changes
너무 뒤늦게 확인합니다! 고생하셨어요!!

2023-01-18 09:58 UTC, kimeodml commented on src/pages/Auth/Login/index.tsx
> +        }
비밀번호가 틀릴경우 `유효하지 않은 접근입니다.`라는 메세지가 뜨는 데 혹시 백엔드 상에서 에러 메세지 변경할 수 있나요..? 문구가 너무 모호해서 무엇이 잘못되었는지 사용자가 파악을 못할것 같아서요

2023-01-18 10:00 UTC, ChoiWonBeen commented on src/pages/Auth/Login/index.tsx
> +        }
해당 메시지는 서버에서 에러가 난 경우(500에러)를 대응한 것이고,
유효하지 않은 접근이라는 표현은 바꿔주신다고 백엔드개발자분과 이야기되었어요. 알맞게 바꿔주신다네요.
근데 좀 지나서 다시 언급해봐야겠네요 ㅋㅋ

2023-01-20 05:04 UTC, kimeodml approved these changes

2023-01-20 05:18 UTC, merged