Feature/#16 [Map] 메이페이지 지도 추가
BCSDLab/TEMP_PROJECT_FE pull request #50
Opened 2023-01-09 09:44 UTC by kimeodml

## [[#44](https://github.com/BCSDLab/JJBAKSA_FRONT_END/issues/44)] request

메인페이지의 지도를 구현했습니다.
- 클릭시 지도가 부드럽게 이동하는 기능을 추가하였습니다.
- 그와 동시에 하이라이트 기능도 추가하였습니다.
- 마크 모양을 변경할 수 있는 content의 타입이 `string | HTMLElement`라 부득이하게 코드를 다 넣었는데 추후에 수정하겠습니다. 

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

### Screenshot
<img src="https://user-images.githubusercontent.com/88065770/211278455-16b94ad0-0142-4499-a782-bb931f84700b.png" width="40%" height="40%"/>
<img src="https://user-images.githubusercontent.com/88065770/211278534-af2c2464-f491-47c7-a18f-023b6afceee8.png" width="80%" height="80%"/>

2023-01-09 12:49 UTC, ChoiWonBeen reviewed
마커 클러스터링은 어떻게됐나요?

2023-01-09 16:52 UTC, ChoiWonBeen requested changes
고생하셨어요~ 처음 만져보는 지도일거라 복잡하셨을텐데 어떻게 마커까지 잘 나오네요.
다만 컴포넌트 로직이 너무 무거워져서, 이 부분을 어떻게 해결할지 고민을 해봐야 할 것 같아요.
일단은 눈에 보이는 수정사항들을 리뷰해놨는데, 크리티컬한 부분들도 있으니 확인하고 수정해주세요~

2023-01-09 16:52 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/index.tsx
> +                '<div style="display:flex;justify-content:center;text-align:center;border:1px solid #FF7F23;background-color:white;border-radius:32.5px;min-width:205px;height:65px;">',
`HTMLElement`를 활용하는게 힘들었다면 class와 css파일을 함께 쓰는게 어땠을까 싶어요.
가능하면 `HTMLElement`로 쓰는게 좋아보이긴 하는데.. JSX처럼 써넣는건 아닌가보네요?

2023-01-09 16:52 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/index.tsx
> +                '<img src="" style="width:68px;height:68px;border-radius:89.5px;"slt="음식점 사진"/>',
alt의 오타인 것 같죠?
```suggestion
                '<img src="" style="width:68px;height:68px;border-radius:89.5px;" alt="음식점 사진"/>',
```

2023-01-09 16:52 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/index.tsx
> +            '<img src={FoodIcon} style="width:68px;height:68px;border-radius:89.5px;"slt="음식점 사진"/>',
테스트를 하는데 있어 UI가 보이지 않아 불편해요
임시 이미지를 넣어주면 확인하기 쉬울 것 같아요.
```suggestion
//... 상단에서 공용 이미지 import
// import defaultImage from 'assets/images/search/default-image.png';
            `<img src="${defaultImage}" style="width:68px;height:68px;border-radius:89.5px;"slt="음식점 사진"/>`,
```

2023-01-09 16:52 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/index.tsx
> +            '<img src={FoodIcon} style="width:68px;height:68px;border-radius:89.5px;"slt="음식점 사진"/>',
그런데 사진을 넣어보니 사진 비율이 안맞네요. 이부분도 확인해주세요~
<img width="263" alt="image" src="https://user-images.githubusercontent.com/50780281/211348804-478b8b0d-8f9e-4466-85b2-a980549e2424.png">

2023-01-09 16:52 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/index.tsx
> +          ].join(''),
이렇게 두고 join을 통해 문자열로 만들거라면
그냥 백틱(`)을 사용해서 JSX처럼 적는건 어땠을까요?
```tsx
content: `
  <div>
    <img src="${defaultImage}">
  </div>
`
```
이를 깔끔하게 반환하는 함수나 값으로 다른 곳에 분리해두는 것도 필요해보여요. useEffect내에 너무 많은 로직이 담겨있다는 생각이 드네요

2023-01-09 16:52 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/index.tsx
> +      naver.maps.Event.addListener(markerCur, 'click', () => {
클린업함수도 필요해보이는데 없어도 괜찮을까요?

2023-01-09 16:52 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/index.tsx
> +    for (let i = 0; i < marker.length; i += 1) {
for문을 쓰기보단, 선언적으로 `map` 이나 `forEach`를 활용해주세요

2023-01-09 16:52 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/index.tsx
> +      markerClickEvent(markerRef.current, marker[i]);
클릭이벤트인데 그냥 실행하는건 이상한 것 같죠?
클릭이벤트를 하이드레이션한다는 목적에 맞춰 네이밍을 수정할 필요가 있어보여요.

2023-01-09 16:52 UTC, ChoiWonBeen commented on src/pages/Home/components/OptionButtons/index.tsx
> +      { isMobile ? <FilterMenu /> : (
PC는 필터가 안열리네요? 디자인이 없어서 그런 것 같은데..
이런 부분은 프로젝트 채널에 공유하거나 바로 트랙 채널에 공유해주셔야 주간공유때 언급할 수 있어요 인지해주세요!

2023-01-09 16:52 UTC, ChoiWonBeen commented on src/pages/Home/index.tsx
> +          검색어를 입력해주세요.
검색을 한번 하고 왔는데, 컴포넌트의 인스턴스가 새로 만들어져서인지, 지도를 처음부터 렌더링해 시간이 매우 오래 걸리네요?
백그라운드에 유지하는 방법을 필히 고민해야할 것 같아요.

2023-01-09 16:52 UTC, ChoiWonBeen commented on src/pages/Home/static/marker.ts
> +const marker = [
나중에 쓰진 않겠지만, 상수는 `UPPER_CASE`로 통일해왔습니다.

2023-01-10 10:57 UTC, kimeodml commented
> 마커 클러스터링은 어떻게됐나요?

이것도 이것저것 시도해보고 있는 중이라 추후에 추가하겠습니다.

2023-01-11 01:59 UTC, SimYunSup requested changes

2023-01-11 01:59 UTC, SimYunSup commented on src/pages/Home/components/Map/index.tsx
> +                '<div style="display:flex;justify-content:center;text-align:center;border:1px solid #FF7F23;background-color:white;border-radius:32.5px;min-width:205px;height:65px;">',
해당 부분은 CSS modules를 쓰지않으면 class로 관리할 수 있습니다. CSS Modules의 `:global`키워드를 더 알아보세요.
https://github.com/css-modules/css-modules#exceptions

2023-01-11 01:59 UTC, SimYunSup commented on src/pages/Home/components/Map/index.tsx
> +  const selectedMarker = useRef<any | null>(null);
```suggestion
  const mapRef = useRef<naver.maps.Map | null>(null);
  const markerRef = useRef<naver.maps.Marker | null>(null);
  const selectedMarker = useRef<naver.maps.Marker | null>(null);
```
타이핑 가능하면 any는 지양해주세요.

2023-01-11 01:59 UTC, SimYunSup commented on src/pages/Home/components/Map/index.tsx
> +      naver.maps.Event.addListener(markerCur, 'click', () => {
Marker를 그리는데 클린업은 필요 없고 Map을 그리는데만 클린업이 필요합니다. `mapRef`를 초기화 하는 Effect에서 클린업을 추가해주세요.

2023-01-11 01:59 UTC, SimYunSup commented on src/pages/Home/components/Map/index.tsx
> +      markerRef.current = new naver.maps.Marker({
이 초기화 과정은 왜 있는건가요?

2023-01-11 01:59 UTC, SimYunSup commented on src/pages/Home/components/OptionButtons/FilterMenu.tsx
> +import useBoolean from 'utils/hooks/useBoolean';
해당 hooks는 어디서 가져온 것인가요? 현재 `develop`브랜치에서는 `useBooleanState`를 사용하고 있는데요.

2023-01-12 12:40 UTC, kimeodml commented on src/pages/Home/components/Map/index.tsx
> +          ].join(''),
수정했습니다. [0d9b88b](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/50/commits/0d9b88ba5e54423d5a7ecce06c604fb5486934c4)

2023-01-12 12:40 UTC, kimeodml commented on src/pages/Home/components/Map/index.tsx
> +                '<img src="" style="width:68px;height:68px;border-radius:89.5px;"slt="음식점 사진"/>',
수정했습니다. [0d9b88b](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/50/commits/0d9b88ba5e54423d5a7ecce06c604fb5486934c4)

2023-01-12 12:40 UTC, kimeodml commented on src/pages/Home/components/Map/index.tsx
> +            '<img src={FoodIcon} style="width:68px;height:68px;border-radius:89.5px;"slt="음식점 사진"/>',
수정했습니다. [0d9b88b](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/50/commits/0d9b88ba5e54423d5a7ecce06c604fb5486934c4)

2023-01-12 12:41 UTC, kimeodml commented on src/pages/Home/components/Map/index.tsx
> +                '<div style="display:flex;justify-content:center;text-align:center;border:1px solid #FF7F23;background-color:white;border-radius:32.5px;min-width:205px;height:65px;">',
수정했습니다. [0d9b88b](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/50/commits/0d9b88ba5e54423d5a7ecce06c604fb5486934c4)

2023-01-12 12:42 UTC, kimeodml commented on src/pages/Home/components/Map/index.tsx
> +      naver.maps.Event.addListener(markerCur, 'click', () => {
추가했습니다. [9d18908](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/50/commits/9d18908dc1093c1d4d33924e86898f89c32f93e3) 제가 아직 클린업 함수가 미숙해서 그런데 왜 추가하는지 알 수 있을까요?

2023-01-12 12:45 UTC, kimeodml commented on src/pages/Home/components/Map/index.tsx
> +    for (let i = 0; i < marker.length; i += 1) {
수정했습니다. [4b342c8](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/50/commits/4b342c8a6539bd49188bf8895f6849e5978ba443)

2023-01-12 12:45 UTC, kimeodml commented on src/pages/Home/components/Map/index.tsx
> +      markerClickEvent(markerRef.current, marker[i]);
수정했습니다. [4b342c8](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/50/commits/4b342c8a6539bd49188bf8895f6849e5978ba443)

2023-01-12 12:47 UTC, kimeodml commented on src/pages/Home/components/Map/index.tsx
> +  const selectedMarker = useRef<any | null>(null);
수정했습니다. [4afa320](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/50/commits/4afa320d9e2434142e8aab5b21585abaecdd83b4)

2023-01-12 12:49 UTC, kimeodml commented on src/pages/Home/components/Map/index.tsx
> +      markerRef.current = new naver.maps.Marker({
예시로 만든 마커를 나타내려고 반복문으로 만들었습니다. 현재는 forEach를 사용해 나타내 주었습니다. [4b342c8](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/50/commits/4b342c8a6539bd49188bf8895f6849e5978ba443)

2023-01-12 13:08 UTC, kimeodml commented on src/pages/Home/components/OptionButtons/FilterMenu.tsx
> +import useBoolean from 'utils/hooks/useBoolean';
머지 후 수정했습니다. [bc71d93](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/50/commits/bc71d939b054445c84afa9a01b5145d010247587)

2023-01-13 00:31 UTC, SimYunSup commented on src/pages/Home/components/Map/index.tsx
> +      markerRef.current = new naver.maps.Marker({
반복문으로 만들면서 해당 `markerRef`를 저장하는 로직은 바뀌지 않은 것 같은데요. 해당 `markerRef`를 저장하고 이를 함수에 넘겨줄 이유가 없어보이는데 이렇게 만든 이유가 궁금합니다.

2023-01-13 00:41 UTC, SimYunSup commented on src/pages/Home/components/Map/index.tsx
> +      naver.maps.Event.addListener(markerCur, 'click', () => {
보통 map에 대한 인스턴스를 지우게 되면서 인스턴스가 차지하는 메모리를 비우거나 같거나 다른 컴포넌트에서 지도를 호출했을 때 오류가 발생하는 것을 막기 위해서입니다.
카카오에서는 destory함수를 제공하지 않아 layout을 다시 그리도록 [안내](https://devtalk.kakao.com/t/ionic-3/114302)하거나 메모리를 비우는 함수는 없다고 [안내](https://devtalk.kakao.com/t/map/67731?u=lea.ju)하는 모습을 볼 수 있습니다.

2023-01-15 09:06 UTC, kimeodml commented on src/pages/Home/components/OptionButtons/index.tsx
> +      { isMobile ? <FilterMenu /> : (
수정했습니다. [95c6be2](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/50/commits/95c6be2c7f7d2d6397dbc1c05a73eda0f8f6b71f)
[128fc6a](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/50/commits/128fc6a061d9b08d9ca5e85556d58eff28e714d1)

2023-01-15 10:17 UTC, kimeodml commented on src/pages/Home/components/Map/index.tsx
> +      markerRef.current = new naver.maps.Marker({
useEffect 내부에  `const markers = new naver.maps.Marker({..})`의 형식으로 생성해 `markers`를 넘겨주면 나중에 마커가 많을 때 성능저하를 일으킬 것 같아 markerRef로 선언해 넘겨주었습니다.

2023-01-16 09:04 UTC, kimeodml commented on src/pages/Home/static/marker.ts
> +const marker = [
나중에 없앨거지만 수정했습니다. [b5d6428](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/50/commits/b5d6428b6c31d57fa4916c8347135f3fc304cab0)

2023-01-16 09:04 UTC, kimeodml commented on src/pages/Home/index.tsx
> +          검색어를 입력해주세요.
다른 컴포넌트를 이동할 때마다 클린업 함수로 지도를 지우고 다시 맵 인스턴스로 돌아오면 렌더링되는데 이 상황에서 백그라운드에 유지할 수 있나요...? 아니면 로딩 스피너라도 넣을까요?

2023-01-18 04:17 UTC, SimYunSup commented on src/pages/Home/components/Map/index.tsx
> +      markerRef.current = new naver.maps.Marker({
"마커가 많을 경우" 테스트를 한 결과가 있을까요? 코드를 보기만 할 때에는 없앴을 경우 성능저하를 부르는 코드가 없는데요.

2023-01-18 07:42 UTC, kimeodml commented on src/pages/Home/components/Map/index.tsx
> +      markerRef.current = new naver.maps.Marker({
아, 제가 잘못 생각하고 있었네요. 마커를 참조하는 useRef를 생성하게 되면 메모리 사용량이 늘어서 오히려 더 안 좋아질 수가 있겠네요. useRef로 사용하면 각각의 마커에 이번트를 다루는 데 있어 효율적이라 성능저하가 덜할 것이라 생각했는데 이 또한 useRef라 메모리 사용량이 많아져서 오히려 const markers로 이용하는게 더 효율적이네요. 수정하겠습니다!

2023-01-18 10:00 UTC, kimeodml commented on src/pages/Home/components/Map/index.tsx
> +      markerRef.current = new naver.maps.Marker({
수정했습니다. [1ebd313](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/50/commits/1ebd313167a8674b2280d8fae4f4cc89babc3079)
[eccde10](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/50/commits/eccde109b04f8dbab153e9f3de496fb797ecdef8)

2023-01-20 08:35 UTC, kimeodml commented
UI 변경된 부분 추가했습니다. 구글지도 api 등의 변경 사항은 다음 브랜치에서 수정하겠습니다.

2023-01-20 15:43 UTC, ChoiWonBeen requested changes

2023-01-20 15:43 UTC, ChoiWonBeen commented on src/layout/DefaultLayout/index.tsx
>        {isMobile && <BottomNavigation />}
지금도 검색창에 다녀올때마다 지도를 처음부터 렌더링하고있어요.
중첩 라우팅의 상위 라우팅인 이곳에서 지도를 정의하고 만들어두면 내부 라우팅과는 관계없이 지도를 유지할 수 있겠죠?

2023-01-20 15:43 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/components/MarkerHtml.tsx
> +    </div>
![image](https://user-images.githubusercontent.com/50780281/213741621-1df242c9-9e93-4493-8cb8-af45f5977cc1.png)
마커 스타일링이 변경되지 않은듯 해요~

2023-01-25 08:57 UTC, kimeodml commented on src/pages/Home/components/Map/components/MarkerHtml.tsx
> +    </div>
`장소6` 눌렀을 때 이렇게 안 변했나요..?
![image](https://user-images.githubusercontent.com/88065770/214520547-3931498e-5f2a-4365-85fa-df8f786b00f3.png)

2023-01-25 09:11 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/components/MarkerHtml.tsx
> +    </div>
정렬이 조금 어색하지않나요? ㅋㅋㅋ 
> PC

![image](https://user-images.githubusercontent.com/50780281/214523484-c5a06fd1-4171-4a07-b885-b1dea8b844cb.png)

> Mobile

![image](https://user-images.githubusercontent.com/50780281/214523518-7a5eecd2-2e50-4ed0-b0c1-d7d91494812a.png)

2023-01-25 11:04 UTC, kimeodml commented on src/layout/DefaultLayout/index.tsx
>        {isMobile && <BottomNavigation />}
수정했습니다. [3b533df](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/50/commits/3b533dfa08329b6fbd11eb437dc7d54d72649c86)

2023-01-25 11:37 UTC, SimYunSup requested changes

2023-01-25 11:37 UTC, SimYunSup commented on src/pages/Home/components/Map/index.tsx
> +  const markerHighlightEvent = (markerCur:any, item:Props) => {
`any`타입은 지양해달라고 말씀드렸습니다. 그리고 Props는 해당 컴포넌트의 props로 착각할 수 있으므로 다른 이름을 지어주세요.

2023-01-25 11:37 UTC, SimYunSup commented on src/pages/Home/components/Map/index.tsx
> +  }, [location]);
의도된 deps인가요?

2023-01-25 11:37 UTC, SimYunSup commented on src/pages/Home/components/Map/components/MobileOptions.tsx
> +import styles from '../Map.module.scss';
한 곳에서 스타일을 가져오는 이유라도 있을까요? 나눠놓아도 될 것으로 보이는데요.

2023-01-25 11:37 UTC, SimYunSup commented on src/layout/DefaultLayout/index.tsx
> +      })}
cn을 쓰는 이유가 무엇인가요

2023-01-26 10:29 UTC, kimeodml commented on src/pages/Home/components/Map/components/MobileOptions.tsx
> +import styles from '../Map.module.scss';
Map 컴포넌트에 각각의 컴포넌트를 불러오는 형식이라서 한 곳에 스타일을 몰아 넣었는데 제가 봐도 많아보여서 분리했습니다. [98b915c](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/50/commits/98b915c710ab9db2b29bf833069b9adf2fb4d1cf)

2023-01-26 10:30 UTC, kimeodml commented on src/pages/Home/components/Map/index.tsx
> +  const markerHighlightEvent = (markerCur:any, item:Props) => {
수정했습니다. [f2d3063](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/50/commits/f2d3063d13ae02391f27eceb3d471e52bbb127e4)

2023-01-26 10:36 UTC, kimeodml commented on src/layout/DefaultLayout/index.tsx
> +      })}
cn을 활용해 조건문을 주지 않으면 `<Outlet />` 밑에 지도가 계속 표시 되어서 사용했습니다. 혹시 다른 방법이 있나요?

2023-01-27 07:25 UTC, ChoiWonBeen commented on src/layout/DefaultLayout/index.tsx
> +      })}
지도 전체에 absolute와 z-index를 두고, 감싸는 레이아웃에서 z-index를 한 칸 높게 두면 해결되지 않을까요?

2023-01-28 04:45 UTC, kimeodml commented on src/layout/DefaultLayout/index.tsx
> +      })}
웹페이지 기본 배경화면에 background-color를 주지 않아서 z-index를 줘도 검색 지도가 보이게 되어 background-color를 추가하면 또 z-index 때문에 지도 페이지에선 지도가 가려지더라고요. cn의 방식으로 가야할것 같아요.

2023-01-28 05:17 UTC, kimeodml commented on src/pages/Home/components/Map/index.tsx
> +  }, [location]);
빈 배열을 넣으면 마커가 뜨질 않아서 location을 추가하였습니다.

2023-01-28 06:21 UTC, kimeodml commented on src/pages/Home/components/Map/components/MarkerHtml.tsx
> +    </div>
수정했습니다. [86c9d40](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/50/commits/86c9d4097844012c00e477ac500133523c2faf8d) [8fbac83](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/50/commits/8fbac83c8e33844ee67f42095ef7b46abfd831be)

2023-01-28 14:33 UTC, ChoiWonBeen requested changes
거의 다 온 것 같네요 ㅋㅋ
아래 몇가지 더 수정할만한 사항도 언급해봤어요.
로딩시간동안 스피너를 보여줄 수 있으면 좋을 것 같은데.. 이것도 한번 고려해보죠 ㅋㅋ

<img width="366" alt="image" src="https://user-images.githubusercontent.com/50780281/215271928-cfcb36a3-63e2-4789-9a6c-872426967df7.png">
모바일에선 확대바가 불필요해보이고, 이때문인지 툴팁 글자가 줄바꿈이되어요. width를 auto로 설정할 수 있게끔 조정이 필요해보여요.
마커의 주변도 디자인보다 두꺼운 것 같구요??

2023-01-28 14:33 UTC, ChoiWonBeen commented on src/layout/DefaultLayout/index.tsx
> +      })}
아래처럼 줄여서 사용할 수 있을 것 같아요.
```suggestion
      <div className={cn({ [styles.home]: location.pathname !== '/' })}
```

2023-01-28 14:33 UTC, ChoiWonBeen commented on src/pages/Home/index.tsx
>  }
`<Home />` 안에 `<Map />`만 들어있는데 그냥 `<Map />`만 렌더링하는건 어떨까요?

2023-01-28 14:33 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/components/MobileOptions/MobileOptions.module.scss
> +    &--clicked {
사소하지만 `selected`가 더 적절할 것 같아요!

2023-01-30 02:06 UTC, SimYunSup commented on src/pages/Home/components/Map/index.tsx
> +  }, [location]);
일반적으로 재사용할 수 있도록 만드려면 `useGeolocation`의 상태와 지도 렌더링의 상태를 받아와서 useEffect에서 사용하는 것이 맞는 것 같습니다.

2023-01-30 02:06 UTC, SimYunSup commented on src/pages/Home/components/Map/index.tsx
> +      }
제공된 UI로 봐서는 selectedMarker가 ref로 저장될 것이 아니라 state로 저장되야 할 것으로 보입니다. 다른 side effect를 트리거해야 할 것으로 보이니까요.

2023-01-30 10:22 UTC, kimeodml commented on src/layout/DefaultLayout/index.tsx
> +      })}
수정했습니다. [c6f3226](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/50/commits/c6f322676d567c0975e74acc79c7afdb5d1c323b)

2023-01-30 10:31 UTC, kimeodml commented on src/pages/Home/components/Map/components/MobileOptions/MobileOptions.module.scss
> +    &--clicked {
selected로 변경하면서 버튼 너비도 수정했습니다. 지도 옵션이 고정되기 때문에 지도 확대 디자인과 위치를 변경했습니다. [8f0ec9c](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/50/commits/8f0ec9c14baac5b7dc66134ebca14f1f88d7a8b6)
<img src="https://user-images.githubusercontent.com/88065770/215451534-8b8271fd-5207-4d4d-a751-254f29967dac.png" width="300"/>

2023-01-30 10:31 UTC, kimeodml commented on src/pages/Home/index.tsx
>  }
`<Home />` 컴포넌트에 지도 말고도 핀 보기 컴포넌트나 주소 모달창이 렌더링할 수도 있을 것 같아서 혹시 몰라 `<Home />` 컴포넌트에 렌더링 한 건데 그냥 바로 `<Map />` 컴포넌트만 렌더링할까요?

2023-01-31 02:06 UTC, ChoiWonBeen commented on src/pages/Home/index.tsx
>  }
오 그런 이유라면 유지해도 괜찮겠네요 :+1:

2023-02-01 11:22 UTC, kimeodml commented on src/pages/Home/components/Map/index.tsx
> +      }
이 기능 다음 브랜치로 넘길 수 있을까요? 해결해 보려고 하는데 오류가 계속 생겨서 오래걸릴 것 같아요.

2023-02-03 03:01 UTC, SimYunSup approved these changes

2023-02-03 03:01 UTC, SimYunSup commented on src/pages/Home/components/Map/index.tsx
> +      }
알겠습니다.

2023-02-03 08:12 UTC, ChoiWonBeen approved these changes

2023-02-03 08:12 UTC, merged