Feature/#67 비밀번호 찾기 기능 추가 및 favicon 변경
BCSDLab/TEMP_PROJECT_FE pull request #53
Opened 2023-01-31 08:38 UTC by chaeseungyun

비밀번호 찾기 기능을 구현했습니다.
Figma에 아이디 입력칸이 없어서 임의로 추가했습니다.
아이디가 존재하는지 체크하는 api가 따로 없어서 아이디 중복 체크 api를 사용했습니다.

새로운 쩝쩝박사 favicon울 추가하고 웹 title을 수정했습니다.

모달 UI를 수정했습니다.

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [ ] Docs updated for breaking changes

### Screenshot

2023-02-01 13:25 UTC, ChoiWonBeen requested changes
고생하셨어요. 더 알아보면 좋을 부분들 확인해드렸고,
PR 템플릿에 존재하는 체크박스는 본인이 PR을 올리기 전에 직접 확인하는 목록이니 스스로 확인하면서 체크박스를 채워주세요.
그리고 상단바 로고에도 해당 파비콘 asset에 담아둔거 사용해 추가해주세요~

2023-02-01 13:25 UTC, ChoiWonBeen commented on public/index.html
>    </head>
지난번에도 언급했지만, `og:` 메타태그나 `twitter:`메타태그처럼 헤더에 좋은 요소들이 많으니 찾아서 추가해주세요

2023-02-01 13:25 UTC, ChoiWonBeen commented on src/api/user/index.ts
> +export const checkIdExist = (param: EmailParams) => userApi.get(`/exists?account=${param.account}`);
얘만 혼자 타입 이름이 통일이 안된 것 같죠? ㅋㅋ 
근데 그건 둘째치고 이 함수, 좀 위에 `checkIdDuplicate`라는 이름으로 존재합니다.

2023-02-01 13:25 UTC, ChoiWonBeen commented on src/pages/Auth/FindIDPassword/index.tsx
> +  };
이런 로직들은 충분히 훅으로 분리해서 작성하는게 더 깔끔할 거예요.

2023-02-01 13:25 UTC, ChoiWonBeen commented on src/pages/Auth/FindIDPassword/VerifyCode.tsx
>  import { useState } from 'react';
`VerifyCode`와 `VerifyField`도 컴포넌트에 담아두는게 구조상 더 적절할 것 같은데요?

2023-02-01 13:25 UTC, ChoiWonBeen commented on src/pages/Auth/FindIDPassword/index.module.scss
>  }
사소하지만, 다른 파일들을 참고하면 `index.module.scss`로 안쓰고
`컴포넌트명.module.scss`처럼 작성했네요. 얘만 다르니 바꿔두는게 어떨까 싶어요.
`VerifyCode`와 `Field`에서 해당 scss파일을 참조한다면, 완전히 분리해두는것도 좋아보이네요.
다른 폴더들 참고해주세요!

2023-02-01 13:25 UTC, ChoiWonBeen commented on src/api/user/entity.ts
> +export interface EmailParams {
정확히 어떤 파라미턴지 이해하기 어려운데, 적절한 네이밍이 있을 것 같아요.

2023-02-03 01:14 UTC, chaeseungyun commented on src/pages/Auth/FindIDPassword/index.module.scss
>  }
모든 컴포넌트가 이 index.module.scss를 참조합니다
UI 구성이 같기 때문인데요, 컴포넌트마다 분리하는 것은 조금 비효율적일 수도 있다고 생각해서 index로 묶어두었습니다.

2023-02-03 01:14 UTC, chaeseungyun commented on src/api/user/index.ts
> +export const checkIdExist = (param: EmailParams) => userApi.get(`/exists?account=${param.account}`);
뒤늦게 파악하긴 했는데.. 파라미터가 달라서 일단 분리했었습니다. 위 함수 재활용하겠습니다

2023-02-03 05:11 UTC, jaewoogwak reviewed
고생하셨습니다~ 코멘트 남겼어요

2023-02-03 05:11 UTC, jaewoogwak commented on src/pages/Auth/FindIDPassword/VerifyCode.tsx
> +      if (param.id === 'id') {
`param.id`가 `id`라는 조건인데 `param.id`는 id 값을 들고 있을거라고 유추하게 되네요 `param.id` 대신 `param.type` 같이 더 잘 나타내는 파라미터 네이밍을 써주면 좋을거 같아요

2023-02-03 05:11 UTC, jaewoogwak commented on src/pages/Auth/FindIDPassword/VerifyCode.tsx
> +      nextStep();
`nextStep()`만 봐선 함수가 무슨 일을 하는지 파악하기 힘든 거 같아요

2023-02-06 08:07 UTC, kimeodml requested changes
오류 문구 뜰 때 문구가 뜬 다음 svg 이미지가 시간차 있게 뜨는 데 혹시 이 부분도 같이 수정해 줄 수 있나요?

2023-02-06 08:07 UTC, kimeodml commented on src/pages/Auth/FindIDPassword/ChangePassword.tsx
>    const [isComplete, setIsComplete] = useState<boolean>();
type이 boolean인 상태값들은 잘 확인해서 `useBooleanState` hook으로 사용하면 될 것 같아요.

2023-02-06 08:07 UTC, kimeodml commented on src/pages/Auth/FindIDPassword/ChangePassword.tsx
>      <div className={style.layout}>
style 추가 아직 모바일만 하신 건가요?

2023-02-06 08:07 UTC, kimeodml commented on src/pages/Auth/FindIDPassword/VerifyCode.tsx
>            으로 가입된 아이디는
글자가 길면 다음 줄로 애매하게 넘어가는데 줄 바꿈을 하든가 letter-spacing으로 줄여야 할 것 같아요.

2023-02-06 13:24 UTC, chaeseungyun commented on src/pages/Auth/FindIDPassword/ChangePassword.tsx
>    const [isComplete, setIsComplete] = useState<boolean>();
넵 useBooleanState 훅 사용하도록 하겠습니다

2023-02-06 13:24 UTC, chaeseungyun commented on src/pages/Auth/FindIDPassword/VerifyCode.tsx
>            으로 가입된 아이디는
말씀해주신 부분 수정하겠습니다

2023-02-06 13:25 UTC, chaeseungyun commented on src/pages/Auth/FindIDPassword/ChangePassword.tsx
>      <div className={style.layout}>
네 현재 모바일만 구성했습니다.
svg가 조금 늦게 뜨는 부분은 조금 더 생각해 보아야 할 것 같습니다.
아직 원인 파악을 못했습니다

2023-02-06 13:26 UTC, chaeseungyun commented on src/pages/Auth/FindIDPassword/VerifyCode.tsx
> +      if (param.id === 'id') {
앞에서도 type을 사용했었는데 여기선 id라고 했네요
바로 수정하겠습니다

2023-02-06 13:27 UTC, chaeseungyun commented on src/pages/Auth/FindIDPassword/VerifyCode.tsx
> +      nextStep();
다음 단계에서 로그인을 하거나 비밀번호를 변경하므로 loginOrChangePassword라는 함수명으로 수정해보겠습니다

2023-02-08 08:33 UTC, chaeseungyun commented on src/pages/Auth/FindIDPassword/VerifyCode.tsx
>  import { useState } from 'react';
VerifyField에서 VerifyCode를 사용하므로 Code는 컴포넌트로 이동하고 Field는 유지해야한다고 생각하는데 어떠신가요
우선 VerifyCode는 컴포넌트에 담아두었습니다

2023-02-08 08:40 UTC, chaeseungyun commented on src/api/user/entity.ts
> +export interface EmailParams {
checkIdDuplicate를 재사용하게 됨으로서 위 파라미터는 삭제하겠습니다.

2023-02-16 10:36 UTC, ChoiWonBeen approved these changes
로그인페이지에도 기존 로고 대체이미지가 남아있는데 해당 이미지 추적해서 바꾼다음 머지해주세요~
기존 이미지는 없애도 될 것 같네요.

2023-02-20 05:29 UTC, kimeodml approved these changes
고생하셨습니다~

2023-02-22 10:52 UTC, merged