Feature/#17 PC버전 검색 결과창 구현
BCSDLab/TEMP_PROJECT_FE pull request #54
Opened 2023-02-12 15:35 UTC by jaewoogwak

## [PC버전 검색 결과 추가 #46] request

PC 버전 검색 결과창 UI 구현했습니다.

디자인팀에게 PC 버전 웹을 모바일 버전으로 축소하면 화면이 어떻게 배치되는지에 대한 답을 아직 듣지 못해서 `SearchItemPC.tsx`에 따로 구현하였습니다. `SearchItemPC.tsx` 중심으로 봐주시면 될 거 같습니다.

모바일로 축소하면 어떻게 화면이 배치되는지 파악하면 추후 적용할 예정입니다.

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

### Screenshot

2023-02-13 06:43 UTC, hanagertrudekim reviewed
궁금한점 하나 리뷰했습니다~ 수고하셨습니다~

2023-02-13 06:43 UTC, hanagertrudekim commented on src/pages/SearchDetails/components/SearchItemPC.tsx
> +              <span className={styles.item__closing}>- 21:00에 영업 종료</span>
className을 `status--close`로 통일하는게 아닌 `item__closing` 을 쓰신 이유가 있나요??
확인해보니 scss 파일에는 두개 다 존재해서요

2023-02-13 08:08 UTC, jaewoogwak commented on src/pages/SearchDetails/components/SearchItemPC.tsx
> +              <span className={styles.item__closing}>- 21:00에 영업 종료</span>
32라인의 `item__status--open`은 `item__status--closed`와 같은 맥락으로 영업중/영업 종료 상태를 나타내려 했고
33라인은 영업 종료 시간 자체를 나타내려고해서 `item__closing`으로 나타냈습니다

2023-02-16 13:57 UTC, ChoiWonBeen requested changes
고생하셨어요~ 리뷰 남겼으니 확인하고 변경할 것들 변경해주세요!
리뷰가 늦어져 죄송합니다 🙇‍♂️

2023-02-16 13:57 UTC, ChoiWonBeen commented on src/pages/SearchDetails/SearchDetails.module.scss
> +    background-color: #03c75a;
이거..모바일이면 초록색으로 나오는데 의도된건가요?
<img width="1740" alt="image" src="https://user-images.githubusercontent.com/50780281/219366763-7364999b-4300-4c3d-a829-1c130a767cdc.png">

2023-02-16 13:57 UTC, ChoiWonBeen commented on src/pages/SearchDetails/components/SearchItemPC.tsx
> +          <img className={styles['image__other--fourth']} alt="가게 이미지 없음" src={defaultImage} />
2번째, 3번째, 4번째 이미지에 서로 다른 CSS가 할당될 이유가 없어 보이는데..
혹시 가운데 사진의 height이 1px더 작아서 이런거라면 디자인쪽의 실수일 가능성이 높아요 ㅋㅋ

2023-02-16 13:57 UTC, ChoiWonBeen commented on src/pages/SearchDetails/components/SearchItemPC.tsx
> +        <img className={styles.image__main} alt="가게 이미지 없음" src={defaultImage} />
개인적으로 컴포넌트에 임시 데이터를 담을 때에는 API Response를 쓴 것 처럼 목업 함수를 만들어서 그 함수가 반환하는 값으로 데이터를 담아두면 바꾸기에도, 읽기에도 훨씬 좋지 않을까 싶어요.
해당 이미지가 없으면 임시 이미지를 보이게 하고, 시간이나 가게 이름 등은 임시 static데이터로 만들어두면 더 깔끔하겠죠?

2023-02-16 13:57 UTC, ChoiWonBeen commented on src/pages/SearchDetails/components/SearchItemPC.tsx
> +              010-0000-0000
사소하지만, 개인적으로 한 줄에 텍스트를 담는걸 선호해요
```suggestion
              {`전화하기 ${data.phoneNumber}`}
```

2023-02-16 13:57 UTC, ChoiWonBeen commented on src/pages/SearchDetails/components/SearchItemPC.tsx
> +            </div>
실제로 전화를 바로 걸 수 있도록 a태그를 사용해 링크를 거는 방법도 있는데 한번 찾아보시죠!

2023-02-16 13:57 UTC, ChoiWonBeen commented on src/pages/SearchDetails/components/SearchItemPC.tsx
> +    <div className={styles.item}>
`.item`에 `hover - background`를 주셨던데 이 카드 자체를 링크로 만들면 어떨까요?

2023-02-18 12:28 UTC, jaewoogwak commented on src/pages/SearchDetails/components/SearchItemPC.tsx
> +    <div className={styles.item}>
네 좋아보이네요 적용하겠습니다~

2023-02-18 12:29 UTC, jaewoogwak commented on src/pages/SearchDetails/SearchDetails.module.scss
> +    background-color: #03c75a;
아 테스트 해보다가 모바일을 놓쳤네요..ㅎ 수정했습니다.
[3d70124](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/54/commits/3d70124725174fe9d32471e7fe437cb85c75f58b)

2023-02-18 12:29 UTC, jaewoogwak commented on src/pages/SearchDetails/components/SearchItemPC.tsx
> +    <div className={styles.item}>
이 부분은 아이템 클릭 후 아이템 관련 상세페이지 작업할 때 추가하는건 어떨까요?

2023-02-21 06:52 UTC, ChoiWonBeen commented on src/pages/SearchDetails/components/SearchItemPC.tsx
> +    <div className={styles.item}>
상세페이지보다는 지금 브랜치의 기능으로 생각하는게 더 적절해보이긴 해요

2023-02-27 14:48 UTC, jaewoogwak commented on src/pages/SearchDetails/components/SearchItemPC.tsx
> +            </div>
전화거는 거 추가하고 mock함수를 만들어서 임시 데이터를 사용하도록 하였습니다.
[bdf3753](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/54/commits/bdf3753d1a1aedc7217d03b2e37a01321c669aeb)
[03ce6fa](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/54/commits/03ce6faa6a41ff6da5bd3adc32a697bcbf58546b)

2023-02-28 16:00 UTC, jaewoogwak commented on src/pages/SearchDetails/components/SearchItemPC.tsx
> +    <div className={styles.item}>
적용했습니다 [fb70c75](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/54/commits/fb70c751720aec4ef8a79776b5a10a0aeb9bc06c)

2023-03-03 06:25 UTC, ChoiWonBeen requested changes
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/50780281/222647122-edeab04a-566e-45fc-9456-c6fdb439e6f3.png">
pc에서 이 부분 너무 겹치는 것 같은데 확인해주세요~

2023-03-03 06:25 UTC, ChoiWonBeen commented on src/pages/SearchDetails/components/SearchItemPC.tsx
> +              {`전화하기    ${phoneNumber}`}
전화번호 링크가 잘못 걸린 것 같죠?
```suggestion
            <a href={`tel:${phoneNumber}` className={styles.item__phone}>
              {`전화하기    ${phoneNumber}`}
```

2023-03-03 06:25 UTC, ChoiWonBeen commented on src/pages/SearchDetails/components/SearchItemPC.tsx
> +        <img className={styles.image__main} alt={imageAlt} src={defaultImage} />
실제 데이터를 쓰게 된다면 defaultImage를 조건부로 쓰게 되겠죠?
목업데이터라면 구분해두는게 좋아보이네요.
```suggestion
        <img className={styles.image__main} alt={imageAlt} src={shop.image ?? defaultImage} />
```

근데 또 아래에는 잘 돼있네요? ㅋㅋ

2023-03-03 07:16 UTC, jaewoogwak commented on src/pages/SearchDetails/components/SearchItemPC.tsx
> +              {`전화하기    ${phoneNumber}`}
링크 href 값 수정하고 기존에 카드를 클릭하면 바로 이동하도록 변경해서 전화번호 클릭 시 전화 기능이 작동하지 않는 현상도 해결했습니다.
원인: 이벤트 버블링
[2f8ba7f](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/54/commits/2f8ba7f621ed9d89886bf3435639b74fa7784363)

2023-03-03 07:16 UTC, jaewoogwak commented on src/pages/SearchDetails/components/SearchItemPC.tsx
> +        <img className={styles.image__main} alt={imageAlt} src={defaultImage} />
수정했습니다.
[5a10598](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/54/commits/5a10598f40b0eefd59cac85fb4aa9b7b6fbc8695)

2023-03-03 07:22 UTC, ChoiWonBeen approved these changes

2023-03-03 07:22 UTC, merged