Feature/#58  쩝박 설정창 UI 추가
BCSDLab/TEMP_PROJECT_FE pull request #59
Opened 2023-03-14 17:01 UTC by hyejun0228

figma를 참고해 쩝박 설정창 UI을 추가했습니다.

2023-03-15 01:18 UTC, jaewoogwak reviewed
고생하셨어요~ 아래 리뷰 남겼으니 확인 부탁드립니다.

그리고 /setting 페이지 확인해보면 중앙정렬이 안된채로 왼쪽에 치우쳐서 나오는데 확인 부탁드립니다~

2023-03-15 01:18 UTC, jaewoogwak commented on src/pages/Setting/components/idChange.tsx
> +export default function idChage(): JSX.Element {
컴포넌트 이름은 대문자로 시작해야할거 같아요

2023-03-15 01:18 UTC, jaewoogwak commented on src/App.tsx
> +          <Route path="/setting" element={<Setting />} />
URL 이동할 때 /setting으로 이동하면 다시 /로 돌아가는데, `<ProtectedRoute />`안에 라우팅을 걸어놔서 그런거 같아요. 이유가 있나요?

2023-03-15 01:28 UTC, daepan requested changes
PR에 문제가 많아 보여서 한번 내용체크해보시고 다시 PR을 작성하면 좋을 것 같습니다.
1. PR 기본 템플릿을 지우지 마세요
- PR의 기본적인 목적은 자신이 작성한 코드가 기능에 대한 개선이나 추가에 대한 코드가 올바른 방법인지, 우리들의 제품에 들어갈만한 코드인지 평가하는 과정입니다.
그래서 그에 대한 평가를 받기 위해서는 자신의 코드가 어디가 변화하였고 어떻게 동작하는지를 보여줄 수 있도록 서술하거나 매체자료를 활용하면 좋습니다.
이를 저희 보고서 형식으로 정리한 PR 템플릿을 지우지 마시고 참고해주세요
2. lint 경고를 확인해주세요
현재 머지버튼에 빨간불이 들어와있습니다. stylelint에 대한 설정을 확인해주시고 바로 머지가 가능한 상태로 코드들을 수정하고 올려주세요

단순한 Approve/Reject 리뷰를 떠나서 개발자간의 대화에서 건설적인 대화의 시간을 가지셨으면 좋겠습니다.
이번 PR을 닫으시고 lint수정과 PR 템플릿을 참고해서 자신의 코드를 설명하는 PR을 다시 올려주시면 감사하겠습니다.

2023-03-15 02:00 UTC, jaewoogwak commented
> PR에 문제가 많아 보여서 한번 내용체크해보시고 다시 PR을 작성하면 좋을 것 같습니다.
> 
> 1. PR 기본 템플릿을 지우지 마세요
> 
> * PR의 기본적인 목적은 자신이 작성한 코드가 기능에 대한 개선이나 추가에 대한 코드가 올바른 방법인지, 우리들의 제품에 들어갈만한 코드인지 평가하는 과정입니다.
>   그래서 그에 대한 평가를 받기 위해서는 자신의 코드가 어디가 변화하였고 어떻게 동작하는지를 보여줄 수 있도록 서술하거나 매체자료를 활용하면 좋습니다.
>   이를 저희 보고서 형식으로 정리한 PR 템플릿을 지우지 마시고 참고해주세요
> 
> 2. lint 경고를 확인해주세요
>    현재 머지버튼에 빨간불이 들어와있습니다. stylelint에 대한 설정을 확인해주시고 바로 머지가 가능한 상태로 코드들을 수정하고 올려주세요
> 
> 단순한 Approve/Reject 리뷰를 떠나서 개발자간의 대화에서 건설적인 대화의 시간을 가지셨으면 좋겠습니다. 이번 PR을 닫으시고 lint수정과 PR 템플릿을 참고해서 자신의 코드를 설명하는 PR을 다시 올려주시면 감사하겠습니다.

2023-03-15 02:18 UTC, ChoiWonBeen requested changes
우선 스타일린트 Extension 먼저 설치하셔야 할 것 같고..
PR 작성내용에 대한 부분은 위 코멘트 지켜주시면 될 것 같아요.

추가로 commit header의 `style: ` 은 스타일링 변경이 아닌, 오탈자 수정 / 린트를 위한 공백 맞추기 등 코드 스타일링을 위한 헤더입니다.
디자인 수정은 기능인 `feat:`에 가까워요.

2023-03-15 02:18 UTC, ChoiWonBeen commented on src/pages/Setting/components/Setting.module.scss
> +}
yarn lint를 해보시면 (혹은 StyleLint Extension만 설치하더라도) 모든 scss파일에 에러가 납니다.
인덴트가 2space가 아닌 tab으로 들어가서일 것 같은데, 린트 확인해주세요

2023-03-15 02:18 UTC, ChoiWonBeen commented on src/pages/Setting/components/index.tsx
> +            <Link to="/"><ArrowRight /></Link>
프로젝트의 클래스네임은 `bem-naming-convention`을 따릅니다.
[잘 설명한 글](https://nykim.work/15)이 있으니 보면서 css네이밍을 수정해주세요.
아마 한번 보는걸론 이해하기 쉽지 않을테니, 다른 분들의 코드를 참고하면서 비교해주세요.

2023-03-15 02:18 UTC, ChoiWonBeen commented on src/pages/Setting/components/index.tsx
> +        </div>
`components/common`에 뒤로가기용 공용 컴포넌트가 있던거같은데 사용할 수 없었을까요?

2023-03-17 04:03 UTC, hyejun0228 commented on src/pages/Setting/components/idChange.tsx
> +export default function idChage(): JSX.Element {
컴포넌트 대문자로 수정했습니다!
setting 페이지가 아직 모바일 UI로 밖에 안나와서 Pc UI는 나중에 추가해야할것 같습니다.

2023-03-17 04:15 UTC, hyejun0228 commented on src/App.tsx
> +          <Route path="/setting" element={<Setting />} />
`<ProtectedRoute />` 가 설정창 UI에 필요하지 않다고 생각해 따로 빼줬습니다..!

2023-03-17 04:17 UTC, hyejun0228 commented
> Member

PR 기본 템플릿 형식 지켜서 다시 올렸습니다!

2023-03-17 04:20 UTC, hyejun0228 commented
> PR에 문제가 많아 보여서 한번 내용체크해보시고 다시 PR을 작성하면 좋을 것 같습니다.
> 단순한 Approve/Reject 리뷰를 떠나서 개발자간의 대화에서 건설적인 대화의 시간을 가지셨으면 좋겠습니다. 이번 PR을 닫으시고 lint수정과 PR 템플릿을 참고해서 자신의 코드를 설명하는 PR을 다시 올려주시면 감사하겠습니다.

PR 템플릿 형식 지켜서 다시 올렸습니다! 다음부터는 주의하겠습니다.
@daepan

2023-03-17 04:21 UTC, hyejun0228 commented on src/pages/Setting/components/Setting.module.scss
> +}
수정했습니다! 
68fd9652d86cd3712470cde4701c9718b0c61e5c

2023-03-17 06:52 UTC, hyejun0228 commented on src/pages/Setting/components/index.tsx
> +        </div>
수정했습니다! 
4c989be1b02008f531bc3a587787467a87b05816

2023-03-18 04:34 UTC, chaeseungyun reviewed
고생하셨습니다
궁금한거 하나 적어보았습니다!

2023-03-18 04:34 UTC, chaeseungyun commented on src/pages/Setting/components/idChange.tsx
> +      <div className={styles['meue-back']}>&lt;</div>
추가하신 svg를 사용하지 않고 &lt를 적으신 이유가 있으신가요??

2023-03-19 05:23 UTC, ChoiWonBeen requested changes
포맷 잘 지켜졌네요 👍 
이제 몇가지 수정사항들과 `bem-naming-convention`만 좀 맞춰주면 끝날 것 같아요.
추가적으로 로그인되지 않은 상황에서 setting페이지에 접근했을때에 대한 로직도 생각해보면 좋을듯함다

2023-03-19 05:23 UTC, ChoiWonBeen commented on src/pages/Setting/components/index.tsx
> +          <div className={styles['current-text']}>fgnsdbcxb</div>
`useAuth()` hook을 만들어두었는데 이를 이용하면 쉽게 아이디에 접근할 수 있어요.
```ts
  const auth = useAuth();
```
```suggestion
          <div className={styles['current-text']}>{auth?.account}</div>
```

2023-03-19 05:23 UTC, ChoiWonBeen commented on src/pages/Setting/components/index.tsx
> +        </div>
하이퍼링크가 화살표에만 붙어있으니 UX적으로 상당히 불편하네요. 블록 전체를 링크로 감싸는 건 어떨까요?
그리고 bem convention도 다시 한번 생각해주세요 ㅋㅋ

2023-03-19 05:23 UTC, ChoiWonBeen commented on src/pages/Setting/components/index.tsx
> +          </div>
버전에 대한 API가 있는지 확인해볼 필요도 있어보이네요.

2023-03-19 05:23 UTC, ChoiWonBeen commented on src/App.tsx
>          <Route element={<ProtectedRoute />}>
`DefaultLayout`에 포함되지 않게 만든 이유가 있을까요?
모바일 UI로 보면 하단바가 있는게 더 적절하다는 생각이 들어서요

2023-03-19 05:23 UTC, ChoiWonBeen commented on src/pages/Setting/components/Setting.module.scss
> +}
로그인이나 회원가입 등 다른 UI의 반응형을 보면 중앙에 모여잇게끔 만들었기에 맞춰서 중앙정렬되게끔 통일하면 더 좋을거같아요

2023-03-19 05:24 UTC, ChoiWonBeen commented on src/pages/Setting/components/index.tsx
> +          <div className={styles['current-text']}>fgnsdbcxb</div>
+ 로그인되지 않았을 때는 auth가 null이라 나오지 않을텐데, 
비로그인 상태에서 해당 페이지에 접근하지 못하도록 막는 장치가 필요해보이네요

2023-03-19 11:23 UTC, hyejun0228 commented on src/pages/Setting/components/idChange.tsx
> +      <div className={styles['meue-back']}>&lt;</div>
초반에는 svg를 사용한다는 생각을 하지 못해서 &lt을 적었습니다..! 지금은 svg로 수정했습니다

2023-03-19 12:11 UTC, hyejun0228 commented on src/App.tsx
>          <Route element={<ProtectedRoute />}>
figma에서 설정창UI을 보면 하단바가 포함돼있지 않고, 화면에서 탈퇴하기 버튼과 로그아웃 버튼이 하단바와 겹치게 되어 `DefaultLayout`에서 포함되지 않게 만들었습니다.  설정창 UI밑부분을 조금 변경해 하단바가 있게 수정할까요?!

2023-03-19 12:36 UTC, hyejun0228 commented on src/pages/Setting/components/Setting.module.scss
> +}
수정했습니다!
af94415c4423664452d0804940b9429b1ab2678e

2023-03-19 13:37 UTC, jaewoogwak commented
lint 에러난거 수정해주시고 원빈이가 언급한거 수정하고나면 좋아보입니다~

2023-03-19 13:38 UTC, jaewoogwak reviewed
lint 에러난거 수정해주시고 원빈이가 언급한거 수정하고나면 좋아보입니다~
수정완료되면 approve 할게요

2023-03-20 00:25 UTC, ChoiWonBeen commented on src/App.tsx
>          <Route element={<ProtectedRoute />}>
로그아웃/탈퇴하기가 과하게 밑에 내려가있다는 느낌도 들어요. slide를 가능하게 주면 문제는 없을거같아요.
둘 다 해보고 괜찮은 쪽으로 가는거로하죠 ㅋㅋ

2023-03-20 02:08 UTC, haejinyun commented
수고하셨습니다!

2023-03-20 08:11 UTC, hyejun0228 commented on src/pages/Setting/components/index.tsx
> +            <Link to="/"><ArrowRight /></Link>
수정했습니다! 
ff8004694c0a4f4c715436803a8ad3da54b49a4c

2023-03-20 08:11 UTC, hyejun0228 commented on src/pages/Setting/components/index.tsx
> +        </div>
수정했습니다!
ff8004694c0a4f4c715436803a8ad3da54b49a4c

2023-03-27 04:33 UTC, KimKyungYun reviewed
고생많으셨습니다~! 디자인 관련해서 figma와 다른 몇가지 수정 사항들이 보여 적어두었습니다!

2023-03-27 04:33 UTC, KimKyungYun commented on src/pages/Setting/components/index.tsx
> +        <div className={styles['account__sub-title']}>계정 관리</div>
font weight나 margin등 디자인 변경이 필요해 보입니다.  account__sub-title속성에 계정관리와 속성 사이의 간격이 부족하고 font-weight도 500으로 설정해주셔야 할 것 같습니다. 그리고 왼쪽으로 더 붙여서 정렬해주어야 할 것 같습니다~!

2023-03-27 04:33 UTC, KimKyungYun commented on src/pages/Setting/components/index.tsx
> +            <div className={styles.account__text}>아이디 변경</div>
아이디를 표시해주는 부분이 figma와 다르게 너무 왼쪽으로 치우쳐져 있고, 글씨의 색도 다르게 설정되어 있습니다! 
figma에서는 #ff7f23 색상을 사용하고 있네요!

2023-03-27 04:33 UTC, KimKyungYun commented on src/pages/Setting/components/index.tsx
> +        <div className={styles['service__sub-title']}>서비스</div>
sub-title이 왼쪽으로 더 붙고 위의 계정관리 목록과는 상하 여백이 더 필요해보입니다!

2023-03-27 04:33 UTC, KimKyungYun commented on src/pages/Setting/components/index.tsx
> +      </div>
figma에는 좌측으로 정렬되어있는데 가운데로 정렬이 된 것 같습니다. 
좌측정렬로 붙도록 수정하면 될 것 같습니다~!

2023-03-27 08:12 UTC, hyejun0228 commented on src/pages/Setting/components/index.tsx
> +          <div className={styles['current-text']}>fgnsdbcxb</div>
수정했습니다!
77e42ea667a0b0ce83db590d1d6f4524b4f6eaa5

2023-03-27 08:13 UTC, hyejun0228 commented on src/pages/Setting/components/index.tsx
> +      </div>
수정했습니다!
77e42ea667a0b0ce83db590d1d6f4524b4f6eaa5

2023-03-27 08:33 UTC, hyejun0228 commented on src/pages/Setting/components/index.tsx
> +        <div className={styles['account__sub-title']}>계정 관리</div>
font-weight 수정했습니다!
margin 등은 figma디자인과 최대한 비슷하도록 수정하려 했으나 margin이 통일되지 않아 코드를 통일되게 짜는데 어려움이 있어 계정관리란은 `14px` , 서비스란은 `12.5px` 로 통일 했습니다..!
9e6283d69d11832c8338c689a5c1d4c4281a70bc

2023-03-27 08:34 UTC, hyejun0228 commented on src/pages/Setting/components/index.tsx
> +            <div className={styles.account__text}>아이디 변경</div>
수정했습니다! 
9e6283d69d11832c8338c689a5c1d4c4281a70bc

2023-03-27 08:40 UTC, hyejun0228 commented on src/pages/Setting/components/index.tsx
> +        <div className={styles['service__sub-title']}>서비스</div>
수정했습니다!
00dab06a985dcf2e36b8e93a071183beccc2762b

2023-03-27 08:52 UTC, hyejun0228 commented on src/App.tsx
>          <Route element={<ProtectedRoute />}>
수정했습니다!
72511e553f4312b88b9ee66392b94a5a80312196

2023-03-27 08:56 UTC, hyejun0228 commented on src/pages/Setting/components/index.tsx
> +          </div>
스웨거에 버전에 대한 API가 없는것같습니다. 혹시 백엔드에 요청을 해야하는 사항일까요?

2023-03-27 14:44 UTC, KimKyungYun reviewed
디자인 사항은 다 잘 수정된 것으로 보입니다!
근데 실행 시키면 에러가 나옵니다.
아래 체크해두었으니 한번 확인 부탁드립니다~

2023-03-27 14:44 UTC, KimKyungYun commented on src/App.tsx
> +import IdChange from 'pages/Setting/components/IdChange';
해당 페이지의 원본에 오타가 있습니다~ 컴포넌트 명을 소문자인 idChange로 작성하시고 대문자로 호출하셨어요!
그리고 idChange 컴포넌트의 리턴값이 IdChage로 오타가 있구요
혹시 테스트 케이스 작성하시고 지우시지 않은 건가 궁금해서 질문해봅니다

2023-03-27 14:44 UTC, KimKyungYun commented on src/pages/Setting/components/idChange.tsx
> +export default function IdChage(): JSX.Element {
여기 이름이 잘못되었어요!

2023-03-27 14:52 UTC, hyejun0228 commented on src/pages/Setting/components/idChange.tsx
> +export default function IdChage(): JSX.Element {
수정했습니다!  
9f3b7ec75145ffb246664948ef3ac8087610d3b9

2023-03-27 14:55 UTC, hyejun0228 commented on src/App.tsx
> +import IdChange from 'pages/Setting/components/IdChange';
컴포넌트명을 소문자로 적으셨다고 했는데 위치를 자세히 알 수 있을까요..? ㅠㅠㅜㅠ

2023-03-27 15:00 UTC, KimKyungYun commented on src/App.tsx
> +import IdChange from 'pages/Setting/components/IdChange';
Setting 폴더에 idChange 입니다
Import는 IdChange 로 되었는데 이름이 idChange 라서 오류가 나는 것 같아요

2023-03-27 16:02 UTC, ChoiWonBeen commented on src/App.tsx
> +import IdChange from 'pages/Setting/components/IdChange';
nick catch 👍

2023-03-28 02:04 UTC, hyejun0228 commented on src/App.tsx
> +import IdChange from 'pages/Setting/components/IdChange';
윈도우가 소문자랑 대문자를 구분하지 못해서 파일명을 대문자로 고쳤는데도 다른 환경에서 에러가 나는 것 같습니다..맥북으로 수정해서 올리겠습니다..!

2023-03-28 03:25 UTC, ChoiWonBeen requested changes
몇가지 수정사항 확인해주시고, 너무 기능이 커진다 싶으면 UI만 병합하로 다음 브랜치에서 Public Route를 관리해주셔도 괜찮아요.
물론 한번에 끝내도 문제는 없습니다 ㅋㅋ

2023-03-28 03:25 UTC, ChoiWonBeen commented on src/App.tsx
> +import IdChange from 'pages/Setting/components/IdChange';
운영체제 탓은 아니고, git이 파일/폴더명의 대소문자를 구분하지 못해요. 삭제 커밋 후 다시 추가 커밋하면 해결될거예요

2023-03-28 03:25 UTC, ChoiWonBeen commented on src/pages/Setting/components/index.tsx
> +  }, [isLogin]);
로그인이 안되어있을때는 UI가 바뀌는 게 아니라, 로그인페이지로 리다이렉팅이 되어야할거같아요.
아래 로그아웃, 탈퇴하기 등 다양한 기능들이 비로그인 상태에서 접근이 가능한게 이상하잖아요?

2023-03-28 03:25 UTC, ChoiWonBeen commented on src/pages/Setting/components/index.tsx
> +  };
앞 내용을 바꾼다면 이 페이지에는 로그인 된 상태로만 접근할 수 있으므로 간단히 `<Link to="/id-change" />`처럼 바꿀 수 있겠죠?

2023-03-28 03:25 UTC, ChoiWonBeen commented on src/pages/Setting/components/setting.ts
> +};
static 파일을 모은다면 폴더명이 `components/`가 아닌 `static/`에 넣어두는게 더 적절할 것 같아요.
필요없어질수도있지만 ㅋㅋ

2023-03-28 03:25 UTC, ChoiWonBeen commented on src/pages/Setting/components/index.tsx
> +              <ArrowRight />
여기에는 한 줄을`<Link />`로 묶지 않은 이유가 있나요?

2023-03-28 04:35 UTC, hyejun0228 commented on src/App.tsx
> +import IdChange from 'pages/Setting/components/IdChange';
넵!

2023-03-28 06:10 UTC, hyejun0228 commented on src/App.tsx
> +import IdChange from 'pages/Setting/components/IdChange';
수정했습니다!
370ba2a85eed2746d34841599bfe52ba5762e342

2023-03-28 06:20 UTC, hyejun0228 commented on src/pages/Setting/components/index.tsx
> +  }, [isLogin]);
수정했습니다!
bddad948d2806ddc74e4a7036229069eb08c665d

2023-03-28 06:20 UTC, hyejun0228 commented on src/pages/Setting/components/index.tsx
> +  };
수정했습니다!
bddad948d2806ddc74e4a7036229069eb08c665d

2023-03-28 06:34 UTC, hyejun0228 commented on src/pages/Setting/components/index.tsx
> +              <ArrowRight />
만약에 한 줄을  `<Link />`로 묶어주게 되면 거의 모든 화면이 Link기능을 하는 것과 마찬가지인 것 같아, 이동 버튼에만 `<Link />` 로 묶어줬습니다. 지금은 모든 Link를 이동 버튼에만 적용되게 바꿔 났습니다. 혹시 한 줄 전체에 `<Link />`를 걸어 놓는 게 더 나은 방법일까요??

2023-03-28 06:41 UTC, chaeseungyun approved these changes
pr 수정하면서 많이 알아가신 것 같습니다

2023-03-28 06:54 UTC, hyejun0228 commented on src/pages/Setting/components/setting.ts
> +};
일단은 문구로 표시해주는게 좋을것같아 `Setting` 폴더 내에 `static`함수를 추가에 두어 넣어놨습니다!

2023-03-30 03:02 UTC, KimKyungYun commented
다 잘 반영된 것으로 보이네요ㅎ
고생하셨습니다~

2023-04-02 03:15 UTC, KimKyungYun approved these changes
아직도 App에서 IdChange쪽 구문오류가 발생하네요~
그것만 수정되면 괜찮을 것 같습니다
고생하셨어요

2023-04-03 02:43 UTC, ChoiWonBeen requested changes
`PrivateRoute`와 `PublicRoute`구분이 된다면 다시 리뷰할게여~

2023-04-07 09:24 UTC, ChoiWonBeen approved these changes
오래 리뷰받느라 고생하셨어요~
아래 변경사항들 확인하시고 마저 수정되면 직접 머지하셔도 될 듯 합니다 ㅋㅋ

2023-04-07 09:24 UTC, ChoiWonBeen commented on src/App.tsx
>            <Route path="/login" element={<Login />} />
ㅋㅋㅋㅋㅋ적용이 반대로 된 것 같지 않나요?
저는 `NonAuthRoute`라면 **로그인이 안 된 상태로 갈 수 있는 경로**이라는 생각이 듭니다

2023-04-07 09:24 UTC, ChoiWonBeen commented on src/components/common/NonAuthRoute/index.tsx
> +export default function NonAuthRoute({ loginPage = '/login' }: Props) {
`redirectRoute`의 기본값을 로그인페이지로 정해둔 건 좋은 선택같아요.
다만 해당 변수는 **옮길 경로**를 나타내기때문에, `loginPage`라기보단, `redirectRoute`를 유지하는게 좋아보입니다.
회원가입으로 넘기는 경우도 있을거고~ 그런 생각이 드네요 ㅋㅋ

2023-04-07 09:24 UTC, ChoiWonBeen commented on src/pages/Setting/components/index.tsx
> -  const [id, setId] = useState(SETTING_TEXT.requiredLogin);
`SETTING_TEXT`를 포함하고있는 파일도 지워도 될 것 같아요

2023-04-09 15:25 UTC, daepan approved these changes
수고하셨습니다.

2023-04-10 02:23 UTC, hyejun0228 commented on src/components/common/NonAuthRoute/index.tsx
> +export default function NonAuthRoute({ loginPage = '/login' }: Props) {
혹시 `redirectRoute` 라는 것이 NonAuthRoute에 있는 `redirectPath = '/'`를 말하시는 건가요...?!

2023-04-10 02:26 UTC, hyejun0228 commented on src/pages/Setting/components/index.tsx
> -  const [id, setId] = useState(SETTING_TEXT.requiredLogin);
수정했습니다 
2f87e3aa6368c4c4d025e2f2cdf51de3ade7862d

2023-04-10 02:26 UTC, hyejun0228 commented on src/App.tsx
>            <Route path="/login" element={<Login />} />
수정했습니다! 
2f87e3aa6368c4c4d025e2f2cdf51de3ade7862d

2023-04-10 02:31 UTC, hyejun0228 commented on src/components/common/NonAuthRoute/index.tsx
> +export default function NonAuthRoute({ loginPage = '/login' }: Props) {
'redirectRoute` 의 기본값을 지우는게 더 좋다는 말씀이신가요?!

2023-04-10 02:31 UTC, hyejun0228 commented on src/components/common/NonAuthRoute/index.tsx
> +export default function NonAuthRoute({ loginPage = '/login' }: Props) {
`redirectRoute` 의 기본값을 지우는게 더 좋다는 말씀이신가요?!

2023-04-10 02:41 UTC, ChoiWonBeen commented on src/components/common/NonAuthRoute/index.tsx
> +export default function NonAuthRoute({ loginPage = '/login' }: Props) {
props로 받는 이동될 경로를 담는 변수명을 `redirectRoute` 라고 유지하는 게 더 나을거같다는 말이예요.
어디로 이동할 지에 대해서 props로 받는거라, 꼭 `/login`경로가 아닐 수 있기 때문이죠

2023-04-12 19:06 UTC, hyejun0228 commented on src/components/common/NonAuthRoute/index.tsx
> +export default function NonAuthRoute({ loginPage = '/login' }: Props) {
수정했습니다! 
d8998731d14327e20c9792e809082bfe53f87bf8

2023-04-13 05:02 UTC, merged