Feature/#57
BCSDLab/TEMP_PROJECT_FE pull request #61
Opened 2023-03-15 10:44 UTC by haejinyun

## [57] request

로그인 페이지 로그인 버튼에 마우스 커서 변경하였습니다.
검색창에 카피 문구, 검색입력란, 슬라이드바 디자인 변경하였습니다.

---

`dangerouslySetInnerHTML`를 사용했는데 Dangerous property라고 warning이 뜹니다.

```Typescript
var React = require('react');

var Hello = <div dangerouslySetInnerHTML={{ __html: "Hello World" }}></div>;
```
위와 같은 코드를
```Typescript

var React = require('react');

var Hello = <div>Hello World</div>;
```
아래처럼 변경하여 사용을 권장하는데  UI에 해당 태그를 렌더링해서 나오게끔하려면 `dangerouslySetInnerHTML`를 사용할 수 밖에 없었습니다. 혹시 다른 방법이 있을까요?

---

슬라이드 바 부분에서 피그마에 있는 디자인은 활성화 되어 색이 변하는것을 `hover`로 구현하였습니다.
차후 이벤트가 확실히 정해지면 수정이 필요할 것 같습니다. 

## Please check if the PR fulfills these requirements

- [X] It's submitted to `develop` branch, __not__ the `main` branch
- [X] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [X] Docs updated for breaking changes

### Screenshot

<img width="509" alt="image" src="https://user-images.githubusercontent.com/86779590/225285300-8434c97c-d9bb-449d-9744-54b5b842e9ba.png">

<img width="799" alt="image" src="https://user-images.githubusercontent.com/86779590/225285716-c92f2822-20f6-4214-b5bf-941c66fbc9f2.png">

2023-03-15 15:28 UTC, ChoiWonBeen requested changes
고생하셨어요~
앞에  #59 리뷰에서도 언급했지만, StyleLint확인해서 스타일 수정이 필요해보여요.
PR Template에 적용되어있는 체크박스들은 적힌 그대로 **Requirements**이므로, 전부를 충족한다고 스스로 판단했을때 PR을 올리는 거라고 보시면 됩니다.
린트 수정되면 다시 리뷰할게여

2023-03-15 15:28 UTC, ChoiWonBeen commented on src/pages/Search/components/SearchBar/RollingBanner.tsx
> +                </span>
사소하지만 이렇게 작성하면 문자 + 변수를 한 줄에 깔끔하게 쓸 수 있어요
```suggestion
                <span className={styles['search-rolling-banner__tag-style']}>
                  {`#${tag}`}
                </span>
```

2023-03-15 15:28 UTC, ChoiWonBeen commented on src/pages/Search/static/recommend.ts
> +  ['<strong>추억의 장소</strong>를\n검색을 통해 찾아보세요!'],
배열은 왜 생긴걸까요?

2023-03-15 15:28 UTC, ChoiWonBeen commented on src/pages/Search/components/SearchBar/Recommendation.tsx
> +  const recommendationSentence = RECOMMEND_TEXT[recommendIdx.current][0];
문장을 변수로 만든 접근은 좋은데 위 리뷰와 더불어 0번째라는 게 읽을때 무슨의미인가 헷갈렸어요.
랜덤번째 문장이면 충분하겠죠?

2023-03-16 01:04 UTC, haejinyun commented on src/pages/Search/static/recommend.ts
> +  ['<strong>추억의 장소</strong>를\n검색을 통해 찾아보세요!'],
해당 부분 수정 했습니다!

2023-03-16 01:05 UTC, haejinyun commented on src/pages/Search/components/SearchBar/Recommendation.tsx
> +  const recommendationSentence = RECOMMEND_TEXT[recommendIdx.current][0];
위 코드처럼 변수안에 배열 안의 배열이라 생겼던 것이었습니다.
위 부분 해결하고 해당 부분도 해결 했습니다!

2023-03-16 04:37 UTC, jaewoogwak approved these changes
수고하셨습니다~

2023-03-16 04:37 UTC, jaewoogwak commented on src/pages/Search/components/SearchBar/Recommendation.tsx
> +      dangerouslySetInnerHTML={{ __html: recommendationSentence }}
어쩔 수 없이 넣어야한다면 린트 설정을 끄는게 좋다고 생각하는데 다른 분들 의견도 듣고 적용하면 될듯합니다

2023-03-16 05:05 UTC, ChoiWonBeen commented
`tsx, jsx`파일에서는 jsx구문을 사용할 수 있으니
`RECOMMEND_TEXT`를 담은 static파일을 tsx로 확장자를 변경하고 아래처럼 쓰는것도 가능해요
```tsx
const RECOMMEND_TEXT = [
  <div>오늘은\n<strong>어떤 음식</strong>이 땡기나요?</div>,
  ...
]

2023-03-18 04:37 UTC, haejinyun commented on src/pages/Search/components/SearchBar/Recommendation.tsx
> +      dangerouslySetInnerHTML={{ __html: recommendationSentence }}
네 알겠습니다!

2023-03-20 02:13 UTC, haejinyun commented
> `tsx, jsx`파일에서는 jsx구문을 사용할 수 있으니 `RECOMMEND_TEXT`를 담은 static파일을 tsx로 확장자를 변경하고 아래처럼 쓰는것도 가능해요
> 
> ```tsx
> const RECOMMEND_TEXT = [
>   <div>오늘은\n<strong>어떤 음식</strong>이 땡기나요?</div>,
>   ...
> ]
> ```

해당 방법으로 진행을 해보려고 하였는데 `__html`의 값으로 문자열만 들어갈 수 있어서 이번 상황에서는 문자열로 진행하였습니다

2023-03-20 02:18 UTC, ChoiWonBeen commented
> 해당 방법으로 진행을 해보려고 하였는데 `__html`의 값으로 문자열만 들어갈 수 있어서 이번 상황에서는 문자열로 진행하였습니다

JSX로 반환하면 `dangerouslySetInnerHTML`을 사용하는 것이 아닌, `{text}`처럼 사용하는 것을 말한건데 안되려나요?
그리고 PR제목을 바꿔주세요

2023-03-20 02:53 UTC, haejinyun commented
> > 해당 방법으로 진행을 해보려고 하였는데 `__html`의 값으로 문자열만 들어갈 수 있어서 이번 상황에서는 문자열로 진행하였습니다
> 
> JSX로 반환하면 `dangerouslySetInnerHTML`을 사용하는 것이 아닌, `{text}`처럼 사용하는 것을 말한건데 안되려나요? 그리고 PR제목을 바꿔주세요

네 수정했습니다! 말씀해주신 부분 조금 바꿔서 수정 했습니다! 바로 다시 커밋하겠습니다

2023-03-20 03:13 UTC, ChoiWonBeen approved these changes
잘 동작하네요 👍  `dangerouslySetInnerHTML`가 린트에 걸린다는걸 알면서 새로운 시도를 해봤는데 성공한 것 같아 기분이 좋네요

2023-03-22 04:28 UTC, ChoiWonBeen commented
추가 리뷰 없다면 가장 최근의 develop merge해서 브랜치 최신화한 뒤, 머지해주세요

2023-03-22 07:48 UTC, merged