Feature/#60 로그인 페이지 UI변경 수정,favicon 변경
BCSDLab/TEMP_PROJECT_FE pull request #63
Opened 2023-03-21 09:34 UTC by KimKyungYun

## [Copy here issue number] request

새롭게 바뀐 로그인페이지 UI를 수정하였습니다.
favicon도 새롭게 변경되어 수정,적용해주었습니다.

commit 메시지 바꿨습니다 ㅠㅠㅋㅋㅋㅋㅋㅋㅋ

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [ ] Docs updated for breaking changes

### Screenshot
![1](https://user-images.githubusercontent.com/60084235/226566519-1f42b447-c50f-4ad7-8cd3-e786f4d5b63d.PNG)

2023-03-21 13:53 UTC, jaewoogwak requested changes
figma 시안이랑 조금 안 맞는 부분이 있어서 해당 부분 관련 코멘트 남기겠습니다~

2023-03-21 13:53 UTC, jaewoogwak commented on src/pages/Auth/Login/index.tsx
> +            <div className={styles.loginform__detail}>{'쩝쩝박사의 서비스를 이용하려면\n로그인하세요.'}</div>
"로그인하기"와 "쩝쩝박사의 서비스를 이용하려면 로그인하세요"를 감싸는 div 요소끼리 너무 붙어있어서 padding을 줄 필요가 있어보여요

2023-03-21 13:53 UTC, jaewoogwak commented on src/pages/Auth/Login/index.tsx
>                  <span className={styles.autologin__text}>자동 로그인</span>
이 부분도 figma에선 한 줄에 나타나게 돼 있어요. div 태그로 감싸서 flex를 주는 방법도 있고 span 태그로 감싸는 방법도 있겠네요

추가로 "계정이 없으신가요?" 부분과 "회원가입" 부분도 거리를 줘야할거 같아요

2023-03-21 14:28 UTC, KimKyungYun commented on src/pages/Auth/Login/index.tsx
>                  <span className={styles.autologin__text}>자동 로그인</span>
생각보다 디자인들을 깜빡한게 많았네요.. 죄송합니다. 수정했습니다! 
[f225b3f](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/63/commits/f225b3f3e84dc2c57e270a6661f610811283db0d)

2023-03-21 14:50 UTC, jaewoogwak approved these changes
확인했습니다 저는 좋아보입니다~

2023-03-22 04:25 UTC, ChoiWonBeen requested changes
고생하셨어요~ 색상, 글자 크기같은게 맞지 않는 부분들이 있어서 적어뒀습니다.

추가로 모바일 반응형 디자인이 다 깨지게 되었는데, figma에 찾아보니 앱쪽은 이전 UI로 만들어져있더라구요?
이럴땐 디자인 팀에게 앱쪽 로그인 UI도 변경된 웹과 유사하게 변경되는지 확인하고, 새로 만들지 않는다고 하면 이 UI를 깨지지 않게만 조금 조정하게끔 변경해주면 될 것 같아요.
<img width="427" alt="image" src="https://user-images.githubusercontent.com/50780281/226801838-cec1dab8-5a20-4735-b093-dfee14da6f40.png">

2023-03-22 04:25 UTC, ChoiWonBeen commented on src/pages/Auth/Login/index.tsx
> +            <div className={styles.loginform__detail}>{'쩝쩝박사의 서비스를 이용하려면\n로그인하세요.'}</div>
컬러가 `#666666`으로 바뀌어야 할 것 같아요

2023-03-22 04:25 UTC, ChoiWonBeen commented on src/pages/Auth/Login/index.tsx
> +                계정이 없으신가요?&nbsp;
여기도 컬러 다르게 들어가있습니다

2023-03-22 04:25 UTC, ChoiWonBeen commented on src/pages/Auth/Login/index.tsx
>              </Link>
여기도 색상 변경과 underline 추가가 필요해보여요

2023-03-22 04:25 UTC, ChoiWonBeen commented on src/pages/Auth/Login/index.tsx
>              <div className={styles.social__title}>SNS 계정으로 로그인하기</div>
여기도!

2023-03-22 04:25 UTC, ChoiWonBeen commented on src/pages/Auth/Login/index.tsx
> +                계정이 없으신가요?&nbsp;
font-size도 디자인에는 14px로 들어가있는 것 같은데 UI엔 18px로 나와요

2023-03-22 05:09 UTC, KimKyungYun commented on src/pages/Auth/Login/index.tsx
>              <div className={styles.social__title}>SNS 계정으로 로그인하기</div>
보통 가로선을 제가 해둔 after,before 방식으로 가로선을 표기하나요 아니면 다른 방법으로 표현하나요??
우선 figma에 명시된 대로 border속성으로 표기하는 방식으로 변경하였습니다~! 

[b9d0727](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/63/commits/b9d0727e702ec694eac6f7990bcdef431b71faee)

2023-03-22 05:16 UTC, ChoiWonBeen commented on src/pages/Auth/Login/index.tsx
>              <div className={styles.social__title}>SNS 계정으로 로그인하기</div>
때에 따라 다르겠지만 앞뒤라면 before,after 가상 요소선택자를 쓰는게 적절해요.
figma에 적힌 border는 디자인 툴로 그렸을 뿐이니 그대로 가져다 사용하기엔 좀 부적절할 수 있어요. 때에 따라 적절한 걸 찾아 써야할 것 같네요 ㅋㅋ

2023-03-22 05:56 UTC, KimKyungYun commented on src/pages/Auth/Login/index.tsx
>              <div className={styles.social__title}>SNS 계정으로 로그인하기</div>
넵넵 알겠습니다ㅋㅋ이번에는 한번 border로 그려볼게요ㅋㅋ

2023-03-22 15:22 UTC, KimKyungYun commented on src/pages/Auth/Login/index.tsx
>              <div className={styles.social__title}>SNS 계정으로 로그인하기</div>
모바일버전까지 수정 완료했습니다~!

[e8786fa](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/63/commits/e8786faca18c665e032e872d4319102d99d12a52)

2023-03-24 05:43 UTC, ChoiWonBeen approved these changes
잘 바꼈네요 고생하셨어요~

2023-03-24 08:19 UTC, merged