Feature/#77 친구목록 페이지 팔로우 기능 추가
BCSDLab/TEMP_PROJECT_FE pull request #67
Opened 2023-04-10 16:43 UTC by chaeseungyun

친구목록 페이지 일부 UI와 팔로우 요청, 승인 기능을 추가했습니다.

UI 관련해서 Figma에 질문했을 때 친구목록 페이지는 현재 개편중이라는 말을 듣고 받은 요청 탭을 제 임의로 만들었습니다.
현재 자신의 친구 목록을 보여주는 컴포넌트는 이번 pr이 끝나고 레귤러들끼리 팔로우가 이루어지면 마무리하겠습니다.

현재 처리하지 못한 예외 처리가 하나 있습니다.
팔로우 요청은 한 쪽에서만 할 수 있고 요청을 받은 사람은 요청을 한 사람에게 팔로우 요청을 할 수 없습니다.
받은 요청을 보여주는 기능과 유저를 검색하는 기능은 서로 다른 api를 사용하고 있습니다.
따라서 누군가 나에게 팔로우를 요청했을 때 받은 요청에 표시가 되지만,
유저 검색 시 그 사람이 나에게 팔로우 요청을 했는 지는 알 수 없습니다.
자신에게 팔로우 요청을 한 사람은 유저 검색 시 안보이게 하고 싶은데 사용하는 api가 다르고 response 형태가 달라서 어려움에 있습니다. 이 부분은 추후 수정하겠습니다.

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [ ] Docs updated for breaking changes

### Screenshot
![image](https://user-images.githubusercontent.com/101871802/230948312-dda58af3-e630-4ffc-8b83-513a67c1d53c.png)
대략적인 UI입니다. 팔로우 요청을 받으면 받은 요청 목록에 표시됩니다.

![image](https://user-images.githubusercontent.com/101871802/230948482-ea5abf3e-cbae-42e8-87d7-99ba41262763.png)
![image](https://user-images.githubusercontent.com/101871802/230948596-7f0a5778-f7e4-4f65-9c92-13d25100419a.png)
키워드를 통해 유저를 검색할 수 있습니다. 나와의 관계에 따라 버튼 UI가 바뀝니다.

![image](https://user-images.githubusercontent.com/101871802/230948692-f7027211-af0f-4e6e-b523-114a3ab743af.png)
탭을 클릭하여 목록을 숨길 수 있습니다.

2023-04-12 12:05 UTC, jaewoogwak requested changes, later dismissed
고생하셨습니다~
우선 URL이 `freind-list`로 되어있는데 오타인듯한데 `friend-list`로 바꿔야할거 같습니다.
그리고 팔로우를 요청하고 다시 눌렀을 때 취소할 수 있는 기능은 추후 추가될 예정인거죠?

2023-04-12 12:05 UTC, jaewoogwak commented on src/pages/FollowList/components/FailToSearch.tsx
> +}
모바일 반응형은 아직 추가되지 않은건가요?

2023-04-13 02:48 UTC, ChoiWonBeen requested changes
고생하셨습니다~ 👍  코드상 보이는 부분들중에 리뷰할만한 부분들 짚어드렸으니 확인하고 수정해주세요!

2023-04-13 02:48 UTC, ChoiWonBeen commented on src/api/follow/index.ts
> +});
비슷한 요청같아보이는데 요청 폼이 다르네요?
Swagger에서도 예시 요청은 같아보이는데 다르게 적힌 이유가 있나요?

2023-04-13 02:48 UTC, ChoiWonBeen commented on src/api/follow/index.ts
> +export const checkSendedFollow = (param: CheckSendedFollowParams) => followApi.get(`/requests/send?page=${param.page}&pageSize=${param.pageSize}`);
`getFollowList`같은 네이밍으로 바꾸는 건 어떨까요? 더 명확하게 보인다고 생각해요

2023-04-13 02:48 UTC, ChoiWonBeen commented on src/index.tsx
>      },
이게 없었군요....ㅋㅋㅋㅋㅋㅋ

2023-04-13 02:48 UTC, ChoiWonBeen commented on src/api/follow/entity.ts
> +}
그냥 `FollowerParams`라고 하면 어떤 API의 파라미터일지 잘 느낌이 안올 것 같은데(get, post, put 등..)
나눠보는걸 고민해봐도 괜찮을 것 같아요.
혹 같은 타입을 쓰고있다면 extends로 정의해두는것도 괜찮아보이구요.

2023-04-13 02:48 UTC, ChoiWonBeen commented on src/pages/FollowList/components/FollowList.module.scss
> +  height: 40px;
지난 주에 회의때 말했던 BEM 컨벤션으로 바꿔보져

2023-04-13 02:48 UTC, ChoiWonBeen commented on src/pages/FollowList/components/FollowList.tsx
> +};
바로 전 혜준님 리뷰에도 언급했었지만,
getMe에 대한 데이터는 이미 `useAuth` 훅에 정의되어있습니다.
내정보를 쉽게 갖고올 수 있죠.
```ts
const auth = useAuth();
```

2023-04-13 02:48 UTC, ChoiWonBeen commented on src/pages/FollowList/components/FollowList.tsx
> +  const [value, , ,toggle] = useBooleanState(true);
value는 무엇을 의미할까요?
위치에 맞게 배열로 갖고왓으니 이름을 적절히 바꾸는게 좋아보이네요.

2023-04-13 02:48 UTC, ChoiWonBeen commented on src/pages/FollowList/components/FollowList.tsx
> +        )}
봤을때 `--down`에 해당하는 CSS가 없다고 봣는데,, 그럼 불필요하겠죠?
arrow에 해당하는 css를 작성하고,(지금은 없다지만)
아래처럼 바꾸는 게 적절해보여요.
```suggestion
        <Arrow className={cn(
          {
            [style['title__arrow']]: true,
            [style['title__arrow--up']]: value,
          },
        )}
```

2023-04-13 02:48 UTC, ChoiWonBeen commented on src/pages/FollowList/components/FollowList.tsx
> +       && value && data && data.filter((e) => e.followedType === 'FOLLOWED').map((item) => (
이 반복되는 코드가 더 읽기 쉽게 표현할 방법이 있을 것 같은데,,,
일단 반복되는 `value && data`로 이 바깥쪽을 묶는 건 어떨까요?

2023-04-13 02:48 UTC, ChoiWonBeen commented on src/pages/FollowList/components/Follower.tsx
> +  return { request };
쿼리 무효화로 재요청 적절하네요.
근데 객체로 묶어서 넘기고 받을때도 객체를 풀어서 쓰는 이유가 있을까요?
아래처럼 쓰면 안되는걸까요?ㅋㅋㅋ
이름도 그냥 request보다는 더 명확한 네이밍이 좋을 것 같아요. 팔로우 요청이니 그런 의미의 이름으로..?

```ts
const useRequestAndUpdate = () => {
  // ...
  return request
}

const request = useRequestAndUpdate()
```

2023-04-13 02:48 UTC, ChoiWonBeen commented on src/pages/FollowList/components/SearchPage.tsx
> +      <FollowList title="새 친구" data={data} />
data라는 이름보다는.. 적절한 게 있을것 같고
내 친구랑 새 친구가 같은 데이터가 들어가는게 맞나요?

2023-04-13 02:48 UTC, ChoiWonBeen commented on src/pages/FollowList/index.tsx
> +  const { data: receive } = useQuery('received', () => checkReceivedFollow({ page: 0, pageSize: 100 }));
페이지네이션을 적용해야할것같아요! 100개를 한번에 가져오는건 좀 무거워보이고,
인자로 page를 주고 page state를 사용하면 될 것 같네요.

2023-04-29 07:55 UTC, chaeseungyun commented on src/pages/FollowList/components/FailToSearch.tsx
> +}
넵 일단 기능 위주로 개발했습니다.
다음 pr때 모바일 반응형 추가해서 올리겠습니다!

2023-04-29 07:56 UTC, chaeseungyun commented on src/index.tsx
>      },
작은 이슈였습니다 ㅋㅋ

2023-04-29 07:56 UTC, chaeseungyun commented on src/api/follow/index.ts
> +export const checkSendedFollow = (param: CheckSendedFollowParams) => followApi.get(`/requests/send?page=${param.page}&pageSize=${param.pageSize}`);
제안해주신 네이밍으로 적용하겠습니다

2023-04-29 07:57 UTC, chaeseungyun commented on src/pages/FollowList/components/Follower.tsx
> +  return { request };
객체로 묶는 것은 그냥 버릇처럼 썻습니다..
불필요한 것 같으니 수정하겠습니다

2023-04-29 07:59 UTC, chaeseungyun commented on src/pages/FollowList/components/SearchPage.tsx
> +      <FollowList title="새 친구" data={data} />
넵 '/users'에서 데이터를 받아서 followtype으로 필터하고 있습니다
이름은 신경써보겠습니다!

2023-04-29 08:00 UTC, chaeseungyun commented on src/pages/FollowList/components/FollowList.tsx
> +};
넵 바로 적용하겠습니다
다른 코드들도 주의깊게 보겠습니다..

2023-04-29 09:14 UTC, ChoiWonBeen commented on src/pages/FollowList/components/SearchPage.tsx
> +      <FollowList title="새 친구" data={data} />
상단에서 필터한 값을 뿌려주는건 어떨까요? 하위 컴포넌트의 관심사를 확실히 할 수 있을것같아요.

2023-05-02 04:49 UTC, chaeseungyun commented on src/pages/FollowList/components/FollowList.tsx
> +        )}
넵 굳이 쓰이지 않는 클래스명을 만들 필요는 없었던 것 같습니다

2023-05-02 05:30 UTC, chaeseungyun commented on src/pages/FollowList/components/SearchPage.tsx
> +      <FollowList title="새 친구" data={data} />
하위 컴포넌트인 followlist에서는 새 친구인지 나의 친구인지가 관심사가 아니고 친구 목록을 보여주는데 초점을 둔 컴포넌트였습니다. 따라서 지금처럼 그냥 데이터를 받고 followlist안에서 필터를 통해 content를 보여주었습니다
그래서 혹시 이대로 유지하는 건 어떨까요??

2023-05-02 05:39 UTC, chaeseungyun commented on src/pages/FollowList/components/FollowList.tsx
> +  const [value, , ,toggle] = useBooleanState(true);
친구목록을 숨기기/보이기 역할을 하기 때문에 isShow로 변경했습니다

2023-05-02 05:47 UTC, chaeseungyun commented on src/api/follow/index.ts
> +});
delete 요청시 body에 내용을 바로 담으려 하니 오류가 떠서 data에 담아보니 에러가 해결되었습니다
그래서 data: 안에 담았습니다

2023-05-02 05:48 UTC, chaeseungyun commented on src/api/follow/index.ts
> +});
그리고 삭제 기능을 넣지 않아서 따로 테스트는 하지 않았습니다..

2023-05-22 08:21 UTC, ChoiWonBeen commented on src/api/follow/index.ts
> +});
그럼 스웨거 입력 예시가 잘못된거니 백엔드쪽을 고쳐달라고 부탁해야 할 것 같아요

2023-05-22 08:26 UTC, ChoiWonBeen commented on src/pages/FollowList/components/SearchPage.tsx
> +      <FollowList title="새 친구" data={data} />
`FollowList` 안에서 필터링을 한다면 조건은 title이 되나요?
코드를 보니 title인것 같은데, 상위컴포넌트에서 미리 filter를 하고 이를 거친 데이터만 넘겨주면 `FollowList`는 훨씬 결합성을 줄일 수 있을 것 같아요.

2023-05-22 12:50 UTC, chaeseungyun commented on src/pages/FollowList/index.tsx
> +  const { data: receive } = useQuery('received', () => checkReceivedFollow({ page: 0, pageSize: 100 }));
따로 피드백 받은대로 page state를 만들고 우선 10으로 지정했습니다.
추후에 ui가 확정되면 페이지네이션을 적용하겠습니다

2023-05-29 07:59 UTC, chaeseungyun commented on src/api/follow/entity.ts
> +}
같은 타입을 쓰고 있기 때문에 extends로 보기 쉽게 나누었습니다

2023-05-29 09:18 UTC, chaeseungyun commented on src/api/follow/index.ts
> +});
넵!

2023-05-29 09:25 UTC, chaeseungyun commented on src/pages/FollowList/components/SearchPage.tsx
> +      <FollowList title="새 친구" data={data} />
수정중에 궁금한 사항이 있어서 질문드립니다
filter를 하고 props로 데이터를 넘겨주게 되면 FollowList가 받는 props가 되게 많아질 것 같은데 결합성을 줄이게 되는게 맞는건가요??
제가 생각하는 FollowList의 관심사는 컴포넌트 이름 그대로 친구목록을 보여주는 것이고, Follower 컴포넌트를 재사용하면서 이를 구현했습니다

2023-05-29 09:38 UTC, chaeseungyun commented on src/pages/FollowList/components/FollowList.module.scss
> +  height: 40px;
나름 bem으로 작성해보았습니다..

2023-05-30 15:11 UTC, ChoiWonBeen approved these changes
Good `<FollowList />`가 이제 명확한 목적을 가진 컴포넌트가 된 것 같네요. 고생하셨습니다~

2023-05-30 15:11 UTC, ChoiWonBeen approved these changes
Good `<FollowList />`가 이제 명확한 목적을 가진 컴포넌트가 된 것 같네요. 고생하셨습니다~

2023-05-30 15:12 UTC, merged