Feature/#66 회원가입 UI변경, 모달 추가
BCSDLab/TEMP_PROJECT_FE pull request #68
Opened 2023-04-11 02:13 UTC by KimKyungYun

## [#66] request
회원가입 UI변경하고 가입완료 모달 추가했습니다. 
모달의 정확한 목적이 가입 완료 후 인증 이메일을 통한 링크로 가입을 완료하는 것으로 보여서 우선 닉네임 설정창에 구현해 놓았습니다.
 figma에는 다시 약관동의 창으로 이동하여 모달을 띄우는 방식이었는데 전역상태를 사용하지 않고 있어서 구현하기 어려울 것 같습니다. 

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [ ] Docs updated for breaking changes

### Screenshot
![image](https://user-images.githubusercontent.com/60084235/231029460-e72ff542-b266-4fe3-af4d-b44eb07b6efd.png)
![image](https://user-images.githubusercontent.com/60084235/231029500-72e4d8ff-d2bb-4ef3-86b9-24649bbe628e.png)
![image](https://user-images.githubusercontent.com/60084235/231029569-56a6e61e-7d37-4fd8-aed6-18ef1b78471d.png)

2023-04-12 08:30 UTC, ChoiWonBeen requested changes
고생하셨어요~ 변경할 만한 점들 짚어드렸고,
UI가 전체적으로 마진이나 디테일한 정렬 등이 안맞는 부분들이 있어서 좀 더 꼼꼼하게 확인하며 수정하셨으면 좋겠습니다!

2023-04-12 08:30 UTC, ChoiWonBeen commented on src/components/Auth/AuthDetail/index.tsx
> +{ name :string, first:string, second:string }) {
따로 규칙을 정해둔 건 아니지만, 가독성 측면에서는 props가 3개 이상 늘어나면 타입을 따로 지정해주는게 더 깔끔하게 보인다고 생각해요.
```suggestion
interface Props { 
  name :string;
  first:string;
  second:string;
}
export default function AuthDetail({ name, first, second }: Props) {
```

그리고 보니깐 헤더 문구를 지정하는 컴포넌트니, `phrase, heading`같은 표현으로 바꿔주는건 어떨까요?

2023-04-12 08:30 UTC, ChoiWonBeen commented on src/pages/Auth/Signup/TermsOfServicePage/index.tsx
> +                <details className={styles.checkbox__detail}>
이부분 화살표와의 간격이 맞지 않아요

2023-04-12 08:30 UTC, ChoiWonBeen commented on src/pages/Auth/Signup/TermsOfServicePage/index.tsx
>                      <Arrow className={styles.checkbox__icon} />
이 부분이 지워져서 그런 건지는 모르겠는데, `detail`-`summary`구조임에도 `summary`를 클릭할때 펼져지지가 않아요.
svg만 클릭이 되는데, svg는 `cursor`가 포함돼있지 않네요.

<img width="325" alt="image" src="https://user-images.githubusercontent.com/50780281/231370988-a869b771-43f1-465e-a625-a24f2df9c959.png">

2023-04-12 08:30 UTC, ChoiWonBeen commented on src/pages/Auth/Signup/CompletePage/Complete.module.scss
> +  &__image {
회의때 언급했던 BEM형식에 맞춰서 네이밍을 통일해주세요!

2023-04-12 08:30 UTC, ChoiWonBeen commented on src/pages/Auth/Signup/Mixin.module.scss
> +  border-radius: 999px;
끝을 완전히 둥글게 만들고 싶은거라면 아래처럼 쓸 수 있어요
```suggestion
  border-radius: 100%;
```

2023-04-12 08:30 UTC, ChoiWonBeen commented on src/pages/Auth/Signup/CompletePage/index.tsx
> +          <Progress />
기존 Complete 창의 template이 다른 container들관 다르게 과도한 `margin-top`을 가지고 있는데 일관성을 가질 수 있게 바꿔줘야 할 것 같아요.

2023-04-12 08:30 UTC, ChoiWonBeen commented on src/pages/Auth/Signup/CompletePage/index.tsx
> +import { ReactComponent as Complete } from '../../../../assets/svg/auth/complete.svg';
다른 import처럼 절대경로를 쓰면 깔끔하게 작성할 수 있어요.
근데 해당 방식을 막는 Lint rule이 있는 줄 알았는데 없어졌나보네요? 다시 추가해도 괜찮을듯

2023-04-12 08:30 UTC, ChoiWonBeen commented on src/pages/Auth/Signup/CompletePage/components/CompleteModal.tsx
> +  };
props로 `setFalse`함수를 넘겨주면 어땠을까요?
적절하게 추상화한 `useBooleanState` 라는 커스텀 훅이 있으니 이를 활용해 수정해보는것도 괜찮을 듯 싶어요.

2023-04-12 16:42 UTC, chaeseungyun requested changes
고생하셨습니다!! 수정이 필요한 부분과 궁금한 사항 몇개 적어두었습니다

2023-04-12 16:42 UTC, chaeseungyun commented on src/pages/Auth/Signup/TermsOfServicePage/index.tsx
>                      <label className={styles['checkbox__summary-text']} htmlFor={res.summary}>
이 부분에 마우스를 갖다 대면 pointer로 커서가 바뀌는데 정작 클릭 시 약관이 펼쳐지지는 않습니다!
이 부분 수정 가능하신가요?

2023-04-12 16:42 UTC, chaeseungyun commented on src/pages/Auth/Signup/CompletePage/Complete.module.scss
> +
modal의 scss 파일과 complete의 scss 파일을 분리하지 않은 이유가 있나요??

2023-04-12 16:42 UTC, chaeseungyun commented on src/pages/Auth/Signup/CompletePage/Complete.module.scss
> +  &__button {
완료 버튼이 왼쪽으로 살짝 치우쳐진 것 같아요

2023-04-13 03:01 UTC, kimeodml requested changes
고생하셨습니다!

2023-04-13 03:01 UTC, kimeodml commented on src/pages/Auth/Signup/SignupPage/index.tsx
>              <EmailInput />
`emailDomain`을 무조건 입력해야 다음으로 넘어가 지는데 모바일의 경우 그 `emailDomain`이 제거되었기 때문에 유효성 검사를 통해 이메일을 입력해도 다음 단계로 넘어가 지지 않네요. 브랜치가 UI만 수정하는 브랜치 같아서 이 부분은 이슈 새로 만들고 수정하셔야 할것 같아요.

2023-04-13 03:01 UTC, kimeodml commented on src/pages/Auth/Signup/static/privacy.ts
>  .`,
마침표 하나 제거해주세요.

2023-04-13 03:01 UTC, kimeodml commented on src/pages/Auth/Signup/SignupPage/index.tsx
>      <div className={styles.template}>
모바일 버전에서 하단의 margin이 없는 것 같습니다.

2023-04-13 08:13 UTC, KimKyungYun commented on src/components/Auth/AuthDetail/index.tsx
> +{ name :string, first:string, second:string }) {
수정했습니다!

2023-04-13 08:13 UTC, KimKyungYun commented on src/pages/Auth/Signup/TermsOfServicePage/index.tsx
> +                <details className={styles.checkbox__detail}>
확인해보니까 scss가 지워져있었네요.. 
수정했습니다

2023-04-14 02:04 UTC, KimKyungYun commented on src/pages/Auth/Signup/Mixin.module.scss
> +  border-radius: 999px;
figma 요청사항에 따라서 그대로 작성했더니 저렇게 표현해버렸네요..ㅎ 수정했습니다

2023-04-14 02:30 UTC, KimKyungYun commented on src/pages/Auth/Signup/TermsOfServicePage/index.tsx
>                      <Arrow className={styles.checkbox__icon} />
summary부분 전체에 cursor부여하고 어디를 클릭하더라도 펼쳐지도록 수정했습니다.

2023-04-14 02:41 UTC, KimKyungYun commented on src/pages/Auth/Signup/CompletePage/index.tsx
> +import { ReactComponent as Complete } from '../../../../assets/svg/auth/complete.svg';
아하 이걸 상대경로로 작성해두었었네요
수정했습니다ㅎ

2023-04-14 02:43 UTC, KimKyungYun commented on src/pages/Auth/Signup/CompletePage/Complete.module.scss
> +  &__image {
수정했습니다!

2023-04-15 06:28 UTC, KimKyungYun commented on src/pages/Auth/Signup/CompletePage/index.tsx
> +          <Progress />
수정했습니다

2023-04-15 07:12 UTC, KimKyungYun commented on src/pages/Auth/Signup/CompletePage/components/CompleteModal.tsx
> +  };
수정했습니다~!

2023-04-15 07:12 UTC, KimKyungYun commented on src/pages/Auth/Signup/TermsOfServicePage/index.tsx
>                      <label className={styles['checkbox__summary-text']} htmlFor={res.summary}>
수정했습니다~!

2023-04-15 07:20 UTC, KimKyungYun commented on src/pages/Auth/Signup/CompletePage/Complete.module.scss
> +
이전 작성자분이 component를 모두 index의 scss에서 사용하셔서 저도 그렇게 작성했는데
분리가 확실히 좋아보여서 분리작성하였습니다 ㅎ 
수정했습니다

2023-04-15 07:28 UTC, KimKyungYun commented on src/pages/Auth/Signup/CompletePage/Complete.module.scss
> +  &__button {
수정했습니다.

2023-04-15 07:37 UTC, KimKyungYun commented on src/pages/Auth/Signup/SignupPage/index.tsx
>              <EmailInput />
아아 디자인에서도 수정된 부분이 있었네요.. 
제가 만든게 아니라 눈치를 못챘네요 ㅠ
디자인수정하고 이슈만들어서 수정하겠습니다

2023-04-15 07:40 UTC, KimKyungYun commented on src/pages/Auth/Signup/static/privacy.ts
>  .`,
수정했습니다.

2023-04-15 07:52 UTC, KimKyungYun commented on src/pages/Auth/Signup/SignupPage/index.tsx
>      <div className={styles.template}>
수정했습니다

2023-04-15 12:31 UTC, ChoiWonBeen requested changes
일단 lint 안맞는 문제 해결해주시고,
추가적인 변경사항들 언급해놨으니 확인 부탁드립니다~

2023-04-15 12:31 UTC, ChoiWonBeen commented on src/pages/Auth/Signup/CompletePage/components/CompleteModal.tsx
> +};
다른 곳들은 다 `interface`로 정의했을텐데 `type`으로 정의한 이유가 있나요?

2023-04-15 12:31 UTC, ChoiWonBeen commented on src/pages/Auth/Signup/CompletePage/components/CompleteModal.tsx
> +        <AuthDetail name="이메일 알맞게 입력하셨나요?" first="가입한 이메일로 링크를 보냈습니다!" second="새로운 링크로 들어와주세요." />
오타가 있어요
```suggestion
        <AuthDetail name="이메일을 알맞게 입력하셨나요?" first="가입한 이메일로 링크를 보냈습니다!" second="새로운 링크로 들어와주세요." />
```

2023-04-15 12:31 UTC, ChoiWonBeen commented on src/pages/Auth/Signup/CompletePage/components/CompleteModal.tsx
> +export default function CompleteModal({ setFalse } : Props) {
함수의 동작은 boolean값을 `false`로 바꾸는 것이 맞지만, 해당 모달이 props로 boolean에 대한 관심사를 표시할 필요는 없다고 생각합니다.
`closeModal`같은 명칭으로 컴포넌트의 관심사를 확실히 하는 건 어떨까요?

2023-04-15 12:31 UTC, ChoiWonBeen commented on src/pages/Auth/Signup/CompletePage/index.tsx
> +            <Progress className={styles['form__nickname-Progress']} />
클래스명에 오타가 있는 것 같아요

2023-04-15 12:31 UTC, ChoiWonBeen commented on src/pages/Auth/Signup/SignupPage/components/EmailInput.tsx
>      </div>
도메인 선택이 없어져서 회원가입 동작이 이상해집니다.
기존에는 `email + @ + domain` 으로 동작하는데,
domain을 없앴다보니, 이메일을 입력해도 뒤에 골뱅이만 남은 채로 요청이 진행됩니다.
ex)`abcd@gmail.com` + `@`
이래서 회원가입창에서 다음으로 넘어갈 수가 없네요.

2023-04-16 01:13 UTC, KimKyungYun commented on src/pages/Auth/Signup/CompletePage/components/CompleteModal.tsx
> +};
무의식적으로 type으로 작성했네요.. 
수정했습니다!

2023-04-16 01:13 UTC, KimKyungYun commented on src/pages/Auth/Signup/CompletePage/components/CompleteModal.tsx
> +        <AuthDetail name="이메일 알맞게 입력하셨나요?" first="가입한 이메일로 링크를 보냈습니다!" second="새로운 링크로 들어와주세요." />
수정했습니다

2023-04-16 01:22 UTC, KimKyungYun commented on src/pages/Auth/Signup/CompletePage/index.tsx
> +            <Progress className={styles['form__nickname-Progress']} />
수정했습니다

2023-04-16 02:00 UTC, KimKyungYun commented on src/pages/Auth/Signup/CompletePage/components/CompleteModal.tsx
> +export default function CompleteModal({ setFalse } : Props) {
수정했습니다

2023-04-16 03:46 UTC, KimKyungYun commented on src/pages/Auth/Signup/SignupPage/components/EmailInput.tsx
>      </div>
회원가입 동작 정상작동하도록 수정하였습니다.
새롭게 바뀐 UI에 따라 dropdown을 없애고 직접입력으로 수정하였습니다.

2023-04-17 02:50 UTC, ChoiWonBeen approved these changes
고생하셨습니다~ 최신 develop브랜치 머지받아주세요!

2023-04-17 07:18 UTC, kimeodml approved these changes

2023-04-17 10:12 UTC, merged