Feature/#1 media query utils 추가
BCSDLab/TEMP_PROJECT_FE pull request #7
Opened 2022-09-06 07:13 UTC by ChoiWonBeen

## #1 request

반응형을 위한 media-query를 관리하는 utils를 추가했습니다.
- 모바일 여부를 반환하는 useMediaQuery hook
- media-breakpoint를 쉽게 사용하기 위한 mixin

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [ ] Docs updated for breaking changes

### Screenshot
![responsive](https://user-images.githubusercontent.com/50780281/188569293-9c3e4f2e-f101-4a6f-b966-5c3d05b96720.gif)

2022-09-06 07:31 UTC, SimYunSup requested changes
바꿔야 할 것 하나, 고려해보면 좋을 것 하나 리뷰해드렸습니다.
다른 참가하신 분들도 리뷰 보시면서 왜 이렇게 썼는가에 대해 고민해보시면 좋습니다 :100:

2022-09-06 07:31 UTC, SimYunSup commented on src/utils/hooks/useMediaQuery.ts
> +    window.addEventListener('resize', resizeHandler);
matchMedia를 사용하셨는데 media query의 change 이벤트가 아닌 resize 이벤트를 사용한 이유를 알고 싶네요. resize될때마다 resizeHandler를 호출하여 비효율적일텐데요.
https://github.com/BCSDLab/KOIN_WEB_RECODE/blob/develop/src/utils/hooks/useMediaQuery.ts
위의 경우를 참조하면 좋을 것으로 보입니다.

2022-09-06 07:31 UTC, SimYunSup commented on src/utils/styles/mediaQuery.scss
> +      @media screen and (max-width: $size) {
bootstrap처럼 `min-width`을 사용하는 방향도 고려해주세요 :)
KOIN은 기존에 `max-width`를 사용했기에 그대로 가는 방향밖에 없었는데 한 번 고려해보았으면 좋겠습니다.

2022-09-06 07:39 UTC, ChoiWonBeen commented on src/utils/styles/mediaQuery.scss
> +      @media screen and (max-width: $size) {
생각해보니 이번 프로젝트 자체가 모바일 퍼스트니 min-width를 우선적으로 고려하는것도 좋아보이네요.
media-breakpoint-reverse를 만들어서 max-width로, 기존을 min-width로 두는 건 어떨까요?

2022-09-06 07:43 UTC, SimYunSup commented on src/utils/styles/mediaQuery.scss
> +      @media screen and (max-width: $size) {
좋습니다 :) `media-breakpoint-up` `media-breakpoint-down`식으로 [이름](https://getbootstrap.com/docs/5.2/layout/breakpoints/#media-queries)을 변경해도 좋습니다.

2022-09-06 07:44 UTC, ChoiWonBeen commented on src/utils/hooks/useMediaQuery.ts
> +    window.addEventListener('resize', resizeHandler);
matchMedia가 리턴하는 MediaQueryList 프로토타입에 대해서 인지하지 못했었네요 ㅋㅋ
확인하고 수정하겠습니다 👍

2022-09-06 08:57 UTC, ChoiWonBeen commented on src/utils/hooks/useMediaQuery.ts
> +    window.addEventListener('resize', resizeHandler);
[943d481](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/7/commits/943d481195f891807111315c82fc9a4b514e0078)
수정했습니다.

2022-09-06 08:58 UTC, SimYunSup approved these changes
좋습니다 :) 다른 분들도 질문이나 리뷰 해주세요!

2022-09-07 05:33 UTC, daepan approved these changes
궁금한 점만 올려두었습니다

2022-09-07 05:33 UTC, daepan commented on src/utils/styles/mediaQuery.scss
> +  mobile: 576px,
궁금한 점입니다!
mobile에 대한 px 이외에 태블릿 사이즈에 대한 처리가 필요할 수도 있을 것 같은데 그 부분에 대해 대처를 어떻게 생각하시나요!?

2022-09-07 07:05 UTC, ChoiWonBeen commented on src/utils/styles/mediaQuery.scss
> +  mobile: 576px,
일단은 디자인이 모바일/PC만으로 이루어져있어 구분하지 않았지만, 아래 믹스인 함수들이 재사용성이 좋아 간단하게 변수 추가만 해도 추가적인 반응형을 대응할 수 있습니다 😃

2022-09-07 13:27 UTC, D0Dam commented on src/utils/styles/mediaQuery.scss
> +$media: (
가로 Desktop과 moblie을 나누는 기준 width가  정확히 576px인 이유가 뭔가요..?
나중에 tablet이 추가되면 기준을 어떻게 나눌지 궁금합니다!

2022-09-07 19:00 UTC, D0Dam commented
저도 궁금한 점 올려둡니다~!

2022-09-07 19:05 UTC, D0Dam commented on src/utils/hooks/useMediaQuery.ts
> +  const [matches, setMatches] = useState(() => window.matchMedia(MOBILE_MEDIA_QUERY).matches);
matches를 사용해서 mobile이냐 desktop이냐를 boolean값으로 구분할 수 있게끔 작성 한 것 같은데 이렇게 되면 tablet과 같은 media 처리를 나중에 추가하려면 로직이 많이 추가 되지 않을까 생각해봤습니다.

2022-09-07 19:09 UTC, D0Dam commented on src/utils/styles/mediaQuery.scss
> +}
이 breakpoint-max 함수의 return 값에서 $max-0.02를 해주셨는데 여기서 왜 0.02를 빼준 것인지 궁금합니다.

2022-09-07 23:08 UTC, ChoiWonBeen commented on src/utils/hooks/useMediaQuery.ts
> +  const [matches, setMatches] = useState(() => window.matchMedia(MOBILE_MEDIA_QUERY).matches);
다른 breakpoint가 생긴다면 ref변수를 배열로 담아서 관리할 수 있게끔 바꿔야할거예요. 훅의 반환을 값이 아닌 객체의 프로퍼티로 바꾸었으니, 그나마 추가하는데 있어 훅을 호출하는 곳에서의 로직을 수정할 필요는 없게끔 설계했습니다.

2022-09-07 23:11 UTC, ChoiWonBeen commented on src/utils/styles/mediaQuery.scss
> +}
max-width 576px과
min-width 576px을 사용하게 되면
정확히 576px에서는 두가지 전부 동작하지 않게 됩니다. 그렇다고 1px차이를 두자니, 소수점의 width가 생길 수도 있다고 bootstrap에서 고려하고 있어서, 이를 참고했습니다.

2022-09-08 00:00 UTC, jaewoogwak commented on src/utils/styles/mediaQuery.scss
> +}
오 하나 알아갑니다... 그러면 0.02가 최소한의 차이를 두고자 설정한 값이라고 이해하면 되는걸까요?

2022-09-08 00:04 UTC, kimeodml commented on src/utils/hooks/useMediaQuery.ts
> +  const matchMediaRef = useRef<MediaQueryList | null>(null);
바로 matchMedia.이벤트핸들러로 접근하지 않고 useRef를 선언 후에 이벤트 핸들러에 접근한 이유가 궁금합니다.

2022-09-08 00:18 UTC, ChoiWonBeen commented on src/utils/styles/mediaQuery.scss
> +}
@jaewoogwak 넵 0.01px을 사용하지 않은 이유는 [사파리 브라우저의 반올림 버그](https://stackoverflow.com/a/51567792)때문이라고 합니다.

2022-09-08 00:20 UTC, ChoiWonBeen commented on src/utils/hooks/useMediaQuery.ts
> +  const matchMediaRef = useRef<MediaQueryList | null>(null);
matchMedia는 MediaQueryList라는 이벤트타겟을 반환합니다. 해당 이벤트타겟에 이벤트리스너를 담아주어야 하는데, hook특성상 클린업 처리를 해주어야해서 해당 이벤트를 저장할 변수가 필요했습니다.

2022-09-08 00:20 UTC, merged

2022-09-08 00:32 UTC, ChoiWonBeen commented
개인 브랜치에 해당 utils 머지받아서 활용해주세요~

2022-09-08 04:49 UTC, chaeseungyun commented on src/utils/hooks/useMediaQuery.ts
> +    handleChange();
여기서 함수를 실행시킨 이유가 무엇인가요???
함수를 지워도 정상적으로 작동해서 질문합니다

2022-09-08 05:16 UTC, ChoiWonBeen commented on src/utils/hooks/useMediaQuery.ts
> +    handleChange();
어라? 이미 state에 초기값을 줘서 의미없는 초기화였네요? 다음 PR에 하단에 불필요한 주석이랑 같이 지워서 올리겠습니다 ㅋㅋ