Feature/#71 문의하기 페이지 UI
BCSDLab/TEMP_PROJECT_FE pull request #72
Opened 2023-04-28 10:21 UTC by hyejun0228

## [#71 ] 문의하기 페이지 UI

문의하기 페이지 UI를 만들었습니다.
아직 figma에 문의하기 추가 및 작성시 UI 등등이 나와있지않아 기본 페이지 UI 만 만들어놨습니다
추후에 디테일한 UI가 나온다면 기능을 추가하도록 하겠습니다.

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

### Screenshot
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/114041848/235122194-9887fce3-7cfd-4470-ba7f-25d28e80ec29.png">

2023-04-28 14:17 UTC, ChoiWonBeen requested changes
고생하셨어요~ 전체적인 레이아웃 관해서 코멘트를 먼저 드리려구요.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/50780281/235170441-c775c4b7-5fb2-4222-b8fb-8eaeee295797.png">

UI가 넓어지면, 각 위치가 깨지는 현상이 발생합니다.
이는 margin으로 관리하기보단, 가운데 영역의 width를 고정한 채로, 더 상위 컨테이너에서 중앙정렬을 해주는 편이 더 좋겠죠?

또한, 테이블의 높이는 최대 아이템 개수를 가진 채로 고정이어야 하지 않을까 생각합니다.
그런 만큼 임시 데이터를 담아서 UI를 보여주는 편이 이번 UI 피처에서는 더 좋을 것 같아요.
현재 테이블에 필요한 UI에는 글 목록과 페이지네이션도 포함이기에, 만들어두면 좋겠죠.

그리고 페이지네이션은 필수 UI예요! < 1 > 같은 상태로 있어야한다고 생각해요.
다음 기능에서 목록 조회 API를 사용해 제작할텐데, UI개발과 동시에 진행하기엔 힘들테니 이번 피쳐에서 미리 페이지네이션 / 목록을 구현해두면 더 좋을 것 같다는 생각이 들어요. 물론 선택은 본인의 몫!

2023-04-28 14:17 UTC, ChoiWonBeen commented on src/pages/Setting/components/Inquiry.tsx
> +        <input type="text" value="제목 혹은 작성자를 검색해보세요!" className={styles.footer__search} />
value라서 입력이 안들어가요 ㅋㅋ `placeholder`로 담아줘야겠죠?
그리고 위치가 중앙이 아닌, 테이블의 왼쪽 끝과 맞아야 할 것 같은데 이건 전체적으로 한번 언급해볼게요.

2023-04-28 14:17 UTC, ChoiWonBeen commented on src/pages/Setting/components/Inquiry.tsx
> +      <hr className={styles.mainline} />
block의 기준이 애매하다는 생각이 들어요.
`main__line`, `main__line--second` 같이 쓰는건 어떨까요?

2023-04-28 14:17 UTC, ChoiWonBeen commented on src/pages/Setting/components/Inquiry.tsx
> +        <div className={styles.box__title}>TITLE</div>
box보다는 table에 가까운 요소로 보여요.
table 관련 태그는 쓸 필요가 없어보이긴 하지만, `table__th--number` 처럼 쓰는건 어떨까 싶은데, 이 방법도 그렇게 좋아보이진 않네요. 더 나은 네이밍을 고민해보면 좋을 것 같아요!

2023-04-28 14:17 UTC, ChoiWonBeen commented on src/pages/Setting/components/Inquiry.module.scss
> +  }
thead 각각의 요소를 마진으로 간격을 관리하기보다는, container 역할을 하는 태그에 `display: grid`를 쓰는건 어떨까요?
`grid-template-columns`로 적절하게 관리할 수 있을 것 같아요!
각 행 또한 마찬가지로 관리할 수 있겠죠.

2023-04-28 14:17 UTC, ChoiWonBeen commented on src/pages/Setting/components/Inquiry.module.scss
> +    background: $highlight;
찾기 버튼은 `cursor: pointer`가 들어가면 좋은 UX를 줄 수 있다고 생각이 드는데 어떨까요?

2023-04-28 14:17 UTC, ChoiWonBeen commented on src/pages/Setting/components/Inquiry.tsx
> +        <button type="submit" className={styles['footer__search-button']}>찾기</button>
`type=submit` 버튼은 `<form>`에 속하는 데이터를  제출하므로 `form`으로 묶여야할 것 같아요.
지금은 눌러도 아무 동작을 하지 않으니 실제로 검색을 만들땐 submit 이벤트까지 관리해줘야겠죠?

2023-04-28 14:17 UTC, ChoiWonBeen commented on src/pages/Setting/components/index.tsx
> +            <button type="submit" className={styles.service__announcement}>
버튼에 `cursor: pointer`가 필요해보여요

2023-04-28 14:17 UTC, ChoiWonBeen commented on src/pages/Setting/components/index.tsx
> +          <Link to="Inquiry">
문의하기 경로가 `/setting` 에 중첩해서 작성할 필요가 있을까요?
`I`가 다른 경로와 다르게 대문자인것도 신경이 쓰이기도 하구요
아마 경로를 변경하게 된다면 `/inquiry`처럼 바꿔야 하지 않을까... 개인적으로 생각해봅니다 ㅋㅋ

2023-04-28 14:17 UTC, ChoiWonBeen commented on src/pages/Setting/components/Inquiry.tsx
> +      </div>
조금은 의미론적인 태그를 사용해주면 어떨까요?
그리고 `font-weight`가 빠진 것 같아요.
```suggestion
      <header className={styles.header}>
        <h1 className={styles.header__title}>문의하기</h1>
        <h3 className={styles['header__sub-title']}>쩝쩝박사에게 궁금한 점이 있나요?</h3>
      </header>
```

2023-04-28 14:17 UTC, ChoiWonBeen commented on src/pages/Setting/components/Inquiry.tsx
> +      <hr className={styles.line} />
hr과 내부 요소를 마진으로 구분하기보단,
내부 요소에 padding을 두고 `border-top, bottom`을 쓰는건 어땠을까요?

2023-04-28 17:41 UTC, hyejun0228 commented on src/pages/Setting/components/Inquiry.tsx
> +      <hr className={styles.mainline} />
fd6d0f8024e3656da48a25b7189a889b4335ba24 
넵! 수정했습니다! 코드 중복도 심한 것 같아 `@extend` 로 처리해줬습니다..!

2023-04-28 18:59 UTC, hyejun0228 commented on src/pages/Setting/components/Inquiry.module.scss
> +  }
수정했습니다!!
b3fd50d15e6001500c0d91ee9800e10090104fc1

2023-04-28 19:04 UTC, hyejun0228 commented on src/pages/Setting/components/Inquiry.tsx
> +        <input type="text" value="제목 혹은 작성자를 검색해보세요!" className={styles.footer__search} />
억 넵! 수정했습니다!
fd6d0f8024e3656da48a25b7189a889b4335ba24

2023-04-28 19:07 UTC, hyejun0228 commented on src/pages/Setting/components/Inquiry.module.scss
> +    background: $highlight;
좋은것 같습니다! 
5c9f2cf599434254976f04f4ab68f1502ed67bb4

2023-04-28 19:10 UTC, hyejun0228 commented on src/pages/Setting/components/index.tsx
> +            <button type="submit" className={styles.service__announcement}>
추가했습니다! 
5c9f2cf599434254976f04f4ab68f1502ed67bb4

2023-04-28 19:24 UTC, hyejun0228 commented on src/pages/Setting/components/index.tsx
> +          <Link to="Inquiry">
지금 보니 너무 이상하군요...수정했습니다..!!
af48260c997fa376a2ab8c4d8843380daefbc0f6

2023-04-29 03:08 UTC, hyejun0228 commented on src/pages/Setting/components/Inquiry.tsx
> +      <hr className={styles.line} />
`grid-template-rows` 와 `grid-template-columns` 를 `margin`대신으로 사용해 수정했습니다! 
b3fd50d15e6001500c0d91ee9800e10090104fc1

2023-04-29 03:12 UTC, hyejun0228 commented on src/pages/Setting/components/Inquiry.tsx
> +      </div>
수정했습니다!
3c121e6c145f1f618f9ca9ed865a3248fb09a553

2023-04-29 04:47 UTC, ChoiWonBeen commented on src/pages/Setting/components/Inquiry.tsx
> +      <hr className={styles.line} />
그렇게 만든 grid container에 border를 주는건 어때보이나요? 내부 글자의 마진보다는, 선과 컨텐츠 사이의 패딩이라고 생각했거든요

2023-04-29 11:23 UTC, hyejun0228 commented on src/pages/Setting/components/Inquiry.tsx
> +      <hr className={styles.line} />
앗 제가 위의 글을 잘못 이해했네요..! 수정했습니다!!
8b455e60acd69c6121c6eab86ee97cacb9d3782d

2023-05-01 10:35 UTC, hanagertrudekim reviewed
파일 구조가 조금 이상해서 `index.tsx`는 컴포넌트가 아니니, 컴포넌트 폴더 밖으로 빼주는게 좋아보여요...!

2023-05-01 10:41 UTC, hyejun0228 commented
> 
넵! `page`컴포넌트 안에 따로 `inquiry` 폴더 만들어서 거기로 빼주겠습니다!

2023-05-01 10:43 UTC, ChoiWonBeen commented
> @hanagertrudekim 넵! `page`컴포넌트 안에 따로 `inquiry` 폴더 만들어서 거기로 빼주겠습니다!

`pages/Setting/components/index.tsx`도 이상한 것 같아요!

2023-05-01 10:58 UTC, hyejun0228 commented
> 파일 구조가 조금 이상해서 `index.tsx`는 컴포넌트가 아니니, 컴포넌트 폴더 밖으로 빼주는게 좋아보여요...!
@ChoiWonBeen 
@hanagertrudekim 

컴포넌트에서 `index.tsx`밖으로 빼주겠습니다! `inquiry`도 `setting`컴포넌트 안에 있기엔 단위가 너무 큰것같으니..밖으로 빼서 따로 폴더 만드는게 나을것같습니다

2023-05-03 05:00 UTC, KimKyungYun requested changes
고생 많이하셨습니다~ 몇가지 수정사항 표시해 놓았으니 확인 부탁드립니다!

2023-05-03 05:00 UTC, KimKyungYun commented on src/pages/Inquiry/index.tsx
> +  console.log(postData);
오류 확인하느라 넣어놓으신 것 같네요~ warning이 떠서 지우시면 될 것 같습니다

2023-05-03 05:00 UTC, KimKyungYun commented on src/pages/Inquiry/index.tsx
> +        </div>
해당 페이지네이션의 페이지 넘버 표시에 오류가 있어 보입니다. 처음 들어가면 이전 페이지의 숫자가 0과 음수로 표시됩니다.
{page - 2 > 0 ? page - 2 : null} 이런식으로 표시페이지를 수정해주시면 될 것 같습니다.

2023-05-03 05:00 UTC, KimKyungYun commented on src/pages/Inquiry/index.tsx
> +        <button type="button" className={styles['page-controler__svg']} onClick={nextTenPage}>
페이지를 넘기는 arrow버튼에 cursor 속성이 추가되어야 할 것 같습니다!

2023-05-03 05:00 UTC, KimKyungYun commented on src/pages/Inquiry/index.tsx
> +  };
이 부분이 동일하게 구성되어있어서 오른쪽으로 한페이지씩 넘어가지 않습니다. 한페이지씩 넘어가도록 nextOnePage를 수정하셔야 할 것 같습니다~

2023-05-04 09:39 UTC, hyejun0228 commented on src/pages/Inquiry/index.tsx
> +  console.log(postData);
넵! 수정했습니다

2023-05-04 09:41 UTC, hyejun0228 commented on src/pages/Inquiry/index.tsx
> +        </div>
수정했습니다! `pagination` 컴포넌트도 따로 분리했습니다 997c75c2cabd2829f6f8fd869957e40630e2de75

2023-05-04 09:46 UTC, hyejun0228 commented on src/pages/Inquiry/index.tsx
> +        <button type="button" className={styles['page-controler__svg']} onClick={nextTenPage}>
넵! 'cursor: pointer` 추가했습니다! 53d0860d705ada22fce94e070b4c670d8b52bbe5

2023-05-04 09:46 UTC, hyejun0228 commented on src/pages/Inquiry/index.tsx
> +  };
997c75c2cabd2829f6f8fd869957e40630e2de75 수정했습니다!

2023-05-05 18:10 UTC, hyejun0228 commented on src/pages/Setting/components/Inquiry.tsx
> +        <div className={styles.box__title}>TITLE</div>
전체적인 `className` 수정했습니다! fe927524711346fb8433ff3b9a1139a1a21d0630

2023-05-05 18:12 UTC, hyejun0228 commented on src/pages/Setting/components/Inquiry.tsx
> +        <button type="submit" className={styles['footer__search-button']}>찾기</button>
넵! 다음 pr 때 기능 추가하겠습니다!

2023-05-06 07:57 UTC, D0Dam reviewed
코드 구경을 왔는데... 제가 끌어올린 비기너 분들이 열심히 성장하는 모습이 최고 멋지네요!! ㅎㅎ

그래서 오랜만에 좀 더 알려주고 싶은 마음에, 간단하게 몇 글자 끄적여 놨습니다..
굳이 바꿔야 할 내용은 아니니 코멘트로 달아 둘게요! 시간이 난다면 한번 알아봐주면 좋겠다~~~!

2023-05-06 07:57 UTC, D0Dam commented on src/pages/Inquiry/pagination.tsx
> +}
보니까 타입정의를 위해서 react를 import해서 `Dispatch, SetStateAction` 을 가지고 온 것 같네요~!
큰 건 아니지만 다음과 같은 방법도 생각해 볼 수 있어요~!
각 방법이 가지는 장점이 뭔지를 한 번 생각해보고 바꾸고 싶은 마음이 들었다면..? 바꿔 보는 것도 좋을 것 같아요~!

1. import를 type으로 해오기
- import를 할 때 type으로 가지고 올 수 있다는 사실! 알고 있었나요? 과연 type 붙이면 어떤 일이 발생할까요?
```
import type {Dispatch, SetStateAction} from 'react';
```

2. React에서 직접 꺼내오기
- 이 경우에는 react를 굳이 import 하지 않아도 된답니다~!
```suggestion
import styles from './Inquiry.module.scss';

interface Props {
  totalPage: number;
  setPage: React.Dispatch<React.SetStateAction<number>>;
  page: number;
}
```

3. 그냥 그대로 쓰기

+add)

약간 추가적으로 쓰고 싶은 팁(?)인데, 가독성을 위해서 `Dispatch<SetStateAction<T>>`을 따로 타입을 정의해서 사용하기도 하더라구여

```tsx
//이런 느낌..?
type Dispatcher<S> = Dispatch<SetStateAction<S>>
```

근데 이건 공통적으로 적용되어야 될 문제 같아서 이렇게도 하는구나~ 하고 넘어가 주세요~!

2023-05-06 07:57 UTC, D0Dam commented on src/pages/Inquiry/pagination.tsx
> +  };
이거! 하나로 합쳐도 되겠다는 생각이 드는데요??
(인자로 몇 페이지를 넘어갈건지 정수를 받는다면...? 예를 들어 movePage(-10)하면 10페이지 뒤로 가는거죠!!)
아마 이렇게 구현을 하려고 하게 되면 onClick 이벤트 때문에 밖으로 함수를 빼는게 어려울 수 있긴 할거에요.
```tsx
//이런식으로 써야되니까...?
<button type="button" className={styles.pagination__svg} onClick={() => movePage(-10)}>
```
그래서 한번 알고 있을 수 있지만 꽤 쓸만한 개념(?)인 **커링**을 공부해보세요! 그럼 다음과 같이 함수를 집어넣을 수 있을거에요!
```tsx
//요렇게!
<button type="button" className={styles.pagination__svg} onClick={movePage(-10)}>
```
[커링 참고](https://ko.javascript.info/currying-partials)

그리고 이건 그냥 궁금한건데, 페이지 뒤로가기 할때는 `prev`가 10보다 큰지 1보다 큰지 비교하는데 반해서 페이지 넘어가기 할때는 props로 page를 받아와서 totalPage와 비교해 주는 이유가 있을까요? `prev`를 쓰게 되면 어떤 문제가 생긴다던가..?

2023-05-06 07:57 UTC, D0Dam commented on src/pages/Inquiry/pagination.tsx
> +      <div className={styles.pagination}>
왜 `div` 가 두번 묶여 있을까요..?

그리고 이 버튼들을 묶어놓은 이 공간... `div` 말고 다른 태그를 사용해도 좋지 않을까요?
지금 당장 바꾸라는 건 아니지만...! 한 번 `semantic tag` 를 왜 사용하는지, 어떤 경우에 어떤 태그를 사용하면 좋을 지 생각하고 적용하는 연습을 지금부터 해 보면 좋을 것 같아요!

2023-05-06 08:45 UTC, ChoiWonBeen requested changes
UI만 만드려던게 어쩌다가 API도 붙이고 컴포넌트화도 진행되고 하고 있는데, 오히려 좋다고 생각해요~
이참에 이것저것 수정해서 기능까지 만들어버리죠 ㅋㅋ

2023-05-06 08:45 UTC, ChoiWonBeen commented on src/api/Post/index.ts
> +  return data;
디자인 상에선 한페이지당 8개의 게시글을 불러오는 것 같아요!

2023-05-06 08:45 UTC, ChoiWonBeen commented on src/pages/Setting/index.tsx
> +          <div className={styles.service__text}>문의하기</div>
이 글자를 눌러도 페이지가 이동하지 않는데 개인적으로 좋은 UX는 아닌 것 같아요..!

2023-05-06 08:45 UTC, ChoiWonBeen commented on src/pages/Setting/index.tsx
> +            <button type="submit" className={styles.service__announcement}>
여기도 `cursor:pointer`가 적용되면 좋을 것 같아요

2023-05-06 08:45 UTC, ChoiWonBeen commented on src/pages/Inquiry/index.tsx
> +          </div>
<img width="234" alt="image" src="https://user-images.githubusercontent.com/50780281/236613236-6fb7c047-84ac-4ae5-be80-812fa13be82d.png">
중앙 정렬이 필요해보여요~

2023-05-06 08:45 UTC, ChoiWonBeen commented on src/pages/Inquiry/index.tsx
> +      <div className={styles.footer}>
검색창, 글쓰기버튼을 footer라고 하기엔 어색해보여요.
아무래도 앱 바닥에 붙어있는, 추가적인 네비게이션과 앱/회사 소개 등이 footer에 어울리죠.

2023-05-06 08:45 UTC, ChoiWonBeen commented on src/pages/Inquiry/index.tsx
> +        </div>
<img width="1756" alt="image" src="https://user-images.githubusercontent.com/50780281/236613355-cd80ecea-015c-47a4-9925-639bd9433a66.png">

중앙정렬이 맞지 않는데, 위 테이블과 같은 container를 공유하게끔 바꾸거나, margin-left와 right를 동시에 auto로 주는 방법 등... 이 있어보이네요 .

2023-05-06 08:45 UTC, ChoiWonBeen commented on src/pages/Inquiry/index.tsx
> +              </div>
th가 `NO`니깐, content보단 index를 통한 접근이 올바른 것 같아요.

2023-05-06 08:45 UTC, ChoiWonBeen commented on src/pages/Inquiry/index.tsx
> +              </div>
각각의 div마다 key가 포함된 이유는 무엇인가요??

2023-05-06 08:45 UTC, ChoiWonBeen commented on src/pages/Inquiry/index.tsx
> +            <div className={styles.body__list}>
오히려 여기엔 key가 필요해보여요.
<img width="915" alt="image" src="https://user-images.githubusercontent.com/50780281/236613596-857b2ddc-a5f3-40d5-8861-99ce27073226.png">

2023-05-06 08:45 UTC, ChoiWonBeen commented on src/pages/Inquiry/index.tsx
> +            <div className={styles.body__list}>
페이지네이션은 컴포넌트로 잘 분리하셨는데, 테이블도 분리할 만 해보이지 않나요? ㅋㅋ 
테이블 헤더 리스트, 데이터 목록 정도만 Props로 다루면 다른 종류의 테이블도 쉽게 만들 수 있을 것 같아요.

2023-05-06 08:45 UTC, ChoiWonBeen requested changes
UI만 만드려던게 어쩌다가 API도 붙이고 컴포넌트화도 진행되고 하고 있는데, 오히려 좋다고 생각해요~
이참에 이것저것 수정해서 기능까지 만들어버리죠 ㅋㅋ

2023-05-07 19:01 UTC, hyejun0228 commented on src/pages/Inquiry/pagination.tsx
> +}
오옹 type을 import 하는 방법이 여러가지였군요..!!! React에서 직접꺼내오는 방법이 코드가 더 간결해지는 것 같아 수정했습니다!! 
d781c095643ab1cec06f893863fd7e7af336140a

2023-05-07 19:11 UTC, hyejun0228 commented on src/api/Post/index.ts
> +  return data;
넵! 수정했습니다!

2023-05-07 19:12 UTC, hyejun0228 commented on src/pages/Setting/index.tsx
> +            <button type="submit" className={styles.service__announcement}>
모든 버튼 부분에 `cursor:pointer`추가하는게 좋을까요?!

2023-05-07 19:18 UTC, hyejun0228 commented on src/pages/Inquiry/index.tsx
> +      <div className={styles.footer}>
`nav` 로 수정했습니다! 태그명도 같은이름으로 수정했습니다! 859ec696ddc7fc7980e930453c26374c9404f229

2023-05-08 00:04 UTC, ChoiWonBeen commented on src/pages/Setting/index.tsx
> +            <button type="submit" className={styles.service__announcement}>
링크로 동작하는 부분에 한해서는 필요하다고 생각해요

2023-05-08 04:47 UTC, hyejun0228 commented on src/pages/Inquiry/index.tsx
> +              </div>
앗 원래 `<button>` 태그였던걸 `<div>`로 바꿔줄때 안지웠나봐요..! 수정하겠습니다!

2023-05-08 09:27 UTC, hyejun0228 commented on src/pages/Inquiry/pagination.tsx
> +      <div className={styles.pagination}>
`<nav>` 로 수정했습니다! 6e51900d95a02ee6b0afaebe9e3f0e7fd045dc78 
지금 코드부터 바꿔보겠습니다!

2023-05-08 09:27 UTC, hyejun0228 commented on src/pages/Setting/index.tsx
> +            <button type="submit" className={styles.service__announcement}>
넵! 수정하겠습니다

2023-05-08 09:54 UTC, hyejun0228 commented on src/pages/Inquiry/index.tsx
> +              </div>
음 `{res.content}` 얘기하시는건가요??!

2023-05-08 12:37 UTC, hyejun0228 commented on src/pages/Inquiry/index.tsx
> +        </div>
수정했습니다! 5196b22c07a38fd31228c95a05ceb60d9011bb7a

2023-05-08 13:08 UTC, hyejun0228 commented on src/pages/Inquiry/index.tsx
> +              </div>
초창기에 map을 통해 하나의 `<div>` 태그를 만들어서 값이 잘 불러와지나 확인했는데 태그들을 복사해서 안의 값만 다르게 해주다보니 key값을 안지운것 같습니다..! 전체 `<div>`를 감싸는 태그에 key값을 넣어주는걸로 수정했습니다! 
52313653462c6de977d69565593207f54fa9fab2

2023-05-08 13:09 UTC, hyejun0228 commented on src/pages/Inquiry/index.tsx
> +            <div className={styles.body__list}>
52313653462c6de977d69565593207f54fa9fab2 
수정했습니다!

2023-05-08 18:59 UTC, ChoiWonBeen commented on src/pages/Inquiry/index.tsx
> +              </div>
몇번째 게시글인지가 중요하니, 아마 글 ID가 적절할 것 같네요. response에 포함돼있다면?

2023-05-09 02:20 UTC, hyejun0228 commented on src/pages/Setting/index.tsx
> +          <div className={styles.service__text}>문의하기</div>
임시로 만들어 놓겠습니다..!

2023-05-09 05:08 UTC, hyejun0228 commented on src/pages/Inquiry/index.tsx
> +          </div>
수정했습니다!

2023-05-09 07:29 UTC, hyejun0228 commented on src/pages/Inquiry/index.tsx
> +            <div className={styles.body__list}>
넵! 분리했습니다!!
80ee6a83a80f9b1aebbe1c1966ec19ea44510b72

2023-05-09 07:31 UTC, hyejun0228 commented on src/pages/Inquiry/index.tsx
> +              </div>
`{
      "title": "테스트 일반 공지7",
      "content": "테스트 내용",
      "boardType": "NOTICE",
      "createdAt": "2023-03-28"
    }`
    한 배열에 딱 4개의 정보뿐이라..수정하긴 힘들것같습니다..! 나중에 문의하기 api가 나온다면 수정하겠습니다!

2023-05-09 16:45 UTC, hyejun0228 commented on src/pages/Inquiry/pagination.tsx
> +  };
으음...커링을 공부해봤는데 각각의 함수 구현이 다르기 때문에 따로 작성할 수 밖에 없지 않을까요..?

앗 원래 `page` 로 쓰이던걸 `prev` 로 바꿔주면서 잘 안바꿔졌나봅니다..! 수정했습니다..!!

2023-05-09 19:17 UTC, ChoiWonBeen approved these changes
긴 리뷰 두 개 달아놨으니 만족스럽게 수정되면 머지해도 될 것 같아요~
다음 공지사항 기능 할때 페이지네이션에 URL 변경되는 searchParam기능까지 같이 추가해서 수정되면 좋을 것 같네요. 이번엔 많이 지연됐으니 다음꺼루 고고

2023-05-09 19:17 UTC, ChoiWonBeen commented on src/pages/Inquiry/index.tsx
> +        }
데이터가 있다는 조건은 `postData`만으로 작성해도 괜찮을 것 같아요. 옵셔널이 붙으니 좀 더 고려할게 늘어나는 느낌?
아래 pagination부분도 동일하구요
```suggestion
        {
          postData && (
            <Datatable data={postData.content} />
          )
        }
```

2023-05-09 19:17 UTC, ChoiWonBeen commented on src/pages/Inquiry/index.tsx
> +          <Link to="/Myinquiry" className={styles.header__link}>
(아직 안쓰는 부분이지만) 링크가 혼자 대문자로 시작해요~

2023-05-09 19:17 UTC, ChoiWonBeen commented on src/pages/Inquiry/pagination.tsx
> +  };
위 리뷰에서도 언급했듯, 하나의 코드로 줄일 수 있을 것 같아요.
한번 이해하고 적용해보세여
```suggestion
  const movePage = (offset: number) => {
    setPage((prev) => {
      if(prev + offset < 1) return 1;
      if(prev + offset > totalPage) return totalPage;
      return prev + offset;
    });
  };
```

2023-05-09 19:17 UTC, ChoiWonBeen commented on src/pages/Inquiry/pagination.tsx
> +        }
limit을 1로 바꾸고 테스트해보면, 게시판의 글이 5페이지가 넘어가자 1, 2, 3밖에 안나오더라구요(디자인은 5까지 나와야함)

그으래서 이 부분을 js를 쓰면 어떻게 고치면서 줄일 수 있을 것 같아서 시도해봤어요.

페이지 목록을 아래 코드처럼 작성하고... (조금 복잡할 수 있으니 이해안되면 얘기 고고)
```ts
 const pageList = [...Array(totalPage)]
    .map((_, index) => index + 1)
    .slice(Math.min(Math.max(page - 3, 0), totalPage - 5), totalPage)
    .slice(0, 5);

  return (
```

링크 부분을 전부 지우고 아래처럼 작성할 수 있어요.
```suggestion
      {pageList.map((item) => (
        <button
          type="button"
          key={item}
          className={
            item === page
              ? styles.pagination__page
              : styles['pagination__sub-page']
          }
          onClick={() => setPage(item)}
        >
          {item}
        </button>
      ))}
```

이렇게하면 페이지 번호를 클릭해도 이동이 가능해지고, 게시판이 최대 5개까지 잘 보이게 됩니다.
다만 `onClick` 을 담으려면 button등 알맞는 태그로 바꿔야 하기에, 바꾼 뒤 추가되는 css를 제거해줘야 할거예요.

이런건 page, subpage처럼 나누기보단, modifier로 `--active`처럼 작성하면 더 명시적이겠죠?
```scss
  &__page {
    color: $default;
    font-size: 16px;
    padding: 13px;
    background-color: $back;
    border: none;
    outline: none;
    cursor: pointer;

    &--active {
      color: $highlight;
    }
  }
```

이를 적용하는 부분에는 `classNames(cn)`을 써서 쉽게 적용할 수 있을거예요.
```tsx
        <button
          type="button"
          key={item}
          className={cn({
            [styles.pagination__page]: true,
            [styles['pagination__page--active']]: item === page,
          })}
          onClick={() => setPage(item)}
        >
          {item}
        </button>
```

2023-05-09 19:17 UTC, ChoiWonBeen approved these changes
긴 리뷰 두 개 달아놨으니 만족스럽게 수정되면 머지해도 될 것 같아요~
다음 공지사항 기능 할때 페이지네이션에 URL 변경되는 searchParam기능까지 같이 추가해서 수정되면 좋을 것 같네요. 이번엔 많이 지연됐으니 다음꺼루 고고

2023-05-10 13:01 UTC, hyejun0228 commented on src/pages/Inquiry/index.tsx
> +        }
넵 수정했습니다!

2023-05-10 13:01 UTC, hyejun0228 commented on src/pages/Inquiry/index.tsx
> +          <Link to="/Myinquiry" className={styles.header__link}>
수정하겠습니다!

2023-05-10 13:52 UTC, ChoiWonBeen commented on src/pages/Inquiry/Myinquiry.tsx
> +export default function myinquiry(): JSX.Element {
컴포넌트 이름은 대문자로 시작해야대여!

2023-05-10 16:25 UTC, hyejun0228 commented on src/pages/Inquiry/pagination.tsx
> +        }
마지막 코드에서 cn 함수가 어떤식으로 쓰였는지 조금 더 설명 가능하신가요..?! ㅠㅠ

2023-05-10 16:32 UTC, hyejun0228 commented on src/pages/Inquiry/Myinquiry.tsx
> +export default function myinquiry(): JSX.Element {
넵! 수정했습니다!

2023-05-10 17:46 UTC, hyejun0228 commented on src/pages/Inquiry/pagination.tsx
> +  };
56a6998d96443b7bd426c42cef55e92045bdad30 
넵! 적용 했습니다!! 감사합니다!

2023-05-10 17:47 UTC, hyejun0228 commented on src/pages/Inquiry/pagination.tsx
> +        }
설명 감사합니다! 이해 했습니다!! 
56a6998d96443b7bd426c42cef55e92045bdad30

2023-05-10 17:49 UTC, merged