Feature/#70 탈퇴하기 페이지 제작
BCSDLab/TEMP_PROJECT_FE pull request #73
Opened 2023-05-02 15:53 UTC by KimKyungYun

## [#70] 탈퇴하기 페이지 제작

탈퇴이유 정보를 받아가는 api가 아직 없어서 틀만 만들어놓은 상태입니다.
이후에 백엔드에서 작업이 완료되면 추가하도록 하겠습니다.

닉네임이 이상한이유는 회원가입 완료 후 닉네임 적는 페이지에 api를 추가시켜야해서 추후 수정하면 고쳐질 예정입니다
## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [ ] Docs updated for breaking changes

### Screenshot
![image](https://user-images.githubusercontent.com/60084235/235718277-73b321ad-7f98-46d1-8ada-e180145fd555.png)
![image](https://user-images.githubusercontent.com/60084235/235718395-6c1450e6-e7cc-494c-8964-d2282cb46c4f.png)
![image](https://user-images.githubusercontent.com/60084235/235718534-6d12f9d0-6dbd-4c94-a4aa-92df423283f2.png)

2023-05-04 02:26 UTC, ChoiWonBeen requested changes
고생하셨어요~ 
몇가지 로직에 대한 궁금한 점들과 생각해볼만한 점들 나열해뒀습니다! 확인해주세요~

2023-05-04 02:26 UTC, ChoiWonBeen commented on src/pages/Setting/Withdrawal/index.tsx
> +          <button type="submit" className={styles.form__button} onClick={() => open()} disabled={!isCheck}>
콜백을 만들어 정의한 이유가 있나여?
```suggestion
          <button type="submit" className={styles.form__button} onClick={open} disabled={!isCheck}>
```

2023-05-04 02:26 UTC, ChoiWonBeen commented on src/pages/Setting/Withdrawal/index.tsx
> +            </label>
label > input 구조면  `htmlFor, id`가 필요없다고 했던 것 같은데 확인해보셨나요?!

2023-05-04 02:26 UTC, ChoiWonBeen commented on src/pages/Setting/Withdrawal/index.tsx
> +  const [isCheck, checked] = useBooleanState(false);
`[state, setState(true)]` 라면  `checked`보다는 `check`가 더 적절할 것 같아요 ㅋㅋ

2023-05-04 02:26 UTC, ChoiWonBeen commented on src/pages/Setting/Withdrawal/index.tsx
> +              <input type="radio" id="discomport" name="reason" onClick={checked} />
onClick에 넣은 함수가 state를 true로만 바꾸는데, 
1. 2번 눌렀을 때는 false가 될까요?
2. 그렇지 않다면 radio는 왜 false가 가능해질까요?
3. 전부 같은 상태(`isCheck`)를 다룬다면 각각의 입력에 대한 핸들링이 가능할까요?
4. 그럼 submit이 실행됐을 때 어떤 input들이 true인지 검증이 가능할까요?

2023-05-04 02:26 UTC, ChoiWonBeen commented on src/store/auth.ts
> +const clearaAuthAtom = atom(null, (get, set) => {
오타가 있어요!
```suggestion
const clearAuthAtom = atom(null, (get, set) => {
```

2023-05-04 02:26 UTC, ChoiWonBeen commented on src/store/auth.ts
> +export const useClearAuth = () => useSetAtom(clearaAuthAtom);
쓰는 쪽에서 이름을 추론하기 어려울 것 같다는 생각도 들어요.
`useLogout` 같은 직관적인 이름도 생각해볼 법도 싶은데, 다른 함수들과의 통일성이 떨어진다고도 보이네요

2023-05-04 02:26 UTC, ChoiWonBeen commented on src/store/auth.ts
> +});
로그아웃이라면, 스토어를 초기화하는 과정도 필요하겠네요.
refreshToken과, accessToken이 함께 쓰고있으니, 이를 없애주면 될 것 같아요.

2023-05-04 02:37 UTC, KimKyungYun commented on src/pages/Setting/Withdrawal/index.tsx
> +          <button type="submit" className={styles.form__button} onClick={() => open()} disabled={!isCheck}>
무한루프 방지하려고 콜백으로 호출하는 습관이 있어서 콜백으로 작성했던 것 같습니다
원래코드가 콜백으로 작성되어있어서 굳이 할 필요가 없던 것 같습니다. 수정해두겠습니다!

2023-05-04 02:41 UTC, KimKyungYun commented on src/pages/Setting/Withdrawal/index.tsx
> +            </label>
htmlfor를 제거하면 lint에러가 발생해서 그냥 놔둔 것 같습니다.  lint예외를 해두는게 좋을까요?

2023-05-04 02:45 UTC, KimKyungYun commented on src/store/auth.ts
> +const clearaAuthAtom = atom(null, (get, set) => {
수정했습니다

2023-05-04 02:50 UTC, KimKyungYun commented on src/pages/Setting/Withdrawal/index.tsx
> +  const [isCheck, checked] = useBooleanState(false);
수정했습니다ㅋㅋ

2023-05-04 02:50 UTC, KimKyungYun commented on src/store/auth.ts
> +});
토큰제거 코드 추가했습니다

2023-05-04 03:10 UTC, KimKyungYun commented on src/pages/Setting/Withdrawal/index.tsx
> +              <input type="radio" id="discomport" name="reason" onClick={checked} />
radio 버튼으로 만들어서 한번 누르면 꺼지지 않고 해당 버튼이 활성화 되는 방식으로 작동하도록 생각해서 true로만 작동하도록 설정해두었습니다.
때문에 두번 누르더라도 false가 되지않고 true상태를 유지한다고 생각했습니다.

아직 api가 없어서 그냥 on off 만 감지해두는 방식으로 작성해두고 나중에 생겼을 때에 value값을 읽어와서 submit하는 방식으로 수정하자~ 라고 생각해서 true만 감지하게 만들었던 것 같습니다..ㅎ

2023-05-04 03:12 UTC, KimKyungYun commented on src/store/auth.ts
> +export const useClearAuth = () => useSetAtom(clearaAuthAtom);
음 auth 제거해서 로그아웃하는 방식을 사용하니깐 이름을 useDeleteAuth 정도로 바꿔두는게 좋을까요?

2023-05-04 03:15 UTC, ChoiWonBeen commented on src/pages/Setting/Withdrawal/index.tsx
> +              <input type="radio" id="discomport" name="reason" onClick={checked} />
사실 저런 UI라면 체크박스를 쓰거나,
4가지 input에 대해 radio를 쓰는게 맞는거같네요.
상태로 어떤 값을 갖고있어야 submit에 쓸 수 있을지 고민해보세여 ㅋㅋ

2023-05-06 09:02 UTC, ChoiWonBeen approved these changes
남은 몇가지만 확인해주시고 병합해도 괜찮을 것 같아요~

2023-05-06 09:02 UTC, ChoiWonBeen commented on src/App.tsx
> +          <Route path="/Withdrawal" element={<Withdrawal />} />
혼자 url이 대문자로 시작해요!

2023-05-06 09:02 UTC, ChoiWonBeen commented on src/pages/Setting/Withdrawal/index.tsx
> +      {modal && <WithdrawalModal />}
시간이 난다면..`createProtal`로 만들어 보는것도...?ㅎㅎㅎ

2023-05-06 09:02 UTC, ChoiWonBeen commented on src/pages/Setting/Withdrawal/components/WithdrawalModal.tsx
> +            navigate('/login', { replace: true });
navigate가 없어도 `clearAuth`만으로도 redirecting이 되지 않나요? 관심사를 분리하려 애쓴 부분이라 피할 수 있다면 피하는 것도 좋아보여요

2023-05-06 09:02 UTC, ChoiWonBeen commented on src/pages/Setting/Withdrawal/index.tsx
> +      </div>
상단바가 큰 화면으로 보면 갑자기 내려오는 것처럼 보여서 맨 위에 고정시키는것도 괜찮아보여요.
![image](https://user-images.githubusercontent.com/50780281/236614081-41fd8d4e-d157-49b6-a0d9-bb42b9387286.png)

2023-05-06 09:02 UTC, ChoiWonBeen approved these changes
남은 몇가지만 확인해주시고 병합해도 괜찮을 것 같아요~

2023-05-06 09:03 UTC, ChoiWonBeen commented on src/store/auth.ts
> +export const useClearAuth = () => useSetAtom(clearaAuthAtom);
다른 살마들이 로그아웃을 만든다면 `useLog...` 처럼 검색할텐데, 이를 생각해서 쉬운 이름으로 만드는것도 괜찮아보여요ㅋㅋ

2023-05-07 02:32 UTC, KimKyungYun commented on src/App.tsx
> +          <Route path="/Withdrawal" element={<Withdrawal />} />
수정했습니다~

2023-05-07 03:23 UTC, KimKyungYun commented on src/store/auth.ts
> +export const useClearAuth = () => useSetAtom(clearaAuthAtom);
참고해서 수정해보겠습니다 ㅎ

2023-05-07 03:24 UTC, KimKyungYun commented on src/pages/Setting/Withdrawal/components/WithdrawalModal.tsx
> +            navigate('/login', { replace: true });
수정했습니다~

2023-05-07 03:27 UTC, KimKyungYun commented on src/pages/Setting/Withdrawal/index.tsx
> +      </div>
수정했습니다

2023-05-07 03:27 UTC, KimKyungYun commented on src/pages/Setting/Withdrawal/index.tsx
> +      {modal && <WithdrawalModal />}
이것까지만 도전해보고 머지하겠습니다ㅋㅋ

2023-05-07 04:13 UTC, merged