Feature/#71 공지사항 페이지 제작
BCSDLab/TEMP_PROJECT_FE pull request #75
Opened 2023-05-15 11:31 UTC by hyejun0228

## [#71] request

- 기존 문의사항 페이지에서 만들어두었던 페이지네이션 컴포넌트와 데이터 테이블 컴포넌트를 통해 공지사항 페이지 추가했습니다. 

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

### Screenshot

<img width="1470" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/114041848/ddc96055-c204-44cc-89fa-29be7c1fe63c">

2023-05-17 08:36 UTC, ChoiWonBeen requested changes
고생하셨어요~ 간단하게 몇가지 코멘트해봤습니다!
근데 브랜치 번호가 유지되었던데, 공지사항 페이지는 #74 이므로 브랜치를 굳이 유지할 필요는 없었을 것 같아요

2023-05-17 08:36 UTC, ChoiWonBeen commented on src/components/DataTable/index.tsx
> +            <Link to="/Myinquiry" className={styles.header__link}>
여기 링크도 대문자로 되어있네요? 소문자로 통일해도 될거같아요

2023-05-17 08:36 UTC, ChoiWonBeen commented on src/components/DataTable/index.tsx
> +          <h3 className={styles['header__sub-title']}>{titleMessage}</h3>
bem 네이밍이 subtitle이라면 props도 `subTitle`로 받는 건 어땠을까요?

2023-05-17 08:36 UTC, ChoiWonBeen commented on src/pages/Inquiry/index.tsx
> +import Datatable from '../../components/DataTable';
절대 경로 지정 룰이 없었나보네요?
다른 프로젝트들처럼 린트 룰도 추가하는건 어떨까요?
```suggestion
import Pagination from 'components/Pagination';
import Datatable from 'components/DataTable';
```

2023-05-17 08:36 UTC, ChoiWonBeen commented on src/components/DataTable/index.tsx
> +          )
컴포넌트에서 해당 부분을 핸들링하기보단, `DataTable`의 optional한 props로 이 부분 UI조각을 넘기는 건 어떨까요?

2023-05-18 06:00 UTC, hyejun0228 commented on src/components/DataTable/index.tsx
> +            <Link to="/Myinquiry" className={styles.header__link}>
넵 수정했습니다!
81b43ffc054677459c9868f34f829aa1930dd48f

2023-05-18 06:00 UTC, hyejun0228 commented on src/components/DataTable/index.tsx
> +          <h3 className={styles['header__sub-title']}>{titleMessage}</h3>
넵 수정했습니다!!
81b43ffc054677459c9868f34f829aa1930dd48f

2023-05-18 06:04 UTC, hyejun0228 commented on src/pages/Inquiry/index.tsx
> +import Datatable from '../../components/DataTable';
수정햇습니다!
ce914a339b8c844c0deecff9860375ddd13372f9

2023-05-18 07:44 UTC, ChoiWonBeen commented on src/pages/Inquiry/index.tsx
> +import Datatable from '../../components/DataTable';
> 다른 프로젝트들처럼 린트 룰도 추가하는건 어떨까요?

이거에 대해선 어떻게 생각하시나요?? 🧐

2023-05-21 19:57 UTC, hyejun0228 commented on src/components/DataTable/index.tsx
> +          )
넵 !  수정했습니다! 
fcc16c7bdc3c53fb73a5f6ab09e6bea0c41c0256

2023-05-22 07:36 UTC, ChoiWonBeen commented on src/components/DataTable/index.tsx
> +          )
지금 수정한 느낌보다는, `DataTable` 의 props로 `tableTopButton ?: 컴포넌트` 같은 구조로 만들어보는게 어떨까했어요.
문의하기 페이지에서만 해당 props로 저 버튼을 넘기면 되고, 그런?

아니면 아예 조합 패턴으로 바꾸는것도 좋아보이고 이상적일 것 같은데 두 가지 방법 모두 생각해볼만 해보여요.
[참고할만한 링크](https://fe-developers.kakaoent.com/2022/221020-component-abstraction/)입니다.

2023-05-24 09:28 UTC, hyejun0228 commented on src/components/DataTable/index.tsx
> +          )
이번에 만든 `<MyInquiry>`가 `<DataTable>` 에서 의존성이 너무 강하다는 것을 깨닫고 Props형식으로 `<MyInquiry>`를 내려주고  'TableTopButton?: React.ElementType;' 같은 구조를 추가했습니다! 
또한 정보가 있으면 출력을 하고 없으면 출력을 안하는 optional을 사용했기 때문에 `{TableTopButton && <TableTopButton />}` 를 추가했습니다. c82f4cd0e40cbdffd1e78cb0afc7b2733ad5fa1c

2023-05-24 10:21 UTC, hyejun0228 commented on src/pages/Inquiry/index.tsx
> +import Datatable from '../../components/DataTable';
1737fcf3d126eeefb9efc5f3aca6578713f57f21 
코인 오너 프로젝트를 참고해서 린트 룰 추가했습니다!

2023-05-25 02:40 UTC, ChoiWonBeen commented on src/components/DataTable/index.tsx
> +          )
딱 원한 구조예요 👍

2023-05-25 02:41 UTC, ChoiWonBeen approved these changes
고생했습니다~ 쩝박 핵심 기능 확정 이전까지 잠시 대기해주셔도 될 것 같고, 다음 글쓰기 만들기로했으니 로직 분석정도는 하고있어도 좋을 것 같아요

2023-05-25 02:41 UTC, merged