Feature/#78
BCSDLab/TEMP_PROJECT_FE pull request #79
Opened 2023-06-23 03:26 UTC by ChoiWonBeen

## [#78] request

전체적으로 디자인 바뀐 부분, 변경 중 에러난 부분들을 찾아 일차적으로 수정했습니다.
- 자동로그인 체크박스가 탈퇴 UI에 포함된 CSS랑 동일해진 문제 수정
- 검색창 제목 글 안맞는 문제 수정
- 아이디 / 비밀번호 찾기 페이지 높이가 낮은 디바이스에서 위아래가 잘리는 문제 수정
- 메인페이지 공용 상단바에 아이콘 추가 / 링크 수정
- 아이디찾기 API 경로 변경된 것 맞춰서 수정

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

코드리뷰가 필요한 부분은 아니고, 기능 동작 한번씩 해보면서 문제없는지와, 운영체제(윈도우)에서 오류없는지만 봐주시면 감사하겠습니당

이것도 근데 몇 분 안돼서 찾은 부분들인데, 한 번 기능 쭉 돌려보면서 문제있는 부분들은 찾아서 이슈에 담아두고 수정해야할 것 같아요.
아이디찾기 - 비밀번호 찾기 PC버전 UI도 추가됐으니 회원가입때 썼던 UI 처럼 활용해 만들면 되겠네요

2023-07-04 07:42 UTC, chaeseungyun requested changes
지금 확인해보니 비밀번호 찾기 관련 api에 변경이 있었던 것 같습니다.
비밀번호 변경 관련 api(PATCH 'user/'password')가 사라진 상태라 비밀번호 찾기가 정상적으로 이루어지지 않고있네요
현재 비밀번호 찾기 api를 호출하면 accessToken을 반환하던데 무슨 의미인지 잘 모르겠어요
그리고 비밀번호 찾기 마지막 페이지에 인증번호 보내기가 아니고 변경 완료와 같은 문구가 있어야 할 것 같습니다

2023-07-11 14:12 UTC, ChoiWonBeen commented
@chaeseungyun 비밀번호 찾기 UI와 API 수정해서 정상작동합니다!
제공하는 accessToken을 활용해 내 정보 변경 api(`PATCH: /user/me`) 를 호출하게끔 바뀌었네요

2023-07-14 03:57 UTC, chaeseungyun requested changes

2023-07-14 03:57 UTC, chaeseungyun commented on src/api/user/index.ts
> +export const changePassword = (param: ChangePasswordParams) => userApi.patch('/me', {
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/101871802/39133e9d-40c8-417d-a68a-5787e05833af)
제 컴퓨터에서는 다음과 같은 에러가 발생하는데 이유가 뭘까요?
단일 필드 변경이 가능하니 닉네임이 없어서 그런것은 아닐텐데요...

2023-07-19 21:23 UTC, ChoiWonBeen commented on src/api/user/index.ts
> +export const changePassword = (param: ChangePasswordParams) => userApi.patch('/me', {
url이 `PATCH: user/modify`가 아니라 `PATCH: user/me`로 바뀌었었네요 ㅋㅋ 맞춰서 수정해서 적용했습니다!

2023-07-20 07:35 UTC, chaeseungyun approved these changes

2023-07-20 07:36 UTC, chaeseungyun commented
고생하셨습니다!!

2023-07-21 20:53 UTC, merged