Feature/#76 메인페이지 마커 디자인변경, 드롭다운메뉴 제작
BCSDLab/TEMP_PROJECT_FE pull request #80
Opened 2023-06-29 12:46 UTC by KimKyungYun

## [#76] request
1차베포버전 메인페이지 디자인 수정했습니다.
마커 디자인변경하고, 마커필터 드롭다운메뉴로 구성변경했습니다. 

마커에 인덱스 번호를 추가하는 과정에서 useEffect와의 충돌로 인덱싱에 문제가 생겨서  마커의 z-index 속성을 이용해서 getZIndex를 사용했습니다.
따로 마커의 인덱스 번호를 방법이 있다면 해당 방법으로 수정하도록 하겠습니다.

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [ ] Docs updated for breaking changes

### Screenshot
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/60084235/9dde2467-d435-43b4-ae68-7bebdaa94847)
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/60084235/5c3058c6-5dd5-4b6f-a493-1fa351e5b98f)
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/60084235/b16da0cd-9a75-44ef-a1e7-2f2108dbbd3b)

2023-07-04 07:00 UTC, ChoiWonBeen requested changes
휴가를 좀 다녀오느라 리뷰가 늦어졌네요 😅 몇가지 수정사항 확인해주세요~~

2023-07-04 07:00 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/components/MarkerHtml/index.tsx
> +          <img src=${defaultImg} alt=""/>
보다가 생각난건데 html 코드에서 `<img>` 태그는 children을 받을 수 없어요! (jsx완 다르게 `<img />` 형태가 아닌 `<img>` 만으로 쓰입니다)
실제 렌더링도 img태그 안에 들어간 게 아닌, 형제 요소로 취급하네요 ㅋㅋ 닫는 Img태그를 없애고 나란히 둬도 괜찮아보여요.

<img width="965" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/50780281/7e1a242e-a953-4d42-a2c2-c2a3737ac70d">

추가적으로 스크린 리더를 고려한다면 가장 바깥 태그에 포커스 가능한 요소를 두고 alt를 해당 상점의 이름으로 두는 건 어떨까 싶어요

2023-07-04 07:00 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/index.tsx
> +        content: ClickedMarkerHtml(defaultImg, item.placeName, item.index),
`defaultImg`가 string으로 추론이 되는데, 이미지 파일이 문자열의 함수 인자로 쓰이는게 부적절한 것 같아요. 해당 컴포넌트 내에서 import를 받아 쓰는게 어떨지 생각해봅니다

2023-07-04 07:00 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/components/MarkerHtml/index.tsx
> +import Selected from 'assets/svg/home/selected-marker.svg';
img의 `src` 속성으로 담을 목적이라면, svg파일보다는 png파일로 받아쓰는게 적절할거예요.
svg파일의 장점을 활용하는건 svg 자체를 렌더링하는 것이 올바르다는 생각이 드네요

2023-07-04 07:00 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/components/MarkerHtml/index.tsx
> +        </div>
이 조건이 무엇인가 싶어서 그냥 index를 찍어봤는데 마커 사진에 글자가 들어가더라고요?
여기 출력한 Index가 무엇을 의미하나요?
```js
${defaultImg === Default ? index : index}
```
<img width="164" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/50780281/fb1cc34c-1d6b-412e-ab9a-e79f7f3cc9f9">

예상이 드는건 이미지가 없을 때 (`defaultImg`가 아닌 `Default` 를 쓰는 경우에 해당하지만 이 조건도 빠진 것 같네요. 둘 사이에 구분도 필요할 듯) Default위에 올라갈 번호인 것 같은데, 확실하게 조건을 수정해줄 필요가 있어보여요.
<img width="158" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/50780281/02a9860c-edf3-46f5-b158-76580f56f18c">
운영체제 차이일 수 있겠지만 아직 제 화면에서는 글자 위치도 조금 깨지는 것 같아요. 확인하시고 수정해주세요!

2023-07-04 07:00 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/components/MarkerHtml/index.tsx
>          </div>
<img width="112" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/50780281/5af3ac99-962c-40fd-a674-a872f7ae6705">

2023-07-04 07:00 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/components/MobileOptions/MobileOptions.module.scss
> +    width: 70%;
여기 상단바를 width의 비율로만 관리하니 마진 뒤에 필터 버튼이 생기고 그러는게 조금 불안한 것 같은데, 
top-options(이름은 nav로 두는게 어떨까 싶네요)를 grid container로 두고, `grid-template-column: 1fr auto` 처럼 두면 필터 버튼의 크기만큼을 제외한 나머지 크기를 search가 100%로 받아 쓸 수 있어요. 
gap만 디자인에 맞춰 작성하면 일정한 간격을 유지할 수 있을 것 같습니다~ 😄

2023-07-04 08:36 UTC, chaeseungyun requested changes
고생하셨습니다!
저는 큰 문제를 못찾아서 수정 사항 완료되면 approve 하겠습니다

2023-07-12 14:13 UTC, KimKyungYun commented on src/pages/Home/components/Map/components/MarkerHtml/index.tsx
> +          <img src=${defaultImg} alt=""/>
수정했습니다

2023-07-12 14:37 UTC, KimKyungYun commented on src/pages/Home/components/Map/components/MarkerHtml/index.tsx
> +import Selected from 'assets/svg/home/selected-marker.svg';
백틱 내부에 작성되어있어서 그런가 ReactComponents로 호출이 안되네요ㅠ
png로 수정해서 작성했습니다

2023-07-12 14:43 UTC, KimKyungYun commented on src/pages/Home/components/Map/components/MarkerHtml/index.tsx
> +        </div>
저 index는 표시되는 figma디자인에 각 마커에 인덱스를 표시해주기위해 사용했습니다. 
사진이랑 글자 위치 세부적으로 수정해두었습니다.

2023-07-13 00:24 UTC, KimKyungYun commented on src/pages/Home/components/Map/components/MarkerHtml/index.tsx
>          </div>
전체블럭을 div로 감싸고 flex 주고 justify-content랑 align-items center로 주는 방식으로 정리했습니다.
클릭했을 때는 absolute로 위치 수정해서 포인트 맞게 변경했습니다

2023-07-13 01:20 UTC, KimKyungYun commented on src/pages/Home/components/Map/components/MobileOptions/MobileOptions.module.scss
> +    width: 70%;
grid로 설정하고 디자인 수정했습니다~!

2023-07-13 07:46 UTC, KimKyungYun commented on src/pages/Home/components/Map/index.tsx
> +        content: ClickedMarkerHtml(defaultImg, item.placeName, item.index),
음 그러면 마커마다 가게의 이미지가 적용되는 경우에는 가게목록을 mapping하면서 이미지를 넘겨주지는 못하지 않을까요?

2023-07-13 16:38 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/index.tsx
> +        content: ClickedMarkerHtml(defaultImg, item.placeName, item.index),
원래라면 각 상점의 이미지를 넣어줘야겠죠?
```ts
{content: ClickedMarkerHtml(item.thumbnail, item.placeName, item.index)}
```
여기서 thumbnail의 타입이 `string | null`일테고, ClickedMarkerHtml내에서 아래와 같은 조건으로 사용하는 건 어떨까요?
```ts
<img src={thumbnail || defaultImg} />
```

2023-07-14 00:40 UTC, KimKyungYun commented on src/pages/Home/components/Map/index.tsx
> +        content: ClickedMarkerHtml(defaultImg, item.placeName, item.index),
오.. 좋은 방법같아요 한번 적용해보겠습니다

2023-07-15 08:19 UTC, ChoiWonBeen approved these changes
위 코멘트대로 `defaultImg`쪽만 바뀌면 병합해도 될 것 같아요~ 고생하셨어여

2023-07-17 03:51 UTC, KimKyungYun commented on src/pages/Home/components/Map/index.tsx
> +        content: ClickedMarkerHtml(defaultImg, item.placeName, item.index),
수정했습니다

2023-07-17 08:58 UTC, merged