Feature/#71 글쓰기 페이지
BCSDLab/TEMP_PROJECT_FE pull request #81
Opened 2023-07-04 15:43 UTC by hyejun0228

## [#71] post

- 페이지 스크롤 기능 추가 
- 다중 이미지 파일 업로드 기능 추가 
- 글꼴 변경 기능 삭제 

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [ ] Docs updated for breaking changes

전체적인 UI부분과 사진 삭제 UI 는 빠른 시일 내에 수정하겠습니다. 

### Screenshot
<img width="337" alt="스크린샷 2023-07-05 오전 12 41 54" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/114041848/71ef5a32-5c42-4860-823c-200d9280d263">
<img width="334" alt="스크린샷 2023-07-05 오전 12 42 04" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/114041848/aa332911-8794-4350-85e7-73ed29ff3d7c">

2023-07-12 07:56 UTC, ChoiWonBeen requested changes
고생하셨어요~ 기능적인 추가는 다음 PR에서 진행하면 될 것 같으니 
몇가지 수정할 사항만 짚고 넘어가면 될 것 같아요.
1. 반응형 대응이 필요하다
2. 저장버튼 및 별점 상점에 대한 정보
3. 사진 추가 시 서버에 업로드 후 해당 사진 활용

2, 3번은 다음 PR에서 진행해도 될 것 같은데, 에디터 부분의 반응형 디자인은 이번 PR에서 잡고가는게 좋아보여요!

2023-07-12 07:56 UTC, ChoiWonBeen commented on src/components/MyInquiry/MyInquiry.module.scss
> +.moveIcon {
클래스명의 단어단위 구분은 하이픈으로 통일해 쓰고있어요!
`styles`를 import하는 구조때문에 사실 camelCase로 적고싶지만.. 다른 코드들이 이미 통일돼서 맞추는 수밖에 없는 것 같아요 ㅠ ㅋㅋ
```suggestion
.move-icon {
```

2023-07-12 07:56 UTC, ChoiWonBeen commented on src/components/editor/Wysiwyg/index.tsx
> +    <div className="wysiwygContainer" ref={containerRef}>
Editor의 크기가 너무 모바일의 고정 width의 맞춰져만있어서 반응형으로 사이즈 조정이 안되는 것 같은데, `+`버튼과 함께 컨테이너의 width가 100% + padding구조로 바뀌어야 할 것 같아요!
어디가 문제인지 찾아가는게 힘들 수 있지만 개발자도구를 열심히 활용해서..! 시도해보시죠 ㅋㅋ

2023-07-12 07:56 UTC, ChoiWonBeen commented on src/components/editor/TextEditor/AddImage/index.tsx
>    }, [imageList, active, inActive]);
얘내들을 모아서 로직을 분리한다면, `useWisiwygImageOpen` 같은 훅으로 모아서 useEffect를 넣어두는 쪽으로 작성한다면 컴포넌트에 로직이 뭉치는 것을 방지할 수 있을 것 같아요

2023-07-12 09:06 UTC, hyejun0228 commented on src/components/MyInquiry/MyInquiry.module.scss
> +.moveIcon {
억..왜 옛날에 만들었던 문의하기 페이지가 같이 PR에 올라갔는지는 모르겠지만...수정이 필요한 부분이 있었군요..! 수정했습니다!

2023-07-12 17:10 UTC, ChoiWonBeen commented on src/components/MyInquiry/MyInquiry.module.scss
> +.moveIcon {
그이유는... 지금 브랜치 (#71) 브랜치가 이전 이슈에 대해 다루고 있기 때문이죠 ㅋㅋ 다음엔 브랜치 새로 만들어서 진행해주세요

2023-07-17 06:10 UTC, hyejun0228 commented on src/components/MyInquiry/MyInquiry.module.scss
> +.moveIcon {
악,,넵!

2023-07-18 07:57 UTC, hyejun0228 commented on src/components/editor/Wysiwyg/index.tsx
> +    <div className="wysiwygContainer" ref={containerRef}>
`@use "src/utils/styles/mediaQuery" as media;` 를 사용하여 반응형으로 사이즈 조절 되게 바꿨습니다! 아직은 전체적으로 보기 어색하지 않을 정도로만 수정하였고, 다음 pr에서 사진 추가 시 서버에 업로드 후 해당 사진을 활용하는 방식으로 바꿔줄 때 글쓰기 페이지 web UI figma 를 참고해서 수정하겠습니다! 

43c4f05e7138afbfdf897bddfdcc1652a7efe72d

2023-07-18 08:09 UTC, hyejun0228 commented on src/components/editor/TextEditor/AddImage/index.tsx
>    }, [imageList, active, inActive]);
`const [opened, active, inActive] = useBooleanState(false);` 에서 반환되는 값들이  useEffect 뿐만아니라 `AddImage.tsx` 에도 쓰이고 있어 컴포넌트를 나눠준다면 더 복잡해지지 않을까요..?!

2023-07-21 21:50 UTC, ChoiWonBeen approved these changes
#89 PR 한번 확인해주시고 해당 PR을 먼저 병합한 뒤, 최신 develop을 병합하고 수정할게 더 있을지 한번 확인해보세요. 전부 괜찮다면 그때 병합해도 괜찮을 것 같네요.

2023-07-24 07:34 UTC, merged