Feature/#1 모바일 하단 네비게이션 추가
BCSDLab/TEMP_PROJECT_FE pull request #9
Opened 2022-09-08 12:21 UTC by ChoiWonBeen

## #1 request

하단 모바일 네비게이션 탭을 추가했습니다.

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] There are no warning message when you run `yarn lint`
- [ ] Docs updated for breaking changes

### Screenshot

![bottomNavigation](https://user-images.githubusercontent.com/50780281/189120050-5f69a7b9-cebc-4eee-9f50-724d02187ee0.gif)

2022-09-08 12:58 UTC, SimYunSup requested changes
간단한 화면일텐데 많은 고민을 하신게 보이네요 :)

생각해볼만할 점을 적어보았습니다.

2022-09-08 12:58 UTC, SimYunSup commented on src/components/common/BottomNavigation/index.tsx
> +const navTabs = [
navTabs는 상수이므로 대문자 SNAKE_CASE로 바꿔주세요.

2022-09-08 12:58 UTC, SimYunSup commented on src/components/common/BottomNavigation/index.tsx
> +              aria-label={`${tab.text}으로 이동`}
`tab.text`와 `a` tag로 충분히 설명이 됩니다. 굳이 필요 없는 속성이라고 생각합니다.

2022-09-08 12:58 UTC, SimYunSup commented on src/components/common/BottomNavigation/index.tsx
> +              <tab.icon className={styles.tab__icon} />
스크린리더에서 필요 없는 태그입니다. `aria-hidden`으로 가려주세요.

2022-09-08 12:58 UTC, SimYunSup commented on src/components/common/BottomNavigation/BottomNavigation.module.scss
> +    &--focused {
focus했을 경우(tab으로 focus했을 경우) 일관성이 떨어집니다. `:hover`, `:focus`했을 경우 중간 색상으로 변하도록 하고 `outline`을 삭제하는 것이 어떨까요?

2022-09-08 12:58 UTC, SimYunSup commented on src/components/common/BottomNavigation/BottomNavigation.module.scss
> +@import "src/utils/styles/mediaQuery";
KOIN_WEB_RECODE에서는 import를 use로 바꿀 예정입니다.
https://sass-lang.com/blog/the-module-system-is-launched#future-plans
10월에 deprecated 예정되어있다고 하니 `@use`를 사용해주세요!

2022-09-08 13:04 UTC, ChoiWonBeen commented on src/components/common/BottomNavigation/index.tsx
> +              aria-label={`${tab.text}으로 이동`}
"홈 링크" 보단 "홈으로 이동 링크"를 만들고 싶었지만...
생각해보니 다른 모든 사이트가 a태그의 "링크"만을 사용할텐데 과하다는 표현이 맞는거같네요.

2022-09-08 13:29 UTC, ChoiWonBeen commented on src/components/common/BottomNavigation/BottomNavigation.module.scss
> +    &--focused {
`focused` 변수명은 수정이 필요해보이네요. 
연한 색상이어도 border가 생기면 디자인이 너무 이상해져서 나머지 요소에게만 적당한 색상을 주고 `outline`을 제거하는건 좋아보이네요. 변경한 내용으로 스크린샷까지 바꿔서 올리겠습니다 😁

2022-09-09 05:45 UTC, jaewoogwak commented on src/utils/ts/classNames.ts
> +    .filter(([, value]) => value)
[key, value] => value와 같은 의미인데 eslint에서 사용하지 않는 변수는 작성하지 않게 해서 [, value] => value로 작성한거군여 하나 배워갑니다👍

2022-09-09 05:47 UTC, jaewoogwak commented on src/layout/DefaultLayout/index.tsx
> +function DefaultLayout({ children }: DefaultLayoutProps): JSX.Element {
DefaultLayout은 다른 브랜치에서도 공통으로 사용하면 되는걸까욥??

2022-09-09 05:49 UTC, jaewoogwak commented on src/components/common/BottomNavigation/index.tsx
> +              <tab.icon className={styles.tab__icon} aria-hidden />
tab.icon이 곧 위에 임포트한 컴포넌트가 되겠네요..!!! 배워갑니다

2022-09-09 05:51 UTC, ChoiWonBeen commented on src/layout/DefaultLayout/index.tsx
> +function DefaultLayout({ children }: DefaultLayoutProps): JSX.Element {
🙆‍♂️ 디자인상으로 공통되는 헤더, 푸터등이 포함되는 기본 레이아웃으로 만들었고, 헤더나 푸터가 포함되지 않은 UI도 생각보다 많아서 선택형으로 쓸 수 있게끔 컴포넌트로 분리했습니다.

2022-09-09 06:00 UTC, ChoiWonBeen commented on src/components/common/BottomNavigation/index.tsx
> +              <tab.icon className={styles.tab__icon} aria-hidden />
`icon: <SVGComponent />,`
처럼 변수로 두고 {tab.icon}처럼 쓰는 방법도 있는데, 배열 내 객체마다 className을 반복해서 써야하는 문제가 있어 위처럼 작성했습니다...만 이게 옳은지에 대해서는 확신이 서진 않네요 ㅋㅋ

2022-09-09 07:19 UTC, D0Dam reviewed
밑에 navbar 한 개 만드는 작업이 생각보다 엄청 정교하다는 사실 깨닫고 갑니다.. 개인적인 의견을 코멘트 해두었습니다.

2022-09-09 07:19 UTC, D0Dam commented on src/components/common/BottomNavigation/BottomNavigation.module.scss
> +    color: #c4c4c4;
코드를 보니 색상들이 #c4c4c4, #222222, #6d6d6d 와 같이 겹치는 색상이 있네요.
아마 프로젝트를 진행하면서 공통적으로 쓰이게 될 색상이라고 생각하는데  개인적으로 이 색상값을 따로 변수로 지정해 활용하는 것도 좋을 것 같다 생각이 들었습니다.

2022-09-09 07:39 UTC, ChoiWonBeen commented on src/components/common/BottomNavigation/BottomNavigation.module.scss
> +    color: #c4c4c4;
한번 이슈올리고 날잡아서 맞출만할 것 같긴 하네요.
앞으로 올라올 디자인도 해당 컬러 테이블을 따라간다면 바꿔도 좋을거같아요

2022-09-09 07:43 UTC, D0Dam approved these changes

2022-09-09 12:04 UTC, jaewoogwak approved these changes

2022-09-09 12:21 UTC, SimYunSup reviewed
`!important`는 최후의 방법으로 써주세요 :) 고생하셨습니다!

2022-09-09 12:21 UTC, SimYunSup commented on src/components/common/BottomNavigation/BottomNavigation.module.scss
> +        color: #222222 !important;
`!important`를 사용하기보다는 `>`을 활용하여 우선순위를 높이는 방향으로 수정해주세요.

2022-09-09 12:23 UTC, daepan approved these changes
고생하셨습니다. 위의 올린 의견은 저의 개인적인 의견이니 한번 참고해주시면 감사하겠습니다.

2022-09-09 12:23 UTC, daepan commented on src/components/common/BottomNavigation/index.tsx
> +
import 부분에 이미지에 대한 NAV_TABS에 대한 부분이 과반수인데, constant 폴더로 관리하는 건 어떨까 생각합니다.

2022-09-09 12:23 UTC, daepan commented on src/layout/DefaultLayout/index.tsx
> +
오 아예 props를 통해 관리하시려는가보군요.  router의 기능 중 저의 경우에는 Outlet이라는 기능을 활용했을 텐데..
다음 블로깅에서 해당 방식과 Outlet을 비교해봐야겠군요

2022-09-09 12:34 UTC, ChoiWonBeen commented on src/components/common/BottomNavigation/index.tsx
> +
이 컴포넌트를 제외하면 쓸 일이 없는 데이터다보니 따로 분리하지는 않았습니다만, import가 과해보이긴 하네요. 앞으로 만들어질 다른 컴포넌트들에 비슷한 구조가 쓰이게된다면 리팩토링을 고려해보겠습니다 👍

2022-09-09 12:40 UTC, ChoiWonBeen commented on src/layout/DefaultLayout/index.tsx
> +
`react-router-dom` 에서 제공하는 `<Outlet />`은 `<Route>` 태그가 중첩이 될 때 사용한다고 알고있는데,
특정 중첩된 라우팅(지금은 '/')에 해당하는 모든 컴포넌트에서 공유하는 레이아웃이 아닌지라 사용할 수 없었습니다.

2022-09-09 13:00 UTC, hanagertrudeKim commented on src/utils/hooks/useMediaQuery.ts
>        matchMediaRef.current?.removeEventListener('change', handleChange);
같은 EventListener를 추가하고 제거하는 과정에서 옵셔널체이닝이 걸린 위치가 다른 이유가 있나요??

2022-09-09 13:11 UTC, ChoiWonBeen commented on src/utils/hooks/useMediaQuery.ts
>        matchMediaRef.current?.removeEventListener('change', handleChange);
클린업 콜백함수에서의 옵셔널체이닝은 `ref.current`가 `null`일 수 있어서 걸어둔건데, 앞 effect 문 내에서의 옵셔널체이닝은 ref변수가 반드시 current를 담고있기에 불필요하네요. 위 `!important` 지우면서 같이 지우겠습니다 👍

2022-09-09 13:15 UTC, ChoiWonBeen commented on src/components/common/BottomNavigation/BottomNavigation.module.scss
> +        color: #222222 !important;
[081ada2](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/9/commits/081ada20053edf1ff67f034a9765d948e1981e20)
수정했습니다 🙆

2022-09-09 13:15 UTC, ChoiWonBeen commented on src/utils/hooks/useMediaQuery.ts
>        matchMediaRef.current?.removeEventListener('change', handleChange);
[081ada2](https://github.com/BCSDLab/JJBAKSA_FRONT_END/pull/9/commits/081ada20053edf1ff67f034a9765d948e1981e20)
수정했습니다 🙆‍♂️

2022-09-09 13:19 UTC, SimYunSup approved these changes

2022-09-09 13:20 UTC, merged