[Post, Search] 리뷰 쓰기 기능 추가, 검색페이지 변경 대응 및 기능 연결
BCSDLab/TEMP_PROJECT_FE pull request #91
Opened 2023-08-10 11:31 UTC by ChoiWonBeen

## [#77, #23] request

기존 검색 페이지와 글쓰기까지의 기능을 연결하고, 리뷰 글쓰기 기능을 추가했습니다.

- 검색 api 변경 대응
  - 검색 결과로 나온 상점의 정보를 가지고 리뷰 글쓰기 페이지로 이동
  - UI에 포함되지 않는 `placeId` 를 `location.state`로 넘겨 활용
  - 상점 사진을 실제 구글 데이터로 변경(1개)
- 글쓰기 기능 추가
  - jotai를 활용해 별점, 위지윅 각각에 존재하는 상태를 저장
  - 이미지 정보를 보내기 위해 `formData`클래스를 활용해 사진의 수만큼 반복해서 `append`

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

### Screenshot
<img width="348" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/50780281/e7bd5320-7f82-494a-88f0-dbe38a1796d0">
<img width="1324" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/50780281/01a4805c-c303-4130-9c3c-642a3a4b10e8">
<img width="424" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/50780281/1344ce3b-4293-459d-a4af-63cf212f30a0">

2023-08-15 12:48 UTC, MinGu-Jeong requested changes

2023-08-15 12:48 UTC, MinGu-Jeong commented on src/api/search/entity.ts
> +  openNow: boolean
세미콜론이 빠졋네요

2023-08-16 13:27 UTC, kimeodml requested changes
고생하셨습니다!

2023-08-16 13:27 UTC, kimeodml commented on src/pages/SearchDetails/components/SearchItemPC.tsx
>              >
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/88065770/d525c027-e7c4-4352-9fac-9054af946189)
`a` 태그 대신 `button` 태그로 변경하는 거 어떤가요?

2023-08-16 13:27 UTC, kimeodml commented on src/pages/SearchDetails/index.tsx
> +              <SearchItemPC key={shop.placeId} shop={shop} />
검색 결과로 상점이 나오는 거니까 Item대신 Shop이라는 명칭으로 바꾸는 거 어떨까요?
근데 뒤에 PC를 붙인 이유를 알 수 있을까요...?

2023-08-16 13:27 UTC, kimeodml commented on src/components/editor/Wysiwyg/index.tsx
>  const Wysiwyg = forwardRef((_props, ref) => {
위지윅 에디터라 내부에 이미지 첨부가 가능한데 용량이 크면 `413` 에러가 떠서 드래그앤드롭 기능을 제한해야할 것 같아요.

2023-08-20 08:25 UTC, ChoiWonBeen commented on src/components/editor/Wysiwyg/index.tsx
>  const Wysiwyg = forwardRef((_props, ref) => {
흠... 사진 첨부기능이 따로 있어서 위지윅 자체 기능을 쓰면 안되는데 기능을 제한하는게 가능한지 확인해야겠네요 ㅋㅋㅋ

2023-08-30 09:12 UTC, ChoiWonBeen commented on src/pages/SearchDetails/components/SearchItemPC.tsx
>              >
전화를 실제로 거는 `href={"tel:..."}`을 쓰려면 a태그가 불가피할 것 같은데 바깥 카드 전체가 Link tag로 되어있는게 적절하게 보이진 않네요. 이 부분을 수정했습니다~ 2f0ae08cf4a24f3cb46fa21b8804fa91a64da4b2

2023-08-30 09:15 UTC, ChoiWonBeen commented on src/pages/SearchDetails/index.tsx
> +              <SearchItemPC key={shop.placeId} shop={shop} />
이전 작업자가 해둔 컴포넌트를 그대로 뒀는데, PC가 붙을 필요는 없어보이네요. 적절하게 `<SearchItem />` 정도로 수정했습니다! 12c70dd78781716f9ad50b3cecea02d60839d259

2023-08-30 09:25 UTC, ChoiWonBeen commented on src/components/editor/Wysiwyg/index.tsx
>  const Wysiwyg = forwardRef((_props, ref) => {
말씀하신 기능은 추가했습니다! 9a0b18f96b371ff66387360350ab5029ec1741fc
추후 피쳐에 위지윅에 직접 사진을 복붙하지 못하게 하는 기능을 막는 것도 생각해봐야겠네요 ㅋㅋ
<img width="759" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/50780281/6aa2871c-6cd2-4fb7-b1fb-12ee3b532de3">

2023-08-30 12:10 UTC, kimeodml reviewed
고생하셨습니다! 상점 검색 쪽 디자인이랑 글쓰기 검색쪽이랑 디자인이 똑같아서 추상화가 필요해 보이는데 브랜치 주제와 많이 벗어나서 무리겠죠...?😢
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/88065770/4d971ee8-aad2-4c88-8e9f-0b35cde0cee3)
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/88065770/d4176de1-2447-4ca0-af73-9d14f463cb22)

2023-08-30 14:39 UTC, ChoiWonBeen commented
> 고생하셨습니다! 상점 검색 쪽 디자인이랑 글쓰기 검색쪽이랑 디자인이 똑같아서 추상화가 필요해 보이는데 브랜치 주제와 많이 벗어나서 무리겠죠...?😢 

아예 그대로 가져가서 써도 될 것 같아요~ 
상점 검색 UI 만들때 가져다 쓰게끔 인지만 하면 될 것 같아요

2023-09-01 12:49 UTC, HAEROOL approved these changes
LGTM 수고하셨습니다

2023-09-02 12:22 UTC, kimeodml approved these changes

2023-09-04 10:34 UTC, merged