[DETAIL] 메인페이지 주소 변경 UI 구현
BCSDLab/TEMP_PROJECT_FE pull request #95
Opened 2023-08-21 10:59 UTC by hyejun0228

## [#94] 메인페이지 주소 변경 UI 구현

- 메인페이지 주소 변경 UI 구현했습니다

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

### Screenshot
<img width="1470" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/114041848/7c5c2a23-d843-42f4-a456-77d095f99170">
<img width="736" alt="image" src="https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/114041848/63579f2d-9f07-4c88-ba39-9e1f70f9f8d6">

2023-08-22 11:57 UTC, kimeodml requested changes
고생하셨습니다! 추후에 모바일 쪽도 수정하면 될것 같아요.

2023-08-22 11:57 UTC, kimeodml commented on src/pages/Home/components/Map/components/Location/index.tsx
> +export default function Map(): JSX.Element {
파일명이 location이라서 함수명 수정해야할것 같아요

2023-08-22 11:57 UTC, kimeodml commented on src/pages/Home/Home.module.scss
> +  box-shadow: 1px 1px 10px 1px #0000001a;
`position: absolute`으로 변경한 후에 right값 주면 괜찮지 않을까 싶습니다. `margin-left: 1550px`은 너무한 것 같아요ㅋㅋㅋㅋ😂

2023-08-22 11:57 UTC, kimeodml commented on src/pages/Home/components/Map/components/Location/Location.module.scss
> +  margin-top: 140px;
margin auto 써 보는 건 어떨까요?

2023-08-22 11:57 UTC, kimeodml commented on src/pages/Home/index.tsx
> +  const [isClickLocation, setIsCilckLocation] = useState(false);
모달 영역 밖 클릭시 닫히게 하거나 useBooleanState를 사용해 토글 형식으로 바꾸는 게 어떨까요? 한번 클릭하면 계속 true로 고정되는 것 같아서요.

2023-08-22 11:57 UTC, kimeodml commented on src/pages/Home/components/Map/components/Location/index.tsx
> +    console.log('열림');
불필요한 console.log는 제거해도 될 것 같아요.

2023-08-28 04:54 UTC, hyejun0228 commented on src/pages/Home/components/Map/components/Location/index.tsx
> +export default function Map(): JSX.Element {
수정했습니다! 0e11dd95672990fd67d6b7d34f80bf8df3b6a283

2023-08-28 04:55 UTC, hyejun0228 commented on src/pages/Home/Home.module.scss
> +  box-shadow: 1px 1px 10px 1px #0000001a;
앗 ㅋㅋㅋ 수정했습니다 ! 0e11dd95672990fd67d6b7d34f80bf8df3b6a283

2023-08-28 04:56 UTC, hyejun0228 commented on src/pages/Home/components/Map/components/Location/Location.module.scss
> +  margin-top: 140px;
`margin: auto` 만으로 원하는 위치에 놓여지지 않아서 `position`의 `top` ` right` 같은 속성들을 이용해서 변경해줬습니다
0e11dd95672990fd67d6b7d34f80bf8df3b6a283

2023-08-28 04:56 UTC, hyejun0228 commented on src/pages/Home/components/Map/components/Location/index.tsx
> +    console.log('열림');
넵 수정했습니다 
0e11dd95672990fd67d6b7d34f80bf8df3b6a283

2023-08-29 02:19 UTC, hyejun0228 commented on src/pages/Home/index.tsx
> +  const [isClickLocation, setIsCilckLocation] = useState(false);
넵! 수정했습니다 5092e325c390ad201ed2452f334449555d606fff

2023-08-30 09:46 UTC, ChoiWonBeen requested changes
어 이게 #92 PR에서 본 내용들이 왜 껴있나 했는데 아직 병합이 안된 브랜치에서 브랜치를 만들어서 두 변경사항이 전부 포함되어 올라왔네요 ㅋㅋㅋ 
빨리 해당 PR을 병합해 변경내용을 먼저 줄여두면 다음 사람들이 리뷰하기 편할 것 같아요 @kimeodml 
몇가지 수정할만한 사항들 올려놨으니 미리 수정해주세요~

2023-08-30 09:46 UTC, ChoiWonBeen commented on .eslintrc.json
> +    ],
이 룰이 추가된 이유는 무엇인가요??

2023-08-30 09:46 UTC, ChoiWonBeen commented on src/pages/Home/index.tsx
> +    const response = await axios.get('/map-reversegeocode/v2/gc', {
제가 401에러가 계속 나는데 이유를 생각해보니 다른 api들관 다르게 헤더를 포함해둔 apiClient를 쓰지 않아서 `Authorization`이 추가가 안된 채로 요청이 반복됐었네요.
그리고 해당 함수는 다른 파일들처럼 API폴더에 추가하고, Response타입을 정의해둘 필요가 있을 것 같아요

2023-08-30 09:46 UTC, ChoiWonBeen commented on src/pages/Home/index.tsx
> +    const apiSecretKey = process.env.REACT_APP_NAVER_CLOUD_MAPS_CLIENT_SECRET_ID as string;
config/constant.ts 파일에서 env파일을 모아 관리하고있어요.
여기쪽에서 export한다면 env파일을 포함하지 않은 사람들에게 알림도 줄 수 있을테니 확인해서 사용해주세요~

2023-08-30 09:46 UTC, ChoiWonBeen commented on src/pages/Home/index.tsx
> +    const response = await axios.get('/map-reversegeocode/v2/gc', {
아, 생각해보니 Authorization문제는 아니고 그냥 .env파일 내용이 부족해 해당 값이 없어 생기는 문제였던 것 같네요 ㅋㅋ
그래도 파일 분리나 다른 내용들은 똑같이 적용할 필요가 있어보여요

2023-08-30 09:46 UTC, ChoiWonBeen commented on src/pages/Home/index.tsx
> +    const apiSecretKey = process.env.REACT_APP_NAVER_CLOUD_MAPS_CLIENT_SECRET_ID as string;
근데 드라이브에 해당 변수들이 안적혀있어서 찾아 쓸 수도 없었네요..ㅋㅋㅋㅋㅋㅋ 추가해주세요!

2023-08-30 17:02 UTC, hyejun0228 commented on .eslintrc.json
> +    ],
이........부분은 잘 모르겠습니다..만진 파일이 아닌데...다시 바꿔놓겠습니다.

2023-08-30 17:06 UTC, hyejun0228 commented on src/pages/Home/index.tsx
> +    const apiSecretKey = process.env.REACT_APP_NAVER_CLOUD_MAPS_CLIENT_SECRET_ID as string;
constant.ts 파일에 추가하고 BCSD 구글 드라이브에 환경변수정보 업데이트 해놓겠습니다!

2023-08-31 00:29 UTC, ChoiWonBeen commented on .eslintrc.json
> +    ],
다시 바꾸진 말아요! #92 에서 추가된 내용이 아직 develop에 병합되지 않아 해당 내용들이 그대로 딸려온 부분 중 하나인 것 같아요 ㅋㅋ 이번PR에서 지워버린다면 아마 지우는 변경으로 처리돼버릴거예요

2023-08-31 01:35 UTC, hyejun0228 commented on .eslintrc.json
> +    ],
넵!

2023-09-02 06:35 UTC, hyejun0228 commented on src/pages/Home/index.tsx
> +    const response = await axios.get('/map-reversegeocode/v2/gc', {
현재 위치의 경도, 위도를 주소로 변환해주는 기능, 현재 위치로 맵이 이동하는 기능의 경우에는 커스텀 훅으로 따로 분리해주고 위치를 나타내주는 UI는 따로 컴포넌트 나눠줬습니다! 
94f6a65a3bc8eec9c710483d845f19e11117adeb

2023-09-03 08:35 UTC, kimeodml reviewed
고생하셨습니다! 추가적으로 불필요한 console.log만 지우면 될 것 같아요!

2023-09-03 08:35 UTC, kimeodml commented on src/pages/Home/components/Map/hooks/useHome.ts
> +export default function useHomeLogic() {
파일명이랑 함수명이랑 일치시켜야할 것 같아요.

2023-09-03 08:35 UTC, kimeodml commented on src/api/location/index.ts
> +    return `${data.results[0].region.area1.name} ${data.results[0].region.area2.name}`;
요걸로 변경 한 후에 폰트 그기 줄여야할 것 같아요!
```suggestion
    return `${data.results[0].region.area1.name} ${data.results[0].region.area2.name} ${data.results[0].region.area3.name} ${data.results[0].land.name} ${data.results[0].land.number1}`;
    
```

2023-09-03 08:35 UTC, kimeodml commented on src/pages/Home/components/Map/components/Location/index.tsx
> +    <div>
불필요한 div는 제거해도 좋을것 같아요

2023-09-03 08:35 UTC, kimeodml commented on src/pages/Home/index.tsx
> +          <div>
이 부분 div도 불필요해 보여요!

2023-09-03 08:35 UTC, kimeodml commented on src/pages/Home/components/Map/components/Location/Location.module.scss
> +  left: 700px;
가운데 정렬이 고정이 되어 있어서 화면을 줄이면 잘려서 fixed 형식으로 수정해야할 것 같아요.
주소 검색창과 모달창이 겹쳐서 margin을 줘야할 필요가 있을 것 같습니다. 아니면 top값을 변경해도 좋고요.
```suggestion
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
```

2023-09-03 08:35 UTC, kimeodml commented on src/pages/Home/components/Map/hooks/useHome.ts
> +      document.removeEventListener('mousedown', handleClickOutside);
누를 때 이벤트가 발생해서 모달창이 열려 있는 상태로 주소 검색창을 누르면 모달창이 깜빡이는데 `mouseup`으로 변경하면 어떨까요?

2023-09-04 06:20 UTC, hyejun0228 commented on src/pages/Home/components/Map/hooks/useHome.ts
> +export default function useHomeLogic() {
앗 넵 수정했습니다
477f29e9c687ada18e4fafd5ef7afb8405ad61f5

2023-09-04 06:20 UTC, hyejun0228 commented on src/pages/Home/components/Map/components/Location/Location.module.scss
> +  left: 700px;
넵 수정했습니다! 
477f29e9c687ada18e4fafd5ef7afb8405ad61f5

2023-09-04 06:21 UTC, hyejun0228 commented on src/pages/Home/components/Map/hooks/useHome.ts
> +      document.removeEventListener('mousedown', handleClickOutside);
좋습니다..! 이부분은 생각도 못했네요.. 
477f29e9c687ada18e4fafd5ef7afb8405ad61f5

2023-09-04 07:03 UTC, hyejun0228 commented on src/api/location/index.ts
> +    return `${data.results[0].region.area1.name} ${data.results[0].region.area2.name}`;
변경후에 폰트는 그대로 두고 글자 길이에 따라 너비 조절될수 있게 바꿨습니다! 
64369f280d46b5358df6b980f7cd4d4f3118e01c

2023-09-04 12:16 UTC, kimeodml approved these changes
고생하셨습니다. 브랜치 최신화한 상태로 머지해 주세요!!

2023-09-04 14:41 UTC, ChoiWonBeen approved these changes
확인하면서 문제된 부분들은 없었는데, 고려할 만한 부분들이 몇개 있어서 쭉 정리해봣어요. 확인해보고 변경할 부분들은 바꾼다음 병합해주세요~

2023-09-04 14:41 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/components/Location/index.tsx
> +      </div>
검색 완료 시 enter키 등으로 결과를 확인하려면 구조를 어떻게 바꿔야할까요?

2023-09-04 14:41 UTC, ChoiWonBeen commented on src/pages/Home/components/LocationInfo/index.tsx
> +    >
그냥 button태그로 만들지 않은 이유가 있나요?
`onKeyDown`이벤트가 섞인게 적절하지 않아보이기도 하고
`map-container` 라는 이름에 맵 전체 컨테이넌줄 알았는데 작은 버튼이더라구요? ㅋㅋ
개인적으론 열린 채로 이 버튼이 눌렸을때 닫히는 UX도 괜찮아보여요. svg를 180도 정도 rotate하면서?

2023-09-04 14:41 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/components/Location/Location.module.scss
> +    line-height: 19.97px;
line-height이 대부분의 상황에서 만들어진 UI를 깨뜨릴 수 있다고 생각해요.
특히 소숫점 둘째자리는 더 불안한 감도 있고요 ㅋㅋ
마진 - 패딩 단위로 한다면 기본값인 100%만을 사용하는게 디테일을 유지할 수 있을거예요.
대부분은 디자인 툴의 line-height이 텍스트보다 크더라도, 중앙 정렬이 되어있기 마련인데 브라우저 노드는 기본값이 flex, align center가 아니거든요.

2023-09-04 14:41 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/components/Location/index.tsx
> +        <div className={styles.box__subTitle}>알려주시면 반영하겠습니다.</div>
간단한 줄바꿈이라면 `<br />`태그를 사용하는건 어떨까요?
line-height을 적절히 활용할 수 있고, 수정도 용이하다고 생각해요
```suggestion
        <div className={styles.box__subTitle}>
          현재 계신 곳의 위치를 아래 검색창을 통해
          <br />
          알려주시면 반영하겠습니다.
        </div>
```

2023-09-04 14:41 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/hooks/useHome.ts
> +        console.error('에러', error);
되도록 린트는 지워주시고, catch했을때 어떤 상호작용을 추가할 수 있는지 생각해보죠.
개인적으로 `util` 폴더의 `makeToast`함수는 대부분 린트 에러를 피하고, 보기 좋게 활용할 수 있다고 생각해요.

2023-09-04 14:41 UTC, ChoiWonBeen commented on src/pages/Home/index.tsx
> +          tabIndex={0}
모달창의 배경인 것 같은데 왜 `role="button" + tabindex`가 들어있는걸까요??

2023-09-04 14:41 UTC, ChoiWonBeen commented on package.json
> +    "http-proxy-middleware": "1",
해당 라이브러리가 추가된 이유는 무엇인가요??

2023-09-04 14:41 UTC, ChoiWonBeen commented on package.json
> +    "@types/express": "^4.17.17",
얘도 잘못 추가된 것 같아요

2023-09-04 14:41 UTC, ChoiWonBeen commented on package.json
> +  "proxy": "https://naveropenapi.apigw.ntruss.com"
네이버 로그인을 위한 개발용 프록시였는데, 바꿔야만 동작하나요?

2023-09-04 14:41 UTC, ChoiWonBeen commented on .eslintrc.json
> +    ],
보니깐 직접 변경하신 사항이 맞네요. 추가하셨을때 이유를 까먹은걸수도 있으니 한번 지워보고 어떤 차이가 있는지 확인해본다음 액션을 취하면 될 것 같아요.

2023-09-04 14:49 UTC, hyejun0228 commented on package.json
> +    "http-proxy-middleware": "1",
현재 위치를 가져와 지도에 나타내주는 api 를 가져와줄때 CORS에러 이슈로 해결방법을 찾던중 깐 라이브러리 같습니다. 해결한 이후에 지울 생각을 못한것 같습니다. 삭제하겠습니다

2023-09-04 14:57 UTC, hyejun0228 commented on package.json
> +  "proxy": "https://naveropenapi.apigw.ntruss.com"
네이버 클라우드 플렛폼에 있는 현재의 위치를 가져와 지도에 표시해주는 api를 사용해주기 위해서는 proxy 를 바꿔줄 필요가 있어 바꿔주게 됐습니다. 지금의 프록시로 바꿨을때 네이버 로그인이 작동되는지 확인이 안되는데 따로 확인할 방법이 있을까요? 코드상에서 유추해봐야하는건가요?

2023-09-04 15:01 UTC, hyejun0228 commented on src/pages/Home/components/LocationInfo/index.tsx
> +    >
엇..처음부터 태그를 div로 시작하는 바람에 오류를 고치려고 꾸역꾸역 다양한 걸 넣었더니.. 생각을 못했습니다..! 전체적으로 태그들 수정하겠습니다

2023-09-04 15:37 UTC, hyejun0228 commented on src/pages/Home/components/Map/hooks/useHome.ts
> +        console.error('에러', error);
오오..넵 수정했습니다!

2023-09-04 15:38 UTC, hyejun0228 commented on package.json
> +    "@types/express": "^4.17.17",
수정하겠습니다!

2023-09-04 16:22 UTC, hyejun0228 commented on src/pages/Home/components/Map/components/Location/index.tsx
> +      </div>
키보드 이벤트를 추가해 결과를 입력받는 걸 추가하면 될 것 같습니다! 다음에 만들것이 위치 입력 기능인데 그때 추가하도록 하겠습니다!

2023-09-04 16:25 UTC, hyejun0228 commented on src/pages/Home/components/Map/components/Location/Location.module.scss
> +    line-height: 19.97px;
오옹.. 그럼 마진을 사용해서 코드 수정하겠습니다!

2023-09-04 16:31 UTC, hyejun0228 commented on src/pages/Home/components/Map/components/Location/index.tsx
> +        <div className={styles.box__subTitle}>알려주시면 반영하겠습니다.</div>
이 코드를 사용한다면 각 문장에 추가로 태그 처리를 해줘야 코드를 묶어서 중앙정렬을 해줄수 있어 코드의 길이가 더 늘어나지 않을까요?!

2023-09-04 16:46 UTC, merged

2023-09-05 00:50 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/components/Location/index.tsx
> +      </div>
간단하게 form + submit구조라면 네이티브 기능을 활용해 더 편하게 작성할 수 있을거예요~

2023-09-05 00:52 UTC, ChoiWonBeen commented on src/pages/Home/components/Map/components/Location/index.tsx
> +        <div className={styles.box__subTitle}>알려주시면 반영하겠습니다.</div>
`text-align: center` 를 사용하면 내부 태그 처리가 따로 없어도 될 거예요

2023-09-05 00:53 UTC, ChoiWonBeen commented on package.json
> +  "proxy": "https://naveropenapi.apigw.ntruss.com"
환경변수를 적절히 넣은 다음 네이버 로그인을 시도해보면 되겠죠..?