[FOLLOW] 친구 목록 및 친구 프로필 페이지 구현
BCSDLab/TEMP_PROJECT_FE pull request #96
Opened 2023-08-22 13:00 UTC by chaeseungyun

친구 목록 및 친구 프로필 페이지를 구현했습니다.
프로필은 오직 팔로워끼리만 확인할 수 있습니다.
친구 프로필 페이지의 pc 디자인이 확정되지 않아 모바일뷰를 많이 참고했습니다. 추후 수정하겠습니다.

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] There are no warning message when you run `yarn lint`
- [x] Docs updated for breaking changes

### Screenshot
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/101871802/4f327f85-5c5d-49a9-8cac-0a50fadbbd2f)
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/101871802/07e004e5-9fec-47f5-808f-6df9f9da3a94)
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/101871802/7a79ffa5-dade-4957-827f-313b1476605a)
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/101871802/78e4ef08-b60e-40bf-95c8-025758f90349)
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/101871802/09bdcf89-8c74-4050-bffa-424e7218c294)

2023-08-27 08:18 UTC, kimeodml requested changes
고생하셨습니다! 컴포넌트 내부에 폴더로 묶어서 깔끔하게 정리하면 좋을것 같아요!

2023-08-27 08:18 UTC, kimeodml commented on src/api/follow/index.ts
> +export const checkSendedFollow = (pageParam: number) => followApi.get<SendedOrReceivedFollowResponse>(`/follow/requests/send?page=${pageParam}&pageSize=10`);
sended로 되어 있는 부분 다 sent로 수정해야될 것 같아요!

2023-08-27 08:18 UTC, kimeodml commented on src/pages/Follow/components/FollowList.module.scss
> +
인터넷 익스플로러와 파이어폭스도 추가하면 어떨까요?
```suggestion
  -ms-overflow-style: none; /* 인터넷 익스플로러 */
  scrollbar-width: none; /* 파이어폭스 */
```

2023-08-27 08:18 UTC, kimeodml commented on src/pages/Follow/components/EmptyFriend.tsx
> +export default function EmptyFriend() {
`EmptyFriend` 컴포넌트와 `FailToSearch` 컴포넌트의 구조가 비슷한데  `AuthDetail` 컴포넌트처럼 인자로만 전달하는 방식을 사용하면 어떨까요..?

2023-08-27 08:18 UTC, kimeodml commented on src/pages/Follow/components/Follower.tsx
> +          className={cn({ [style['follower__content--font']]: true })}
font 대신 nickname 어떤가요?
```suggestion
          className={cn({ [style['follower__content--nickname']]: true })}
```

2023-08-27 08:18 UTC, kimeodml commented on src/pages/Follow/index.tsx
> +  };
제가 이 부분이 이해가 안 가서 그런데 이차원 배열에서 일차원 배열로 변경하는 이유를 알 수 있을까요..?

2023-08-27 08:18 UTC, kimeodml commented on src/pages/Follow/components/FollowProfile.tsx
> +import { useDeleteFollow, useRequestAndUpdate } from './Follower';
hooks 폴더에서 import 하면 어떨까요?

2023-08-27 08:18 UTC, kimeodml commented on src/pages/Follow/components/FollowProfile.tsx
> +                <span>count</span>
이 count는 뭔지 알 수 있을까요...?

2023-08-27 08:18 UTC, kimeodml commented on src/pages/Follow/components/Follower.tsx
> +          onClick={() => navigate(`${id}`, {
친구 신청한 후에 서로 맞팔되어 있지 않더라도 FollowProfile로 들어가 지는데 맞팔 전까지는 disabled 하게 만들 수는 없을까요? 친구 신청이나 최근 접속한 친구 또한 Follower 컴포넌트를 사용하고 있어서 불가능하려나요.🤔 만약 변경 가능하다면 toast 띄워서 안내 문구 만들어줘도 좋을 것 같아요.

2023-08-30 09:50 UTC, ChoiWonBeen commented on src/pages/Follow/components/FollowList.module.scss
> +
IE대응은 필요없을것같은데 파폭은 좋아보여요

2023-08-30 11:38 UTC, chaeseungyun commented on src/api/follow/index.ts
> +export const checkSendedFollow = (pageParam: number) => followApi.get<SendedOrReceivedFollowResponse>(`/follow/requests/send?page=${pageParam}&pageSize=10`);
넵 ㅎㅎ

2023-08-30 11:39 UTC, chaeseungyun commented on src/pages/Follow/components/Follower.tsx
> +          className={cn({ [style['follower__content--font']]: true })}
좋습니다

2023-08-30 11:41 UTC, chaeseungyun commented on src/pages/Follow/index.tsx
> +  };
useInfiniteQuery의 반환값은 SendedOrReceivedFollowResponse의 이차원배열이기때문에 map 함수로 한번에 렌더링 하려면 일차원배열로 변경해야했습니다.

2023-08-30 11:41 UTC, chaeseungyun commented on src/pages/Follow/components/FollowProfile.tsx
> +import { useDeleteFollow, useRequestAndUpdate } from './Follower';
넵 폴더구조 변경하겠습니다

2023-08-30 11:41 UTC, chaeseungyun commented on src/pages/Follow/components/FollowProfile.tsx
> +                <span>count</span>
아직 기능하나가 추가가 안 된상태였습니다.
count는 팔로워가 작성한 리뷰의 총 개수입니다

2023-08-30 11:42 UTC, chaeseungyun commented on src/pages/Follow/components/Follower.tsx
> +          onClick={() => navigate(`${id}`, {
어떻게 해결할지 고민해보겠습니다

2023-08-30 11:54 UTC, chaeseungyun commented on src/pages/Follow/components/FollowList.module.scss
> +
파이어폭스 추가 완료했습니다

2023-08-30 14:37 UTC, ChoiWonBeen approved these changes
고생하셨어요~ 문제가 있는 부분들은 없는 것 같고, UX향상으로 고려할만한 부분들을 나열해뒀으니 확인해주세요~

2023-08-30 14:37 UTC, ChoiWonBeen commented on src/pages/Follow/components/FollowList.module.scss
> +  width: 1067px;
위의 타이틀의 `width: 1187`과 더불어서 고정 width가 불편한 것 같아요.
`space-between`을 유지한 채로 100%를 두되, `max-width`를 지금의 수치로 고정하는 방법은 어떨까요??

2023-08-30 14:37 UTC, ChoiWonBeen commented on src/assets/svg/follow/search-fail.svg
이런거는 이미지로 쓰는게 더 좋았을 수도 있을 것 같아요 ㅋㅋㅋ
성능 비교를 어떻게 해야하는지는 몰라서 찾아봐야겠네요

2023-08-30 14:37 UTC, ChoiWonBeen commented on src/pages/Follow/components/Follower.tsx
> +export const useRequestAndUpdate = () => {
`Mutation`이라는 표현이 `RequestAndUpdate`를 함축한다고 생각하는데 `useFriendListMutation`.. 비슷한? 표현은 어떨까 의견 내봐요!

2023-08-30 14:37 UTC, ChoiWonBeen commented on src/pages/Follow/components/Follower.tsx
> +      queryClient.invalidateQueries('sended');
해당 훅들이 정상적이지 않은 계정들(이 앞으로 생길지는 모르겠지만..)에 대해서 500에러가 계속 나서 `onError`에 콜백을 추가해 `makeToast`등의 반응을 제공하는것도 괜찮을 것 같은데 어떻게 생각하시나요?!

2023-08-30 14:37 UTC, ChoiWonBeen commented on src/pages/Follow/components/Follower.tsx
> +        }
switch문으로 이루어진 handleClick 콜백을 만들면 좀 더 깔끔할 것 같기두요??
아래 111L ~ 조건문들까지 생각하면 onClick Function과 UI로 이루어진 객체의 배열을 만들어 반복문과 객체 접근으로 표현하는건 어떨까 싶어요!

2023-08-30 14:37 UTC, ChoiWonBeen commented on src/pages/Follow/components/FollowReview.tsx
> +    ({ pageParam = '' }) => getDetailReview(followerId, placeId, pageParam),
여기에 pageParam이 반드시 undefined로 들어가는데 추후 확장을 고려한 부분일까요?

2023-08-30 14:37 UTC, ChoiWonBeen commented on src/pages/Follow/components/FollowReview.tsx
> +  const { data } = useGetDetailReview(placeId, 361);
팔로워가 아닌 상황에 대해 에러가 발생하는데 해당 쿼리의 onError 콜백에 알림과 함께 이전 페이지로 되돌리는 UX라거나 할만한 부분들을 고려해볼 수 있을 것 같아요

2023-09-05 02:10 UTC, chaeseungyun commented on src/assets/svg/follow/search-fail.svg
성능도 고려하면서 이미지를 사용해야하는군요!

2023-09-05 02:10 UTC, chaeseungyun commented on src/pages/Follow/components/Follower.tsx
> +      queryClient.invalidateQueries('sended');
넵! 현재 정상적이지 않은 계정이 많아서 추가가 필요할 것 같습니다

2023-09-05 06:24 UTC, chaeseungyun commented on src/pages/Follow/components/Follower.tsx
> +          onClick={() => navigate(`${id}`, {
팔로우 타입이 followed일때 FollowProfile로 들어가지도록 했습니다

2023-09-16 04:42 UTC, kimeodml reviewed
![image](https://github.com/BCSDLab/JJBAKSA_FRONT_END/assets/88065770/857cca23-53d7-472c-891c-06e9c714ec7e)
맞팔 아닌 사람 계정 들어가면 400에러 떠서 이 부분 수정해야 할것 같아요. 그거 외에는 피그마 최신 다지인으로 변경하면 괜찮을것 같습니다. 브랜치 최신화 한 후에 진행해 주세요!!!

2023-09-16 04:43 UTC, kimeodml approved these changes

2023-09-18 01:08 UTC, merged